import E6Bridge30
open WeilExplicit RvMBridge11 RvMBridge16 RvMBridge6 RvMBridge8 Zeta23
#print axioms RvMBridge30.re_gaussTest_I_half
#print axioms RvMBridge30.re_gaussTest_neg_I_half
#print axioms RvMBridge30.pole_floor
#print axioms RvMBridge30.bumpR_le'
#print axioms RvMBridge30.setIntegral_bumpR_le'
#print axioms RvMBridge30.psiR_neg
#print axioms RvMBridge30.psiR_abs
#print axioms RvMBridge30.psiR_mono
#print axioms RvMBridge30.serF
#print axioms RvMBridge30.serG
#print axioms RvMBridge30.serF_nonneg
#print axioms RvMBridge30.serF_antitoneOn
#print axioms RvMBridge30.hasDerivAt_neg_serG
#print axioms RvMBridge30.sum_serF_ge
#print axioms RvMBridge30.psiR_ge_series
#print axioms RvMBridge30.serG_bounds
#print axioms RvMBridge30.psiR_ge_rational
#print axioms RvMBridge30.eulerMascheroni_le
#print axioms RvMBridge30.psiR_floor_0
#print axioms RvMBridge30.psiR_floor_1
#print axioms RvMBridge30.psiR_floor_2
#print axioms RvMBridge30.psiR_floor_3
#print axioms RvMBridge30.psiR_floor_4
#print axioms RvMBridge30.psiR_floor_5
#print axioms RvMBridge30.psiR_floor_6
#print axioms RvMBridge30.psiR_floor_7
#print axioms RvMBridge30.psiR_floor_8
#print axioms RvMBridge30.mem_Ioo_abs
#print axioms RvMBridge30.Cake
#print axioms RvMBridge30.cake_base
#print axioms RvMBridge30.cake_step
#print axioms RvMBridge30.cake_integral
#print axioms RvMBridge30.bandSum
#print axioms RvMBridge30.bandSum_eq
#print axioms RvMBridge30.integral_bumpR_mul_psiR_ge_bands
#print axioms RvMBridge30.lam₁
#print axioms RvMBridge30.re_weilForm_gauss_nonneg_1e3
#print axioms RvMBridge30.gaussian_positivity_small_lam_1e3
#print axioms RvMBridge30.gaussian_positivity_small_lam_explicit_1e3
#print axioms RvMBridge30.gaussian_positivity_small_lam'
#print axioms RvMBridge30.psiR_floor_s1
#print axioms RvMBridge30.psiR_floor_s2
#print axioms RvMBridge30.psiR_floor_s3
#print axioms RvMBridge30.psiR_floor_s4
#print axioms RvMBridge30.psiR_floor_s5
#print axioms RvMBridge30.psiR_floor_s7
#print axioms RvMBridge30.psiR_floor_s8
#print axioms RvMBridge30.psiR_floor_s9
#print axioms RvMBridge30.psiR_floor_s10
#print axioms RvMBridge30.psiR_floor_s11
#print axioms RvMBridge30.psiR_floor_s12
#print axioms RvMBridge30.bandSum12
#print axioms RvMBridge30.bandSum12_eq
#print axioms RvMBridge30.integral_bumpR_mul_psiR_ge_bands12
#print axioms RvMBridge30.lam₂
#print axioms RvMBridge30.re_weilForm_gauss_nonneg_3e3
#print axioms RvMBridge30.gaussian_positivity_small_lam_3e3
#print axioms RvMBridge30.gaussian_positivity_small_lam_explicit_3e3
#print axioms gaussianExplicitFormula
#print axioms norm_primeSide_le
#print axioms bumpR_nonneg
#print axioms integrable_bumpR
#print axioms integral_bumpR
#print axioms integrable_bumpR_mul_psiR
#print axioms psiR_eq
#print axioms gaussA_pos
#print axioms integral_archIntegrand_eq
#print axioms autocorr_gaussPhi
#print axioms autocorrGauss_zero
#print axioms weilKernel_zero_eq_gaussTest
#print axioms weilKernel_one_eq_gaussTest
#print axioms gaussTest_conj
#print axioms Zeta23.MuFields.re_digamma_vertical
#print axioms Zeta23.MuFields.re_digamma_mono
#print axioms Zeta23.MuFields.summable_re_terms
#print axioms Real.eulerMascheroniConstant_lt_eulerMascheroniSeq'
#print axioms Real.log_two_gt_d9
#print axioms Real.exp_one_gt_d9
#print axioms Real.pi_gt_d6
#print axioms Real.pi_lt_d6
#print axioms RvMBridge11.gaussian_positivity_small_lam
#check @RvMBridge11.gaussian_positivity_small_lam
#check @gaussianExplicitFormula
