import E6Bridge28
#print axioms RvMBridge28.zeroMult_one_sub_conj
#print axioms RvMBridge28.isNontrivialZero_one_sub_conj
#print axioms RvMBridge28.wOf
#print axioms RvMBridge28.wOf_ne_zero
#print axioms RvMBridge28.one_sub_inv_eq_inv_wOf
#print axioms RvMBridge28.one_sub_inv_one_sub_conj
#print axioms RvMBridge28.liKernel_eq_inv_wOf
#print axioms RvMBridge28.liKernel_one_sub_conj
#print axioms RvMBridge28.re_pow_eq
#print axioms RvMBridge28.re_inv_pow_eq
#print axioms RvMBridge28.pair_re_eq
#print axioms RvMBridge28.pow_add_inv_pow_eq_cosh
#print axioms RvMBridge28.sinh_mul_cos_sub_cosh_mul_sin_nonpos
#print axioms RvMBridge28.cosh_mul_cos_le_one
#print axioms RvMBridge28.cosh_mul_cos_le_one_of_abs_le
#print axioms RvMBridge28.arctan_le_self
#print axioms RvMBridge28.half_le_arctan
#print axioms RvMBridge28.abs_arctan
#print axioms RvMBridge28.wOf_re
#print axioms RvMBridge28.wOf_im
#print axioms RvMBridge28.normSq_sub_one
#print axioms RvMBridge28.normSq_eq_sq_add_sq
#print axioms RvMBridge28.wOf_re_pos
#print axioms RvMBridge28.abs_arg_wOf_eq
#print axioms RvMBridge28.abs_arg_wOf_le
#print axioms RvMBridge28.le_abs_arg_wOf
#print axioms RvMBridge28.abs_log_norm_wOf_le
#print axioms RvMBridge28.pair_re_nonneg_of_far
#print axioms RvMBridge28.pair_re_nonneg_of_on_line
#print axioms RvMBridge28.pair_re_nonneg_of_line_below
#print axioms RvMBridge28.liRe
#print axioms RvMBridge28.liRe_eq
#print axioms RvMBridge28.liRe_add_one_sub_conj
#print axioms RvMBridge28.hasSum_liRe
#print axioms RvMBridge28.liLimit_re_nonneg_of_pairs
#print axioms RvMBridge28.liLimit_re_nonneg_of_line_below
#print axioms RvMBridge28.archSide_add_finiteSide_re_nonneg_of_line_below
#print axioms RvMBridge28.liKernel_one
#print axioms RvMBridge28.liRe_one_nonneg
#print axioms RvMBridge28.liLimit_one_re_nonneg
#print axioms RvMBridge28.archSide_add_finiteSide_one_re_nonneg
#print axioms RvMBridge28.integral_shifted_mul_rpow_nonpos
#print axioms RvMBridge28.integral_fract_eq_shifted
#print axioms RvMBridge28.integrableOn_sawtooth
#print axioms RvMBridge28.integral_sawtooth_nonpos
#print axioms RvMBridge28.integral_fract_mul_rpow_le
#print axioms RvMBridge28.norm_integral_fract_cpow_le
#print axioms RvMBridge28.integral_fract_cpow_eq_of_zero
#print axioms RvMBridge28.zero_constraint
#print axioms RvMBridge28.zero_constraint_reflect
#print axioms RvMBridge28.box_one_sq
#print axioms RvMBridge28.box_one
#print axioms RvMBridge28.box_two
#print axioms RvMBridge28.one_sub_inv_eq_div_normSq
#print axioms RvMBridge28.liKernel_re_eq
#print axioms RvMBridge28.liLimit_re_nonneg_of_termwise
#print axioms RvMBridge28.re_pow_two
#print axioms RvMBridge28.re_pow_three
#print axioms RvMBridge28.re_pow_four
#print axioms RvMBridge28.re_pow_five
#print axioms RvMBridge28.ne_zero_of_nontrivial
#print axioms RvMBridge28.liKernel_two_re_nonneg
#print axioms RvMBridge28.liKernel_three_re_nonneg
#print axioms RvMBridge28.liKernel_four_re_nonneg
#print axioms RvMBridge28.liLimit_two_re_nonneg
#print axioms RvMBridge28.liLimit_three_re_nonneg
#print axioms RvMBridge28.liLimit_four_re_nonneg
#print axioms RvMBridge28.archSide_add_finiteSide_two_re_nonneg
#print axioms RvMBridge28.archSide_add_finiteSide_three_re_nonneg
#print axioms RvMBridge28.archSide_add_finiteSide_four_re_nonneg
#print axioms RvMBridge28.li5c0
#print axioms RvMBridge28.li5c1
#print axioms RvMBridge28.li5c2
#print axioms RvMBridge28.li5c3
#print axioms RvMBridge28.li5c4
#print axioms RvMBridge28.li5c4_nonneg
#print axioms RvMBridge28.li5c3_nonneg
#print axioms RvMBridge28.li5c2_nonneg
#print axioms RvMBridge28.li5c1_nonneg
#print axioms RvMBridge28.li5c0_nonneg
#print axioms RvMBridge28.rung5_identity
#print axioms RvMBridge28.liKernel_five_re_nonneg
#print axioms RvMBridge28.liLimit_five_re_nonneg
#print axioms RvMBridge28.archSide_add_finiteSide_five_re_nonneg
#print axioms RvMBridge6.zeroMult_reflect
#print axioms Zeta23.zeta_reflect_zero
#print axioms RvMBridge6.reflectEquiv
#print axioms RvMBridge15.summable_liPaired
#print axioms RvMBridge15.liPaired_re
#print axioms RvMBridge4.zeroMult_eq_zero_of_not_nontrivial
#print axioms RvMBridge27.liValue
#print axioms Zeta0EqZeta
#check @RvMBridge6.reflectEquiv
#check @RvMBridge15.norm_one_sub_inv_of_on_line
#check @RvMBridge28.liLimit_re_nonneg_of_line_below
