import E6Bridge17
#print axioms RvMBridge17.plainGauss
#print axioms RvMBridge17.Theta
#print axioms RvMBridge17.pterm
#print axioms RvMBridge17.zeroSide_plain_eq
#print axioms RvMBridge17.theta_eq
#print axioms RvMBridge17.plainGauss_re_exponent
#print axioms RvMBridge17.plainGauss_im_exponent
#print axioms RvMBridge17.norm_plainGauss
#print axioms RvMBridge17.norm_pterm
#print axioms RvMBridge17.re_plainGauss
#print axioms RvMBridge17.plainGauss_conj
#print axioms RvMBridge17.plainGauss_ofReal
#print axioms RvMBridge17.pterm_eq_zero_of_not_nontrivial
#print axioms RvMBridge17.norm_plainGauss_mul_le
#print axioms RvMBridge17.plainC
#print axioms RvMBridge17.plainC_nonneg
#print axioms RvMBridge17.norm_pterm_le
#print axioms RvMBridge17.summable_plain_zeroSide
#print axioms RvMBridge17.zeroSide_plain_im
#print axioms RvMBridge17.pterm_re_nonneg_of_rh
#print axioms RvMBridge17.theta_nonneg_of_rh
#print axioms RvMBridge17.exists_lam_cos_neg_one
#print axioms RvMBridge17.badSet'
#print axioms RvMBridge17.exists_generic_centre'
#print axioms RvMBridge17.pmajorant
#print axioms RvMBridge17.pmajorant_nonneg
#print axioms RvMBridge17.summable_pmajorant
#print axioms RvMBridge17.norm_pterm_le_pmajorant
#print axioms RvMBridge17.pconstA
#print axioms RvMBridge17.pconstB
#print axioms RvMBridge17.pconstA_nonneg
#print axioms RvMBridge17.pconstB_nonneg
#print axioms RvMBridge17.tsum_pmajorant
#print axioms RvMBridge17.ptail_bound
#print axioms RvMBridge17.theta_le_pair_add_tail
#print axioms RvMBridge17.exists_theta_neg_of_offline
#print axioms RvMBridge17.rh_iff_theta_positivity
#print axioms RvMBridge17.heatVar
#print axioms RvMBridge17.heatKernel
#print axioms RvMBridge17.heatVar_pos
#print axioms RvMBridge17.heatKernel_nonneg
#print axioms RvMBridge17.continuous_heatKernel
#print axioms RvMBridge17.heat_A_eq
#print axioms RvMBridge17.heat_integrand_eq
#print axioms RvMBridge17.plainGauss_heat
#print axioms RvMBridge17.real_gauss_heat
#print axioms RvMBridge17.heatF
#print axioms RvMBridge17.integrable_heatF
#print axioms RvMBridge17.integral_norm_heatF_le
#print axioms RvMBridge17.summable_integral_norm_heatF
#print axioms RvMBridgeXi.nontrivialZeros_countable
#print axioms RvMBridge17.NZ
#print axioms RvMBridge17.tsum_pterm_NZ
#print axioms RvMBridge17.tsum_pterm_re_NZ
#print axioms RvMBridge17.theta_heat
#print axioms RvMBridge17.theta_pos_mono
#print axioms RvMBridge17.ThetaFree
#print axioms RvMBridge17.ThetaWidths
#print axioms RvMBridge17.thetaFree_mono
#print axioms RvMBridge17.thetaWidths_Ioc_subset
#print axioms RvMBridge17.rh_iff_thetaFree_all
#print axioms RvMBridge17.rh_iff_thetaWidths_eq
#print axioms RvMBridge17.not_thetaFree_of_offline
#print axioms RvMBridge17.thetaWidths_bddAbove_of_offline
#print axioms RvMBridge17.rh_or_thetaWidths_bddAbove
#check @RvMBridge17.rh_iff_theta_positivity
#check @RvMBridge17.theta_heat
#check @RvMBridge17.theta_pos_mono
#check @RvMBridge17.rh_iff_thetaWidths_eq
