import E6Bridge20
#print axioms RvMBridge18.xi
#print axioms RvMBridge18.xi_differentiable
#print axioms RvMBridge18.xi_eq
#print axioms RvMBridge18.xi_eventuallyEq
#print axioms RvMBridge18.logDeriv_xi_eq
#print axioms RvMBridge18.normSq_gammaOf_le
#print axioms RvMBridge18.polTerm
#print axioms RvMBridge18.polTerm_eq_zero_of_not_nontrivial
#print axioms RvMBridge18.norm_polTerm
#print axioms RvMBridge18.norm_polTerm_le_majorant
#print axioms RvMBridge18.finite_zeros_near
#print axioms RvMBridge18.polBound
#print axioms RvMBridge18.summable_polBound
#print axioms RvMBridge18.norm_polTerm_le
#print axioms RvMBridge18.summable_inv_sub_sq
#print axioms RvMBridge18.summable_polTerm
#print axioms RvMBridge18.xiDiffReg
#print axioms RvMBridge18.XiLogDerivDerivEq
#print axioms RvMBridge18.XiDiffRegular
#print axioms RvMBridge18.XiLogDerivDerivDecay
#print axioms RvMBridge18.norm_polTerm_le_real
#print axioms RvMBridge18.polTerm_tendsto_zero
#print axioms RvMBridge18.tsum_inv_sub_sq_tendsto
#print axioms RvMBridge18.eq_const_of_log_growth
#print axioms RvMBridge18.not_nontrivialZero_of_one_le_re
#print axioms RvMBridge18.xi_logDeriv_deriv_eq_of
#print axioms RvMBridgeXi.xi_one_sub
#print axioms RvMBridgeXi.xi_one
#print axioms RvMBridge20.xi_ne_zero_of_one_le_re
#print axioms RvMBridgeXi.xi_eq_zero_iff
#print axioms RvMBridgeXi.xi_ne_zero_of_not_nontrivial
#print axioms RvMBridge20.analyticOrderAt_xi_ne_top
#print axioms RvMBridge20.analyticAt_completedZeta
#print axioms RvMBridge20.analyticOrderAt_xi_eq_of_zero
#print axioms RvMBridge20.analyticOrderAt_xi_eq
#print axioms RvMBridge20.restTerm
#print axioms RvMBridge20.tsum_polTerm_eq
#print axioms RvMBridge20.nearZeros
#print axioms RvMBridge20.nearZeros_finite
#print axioms RvMBridge20.exists_ball_avoid
#print axioms RvMBridge20.polTerm_differentiableAt
#print axioms RvMBridge20.exists_ball_rest
#print axioms RvMBridge20.exists_unit_factor
#print axioms RvMBridgeXi.analyticAt_logDeriv
#print axioms RvMBridge20.deriv_logDeriv_xi_local
#print axioms RvMBridge20.exists_local_form
#print axioms RvMBridge20.xiDiffExt
#print axioms RvMBridge20.xiDiffExt_eq
#print axioms RvMBridge20.xiDiffExt_eventuallyEq
#print axioms RvMBridge20.xiDiffExt_differentiable
#print axioms RvMBridge20.isNontrivialZero_one_sub_iff
#print axioms RvMBridgeXi.logDeriv_xi_one_sub
#print axioms RvMBridgeXi.deriv_logDeriv_xi_one_sub
#print axioms RvMBridgeXi.oneSubEquiv
#print axioms RvMBridgeXi.zeroMult_one_sub
#print axioms RvMBridgeXi.tsum_polTerm_one_sub
#print axioms RvMBridge20.xiDiffReg_one_sub
#print axioms RvMBridge20.xiDiffExt_one_sub
#print axioms RvMBridge20.XiDiffExtGrowth
#print axioms RvMBridge20.XiDiffExtGrowthRight
#print axioms RvMBridge20.xiDiffExtGrowth_of_right
#print axioms RvMBridge20.xiDiffRegular_of
#print axioms RvMBridge20.xiDiffRegular_of_right
#check @RvMBridge18.xi_logDeriv_deriv_eq_of
#check @RvMBridge20.xiDiffRegular_of_right
#print RvMBridge18.xi
#print RvMBridge20.XiDiffExtGrowthRight
