import E6Bridge15
open Zeta23 Complex Filter Topology
#check @Zeta23.WeilEF.xi
#check @Zeta23.WeilEF.xi_eq
#check @Zeta23.WeilEF.xi_differentiable
#check @Zeta23.WeilEF.xi_one_sub
#check @riemannZeta₁
#check @riemannZeta₁_one
#check @deriv_riemannZeta₁_one
#check @differentiable_riemannZeta₁
#check @riemannZeta_eq_inv_sub_mul
#check @riemannZeta_eventually_ne_zero_nhds_one
#check @tsum_even_add_odd
#check @Summable.even_add_odd
#check @zeta_nat_eq_tsum_of_gt_one
#check @Zeta23.hasSum_digamma_series
#check @Zeta23.RvM.logDeriv_Gammaℝ
#check @Zeta23.WeilEF.logDeriv_completedZeta
#check @hasDerivAt_tsum_of_isPreconnected
#check @intervalIntegral.integral_eq_sub_of_hasDerivAt
#check @intervalIntegral.tsum_intervalIntegral_eq_of_summable_norm
#check @MeasureTheory.integral_tsum
#check @Filter.EventuallyEq.iteratedDeriv_eq
#check @iteratedDeriv_add
#check @iteratedDeriv_comp_neg
#check @iter_deriv_inv_linear_sub
#check @iteratedDeriv_const_mul_field
#check @Complex.re_tsum
#check @Complex.digamma_one_half
#check @Zeta23.zetaSeam.finite_window
#check @RvMBridge6.summable_mult_div_one_add_normSq
#check @RvMBridge6.zeroMult_reflect
#check @RvMBridge6.reflectEquiv
#check @RvMBridge4.zeroMult_eq_zero_of_not_nontrivial
#check @logDeriv_apply
#check @tsum_sum
#check @Summable.tsum_finsetSum
#check @HasDerivAt.comp_ofReal
#check @Complex.integerComplement
#check @tendsto_riemannZeta_sub_one_div
#check @riemannZeta_conj
#check @AnalyticAt.contDiffAt
#check @Differentiable.contDiff
#check @iteratedDeriv_eq_iterate
#check @Complex.ofReal_tsum
#check @Summable.of_norm_bounded
#check @zeroMult
#check @Complex.exp_ne_zero
