"""Generate the Lean data + convolution-identity proofs for Davenport-Heilbronn's -D'/D coefficients."""
import json
import sympy as sp
from fractions import Fraction as Fr
d = json.load(open('dh_coeffs.json'))
def fq(x):
    x = Fr(x)
    if x.denominator == 1:
        return '(%d : ℚ)' % x.numerator
    return '((%d : ℚ) / %d)' % (x.numerator, x.denominator)
L = []
L.append('/-- The data of `c_D(n)`, `n <= 56`: a list of `(p, [q_0, q_1, ...])` meaning')
L.append('`sum_p (sum_i q_i kappa^i) log p` (generated by the lane\'s gen_dh.py from the exact recursion). -/')
L.append('def dtab : ℕ → List (ℕ × List ℚ)')
for n in range(2, 57):
    terms = d[str(n)]
    if not terms:
        continue
    items = []
    for p, poly in sorted(terms.items(), key=lambda t: int(t[0])):
        degs = {int(k): v for k, v in poly.items()}
        mx = max(degs)
        coeffs = [fq(degs.get(i, 0)) for i in range(mx + 1)]
        items.append('(%s, [%s])' % (p, ', '.join(coeffs)))
    L.append('  | %d => [%s]' % (n, ', '.join(items)))
L.append('  | _ => []')
open('dtab.lean', 'w').write('\n'.join(L) + '\n')
# convolution proofs: one lemma per n (a single theorem with 56 cases times out), then the dispatcher
P = []
for n in range(1, 57):
    divs = sp.divisors(n)
    P.append('lemma cD_conv_%d : aD %d * Real.log (%d : ℕ) = ∑ d ∈ Nat.divisors %d, cD d * aD (%d / d) := by' % (n, n, n, n, n))
    P.append('  have hdiv : Nat.divisors %d = {%s} := by decide' % (n, ', '.join(str(x) for x in divs)))
    P.append('  rw [hdiv]')
    ins = []
    for i in range(len(divs) - 1):
        rest = divs[i + 1:]
        ins.append('Finset.sum_insert (show (%d : ℕ) ∉ ({%s} : Finset ℕ) by decide)' % (divs[i], ', '.join(str(x) for x in rest)))
    ins.append('Finset.sum_singleton')
    P.append('  simp only [%s]' % ', '.join(ins))
    P.append('  simp only [cD, cDexpr, dtab, polyEval, aD, List.map, List.sum_cons, List.sum_nil]')
    P.append('  norm_num')
    fac = sp.factorint(n)
    if n > 1 and not (len(fac) == 1 and list(fac.values())[0] == 1):
        parts = sorted(fac.items())
        if len(parts) == 1:
            p, e = parts[0]
            P.append('  try rw [show (%d : ℝ) = (%d : ℝ) ^ %d by norm_num, Real.log_pow]' % (n, p, e))
        else:
            expr = ' * '.join('(%d : ℝ) ^ %d' % (p, e) for p, e in parts)
            rw = ['show (%d : ℝ) = %s by norm_num' % (n, expr)]
            rw += ['Real.log_mul (by positivity) (by positivity)'] * (len(parts) - 1)
            P.append('  try rw [%s]' % ', '.join(rw))
        P.append('  try simp only [Real.log_pow]')
    P.append('  try push_cast')
    P.append('  try ring')
    P.append('')
P.append("/-- The defining identity of the coefficients of `-D'/D` (`-D' = D (-D'/D)`), on `n <= 56`. -/")
P.append('theorem cD_conv : ∀ n : ℕ, 1 ≤ n → n ≤ 56 →')
P.append('    aD n * Real.log n = ∑ d ∈ n.divisors, cD d * aD (n / d) := by')
P.append('  intro n h1 h2')
P.append('  interval_cases n')
for n in range(1, 57):
    P.append('  · exact cD_conv_%d' % n)
open('dconv.lean', 'w').write('\n'.join(P) + '\n')
print('wrote dtab.lean, dconv.lean')
