/- Generated by telperion.emit_primality — Pratt/Lucas primality
   certificates discharged through Mathlib's `lucas_primality`.
   DO NOT EDIT BY HAND. -/

import Mathlib

namespace Primality

theorem isPrime_5 : Nat.Prime 5 := by
  refine lucas_primality 5 (2 : ZMod 5) ?_ ?_
  · decide
  · intro q hq hqd
    have hmem : q ∈ Nat.primeFactors (5 - 1) :=
      Nat.mem_primeFactors.mpr ⟨hq, hqd, by norm_num⟩
    fin_cases hmem <;> decide

theorem isPrime_23 : Nat.Prime 23 := by
  refine lucas_primality 23 (5 : ZMod 23) ?_ ?_
  · decide
  · intro q hq hqd
    have hmem : q ∈ Nat.primeFactors (23 - 1) :=
      Nat.mem_primeFactors.mpr ⟨hq, hqd, by norm_num⟩
    fin_cases hmem <;> decide

theorem isPrime_101 : Nat.Prime 101 := by
  refine lucas_primality 101 (2 : ZMod 101) ?_ ?_
  · decide
  · intro q hq hqd
    have hmem : q ∈ Nat.primeFactors (101 - 1) :=
      Nat.mem_primeFactors.mpr ⟨hq, hqd, by norm_num⟩
    fin_cases hmem <;> decide

end Primality
