/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node bg/BG_merge_layer.
   The TYPE below is the registered statement, missions/bg/lean/Statements/
   BG_merge_layer.lean (header sha256 792f475ee7fbd6c5), binders and conclusion verbatim; the
   PROOF is the artifact constant `R3Cert.Step3.merge_normalForm_perL` from R3Cert.R47MergePerL. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   The other imports are the island modules the campaign's vocabulary mirror copies
   from, so a vocabulary constant shadowed by the artifact is a duplicate
   declaration here, not a silent substitution. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import R3Cert.R47MergePerL
import R3Cert.BGSCLHdom
import R3Cert.BGSCLInduction
import R3Cert.BridgeStep3
import R3Cert.BridgeStep3e
import R3Cert.CappedJointAchievable
import R3Cert.CappedJointConfig
import R3Cert.CavityTree
import R3Cert.ExactCruxes
import R3Cert.GStepCore
import R3Cert.Matching
import R3Cert.NearStar
import R3Cert.Plainify
import R3Cert.Potential
import R3Cert.PotentialBound
import R3Cert.R47BGConjecture
import R3Cert.R47Backbone
import R3Cert.R47Capped
import R3Cert.R47HubState
import R3Cert.R47OrderedStep
import R3Cert.R47R7Sized
import R3Cert.R47R7Straighten
import R3Cert.R47Step
import R3Cert.R47StepSize
import R3Cert.R47Tree
import R3Cert.Reach
import R3Cert.Sweep

namespace R3Cert.Step3

open RTree

theorem _root_.MissionJudge.BG_merge_layer :
    ∀ (s : List Hub) (hbal : Balanced s) (hcap : Capped s), ∃ t, Relation.ReflTransGen OrderedStep s t ∧ (∀ u, ¬ OrderedStep t u) ∧
      (lapl (aGraph (realize (dtRealize (backboneU s))))).permanent
          / (∏ v, ((aGraph (realize (dtRealize (backboneU s)))).degree v : ℝ))
        ≤ (lapl (aGraph (realize (dtRealize (backboneU t))))).permanent
          / (∏ v, ((aGraph (realize (dtRealize (backboneU t)))).degree v : ℝ)) :=
  R3Cert.Step3.merge_normalForm_perL

end R3Cert.Step3
