-- DO NOT EDIT BY HAND — generated by telperion mission; node BG_near_star_tie; sha256 9d6e0d4c9e856484
import Statements.BGDefs
open R3Cert

theorem nearStar_tie (c k : ℕ) (h : c + k = 5) : logPhi (nearStarB c k) = 0 := by sorry
