-- DO NOT EDIT BY HAND — generated by telperion mission; node BG_ratio_rate_bound; sha256 82a47b9004278c1e
import Statements.BGDefs
open R3Cert R3Cert.Step3

theorem perm_ratio_le_rate (cs : List UTree) (hpos : 0 < cs.length) :
    (lapl (aGraph (realize (dtRealize (UTree.node cs))))).permanent
        / (∏ v, ((aGraph (realize (dtRealize (UTree.node cs)))).degree v : ℝ))
      ≤ ((cs.length : ℝ) + 1) / (cs.length : ℝ)
          * rhoB ^ usize (UTree.node cs) := by sorry
