-- DO NOT EDIT BY HAND — generated by telperion mission; node BG_tie_root_degree; sha256 5a93a593a50a8d3c
import Statements.BGDefs
open R3Cert.BGSCL

theorem bcc_eq_five_of_bell_eq_zero {b : Branch} (h : bell b = 0) : bcc b = 5 := by sorry
