/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node rh/RH_li_ladder_height_sharp.
   The TYPE below is the registered statement, missions/rh/lean/Statements/
   RH_li_ladder_height_sharp.lean (header sha256 d5ada182fa53be39), binders and conclusion verbatim; the
   PROOF is the artifact constant `LiLadderHeight.li_rung_of_zeros_on_line_below_sharp` from LiLadderSharp. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   The AxiomGuard imports load the whole island, so a vocabulary constant shadowed by
   the artifact is a duplicate declaration here, not a silent substitution. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import LiLadderSharp
import AxiomGuardLiPositivity

namespace LiLadderHeight

open scoped Real
open LiCriterion
open LiFacePrelude

theorem _root_.MissionJudge.RH_li_ladder_height_sharp :
    ∀ (T : ℝ) (hT : 1 ≤ T)
    (hline : ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.re → ρ.re < 1 → |ρ.im| ≤ T → ρ.re = 1 / 2)
    (n : ℕ) (hn : (n + 1 : ℝ) ≤ 2 * π * (T - 1 / 2)), 0 ≤ (taylorCoeff riemannXi n).re :=
  LiLadderHeight.li_rung_of_zeros_on_line_below_sharp

end LiLadderHeight
