/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node rh/RH_zeta_log_bound.
   The TYPE below is the registered statement, missions/rh/lean/Statements/
   RH_zeta_log_bound.lean (header sha256 9482553b398bc972), binders and conclusion verbatim; the
   PROOF is the artifact constant `ZeroFreeBridge.zeta_log_bound` from ZetaLogBound. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   The AxiomGuard imports load the whole island, so a vocabulary constant shadowed by
   the artifact is a duplicate declaration here, not a silent substitution. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import ZetaLogBound
import AxiomGuardLiPositivity

namespace ZeroFreeBridge

open MeasureTheory Filter Topology Set

theorem _root_.MissionJudge.RH_zeta_log_bound :
    ∀ {σ t : ℝ} (hσ1 : 1 ≤ σ) (hσ2 : σ ≤ 2) (ht : 2 ≤ |t|), ‖riemannZeta ((σ : ℂ) + t * Complex.I)‖ ≤ 6 * (1 + Real.log |t|) :=
  ZeroFreeBridge.zeta_log_bound

end ZeroFreeBridge
