-- GENERATED by campaign.py register-lakefile --sharded; DO NOT EDIT.
-- Block-top axiom battery for ZetaBands_h550000: `lake build` fails unless the
-- capstone depends on exactly [propext, Classical.choice, Quot.sound].
-- conjecture1_proved = False (finite localization to height 550000, not RH).
import AllZeros_h550000
/-- info: 'AllZeros_h550000.all_nontrivial_zeros_up_to_height_550000_of_bands' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms AllZeros_h550000.all_nontrivial_zeros_up_to_height_550000_of_bands
