/-
Copyright (c) 2026 Anthropic, PBC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
SPDX-License-Identifier: Apache-2.0
-/
/-
QuadrupleDefect.lean -- MIRRORMERE W2b, the FUNCTIONAL-EQUATION QUADRUPLE AUDIT of the
defect-counting story.

This file discharges the two skeptic caveats standing against the W2b cluster
(`telperion/docs/RH_ROUTES_ROADMAP_2026-09-16.md` Route A):

  * **Quadruple caveat.** "genuine off-line zeros come in functional-equation quadruples
    (rho, 1-rho, conj rho, 1-conj rho), not free pairs; witness-dimension bookkeeping per
    quadruple is an unresolved detail in the defect-counting story."
  * **A2a caveat.** "the theorem quantifies over a synthetic 2x2 block, not the 29-zero data."

## What is settled here, and what it costs the headline claim

**(1) The sigma-pair count of one genuine off-line quadruple is exactly TWO.**
`offline_quadruple_sigma_pair_count`.  The block decomposition of `DefectDictionary` is indexed by
orbits of the involution `sigma rho = 1 - conj rho` (reflection across the critical line), NOT by
zeros and NOT by quadruples.  A zero `rho` with `re rho != 1/2` and `im rho != 0` has a
four-element orbit `{rho, 1-rho, conj rho, 1-conj rho}` under the Klein group generated by `sigma`
and complex conjugation, and that orbit splits into exactly two `sigma`-orbits,
`{rho, 1-conj rho}` and `{conj rho, 1-rho}`.  So ONE genuine off-line zero contributes `p = 2`,
not `p = 1`.  Degenerations are kernel-checked too: a *real* off-line zero (`im rho = 0`) gives a
two-element orbit that is a SINGLE sigma-pair (`quad_real_offline`, `p = 1`), and an on-line zero
is sigma-FIXED (`quad_online`, `p = 0`).

**(2) The witness dimension of a quadruple is NOT determined by the quadruple.**
`quadruple_witness_dimension_not_determined`.  Two configurations of the SAME ambient dimension,
the SAME on-line channel and the SAME number (two) of nonzero off-line channels have defects `1`
and `2` respectively.  The defect measures `dim span {y_j}` -- the rank of the imaginary channel
span -- and the quadruple structure does not fix it.  Concretely, the degenerate configuration is
the one forced by the *reflection-degenerate* evaluation relation `v (conj rho) = conj (v rho)`
(`degenerate_channels`): then `x_2 = x_1` and `y_2 = -y_1`, the two sigma-pairs of the quadruple
carry the SAME rank-one negative channel, and the quadruple leaks ONE negative direction while
contributing `p = 2`.  That relation is not exotic: it is exactly what a node set pointwise
invariant under `tau |-> -tau` (e.g. a single node at the origin) produces.

**Consequence for the advertised dictionary.**  `DefectDictionary.PairDecomp.defect_le_offline_pairs`
(`defect <= p`) is unconditional and survives.  The converse `p <= defect`
(`R2Rigidity.offline_pairs_le_defect`) is TRUE AS STATED -- it carries a `NegativeWitness` of
dimension `p` as an explicit hypothesis -- but the *gloss* "the instrument COUNTS the off-line
pairs" is NOT unconditional: `defect_parallel_channels_eq_one` exhibits a two-channel configuration
where `p = 2` and `defect = 1`, so the `NegativeWitness` hypothesis is load-bearing and can FAIL for
a genuine off-line quadruple.  The honest unconditional statement per quadruple is
`1 <= contribution <= 2`, and the honest headline for a window with `q` genuine off-line quadruples
is `defect <= 2q` (`defect_quadruple_block_le`), with equality only under an independence witness
for all `2q` imaginary channels.

**(3) The synthetic-2x2 caveat, answered.**  `sumPairBlock` is the pair block with an ARBITRARY
finite number `m` of on-line square channels, an ARBITRARY finite number `k` of off-line channels,
in an ARBITRARY finite ambient dimension `d`.  `defect_sumPairBlock_le` (defect <= k) is
unconditional at that generality, and `defect_sumPairBlock_eq` (defect = k) holds under two finite
kernel-checkable hypotheses: linear independence of the `k` imaginary channels and their
orthogonality to the on-line channels.  The `2x2` and `4x4` blocks of `BraggDefect` are the
`m = k = 1` and `m = k = 2` specializations (`sumPairBlock_two`).  The extension is FREE in size
and count; it is NOT free in the separation hypothesis -- without orthogonality to the on-line
channels the on-line part can neutralize an off-line direction, and no unconditional lower bound
on the defect survives (the named residual obligation, see `README` of this file's docstring
below).

**Named residual obligation (not proved here).**  `QuadrupleChannelIndependence`: for the zeta
comb, the `2q` imaginary evaluation channels of `q` genuine off-line quadruples in a window are
linearly independent and orthogonal to the on-line channels.  Nothing in this file, and nothing in
the corpus, proves that; the migration readback of `MM_offline_pairs_le_defect` asserts it
("Vandermonde-type test vectors keep them linearly independent") without proof.  It is a finite,
checkable statement for any concrete node set -- and `degenerate_channels` shows it is FALSE for
flip-invariant node sets.

zeta-free, finite, kernel arithmetic.  conjecture1_proved = False.
-/
import Mathlib
import DefectDictionary
import R2Rigidity

noncomputable section

open Matrix Finset Submodule RHLinalg DefectDictionary
open scoped ComplexOrder BigOperators

namespace QuadrupleDefect

/-! ## Section 1. The functional-equation quadruple and its sigma-pair count

Everything in this section is about the complex plane alone -- no zeta, no analysis.  It is the
combinatorics of the two involutions that the functional equation and the reality of zeta impose
on the zero set: `rho |-> 1 - rho` (functional equation) and `rho |-> conj rho` (reality).  Their
composite is the block-decomposition involution `sigma rho = 1 - conj rho`, reflection across the
critical line, which is the one `DefectDictionary`'s pair blocks are indexed by. -/

/-- The block-decomposition involution: reflection across the critical line,
`sigma rho = 1 - conj rho`.  `DefectDictionary`'s "off-line pair" is a `sigma`-orbit. -/
def sigmaRefl (s : ℂ) : ℂ := 1 - (starRingEnd ℂ) s

/-- The functional-equation quadruple of `rho`: the orbit of `rho` under the Klein group generated
by `rho |-> 1 - rho` (functional equation) and `rho |-> conj rho` (reality of zeta). -/
def quad (s : ℂ) : Finset ℂ := {s, 1 - s, (starRingEnd ℂ) s, 1 - (starRingEnd ℂ) s}

/-- A `sigma`-orbit ("off-line pair" in the dictionary's sense). -/
def sigmaPair (s : ℂ) : Finset ℂ := {s, sigmaRefl s}

/-- The `sigma`-orbits inside the quadruple of `rho`. -/
def quadSigmaPairs (s : ℂ) : Finset (Finset ℂ) :=
  {sigmaPair s, sigmaPair ((starRingEnd ℂ) s)}

lemma sigmaRefl_involutive (s : ℂ) : sigmaRefl (sigmaRefl s) = s := by
  simp [sigmaRefl]

/-- `sigma` fixes exactly the critical line. -/
lemma sigmaRefl_eq_self_iff (s : ℂ) : sigmaRefl s = s ↔ s.re = 1 / 2 := by
  simp only [sigmaRefl, Complex.ext_iff, Complex.sub_re, Complex.sub_im, Complex.one_re,
    Complex.one_im, Complex.conj_re, Complex.conj_im]
  constructor
  · rintro ⟨h, -⟩; linarith
  · intro h; constructor <;> [linarith; ring]

/-- The second `sigma`-orbit of the quadruple is `{conj rho, 1 - rho}`. -/
lemma sigmaPair_conj (s : ℂ) :
    sigmaPair ((starRingEnd ℂ) s) = {(starRingEnd ℂ) s, 1 - s} := by
  unfold sigmaPair sigmaRefl
  rw [Complex.conj_conj]

/-- The six pairwise distinctness facts for a GENUINE off-line zero (`re != 1/2`, `im != 0`). -/
lemma quad_pairwise_ne {s : ℂ} (h1 : s.re ≠ 1 / 2) (h2 : s.im ≠ 0) :
    s ≠ 1 - s ∧ s ≠ (starRingEnd ℂ) s ∧ s ≠ 1 - (starRingEnd ℂ) s ∧
    (1 - s) ≠ (starRingEnd ℂ) s ∧ (1 - s) ≠ 1 - (starRingEnd ℂ) s ∧
    (starRingEnd ℂ) s ≠ 1 - (starRingEnd ℂ) s := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩ <;> intro h
  · exact h1 (by have := congrArg Complex.re h; simp at this; linarith)
  · exact h2 (by have := congrArg Complex.im h; simp at this; linarith)
  · exact h1 (by have := congrArg Complex.re h; simp at this; linarith)
  · exact h1 (by have := congrArg Complex.re h; simp at this; linarith)
  · exact h2 (by have := congrArg Complex.im h; simp at this; linarith)
  · exact h1 (by have := congrArg Complex.re h; simp at this; linarith)

/-- **A genuine off-line zero has a four-element quadruple.** -/
theorem quad_card_eq_four {s : ℂ} (h1 : s.re ≠ 1 / 2) (h2 : s.im ≠ 0) :
    (quad s).card = 4 := by
  obtain ⟨d1, d2, d3, d4, d5, d6⟩ := quad_pairwise_ne h1 h2
  unfold quad
  rw [Finset.card_insert_of_notMem (by simp [d1, d2, d3]),
      Finset.card_insert_of_notMem (by simp [d4, d5]),
      Finset.card_insert_of_notMem (by simp [d6]),
      Finset.card_singleton]

/-- The quadruple is the union of the two `sigma`-orbits `{rho, 1-conj rho}` and
`{conj rho, 1-rho}`. -/
theorem quad_eq_union (s : ℂ) :
    quad s = sigmaPair s ∪ sigmaPair ((starRingEnd ℂ) s) := by
  ext z
  simp only [quad, sigmaPair, sigmaRefl, Complex.conj_conj, Finset.mem_insert,
    Finset.mem_singleton, Finset.mem_union]
  tauto

/-- The two `sigma`-orbits of a genuine off-line quadruple are disjoint. -/
theorem sigmaPair_disjoint {s : ℂ} (h1 : s.re ≠ 1 / 2) (h2 : s.im ≠ 0) :
    Disjoint (sigmaPair s) (sigmaPair ((starRingEnd ℂ) s)) := by
  obtain ⟨d1, d2, d3, d4, d5, d6⟩ := quad_pairwise_ne h1 h2
  rw [Finset.disjoint_left]
  intro a ha hb
  simp only [sigmaPair, sigmaRefl, Complex.conj_conj, Finset.mem_insert,
    Finset.mem_singleton] at ha hb
  rcases ha with rfl | rfl <;> rcases hb with h | h
  · exact d2 h
  · exact d1 h
  · exact d6 h.symm
  · exact d5 h.symm

/-- The two `sigma`-orbits of a genuine off-line quadruple are DISTINCT orbits. -/
lemma sigmaPair_ne_conj {s : ℂ} (h1 : s.re ≠ 1 / 2) (h2 : s.im ≠ 0) :
    sigmaPair s ≠ sigmaPair ((starRingEnd ℂ) s) := by
  obtain ⟨d1, d2, -, -, -, -⟩ := quad_pairwise_ne h1 h2
  intro hEq
  have hs : s ∈ sigmaPair ((starRingEnd ℂ) s) := by
    rw [← hEq]; simp [sigmaPair]
  rw [sigmaPair_conj] at hs
  simp only [Finset.mem_insert, Finset.mem_singleton] at hs
  rcases hs with h | h
  · exact d2 h
  · exact d1 h

/-- **THE ANSWER TO THE QUADRUPLE CAVEAT.**  A genuine off-line zero of the functional-equation
quadruple type -- `re rho != 1/2` (off the critical line) and `im rho != 0` (not real) -- has a
four-element quadruple which splits into EXACTLY TWO disjoint `sigma`-orbits.  Since
`DefectDictionary`'s off-line-pair counter `p` counts `sigma`-orbits, one genuine off-line zero
costs `p = 2`, not `p = 1`. -/
theorem offline_quadruple_sigma_pair_count {s : ℂ} (h1 : s.re ≠ 1 / 2) (h2 : s.im ≠ 0) :
    (quad s).card = 4 ∧
    quad s = sigmaPair s ∪ sigmaPair ((starRingEnd ℂ) s) ∧
    Disjoint (sigmaPair s) (sigmaPair ((starRingEnd ℂ) s)) ∧
    (quadSigmaPairs s).card = 2 := by
  refine ⟨quad_card_eq_four h1 h2, quad_eq_union s, sigmaPair_disjoint h1 h2, ?_⟩
  unfold quadSigmaPairs
  rw [Finset.card_insert_of_notMem (by simpa using sigmaPair_ne_conj h1 h2),
    Finset.card_singleton]

/-- **Degeneration 1: a REAL off-line zero is a single `sigma`-pair (`p = 1`).**  If `im rho = 0`
then `conj rho = rho`, the quadruple collapses to the two-element set `{rho, 1-rho}`, and that set
is a single `sigma`-orbit.  (For zeta this case is empty -- zeta has no real zeros in the critical
strip -- but the bookkeeping must handle it, and nothing in `DefectDictionary` excludes it.) -/
theorem quad_real_offline {s : ℂ} (h1 : s.re ≠ 1 / 2) (h2 : s.im = 0) :
    quad s = sigmaPair s ∧ (quad s).card = 2 := by
  have hconj : (starRingEnd ℂ) s = s := by
    simp [Complex.ext_iff, h2]
  have hne : s ≠ 1 - s := by
    intro h
    exact h1 (by have := congrArg Complex.re h; simp at this; linarith)
  have hq : quad s = ({s, 1 - s} : Finset ℂ) := by
    ext z
    simp only [quad, hconj, Finset.mem_insert, Finset.mem_singleton]
    tauto
  refine ⟨?_, ?_⟩
  · rw [hq]
    unfold sigmaPair sigmaRefl
    rw [hconj]
  · rw [hq, Finset.card_insert_of_notMem (by simpa using hne), Finset.card_singleton]

/-- On the critical line the functional-equation partner IS the conjugate: `1 - rho = conj rho`.
This is why an on-line zero's "quadruple" has only two members. -/
lemma fe_eq_conj_of_online {s : ℂ} (h1 : s.re = 1 / 2) : 1 - s = (starRingEnd ℂ) s := by
  apply Complex.ext
  · simp only [Complex.sub_re, Complex.one_re, Complex.conj_re]; linarith
  · simp only [Complex.sub_im, Complex.one_im, Complex.conj_im]; ring

/-- **Non-vacuity of `quad_card_eq_four`: an ON-LINE point has a TWO-element quadruple.**  So the
hypothesis `re rho != 1/2` is load-bearing, and the on-line contribution to the off-line pair count
is `p = 0` (both members are `sigma`-fixed, `quad_online`). -/
theorem quad_online_card {s : ℂ} (h1 : s.re = 1 / 2) (h2 : s.im ≠ 0) :
    quad s = {s, (starRingEnd ℂ) s} ∧ (quad s).card = 2 := by
  have hfe := fe_eq_conj_of_online h1
  have hfe' : 1 - (starRingEnd ℂ) s = s := by rw [← hfe]; ring
  have hne : s ≠ (starRingEnd ℂ) s := by
    intro h
    exact h2 (by have := congrArg Complex.im h; simp at this; linarith)
  have hq : quad s = ({s, (starRingEnd ℂ) s} : Finset ℂ) := by
    ext z
    simp only [quad, hfe, hfe', Finset.mem_insert, Finset.mem_singleton]
    tauto
  exact ⟨hq, by rw [hq, Finset.card_insert_of_notMem (by simpa using hne), Finset.card_singleton]⟩

/-- **Degeneration 2: an ON-LINE zero is `sigma`-fixed (`p = 0`).**  Both members of the collapsed
quadruple `{rho, conj rho}` are fixed by `sigma`, so an on-line zero contributes no off-line pair
at all. -/
theorem quad_online {s : ℂ} (h1 : s.re = 1 / 2) :
    sigmaRefl s = s ∧ sigmaRefl ((starRingEnd ℂ) s) = (starRingEnd ℂ) s := by
  refine ⟨(sigmaRefl_eq_self_iff s).2 h1, (sigmaRefl_eq_self_iff _).2 ?_⟩
  simpa using h1

/-! ## Section 2. The pair block at ARBITRARY size

The `BraggDefect` instantiations are `2x2` and `4x4` blocks with one and two channels.  This
section replaces them with the general object: `m` on-line square channels, `k` off-line channels,
ambient dimension `d` -- all arbitrary finite. -/

variable {d : Type*} [Fintype d] [DecidableEq d]

/-- The real dot product used throughout (the evaluation pairing of a test vector against a
channel vector). -/
def dotR (v w : d → ℝ) : ℝ := ∑ t, v t * w t

omit [DecidableEq d] in
lemma dotR_comm (v w : d → ℝ) : dotR v w = dotR w v := by
  unfold dotR; exact Finset.sum_congr rfl fun t _ => mul_comm _ _

omit [DecidableEq d] in
lemma dotR_self_eq_zero {v : d → ℝ} (h : dotR v v = 0) : v = 0 := by
  have hnn : ∀ t ∈ (Finset.univ : Finset d), (0 : ℝ) ≤ v t * v t := fun t _ => mul_self_nonneg _
  have := (Finset.sum_eq_zero_iff_of_nonneg hnn).mp h
  funext t
  have ht := this t (Finset.mem_univ t)
  simpa using mul_self_eq_zero.mp ht

/-- **The general pair block** `sum_i x_i x_i^T - sum_j y_j y_j^T`: `m` on-line square channels,
`k` off-line (imaginary) channels, ambient dimension `d`, all arbitrary finite. -/
def sumPairBlock {m k : ℕ} (x : Fin m → (d → ℝ)) (y : Fin k → (d → ℝ)) : Matrix d d ℝ :=
  (∑ i, vecMulVec (x i) (x i)) - (∑ j, vecMulVec (y j) (y j))

omit [DecidableEq d] in
lemma vecMulVec_psd (v : d → ℝ) : (vecMulVec v v).PosSemidef := by
  have h := posSemidef_vecMulVec_self_star v
  rwa [show (star v) = v from rfl] at h

omit [DecidableEq d] in
lemma sum_vecMulVec_psd {ι : Type*} (s : Finset ι) (y : ι → (d → ℝ)) :
    (∑ j ∈ s, vecMulVec (y j) (y j)).PosSemidef := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using (Matrix.PosSemidef.zero (n := d) (R := ℝ))
  | insert a s ha ih => rw [Finset.sum_insert ha]; exact (vecMulVec_psd (y a)).add ih

lemma sumPairBlock_isHermitian {m k : ℕ} (x : Fin m → (d → ℝ)) (y : Fin k → (d → ℝ)) :
    (sumPairBlock x y).IsHermitian :=
  (sum_vecMulVec_psd _ x).isHermitian.sub (sum_vecMulVec_psd _ y).isHermitian

/-- Rank subadditivity for positive-semidefinite summands (via `posIndex` subadditivity). -/
lemma rank_add_le_psd {P N : Matrix d d ℝ} (hP : P.PosSemidef) (hN : N.PosSemidef) :
    (P + N).rank ≤ P.rank + N.rank := by
  have h := posIndex_add_le hP.isHermitian hN.isHermitian
  rwa [posIndex_eq_rank_of_posSemidef (hP.add hN), posIndex_eq_rank_of_posSemidef hP,
    posIndex_eq_rank_of_posSemidef hN] at h

lemma rank_sum_vecMulVec_le {ι : Type*} (s : Finset ι) (y : ι → (d → ℝ)) :
    (∑ j ∈ s, vecMulVec (y j) (y j)).rank ≤ s.card := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert a s ha ih =>
      rw [Finset.sum_insert ha, Finset.card_insert_of_notMem ha]
      have h1 := rank_add_le_psd (vecMulVec_psd (y a)) (sum_vecMulVec_psd s y)
      have h2 : (vecMulVec (y a) (y a)).rank ≤ 1 := Matrix.rank_vecMulVec_le _ _
      omega

lemma hermForm_sum_vecMulVec {ι : Type*} (s : Finset ι) (y : ι → (d → ℝ)) (w : d → ℝ) :
    hermForm (∑ j ∈ s, vecMulVec (y j) (y j)) w = ∑ j ∈ s, (dotR w (y j)) ^ 2 := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [hermForm]
  | insert a s ha ih =>
      rw [Finset.sum_insert ha, hermForm_add, ih, Finset.sum_insert ha,
        hermForm_vecMulVec_real]
      rfl

/-- The general block's quadratic form: `sum_i <w,x_i>^2 - sum_j <w,y_j>^2`. -/
lemma hermForm_sumPairBlock {m k : ℕ} (x : Fin m → (d → ℝ)) (y : Fin k → (d → ℝ)) (w : d → ℝ) :
    hermForm (sumPairBlock x y) w =
      (∑ i, (dotR w (x i)) ^ 2) - (∑ j, (dotR w (y j)) ^ 2) := by
  unfold sumPairBlock
  rw [hermForm_sub, hermForm_sum_vecMulVec, hermForm_sum_vecMulVec]

/-- `defect` transported along an equality of matrices. -/
lemma defect_congr {A B : Matrix d d ℝ} (hA : A.IsHermitian) (hB : B.IsHermitian) (h : A = B) :
    defect hA = defect hB := by
  unfold defect
  exact posIndex_congr hA.neg hB.neg (by rw [h])

/-- **The general upper bound, sharpened to the negative-channel rank.**  `defect <= rank` of the
imaginary channel sum, at ARBITRARY size and channel count. -/
theorem defect_sumPairBlock_le_rank {m k : ℕ} (x : Fin m → (d → ℝ)) (y : Fin k → (d → ℝ)) :
    defect (sumPairBlock_isHermitian x y) ≤ (∑ j, vecMulVec (y j) (y j)).rank := by
  have hX := sum_vecMulVec_psd (Finset.univ : Finset (Fin m)) x
  have hY := sum_vecMulVec_psd (Finset.univ : Finset (Fin k)) y
  unfold defect
  rw [posIndex_congr (sumPairBlock_isHermitian x y).neg (hY.isHermitian.sub hX.isHermitian)
    (by unfold sumPairBlock; rw [neg_sub])]
  exact posIndex_sub_le_rank hY hX

/-- **Row (c) at arbitrary size** (the general-block replacement for `defect_pairBlock_le_one` and
`defect_twoPairBlock_le_two`): the defect of a block with `k` off-line channels is at most `k`,
for ANY ambient dimension and ANY number of on-line channels.  Unconditional. -/
theorem defect_sumPairBlock_le {m k : ℕ} (x : Fin m → (d → ℝ)) (y : Fin k → (d → ℝ)) :
    defect (sumPairBlock_isHermitian x y) ≤ k := by
  refine (defect_sumPairBlock_le_rank x y).trans ?_
  simpa using rank_sum_vecMulVec_le (Finset.univ : Finset (Fin k)) y

omit [DecidableEq d] in
/-- A linear functional vanishing on every channel vanishes on their span. -/
lemma dotR_eq_zero_of_mem_span {k : ℕ} {y : Fin k → (d → ℝ)} {v w : d → ℝ}
    (hv : v ∈ Submodule.span ℝ (Set.range y)) (h : ∀ j, dotR (y j) w = 0) :
    dotR v w = 0 := by
  induction hv using Submodule.span_induction with
  | mem z hz => obtain ⟨j, rfl⟩ := hz; exact h j
  | zero => simp [dotR]
  | add a b _ _ ha hb =>
      unfold dotR at ha hb ⊢
      simp only [Pi.add_apply, add_mul, Finset.sum_add_distrib, ha, hb, add_zero]
  | smul c a _ ha =>
      unfold dotR at ha ⊢
      simp only [Pi.smul_apply, smul_eq_mul, mul_assoc, ← Finset.mul_sum, ha, mul_zero]

/-- **The rigidity direction at arbitrary size.**  Any subspace `W` of the imaginary-channel span
on which every on-line channel functional vanishes is a negative-definite subspace of the block,
hence `dim W <= defect`.  No independence hypothesis, no dimension restriction: this is the honest
general form of the lower bound, and it makes the load-bearing hypothesis explicit -- `W` must
avoid the on-line channels. -/
theorem defect_sumPairBlock_ge_of_subspace {m k : ℕ} {x : Fin m → (d → ℝ)}
    {y : Fin k → (d → ℝ)} {W : Submodule ℝ (d → ℝ)}
    (hW : W ≤ Submodule.span ℝ (Set.range y))
    (hx : ∀ i, ∀ v ∈ W, dotR v (x i) = 0) :
    Module.finrank ℝ W ≤ defect (sumPairBlock_isHermitian x y) := by
  refine offline_pairs_le_defect (sumPairBlock_isHermitian x y)
    { W := W, posDefOn_neg := ?_, finrank_eq := rfl }
  intro v hv hvne
  rw [hermForm_neg, hermForm_sumPairBlock]
  have hxv : ∀ i, dotR v (x i) = 0 := fun i => hx i v hv
  have hzero : (∑ i, (dotR v (x i)) ^ 2) = 0 := by
    refine Finset.sum_eq_zero fun i _ => ?_
    rw [hxv i]; ring
  rw [hzero, zero_sub, neg_neg]
  have hnn : ∀ j ∈ (Finset.univ : Finset (Fin k)), (0 : ℝ) ≤ (dotR v (y j)) ^ 2 :=
    fun _ _ => sq_nonneg _
  rcases lt_or_eq_of_le (Finset.sum_nonneg hnn) with hpos | heq
  · exact hpos
  · exfalso
    have hall := (Finset.sum_eq_zero_iff_of_nonneg hnn).mp heq.symm
    have hy : ∀ j, dotR (y j) v = 0 := by
      intro j
      have := hall j (Finset.mem_univ j)
      rw [← dotR_comm]
      exact pow_eq_zero_iff (n := 2) (by norm_num) |>.mp this
    exact hvne (dotR_self_eq_zero (dotR_eq_zero_of_mem_span (hW hv) hy))

/-- **The two-sided count at ARBITRARY size** -- the general-block replacement for
`bragg_defect_eq_one` / `defect_eq_two`.  With `k` linearly independent off-line channels, each
orthogonal to every on-line channel, the defect of the block is EXACTLY `k`, in any ambient
dimension and for any number of on-line channels.  Both hypotheses are finite kernel checks.
conjecture1_proved = False. -/
theorem defect_sumPairBlock_eq {m k : ℕ} (x : Fin m → (d → ℝ)) {y : Fin k → (d → ℝ)}
    (hli : LinearIndependent ℝ y)
    (horth : ∀ i j, dotR (y j) (x i) = 0) :
    defect (sumPairBlock_isHermitian x y) = k := by
  refine le_antisymm (defect_sumPairBlock_le x y) ?_
  have hfr : Module.finrank ℝ (Submodule.span ℝ (Set.range y)) = k :=
    (finrank_span_eq_card hli).trans (Fintype.card_fin k)
  have := defect_sumPairBlock_ge_of_subspace (x := x) (y := y)
    (W := Submodule.span ℝ (Set.range y)) le_rfl
    (fun i v hv => dotR_eq_zero_of_mem_span hv (fun j => horth i j))
  rwa [hfr] at this

/-! ## Section 3. What one functional-equation quadruple actually costs

Section 1 says a genuine off-line zero contributes `p = 2` `sigma`-pairs.  This section computes
what those two pairs cost in DEFECT, and shows the answer is NOT determined by the quadruple. -/

omit [Fintype d] [DecidableEq d] in
/-- **The reflection-degenerate evaluation relation.**  If the evaluation vector of `conj rho` is
the complex conjugate of that of `rho` -- exactly what a node set pointwise invariant under
`tau |-> -tau` produces, e.g. a single node at the origin -- then the second `sigma`-pair of the
quadruple has real channel `x_2 = x_1` and imaginary channel `y_2 = -y_1`.  The two pairs then
carry the SAME rank-one negative channel. -/
lemma degenerate_channels (u : d → ℂ) :
    (fun t => ((starRingEnd ℂ) (u t)).re) = (fun t => (u t).re) ∧
    (fun t => ((starRingEnd ℂ) (u t)).im) = (-1 : ℝ) • (fun t => (u t).im) := by
  constructor <;> funext t <;> simp

/-- **A quadruple whose two `sigma`-pairs share one channel leaks ONE negative direction.**  With
`y_2 = c * y_1` (`c != 0`) and `y_1` orthogonal to every on-line channel, the defect of the
two-channel block is EXACTLY 1 -- while the `sigma`-pair count is 2.  This is the kernel
counterexample to "the defect counts the off-line pairs": here `p = 2` and `defect = 1`. -/
theorem defect_parallel_channels_eq_one {m : ℕ} (x : Fin m → (d → ℝ)) {u : d → ℝ} (hu : u ≠ 0)
    (c : ℝ) (horth : ∀ i, dotR u (x i) = 0) :
    defect (sumPairBlock_isHermitian x ![u, c • u]) = 1 := by
  refine le_antisymm ?_ ?_
  · refine (defect_sumPairBlock_le_rank x ![u, c • u]).trans ?_
    have hsum : (∑ j, vecMulVec ((![u, c • u] : Fin 2 → (d → ℝ)) j)
        ((![u, c • u] : Fin 2 → (d → ℝ)) j)) = vecMulVec ((1 + c ^ 2) • u) u := by
      rw [Fin.sum_univ_two]
      funext i j
      simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.add_apply,
        vecMulVec_apply, Pi.smul_apply, smul_eq_mul]
      ring
    rw [hsum]
    exact Matrix.rank_vecMulVec_le _ _
  · have hmem : u ∈ Submodule.span ℝ (Set.range (![u, c • u] : Fin 2 → (d → ℝ))) :=
      Submodule.subset_span ⟨0, rfl⟩
    have hW : (Submodule.span ℝ {u}) ≤ Submodule.span ℝ
        (Set.range (![u, c • u] : Fin 2 → (d → ℝ))) := by
      rw [Submodule.span_le, Set.singleton_subset_iff]
      exact hmem
    have hx : ∀ i, ∀ v ∈ Submodule.span ℝ ({u} : Set (d → ℝ)), dotR v (x i) = 0 := by
      intro i v hv
      rw [Submodule.mem_span_singleton] at hv
      obtain ⟨a, rfl⟩ := hv
      unfold dotR at horth ⊢
      simp only [Pi.smul_apply, smul_eq_mul, mul_assoc, ← Finset.mul_sum, horth i, mul_zero]
    have h := defect_sumPairBlock_ge_of_subspace (x := x) (y := ![u, c • u])
      (W := Submodule.span ℝ ({u} : Set (d → ℝ))) hW hx
    rwa [finrank_span_singleton hu] at h

/-- **The orthogonality hypothesis of `defect_sumPairBlock_eq` is LOAD-BEARING.**  With the single
on-line channel EQUAL to the single off-line channel the block is identically zero and the defect
is `0`, although `k = 1` and the channel may be nonzero.  So no unconditional lower bound
`k <= defect` exists: the on-line channel can neutralize an off-line direction completely.  This is
the precise sense in which extending the count to a general block is NOT free. -/
theorem orthogonality_is_load_bearing (u : d → ℝ) :
    defect (sumPairBlock_isHermitian ![u] ![u]) = 0 := by
  have h0 : sumPairBlock ![u] ![u] = 0 := by
    unfold sumPairBlock
    simp
  rw [defect_congr (sumPairBlock_isHermitian ![u] ![u])
    (Matrix.PosSemidef.zero (n := d) (R := ℝ)).isHermitian h0]
  exact defect_posSemidef (Matrix.PosSemidef.zero (n := d) (R := ℝ))

/-- **The general quadruple ceiling.**  A window carrying `q` genuine off-line quadruples carries
`2q` `sigma`-pair channels, so its defect is at most `2q` -- UNCONDITIONALLY.  This is the honest
headline; the matching lower bound is witness-dependent and can fail (see
`quadruple_witness_dimension_not_determined`). -/
theorem defect_quadruple_block_le {m q : ℕ} (x : Fin m → (d → ℝ)) (y : Fin (2 * q) → (d → ℝ)) :
    defect (sumPairBlock_isHermitian x y) ≤ 2 * q :=
  defect_sumPairBlock_le x y

/-- The general block specializes to the island's `twoPairBlock` (so the results above speak about
the very object `BraggDefect.defect_eq_two` is stated on). -/
lemma sumPairBlock_two (x₁ y₁ x₂ y₂ : d → ℝ) :
    sumPairBlock ![x₁, x₂] ![y₁, y₂] = twoPairBlock x₁ y₁ x₂ y₂ := by
  unfold sumPairBlock twoPairBlock
  rw [Fin.sum_univ_two, Fin.sum_univ_two]
  simp

/-! ### The headline correction, in one ambient dimension

Two configurations in the SAME ambient dimension `Fin 4`, with the SAME on-line channel and the
SAME number (two) of NONZERO off-line channels -- i.e. both carrying `p = 2` `sigma`-pairs, both
"one genuine off-line quadruple" -- have DIFFERENT defects: `1` and `2`.  The witness dimension is
`dim span {y_1, y_2}`, and the quadruple structure does not determine it. -/

/-- On-line square channel `f * e_0`. -/
def X1 (f : ℝ) : Fin 4 → ℝ := ![f, 0, 0, 0]
/-- Off-line clearance channel `e_1`. -/
def E1 : Fin 4 → ℝ := ![0, 1, 0, 0]
/-- A second, independent off-line clearance channel `e_3`. -/
def E3 : Fin 4 → ℝ := ![0, 0, 0, 1]

lemma E1_ne_zero : (E1 : Fin 4 → ℝ) ≠ 0 := by
  intro h; have := congrFun h 1; simp [E1] at this

lemma E3_ne_zero : (E3 : Fin 4 → ℝ) ≠ 0 := by
  intro h; have := congrFun h 3; simp [E3] at this

/-- The reflected channel of the degenerate quadruple is itself NONZERO: the degenerate
configuration genuinely carries TWO off-line channels (`p = 2`), not one. -/
lemma neg_E1_ne_zero : ((-1 : ℝ) • E1 : Fin 4 → ℝ) ≠ 0 := by
  intro h; have := congrFun h 1; simp [E1] at this

lemma dotR_E1_X1 (f : ℝ) : dotR E1 (X1 f) = 0 := by
  simp [dotR, E1, X1, Fin.sum_univ_four]

lemma dotR_E3_X1 (f : ℝ) : dotR E3 (X1 f) = 0 := by
  simp [dotR, E3, X1, Fin.sum_univ_four]

lemma E1_E3_linearIndependent : LinearIndependent ℝ (![E1, E3] : Fin 2 → (Fin 4 → ℝ)) := by
  rw [LinearIndependent.pair_iff]
  intro s t hst
  have h1 := congrFun hst 1
  have h3 := congrFun hst 3
  simp [E1, E3, Pi.add_apply, smul_eq_mul] at h1 h3
  exact ⟨h1, h3⟩

/-- **`quadruple_witness_dimension_not_determined` -- THE CORRECTION.**  Same ambient dimension,
same on-line channel, same number of nonzero off-line channels (two, i.e. the two `sigma`-pairs of
ONE genuine off-line quadruple), different defects: `1` for the reflection-degenerate quadruple
(`y_2 = -y_1`, the configuration `degenerate_channels` forces for a flip-invariant node set) and
`2` for the generic quadruple (independent channels).

Therefore the witness dimension a functional-equation quadruple contributes is NOT a function of
the quadruple: it is `dim span {y_1, y_2}`, which is `1` or `2`.  The `NegativeWitness` hypothesis
of `offline_pairs_le_defect` is load-bearing and CAN FAIL for a genuine off-line quadruple.
conjecture1_proved = False. -/
theorem quadruple_witness_dimension_not_determined (f : ℝ) :
    (E1 : Fin 4 → ℝ) ≠ 0 ∧ ((-1 : ℝ) • E1 : Fin 4 → ℝ) ≠ 0 ∧ (E3 : Fin 4 → ℝ) ≠ 0 ∧
    defect (sumPairBlock_isHermitian ![X1 f] ![E1, (-1 : ℝ) • E1]) = 1 ∧
    defect (sumPairBlock_isHermitian ![X1 f] ![E1, E3]) = 2 := by
  refine ⟨E1_ne_zero, neg_E1_ne_zero, E3_ne_zero, ?_, ?_⟩
  · refine defect_parallel_channels_eq_one ![X1 f] E1_ne_zero (-1 : ℝ) ?_
    intro i
    fin_cases i
    simpa using dotR_E1_X1 f
  · refine defect_sumPairBlock_eq ![X1 f] E1_E3_linearIndependent ?_
    intro i j
    fin_cases i
    fin_cases j
    · simpa using dotR_E1_X1 f
    · simpa using dotR_E3_X1 f

/-- The degenerate configuration read on the island's own `twoPairBlock` -- the exact shape
`BraggDefect.defect_eq_two` is stated on, with the second pair being the functional-equation
REFLECTION of the first rather than an independent channel.  `defect = 1`, not `2`. -/
theorem twoPairBlock_reflection_degenerate_defect_eq_one (f₁ f₂ : ℝ) :
    defect (twoPairBlock_isHermitian (X1 f₁) E1 (X1 f₂) ((-1 : ℝ) • E1)) = 1 := by
  have hA : defect (sumPairBlock_isHermitian ![X1 f₁, X1 f₂] ![E1, (-1 : ℝ) • E1]) = 1 := by
    refine defect_parallel_channels_eq_one ![X1 f₁, X1 f₂] E1_ne_zero (-1 : ℝ) ?_
    intro i
    fin_cases i
    · simpa using dotR_E1_X1 f₁
    · simpa using dotR_E1_X1 f₂
  rw [← defect_congr (sumPairBlock_isHermitian ![X1 f₁, X1 f₂] ![E1, (-1 : ℝ) • E1])
    (twoPairBlock_isHermitian (X1 f₁) E1 (X1 f₂) ((-1 : ℝ) • E1))
    (sumPairBlock_two (X1 f₁) E1 (X1 f₂) ((-1 : ℝ) • E1))]
  exact hA

end QuadrupleDefect
