-- DO NOT EDIT BY HAND — generated by telperion mission; node MM_gaussian_positivity_of_window; sha256 e11dd7173e40c90e
import Mathlib
import Statements.MMDefs
open Zeta23 RvMBridge6 RvMBridge12

theorem gaussian_positivity_of_window {c D d δ lam : ℝ} (hD : 0 ≤ D) (hδ : 0 < δ)
    (hgap : d ^ 2 + 1 / 4 < D ^ 2) (hwin : WindowOnLine c D)
    (hnear : ∃ ρ : ℂ, IsNontrivialZero ρ ∧ δ ≤ |ρ.im - c| ∧ |ρ.im - c| ≤ d)
    (hlam : lamThreshold c D d δ ≤ lam) : 0 ≤ (zeroSide (gaussTest c lam)).re := by sorry
