-- DO NOT EDIT BY HAND — generated by telperion mission; node MM_gaussian_approx; sha256 485dc7d51154ba5b
import Mathlib
import Statements.MMDefs

theorem gaussian_approx : RvMBridge6.GaussianApprox := by sorry
