-- DO NOT EDIT BY HAND — generated by telperion mission; node MM_gaussian_transfer; sha256 53da5942a482aeda
import Mathlib
import Statements.MMDefs

theorem gaussian_transfer : RvMBridge6.GaussianTransfer := by sorry
