-- DO NOT EDIT BY HAND — generated by telperion mission; node MM_nt_brick_conditional; sha256 9921b9185d246847
-- VERBATIM statement of zeta_ordinates_not_uniformlyDiscrete_of_unbounded_density
-- (BoundaryLemmas.lean:378-381, v4.32 quasicrystal island, namespace Quasicrystal).
-- The hypothesis RvMUnboundedMeanDensity is the named W2c residual (its own node);
-- Ordinates stays a free binder exactly as in the island.
import Mathlib
import Statements.MMDefs
open Quasicrystal

theorem zeta_ordinates_not_uniformlyDiscrete_of_unbounded_density
    {Ordinates : Set ℝ} (hRvM : RvMUnboundedMeanDensity Ordinates) :
    ¬ IsUniformlyDiscrete Ordinates := by sorry
