-- DO NOT EDIT BY HAND — generated by telperion mission; node MM_rh_implies_weil_positivity; sha256 bbc7d281bc379a43
import Mathlib
import Statements.MMDefs

theorem rh_implies_weil_positivity (hRH : RiemannHypothesis) : ∀ g : ℝ → ℂ, WeilExplicit.IsWeilTest g → 0 ≤ (WeilExplicit.weilForm (WeilExplicit.autocorr g)).re := by sorry
