-- DO NOT EDIT BY HAND — generated by telperion mission; node MM_twofreq_realrooted_iff
-- VERBATIM statement of twoFreq_realRooted_iff (TwoFreqRigidity.lean:92-94, v4.32
-- quasicrystal island, namespace Quasicrystal).
import Mathlib
import Statements.MMDefs
open Quasicrystal

theorem twoFreq_realRooted_iff (c₁ c₂ : ℂ) (lam₁ lam₂ : ℝ)
    (hc₁ : c₁ ≠ 0) (hc₂ : c₂ ≠ 0) (hlam : lam₁ ≠ lam₂) :
    (∀ x : ℂ, twoFreq c₁ c₂ lam₁ lam₂ x = 0 → x.im = 0) ↔ ‖c₁‖ = ‖c₂‖ := by sorry
