-- DO NOT EDIT BY HAND — generated by telperion mission; node MM_weil_positivity_prime_free_window; sha256 8d7b627527e792e5
import Mathlib
import Statements.MMDefs

theorem weil_positivity_prime_free_window (g : ℝ → ℂ) (hg : WeilExplicit.IsWeilTest g) (L : ℝ)
    (hL : 2 * L ≤ Real.log 2) (hsupp : tsupport g ⊆ Set.Icc (-L) L) :
    0 ≤ (WeilExplicit.weilForm (WeilExplicit.autocorr g)).re := by sorry
