-- DO NOT EDIT BY HAND — generated by telperion mission; node MM_weil_positivity_window_half; sha256 e8ea9ae4f537da3f
import Mathlib
import Statements.MMDefs

theorem weil_positivity_window_half (g : ℝ → ℂ) (hg : WeilExplicit.IsWeilTest g) (L : ℝ)
    (hL : 2 * L ≤ 1) (hsupp : tsupport g ⊆ Set.Icc (-L) L) :
    0 ≤ (WeilExplicit.weilForm (WeilExplicit.autocorr g)).re := by sorry
