/-
  Crux3_BandTable -- the 57-entry prime-side table of the band certificate and its kernel check
  (rvm_bridge island, 2026-09-24, crux lane 3).  Generated by the lane's gen_table.py / gen_lam.py
  (exact-rational mirror mirror.py in the lane scratch directory).

  conjecture1_proved = False.

    * `tab`: the 24 prime powers `n <= 56` (`mu = 1/e` for `n = p^e`), all other `n < 57` zero;
    * `tab_ok`: every entry passes `entryOK` for the instance `P0` (A = 9 pi/14, k1 = 763/9,
      k2 = 259/3, s1 s2 = -1) -- `decide +kernel`, pure rational arithmetic;
    * `tab_tamper`: NEGATIVE CONTROL -- the `n = 2` entry with its log lower bound raised by `1e-12`
      is REJECTED by the same kernel checker;
    * `lam_tab`: `Lambda(n) = mu_n log n` for every `n < 57` (Mathlib's von Mangoldt lemmas).
  No `sorry`.
-/
import Crux3_BandNum

open Finset

noncomputable section

namespace Crux3
/-- The table: entry `n` (`n < 57`). -/
def tab : ℕ → TEntry
  | 2 => ⟨(1 : ℚ), ((86643397569993 : ℚ) / 125000000000000), ((693147180559947 : ℚ) / 1000000000000000), ((707106781186547523 : ℚ) / 1000000000000000000), ((353553390593273763 : ℚ) / 500000000000000000), 9, 10⟩
  | 3 => ⟨(1 : ℚ), ((274653072167027 : ℚ) / 250000000000000), ((1098612288668111 : ℚ) / 1000000000000000), ((577350269189625763 : ℚ) / 1000000000000000000), ((288675134594812883 : ℚ) / 500000000000000000), 15, 15⟩
  | 4 => ⟨((1 : ℚ) / 2), ((1386294361119889 : ℚ) / 1000000000000000), ((346573590279973 : ℚ) / 250000000000000), ((499999999999999999 : ℚ) / 1000000000000000000), ((250000000000000001 : ℚ) / 500000000000000000), 19, 19⟩
  | 5 => ⟨(1 : ℚ), ((1609437912434099 : ℚ) / 1000000000000000), ((804718956217051 : ℚ) / 500000000000000), ((223606797749978969 : ℚ) / 500000000000000000), ((447213595499957941 : ℚ) / 1000000000000000000), 22, 22⟩
  | 7 => ⟨(1 : ℚ), ((121619384315957 : ℚ) / 62500000000000), ((389182029811063 : ℚ) / 200000000000000), ((188982236504613613 : ℚ) / 500000000000000000), ((377964473009227229 : ℚ) / 1000000000000000000), 26, 27⟩
  | 8 => ⟨((1 : ℚ) / 3), ((1039720770839917 : ℚ) / 500000000000000), ((2079441541679837 : ℚ) / 1000000000000000), ((353553390593273761 : ℚ) / 1000000000000000000), ((88388347648318441 : ℚ) / 250000000000000000), 28, 29⟩
  | 9 => ⟨((1 : ℚ) / 2), ((1098612288668109 : ℚ) / 500000000000000), ((2197224577336221 : ℚ) / 1000000000000000), ((83333333333333333 : ℚ) / 250000000000000000), ((66666666666666667 : ℚ) / 200000000000000000), 30, 30⟩
  | 11 => ⟨(1 : ℚ), ((2397895272798369 : ℚ) / 1000000000000000), ((599473818199593 : ℚ) / 250000000000000), ((301511344577763621 : ℚ) / 1000000000000000000), ((37688918072220453 : ℚ) / 125000000000000000), 32, 33⟩
  | 13 => ⟨(1 : ℚ), ((512989871492307 : ℚ) / 200000000000000), ((1282474678730769 : ℚ) / 500000000000000), ((1733438113203841 : ℚ) / 6250000000000000), ((277350098112614563 : ℚ) / 1000000000000000000), 35, 35⟩
  | 16 => ⟨((1 : ℚ) / 4), ((138629436111989 : ℚ) / 50000000000000), ((2772588722239783 : ℚ) / 1000000000000000), ((249999999999999999 : ℚ) / 1000000000000000000), ((125000000000000001 : ℚ) / 500000000000000000), 37, 38⟩
  | 17 => ⟨(1 : ℚ), ((566642668811243 : ℚ) / 200000000000000), ((1416606672028109 : ℚ) / 500000000000000), ((60633906259083243 : ℚ) / 250000000000000000), ((9701425001453319 : ℚ) / 40000000000000000), 38, 39⟩
  | 19 => ⟨(1 : ℚ), ((2944438979166439 : ℚ) / 1000000000000000), ((1472219489583221 : ℚ) / 500000000000000), ((57353933467640441 : ℚ) / 250000000000000000), ((229415733870561767 : ℚ) / 1000000000000000000), 40, 40⟩
  | 23 => ⟨(1 : ℚ), ((783873553982287 : ℚ) / 250000000000000), ((3135494215929151 : ℚ) / 1000000000000000), ((208514414057074761 : ℚ) / 1000000000000000000), ((52128603514268691 : ℚ) / 250000000000000000), 42, 43⟩
  | 25 => ⟨((1 : ℚ) / 2), ((3218875824868199 : ℚ) / 1000000000000000), ((1609437912434101 : ℚ) / 500000000000000), ((199999999999999999 : ℚ) / 1000000000000000000), ((100000000000000001 : ℚ) / 500000000000000000), 43, 44⟩
  | 27 => ⟨((1 : ℚ) / 3), ((411979608250541 : ℚ) / 125000000000000), ((3295836866004331 : ℚ) / 1000000000000000), ((192450089729875253 : ℚ) / 1000000000000000000), ((24056261216234407 : ℚ) / 125000000000000000), 44, 45⟩
  | 29 => ⟨(1 : ℚ), ((3367295829986473 : ℚ) / 1000000000000000), ((841823957496619 : ℚ) / 250000000000000), ((92847669088525931 : ℚ) / 500000000000000000), ((37139067635410373 : ℚ) / 200000000000000000), 45, 46⟩
  | 31 => ⟨(1 : ℚ), ((686797440897029 : ℚ) / 200000000000000), ((858496801121287 : ℚ) / 250000000000000), ((179605302026774899 : ℚ) / 1000000000000000000), ((89802651013387451 : ℚ) / 500000000000000000), 46, 47⟩
  | 32 => ⟨((1 : ℚ) / 5), ((138629436111989 : ℚ) / 40000000000000), ((216608493924983 : ℚ) / 62500000000000), ((2209708691207961 : ℚ) / 12500000000000000), ((176776695296636883 : ℚ) / 1000000000000000000), 47, 48⟩
  | 37 => ⟨(1 : ℚ), ((3610917912644223 : ℚ) / 1000000000000000), ((1805458956322113 : ℚ) / 500000000000000), ((164398987305357287 : ℚ) / 1000000000000000000), ((16439898730535729 : ℚ) / 100000000000000000), 49, 50⟩
  | 41 => ⟨(1 : ℚ), ((1856786033352153 : ℚ) / 500000000000000), ((3713572066704309 : ℚ) / 1000000000000000), ((9760860118037879 : ℚ) / 62500000000000000), ((156173761888606067 : ℚ) / 1000000000000000000), 50, 51⟩
  | 43 => ⟨(1 : ℚ), ((3761200115693561 : ℚ) / 1000000000000000), ((940300028923391 : ℚ) / 250000000000000), ((30499714066520933 : ℚ) / 200000000000000000), ((38124642583151167 : ℚ) / 250000000000000000), 51, 52⟩
  | 47 => ⟨(1 : ℚ), ((3850147601710057 : ℚ) / 1000000000000000), ((192507380085503 : ℚ) / 50000000000000), ((72932495748947277 : ℚ) / 500000000000000000), ((145864991497894557 : ℚ) / 1000000000000000000), 52, 53⟩
  | 49 => ⟨((1 : ℚ) / 2), ((6226912476977 : ℚ) / 1600000000000), ((972955074527657 : ℚ) / 250000000000000), ((17857142857142857 : ℚ) / 125000000000000000), ((142857142857142859 : ℚ) / 1000000000000000000), 53, 53⟩
  | 53 => ⟨(1 : ℚ), ((99257297838803 : ℚ) / 25000000000000), ((3970291913552123 : ℚ) / 1000000000000000), ((68680281974344511 : ℚ) / 500000000000000000), ((5494422557947561 : ℚ) / 40000000000000000), 54, 55⟩
  | _ => ⟨0, 0, 0, 0, 0, 0, 0⟩

/-- The instance: `A = 9 pi/14`, `k1 = 763/9`, `k2 = 259/3`, `s1 s2 = -1`. -/
def P0 : BandP := ⟨9 / 14, 763 / 9, 259 / 3, -1⟩

set_option maxRecDepth 100000 in
theorem tab_ok : (List.range 57).all (fun n => entryOK P0 n (tab n)) = true := by decide +kernel

/-- negative control: an entry with a log lower bound shifted up by 1e-12 must be rejected. -/
theorem tab_tamper : entryOK P0 2 ⟨1, (86643397569993 : ℚ) / 125000000000000 + 1 / 10 ^ 12, (693147180559947 : ℚ) / 1000000000000000, (707106781186547523 : ℚ) / 1000000000000000000, (353553390593273763 : ℚ) / 500000000000000000, 9, 10⟩ = false := by decide +kernel


/-- `Λ n = 0` when `n = a b` with coprime `a, b > 1` (`n` is not a prime power). -/
lemma vonMangoldt_eq_zero_of_coprime' {n : ℕ} (a b : ℕ) (ha : 1 < a) (hb : 1 < b)
    (hab : Nat.Coprime a b) (hn : n = a * b) : ArithmeticFunction.vonMangoldt n = 0 := by
  rw [ArithmeticFunction.vonMangoldt_eq_zero_iff]
  intro hpp
  rw [isPrimePow_nat_iff] at hpp
  obtain ⟨p, k, hp, -, hpk⟩ := hpp
  have hadvd : a ∣ p ^ k := by rw [hpk, hn]; exact Dvd.intro b rfl
  have hbdvd : b ∣ p ^ k := by rw [hpk, hn]; exact Dvd.intro_left a rfl
  obtain ⟨i, -, rfl⟩ := (Nat.dvd_prime_pow hp).1 hadvd
  obtain ⟨j, -, rfl⟩ := (Nat.dvd_prime_pow hp).1 hbdvd
  have hi0 : i ≠ 0 := by rintro rfl; simp at ha
  have hj0 : j ≠ 0 := by rintro rfl; simp at hb
  have hdvd : p ∣ Nat.gcd (p ^ i) (p ^ j) := Nat.dvd_gcd (dvd_pow_self p hi0) (dvd_pow_self p hj0)
  have hg : Nat.gcd (p ^ i) (p ^ j) = 1 := hab
  rw [hg] at hdvd
  exact hp.one_lt.ne' (Nat.dvd_one.mp hdvd)

/-- `Λ n = mu_n log n` for every `n < 57` (the table's `mu`). -/
theorem lam_tab : ∀ n < 57, ArithmeticFunction.vonMangoldt n = ((tab n).mu : ℝ) * Real.log n := by
  intro n hn
  interval_cases n
  · have hm : (tab 0).mu = 0 := rfl
    rw [hm]
    simp
  · have hm : (tab 1).mu = 0 := rfl
    rw [hm]
    simp
  · have hm : (tab 2).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 3).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 4).mu = 1 / 2 := rfl
    rw [hm]
    rw [show (4 : ℕ) = 2 ^ 2 by norm_num, ArithmeticFunction.vonMangoldt_apply_pow (by norm_num),
      ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    rw [show (4 : ℝ) = (2 : ℝ) ^ 2 by norm_num, Real.log_pow]
    push_cast
    ring
  · have hm : (tab 5).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 6).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 7).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 8).mu = 1 / 3 := rfl
    rw [hm]
    rw [show (8 : ℕ) = 2 ^ 3 by norm_num, ArithmeticFunction.vonMangoldt_apply_pow (by norm_num),
      ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    rw [show (8 : ℝ) = (2 : ℝ) ^ 3 by norm_num, Real.log_pow]
    push_cast
    ring
  · have hm : (tab 9).mu = 1 / 2 := rfl
    rw [hm]
    rw [show (9 : ℕ) = 3 ^ 2 by norm_num, ArithmeticFunction.vonMangoldt_apply_pow (by norm_num),
      ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    rw [show (9 : ℝ) = (3 : ℝ) ^ 2 by norm_num, Real.log_pow]
    push_cast
    ring
  · have hm : (tab 10).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 11).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 12).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 4 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 13).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 14).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 15).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 3 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 16).mu = 1 / 4 := rfl
    rw [hm]
    rw [show (16 : ℕ) = 2 ^ 4 by norm_num, ArithmeticFunction.vonMangoldt_apply_pow (by norm_num),
      ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    rw [show (16 : ℝ) = (2 : ℝ) ^ 4 by norm_num, Real.log_pow]
    push_cast
    ring
  · have hm : (tab 17).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 18).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 19).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 20).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 4 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 21).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 3 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 22).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 23).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 24).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 8 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 25).mu = 1 / 2 := rfl
    rw [hm]
    rw [show (25 : ℕ) = 5 ^ 2 by norm_num, ArithmeticFunction.vonMangoldt_apply_pow (by norm_num),
      ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    rw [show (25 : ℝ) = (5 : ℝ) ^ 2 by norm_num, Real.log_pow]
    push_cast
    ring
  · have hm : (tab 26).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 27).mu = 1 / 3 := rfl
    rw [hm]
    rw [show (27 : ℕ) = 3 ^ 3 by norm_num, ArithmeticFunction.vonMangoldt_apply_pow (by norm_num),
      ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    rw [show (27 : ℝ) = (3 : ℝ) ^ 3 by norm_num, Real.log_pow]
    push_cast
    ring
  · have hm : (tab 28).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 4 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 29).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 30).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 31).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 32).mu = 1 / 5 := rfl
    rw [hm]
    rw [show (32 : ℕ) = 2 ^ 5 by norm_num, ArithmeticFunction.vonMangoldt_apply_pow (by norm_num),
      ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    rw [show (32 : ℝ) = (2 : ℝ) ^ 5 by norm_num, Real.log_pow]
    push_cast
    ring
  · have hm : (tab 33).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 3 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 34).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 35).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 5 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 36).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 4 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 37).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 38).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 39).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 3 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 40).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 8 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 41).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 42).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 21 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 43).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 44).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 4 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 45).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 9 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 46).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 47).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 48).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 16 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 49).mu = 1 / 2 := rfl
    rw [hm]
    rw [show (49 : ℕ) = 7 ^ 2 by norm_num, ArithmeticFunction.vonMangoldt_apply_pow (by norm_num),
      ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    rw [show (49 : ℝ) = (7 : ℝ) ^ 2 by norm_num, Real.log_pow]
    push_cast
    ring
  · have hm : (tab 50).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 25 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 51).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 3 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 52).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 4 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 53).mu = 1 := rfl
    rw [hm]
    rw [ArithmeticFunction.vonMangoldt_apply_prime (by norm_num)]
    push_cast
    ring
  · have hm : (tab 54).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 2 27 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 55).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 5 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp
  · have hm : (tab 56).mu = 0 := rfl
    rw [hm]
    rw [vonMangoldt_eq_zero_of_coprime' 8 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    simp

end Crux3
