-- DO NOT EDIT BY HAND — generated by telperion mission; node AND_em_tail3_number
-- VERBATIM statement of em_tail3_number (EMZetaTail.lean:469-474, v4.32
-- zeta_reflection island, namespace ZetaReflection).
import Mathlib
import Statements.ANDDefs
open MeasureTheory Set ZetaReflection

theorem em_tail3_number :
    ‖∫ x in Ioi (200 : ℝ),
        (sawBernoulli 3 x : ℂ)
          * (emTailCoeff3 ((1 / 2 : ℂ) + 14 * Complex.I)
              * (x : ℂ) ^ (-((1 / 2 : ℂ) + 14 * Complex.I) - 3))‖
      ≤ (1 : ℝ) / 1000 := by sorry
