-- DO NOT EDIT BY HAND — generated by telperion mission; node AND_g2_reflected_band_kernel; sha256 38e9d3ea99483138
import Mathlib

theorem pilot_kernel :
    ∃ xs : List ℝ, xs.length = 2 ∧ xs.IsChain (· < ·) ∧
        (∀ t ∈ xs, (14 : ℝ) ≤ t ∧ t ≤ (22 : ℝ)) ∧
        (∀ t ∈ xs, completedRiemannZeta (1 / 2 + (t : ℂ) * Complex.I) = 0) := by sorry
