"""Bit-exact Python mirror of Probes/ArbEconomics_Multi.lean (rotor cost proxy) + emitter.

usage: arbecon_multi.py TAG t0 hn hq G N P CHUNK OUTDIR
  grid t_j = t0 + j * hn / 2^hq, j = 0..G-1; Dirichlet terms n = 1..N-1 (no EM tail: cost proxy)
Checks the arithmetic against mpmath at every grid point (max abs error reported) and emits
OUTDIR/ArbEconomics_<TAG>.lean with chunked `decide +kernel` checks of `mrun`.
conjecture1_proved = False.
"""
import sys
import os
import json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import arbecon_model as M
from arbecon_model import ndiv, nsub


def sadd(x, sx, y, sy):
    if sx == sy:
        return x + y, sx
    if y <= x:
        return nsub(x, y), sx
    return nsub(y, x), sy


def cmul(P, v, u):
    a, sa, b, sb = v
    c, sc, d, sd = u
    ac = (a * c) >> P
    bd = (b * d) >> P
    ad = (a * d) >> P
    bc = (b * c) >> P
    re = sadd(ac, sa == sc, bd, not (sb == sd))
    im = sadd(ad, sa == sd, bc, sb == sc)
    return (re[0], re[1], im[0], im[1])


def acc_add(x, v):
    P_, N_, IP, IN = x
    a, sa, b, sb = v
    return (P_ + a if sa else P_, N_ if sa else N_ + a, IP + b if sb else IP, IN if sb else IN + b)


def sweep(P, u, accs, v):
    out = []
    for x in accs:
        out.append(acc_add(x, v))
        v = cmul(P, v, u)
    return out


def mstep(c, hn, hq, s):
    n, llo, lhi, g, accs = s
    m = n + 1
    S, K, pw = M.log_inc(c, m)
    llo2 = llo + S
    lhi2 = lhi + S + K + (ndiv(c.two1, pw) + 1)
    g2 = M.isqrt(c, m, ndiv(c.oneSq, m), g)
    R = g2
    (cm, cs, cr), (sm, ss, sr) = M.trig(c, (c.tn * llo2) >> c.tq, ((c.tn * lhi2) >> c.tq) + 1)
    (ucm, ucs, ucr), (usm, uss, usr) = M.trig(c, (hn * llo2) >> hq, ((hn * lhi2) >> hq) + 1)
    w = ((R * cm) >> c.P, cs, (R * sm) >> c.P, not ss)
    u = (ucm, ucs, usm, not uss)
    return (m, llo2, lhi2, g2, sweep(c.P, u, accs, w))


def acc_lean(x):
    return "(%d, %d, %d, %d)" % x


def mst_lean(s):
    n, llo, lhi, g, accs = s
    return "⟨%d, %d, %d, %d, [%s]⟩" % (n, llo, lhi, g, ", ".join(acc_lean(x) for x in accs))


def main():
    tag, t0, hn, hq, G, N, P, chunk, outdir = (sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]),
                                               int(sys.argv[5]), int(sys.argv[6]), int(sys.argv[7]), int(sys.argv[8]),
                                               sys.argv[9])
    c = M.make_cfg(P, t0, 0)
    one = c.one
    # initial state after n = 1: every grid point gets 1^(-s) = 1
    s = (1, 0, 0, one, [(one, 0, 0, 0) for _ in range(G)])
    states, lens = [s], []
    done, total = 0, N - 2
    while done < total:
        L = min(chunk, total - done)
        for _ in range(L):
            s = mstep(c, hn, hq, s)
        states.append(s)
        lens.append(L)
        done += L
    # numerics check vs mpmath (sum n = 1..N-1)
    import mpmath
    mpmath.mp.dps = 30
    maxerr = 0.0
    for j in range(0, G, max(1, G // 4)):
        tj = mpmath.mpf(t0) + mpmath.mpf(j * hn) / 2 ** hq
        exact = mpmath.fsum(mpmath.power(n, -(mpmath.mpf(1) / 2 + 1j * tj)) for n in range(1, N))
        x = states[-1][4][j]
        val = mpmath.mpf(x[0] - x[1]) / one + 1j * mpmath.mpf(x[2] - x[3]) / one
        maxerr = max(maxerr, float(abs(val - exact)))
    ns = "ArbEcon.MI_%s" % tag
    L = []
    L.append("/-  Probes/ArbEconomics_%s.lean -- rotor cost-proxy benchmark (GENERATED by arbecon_multi.py)." % tag)
    L.append("    grid t_j = %d + j * %d / 2^%d, G = %d points, Dirichlet terms n = 1..%d, P = %d." % (t0, hn, hq, G, N - 1, P))
    L.append("    Arithmetic validated against mpmath (max |error| over sampled grid points = %.2e)." % maxerr)
    L.append("    COST PROXY, not an enclosure theorem.  conjecture1_proved = False.")
    L.append("-/")
    L.append("import Probes.ArbEconomics_Multi")
    L.append("")
    L.append("namespace %s" % ns)
    L.append("")
    L.append("noncomputable section")
    L.append("")
    L.append(M.lean_horner(c.one, c.dcos, "hc"))
    L.append("")
    L.append(M.lean_horner(c.one, c.dsin, "hs"))
    L.append("")
    L.append(M.lean_lnf(c, "lnf"))
    L.append("")
    L.append("def mcfg : ArbEcon.Multi.MCfg := ⟨%s, %d, %d⟩" % (M.cfg_lean(c, "hc", "hs", "lnf"), hn, hq))
    L.append("")
    for i, st in enumerate(states):
        L.append("def s%d : ArbEcon.Multi.MSt := %s" % (i, mst_lean(st)))
    L.append("")
    L.append("end")
    L.append("")
    for i, n in enumerate(lens):
        L.append("theorem chunk_%d : ArbEcon.Multi.MSt.beq (ArbEcon.Multi.mrun mcfg %d s%d) s%d = true := by decide +kernel"
                 % (i, n, i, i + 1))
    L.append("")
    L.append("end %s" % ns)
    L.append("")
    with open(os.path.join(outdir, "ArbEconomics_%s.lean" % tag), "w") as f:
        f.write("\n".join(L))
    print(json.dumps(dict(tag=tag, t0=t0, h=hn / 2 ** hq, G=G, N=N, terms=N - 2, nchunks=len(lens), maxerr=maxerr)))


if __name__ == "__main__":
    main()
