"""Generate the multi-file ArbEconomics instance for one height (v3: with the assembly module).

usage: gen_height.py TAG t N P CHUNK CHUNKS_PER_FILE OUTDIR
  (t a positive integer height; the evaluator supports t = tn / 2^tq, instances use tq = 0)
writes:
  OUTDIR/ArbEconomics_<TAG>_Cfg.lean   unrolled kernels, cfg, all chunk-boundary states
  OUTDIR/ArbEconomics_<TAG>_P<j>.lean  kernel chunk theorems (decide +kernel)
  OUTDIR/ArbEconomics_<TAG>.lean       assembly: Valid, invariant chain, EM remainder, and the
                                       final theorems zeta_re / zeta_im
and prints a JSON summary.  conjecture1_proved = False.
"""
import sys
import os
import json
import time
import math
from fractions import Fraction
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import arbecon_model as M

DIGITS = 8


def frac_lean(q: Fraction) -> str:
    q = Fraction(q)
    if q.denominator == 1:
        return "(%d : ℝ)" % q.numerator
    return "((%d : ℝ) / %d)" % (q.numerator, q.denominator)


def isqrt(n):
    return math.isqrt(n)


def main():
    tag, t, N, P, chunk, cpf, outdir = (sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]),
                                        int(sys.argv[5]), int(sys.argv[6]), sys.argv[7])
    tn, tq = t, 0
    c = M.make_cfg(P, tn, tq)
    Kh = len(c.dcos)
    t0 = time.time()
    s = M.init_state(c)
    states, lens, idx = [s], [], [1]
    total, done = N - 2, 0
    while done < total:
        L = min(chunk, total - done)
        s = M.run(c, s, L)
        states.append(s)
        lens.append(L)
        done += L
        idx.append(idx[-1] + L)
    sN = M.step(c, states[-1])
    pyt = time.time() - t0
    assert states[-1].n == N - 1 and sN.n == N
    base = "ArbEconomics_%s" % tag
    ns = "ArbEcon.I_%s" % tag
    cfgmod = base + "_Cfg"
    K = len(lens)
    # ------------------------------------------------------------ config / state module
    L = []
    L.append("/-  Probes/%s.lean -- ArbEconomics instance data (GENERATED by gen_height.py; do not edit)." % cfgmod)
    L.append("")
    L.append("    t = %d, EM cut N = %d (Dirichlet sum over n = 1..%d), P = %d bits." % (t, N, N - 1, P))
    L.append("    Unrolled kernels, the evaluator configuration, and the %d chunk-boundary states" % len(states))
    L.append("    (plus the state after term N).  conjecture1_proved = False.")
    L.append("-/")
    L.append("import Probes.ArbEconomics_Eval")
    L.append("")
    L.append("namespace %s" % ns)
    L.append("")
    L.append("noncomputable section")
    L.append("")
    L.append(M.lean_horner(c.one, c.dcos, "hc"))
    L.append("")
    L.append(M.lean_horner(c.one, c.dsin, "hs"))
    L.append("")
    L.append(M.lean_lnf(c, "lnf"))
    L.append("")
    L.append("def cfg : ArbEcon.Cfg := %s" % M.cfg_lean(c, "hc", "hs", "lnf"))
    L.append("")
    for i, st in enumerate(states):
        L.append("def s%d : ArbEcon.St := %s" % (i, M.st_lean(st)))
    L.append("def sN : ArbEcon.St := %s" % M.st_lean(sN))
    L.append("")
    L.append("end")
    L.append("")
    L.append("end %s" % ns)
    L.append("")
    with open(os.path.join(outdir, cfgmod + ".lean"), "w") as f:
        f.write("\n".join(L))
    # ------------------------------------------------------------ chunk parts
    parts = []
    for j, start in enumerate(range(0, K, cpf)):
        stop = min(start + cpf, K)
        pm = "%s_P%d" % (base, j)
        L = []
        L.append("/-  Probes/%s.lean -- ArbEconomics kernel chunks %d..%d (GENERATED; do not edit)." % (pm, start, stop - 1))
        L.append("    Each `chunk_i` is a kernel `decide +kernel` check that `ArbEcon.run` maps s_i to s_(i+1).")
        L.append("    conjecture1_proved = False.")
        L.append("-/")
        L.append("import Probes.%s" % cfgmod)
        L.append("")
        L.append("namespace %s" % ns)
        L.append("")
        for i in range(start, stop):
            L.append("theorem chunk_%d : ArbEcon.St.beq (ArbEcon.run cfg %d s%d) s%d = true := by decide +kernel"
                     % (i, lens[i], i, i + 1))
        if stop == K:
            L.append("theorem chunk_N : ArbEcon.St.beq (ArbEcon.run cfg 1 s%d) sN = true := by decide +kernel" % K)
        L.append("")
        L.append("end %s" % ns)
        L.append("")
        with open(os.path.join(outdir, pm + ".lean"), "w") as f:
            f.write("\n".join(L))
        parts.append(pm)
    # ------------------------------------------------------------ numerics of the final bound
    s1 = states[-1]
    one = c.one
    tt = Fraction(t)
    Bre = Fraction(-N) / (2 * (Fraction(1, 4) + tt * tt)) + Fraction(1, 2) + Fraction(1, 24 * N)
    Bim = Fraction(-N) * tt / (Fraction(1, 4) + tt * tt) + tt / (12 * N)
    aRe, aIm = abs(Bre), abs(Bim)
    prod = (Fraction(1, 4) + tt * tt) * (Fraction(9, 4) + tt * tt) * (Fraction(25, 4) + tt * tt)
    Q = Fraction(math.isqrt(int(prod * 10**6)) + 1, 1000)  # Q^2 >= prod
    assert Q * Q >= prod
    r = isqrt(N)
    E = Q / (180 * N * N * r)
    a1 = s1.reP - s1.reN
    b1 = s1.imP - s1.imN
    za = (sN.reP - sN.reN) - a1
    zb = (sN.imP - sN.imN) - b1
    zra = sN.reR + s1.reR
    zrb = sN.imR + s1.imR
    Cre = a1 + za * Bre - zb * Bim
    Rre = s1.reR + zra * aRe + zrb * aIm + E * one
    Cim = b1 + za * Bim + zb * Bre
    Rim = s1.imR + zra * aIm + zrb * aRe + E * one
    D = 10 ** DIGITS
    lo_re = Fraction(math.floor((Cre - Rre) / one * D), D)
    hi_re = Fraction(math.ceil((Cre + Rre) / one * D), D)
    lo_im = Fraction(math.floor((Cim - Rim) / one * D), D)
    hi_im = Fraction(math.ceil((Cim + Rim) / one * D), D)
    # ------------------------------------------------------------ assembly module
    L = []
    L.append("/-  Probes/%s.lean -- KERNEL-CHECKED enclosure of zeta(1/2 + %d i) (GENERATED; do not edit)." % (base, t))
    L.append("")
    L.append("    `zeta_re`, `zeta_im` bound Re / Im of riemannZeta (1/2 + %d i) with NO hypotheses:" % t)
    L.append("      * the Dirichlet sum over n = 1..%d is kernel-evaluated in %d `decide +kernel` chunks" % (N - 1, K))
    L.append("        (parts P0..P%d) and composed by `ArbEcon.chunk_sound` (ArbEconomics_Sound);" % (len(parts) - 1))
    L.append("      * the EM order-3 tail at N = %d is `EMZetaTail.em_zeta_critical_line3_enclosure`" % N)
    L.append("        (via `ArbEcon.em3_remainder_le`, E = Q / (180 N^2 r), Q = %s, r = %d);" % (str(Q), r))
    L.append("      * `ArbEcon.zeta_re_bounds` / `zeta_im_bounds` (ArbEconomics_Zeta) assemble the result.")
    L.append("    Certified: Re in [%s, %s], Im in [%s, %s] (width dominated by E)." % (
        float(lo_re), float(hi_re), float(lo_im), float(hi_im)))
    L.append("    conjecture1_proved = False.  One height, finite interval arithmetic; nothing about RH.")
    L.append("-/")
    L.append("import Probes.ArbEconomics_Zeta")
    for pm in parts:
        L.append("import Probes.%s" % pm)
    L.append("")
    L.append("namespace %s" % ns)
    L.append("")
    L.append("theorem valid : ArbEcon.Valid cfg (%d : ℝ) %d where" % (t, Kh))
    L.append("  one_eq := by decide")
    L.append("  two1_eq := by decide")
    L.append("  oneSq_eq := by decide")
    L.append("  t_eq := by show (%d : ℝ) = ((%d : ℕ) : ℝ) / 2 ^ (%d : ℕ); norm_num" % (t, tn, tq))
    L.append("  pi_ball := by")
    L.append("    show |Real.pi / 2 * 2 ^ (%d : ℕ) - ((%d : ℕ) : ℝ)| ≤ ((%d : ℕ) : ℝ)" % (P, c.hp, c.rp))
    L.append("    have h1 := Real.pi_gt_d20")
    L.append("    have h2 := Real.pi_lt_d20")
    L.append("    rw [abs_le]; constructor <;> norm_num <;> linarith")
    L.append("  umax_le := by decide")
    L.append("  dcos_eq := by decide")
    L.append("  dsin_eq := by decide")
    L.append("  tau_ok := by")
    L.append("    show (2 : ℝ) ^ (%d : ℕ) * ArbEcon.taylorBnd %d ≤ ((%d : ℕ) : ℝ)" % (P, Kh, c.tau))
    L.append("    unfold ArbEcon.taylorBnd; norm_num [Nat.factorial]")
    L.append("  hc_eq := fun _ => rfl")
    L.append("  hs_eq := fun _ => rfl")
    L.append("  lnf_eq := fun _ => rfl")
    L.append("")
    L.append("theorem inv_0 : ArbEcon.Inv cfg (%d : ℝ) 1 s0 := ArbEcon.inv_init cfg _ valid.one_eq" % t)
    for i in range(K):
        L.append("theorem inv_%d : ArbEcon.Inv cfg (%d : ℝ) %d s%d :=\n  ArbEcon.chunk_sound cfg _ %d valid %d %d s%d s%d inv_%d chunk_%d"
                 % (i + 1, t, idx[i + 1], i + 1, Kh, lens[i], idx[i], i, i + 1, i, i))
    L.append("theorem inv_N : ArbEcon.Inv cfg (%d : ℝ) %d sN :=\n  ArbEcon.chunk_sound cfg _ %d valid 1 %d s%d sN inv_%d chunk_N"
             % (t, N, Kh, N - 1, K, K))
    L.append("")
    L.append("theorem remainder :")
    L.append("    ‖riemannZeta (ArbEcon.sOf %d) - ZetaReflection.emZetaFinite3 (ArbEcon.sOf %d) %d‖" % (t, t, N))
    L.append("      ≤ %s / (180 * (%d : ℝ) ^ 2 * (%d : ℕ)) :=" % (frac_lean(Q), N, r))
    L.append("  ArbEcon.em3_remainder_le %d %d (by norm_num) _ (by norm_num) (by norm_num) %d (by norm_num) (by norm_num)"
             % (t, N, r))
    L.append("")
    common = "cfg %d %d (by norm_num) s%d sN inv_%d inv_N _ remainder %s %s" % (t, N, K, K, frac_lean(aRe), frac_lean(aIm))
    L.append("/-- **Re zeta(1/2 + %d i)**, kernel-checked, no hypotheses. -/" % t)
    L.append("theorem zeta_re : %s ≤ (riemannZeta ((1 / 2 : ℂ) + ((%d : ℝ) : ℂ) * Complex.I)).re ∧" % (frac_lean(lo_re), t))
    L.append("    (riemannZeta ((1 / 2 : ℂ) + ((%d : ℝ) : ℂ) * Complex.I)).re ≤ %s :=" % (t, frac_lean(hi_re)))
    L.append("  ArbEcon.zeta_re_bounds %s %s %s" % (common, frac_lean(lo_re), frac_lean(hi_re)))
    L.append("    (by rw [abs_le]; constructor <;> norm_num) (by rw [abs_le]; constructor <;> norm_num)")
    L.append("    (by norm_num [s%d, sN, cfg]) (by norm_num [s%d, sN, cfg])" % (K, K))
    L.append("")
    L.append("/-- **Im zeta(1/2 + %d i)**, kernel-checked, no hypotheses. -/" % t)
    L.append("theorem zeta_im : %s ≤ (riemannZeta ((1 / 2 : ℂ) + ((%d : ℝ) : ℂ) * Complex.I)).im ∧" % (frac_lean(lo_im), t))
    L.append("    (riemannZeta ((1 / 2 : ℂ) + ((%d : ℝ) : ℂ) * Complex.I)).im ≤ %s :=" % (t, frac_lean(hi_im)))
    L.append("  ArbEcon.zeta_im_bounds %s %s %s" % (common, frac_lean(lo_im), frac_lean(hi_im)))
    L.append("    (by rw [abs_le]; constructor <;> norm_num) (by rw [abs_le]; constructor <;> norm_num)")
    L.append("    (by norm_num [s%d, sN, cfg]) (by norm_num [s%d, sN, cfg])" % (K, K))
    L.append("")
    L.append("end %s" % ns)
    L.append("")
    with open(os.path.join(outdir, base + ".lean"), "w") as f:
        f.write("\n".join(L))
    summary = dict(tag=tag, t=t, N=N, P=P, chunk=chunk, nchunks=K, terms=N - 1, python_seconds=round(pyt, 2),
                   cfg_module=cfgmod, parts=parts, assembly=base,
                   lo_re=float(lo_re), hi_re=float(hi_re), lo_im=float(lo_im), hi_im=float(hi_im),
                   E=float(E), rad_re=float(Rre / one), rad_im=float(Rim / one),
                   eval_rad_re=float((s1.reR + zra * aRe + zrb * aIm) / one))
    print(json.dumps(summary))


if __name__ == "__main__":
    main()
