"""Emit Probes/ArbEconomics_Micro.lean: the kernel cost microbenchmarks behind the evaluator design.

Every theorem is a kernel `decide +kernel` check of a loop whose expected value is computed here in
Python; timing is read with `lean -Dprofiler=true -Dprofiler.threshold=1`.
conjecture1_proved = False.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import arbecon_model as M
import arbecon_multi as MM

out = sys.argv[1]
c = M.make_cfg(64, 1000, 0)
L = []
L.append("""/-  Probes/ArbEconomics_Micro.lean -- kernel cost microbenchmarks (GENERATED by gen_micro.py).

    Each `theorem` is a kernel `decide +kernel` check; read the kernel time of each with
      lean -Dprofiler=true -Dprofiler.threshold=1 Probes/ArbEconomics_Micro.lean
    (the lean_lib-free command line is in the ArbEconomics report).  Measured on this host
    (M3 Ultra, v4.32.0), 2026-09-23:

      A. 1e5-iteration loops, 5 mul + 5 shift + 6 add per iteration on ~128-bit numbers
         a_natDirect   (Nat.mul/Nat.add/Nat.shiftRight called directly)   ~2.5 s  (~1.5 us/op)
         a_natNotation (the same with * + >>> on Nat)                     ~9.8 s  (4x)
         a_intDirect   (Int.mul/Int.add/Int.shiftRight called directly)   ~53 s   (21x)
         a_intNotation (the same with notation on Int)                    ~60 s   (24x)
      B. loop overhead, 1e5 iterations of one mul + one add
         b_brecOn (structural recursion by pattern matching)              ~1.5 s
         b_natRec (raw Nat.rec)                                           ~0.33 s (4.7x)
      C. Horner, 2000 evaluations of a 9-step cos Horner
         c_listRec  (List.rec over the divisor list)                      ~130-180 ms
         c_unrolled (per-config unrolled function)                        ~48 ms  (2.7-3.8x)
      D. Bool equality, 20000 evaluations (loop includes 2 mod + 2 beq)
         d_beq  (`a == b` via the BEq/DecidableEq instance)               ~420-475 ms
         d_xnor (raw Bool.rec)                                            ~166 ms (== costs ~13 us more)
      E. evaluator components (2000 calls each, m >= 10000; per call)
         e_log 17 us, e_sqrt 26 us, e_trig 107 us (e_horner 25 us per 9-step Horner), loop 2.5 us

    Also measured (not in this file): plain `decide` = elaborator evaluation + kernel re-check,
    2.4x `decide +kernel` on a 20-term chunk, and it hits `maxRecDepth` on 500-term chunks.

    conjecture1_proved = False.
-/
import Probes.ArbEconomics_Eval

namespace ArbEcon.Micro

noncomputable section
""")
# A: Nat vs Int
L.append("""def a_natDirect (n : Nat) : Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat) (fun acc => acc)
    (fun k ih acc =>
      let x := Nat.add k 340282366920938463463374607431768211297
      let a1 := Nat.shiftRight (Nat.mul x x) 128
      let a2 := Nat.shiftRight (Nat.mul a1 x) 128
      let a3 := Nat.shiftRight (Nat.mul a2 x) 128
      let a4 := Nat.shiftRight (Nat.mul a3 x) 128
      let a5 := Nat.shiftRight (Nat.mul a4 x) 128
      ih (Nat.add acc (Nat.add a1 (Nat.add a2 (Nat.add a3 (Nat.add a4 a5)))))) n
def a_natNotation (n : Nat) : Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat) (fun acc => acc)
    (fun k ih acc =>
      let x := k + 340282366920938463463374607431768211297
      let a1 := (x * x) >>> 128
      let a2 := (a1 * x) >>> 128
      let a3 := (a2 * x) >>> 128
      let a4 := (a3 * x) >>> 128
      let a5 := (a4 * x) >>> 128
      ih (acc + (a1 + (a2 + (a3 + (a4 + a5)))))) n
def a_intDirect (n : Nat) : Int → Int :=
  Nat.rec (motive := fun _ => Int → Int) (fun acc => acc)
    (fun k ih acc =>
      let x : Int := Int.sub (Int.ofNat k) 340282366920938463463374607431768211297
      let a1 := Int.shiftRight (Int.mul x x) 128
      let a2 := Int.shiftRight (Int.mul a1 x) 128
      let a3 := Int.shiftRight (Int.mul a2 x) 128
      let a4 := Int.shiftRight (Int.mul a3 x) 128
      let a5 := Int.shiftRight (Int.mul a4 x) 128
      ih (Int.add acc (Int.add a1 (Int.add a2 (Int.add a3 (Int.add a4 a5)))))) n
def a_intNotation (n : Nat) : Int → Int :=
  Nat.rec (motive := fun _ => Int → Int) (fun acc => acc)
    (fun k ih acc =>
      let x : Int := (k : Int) - 340282366920938463463374607431768211297
      let a1 := (x * x) >>> 128
      let a2 := (a1 * x) >>> 128
      let a3 := (a2 * x) >>> 128
      let a4 := (a3 * x) >>> 128
      let a5 := (a4 * x) >>> 128
      ih (acc + (a1 + (a2 + (a3 + (a4 + a5)))))) n
""")
# B: brecOn vs Nat.rec
L.append("""def b_brecOn : Nat → Nat → Nat
  | 0, acc => acc
  | n+1, acc => b_brecOn n (Nat.add acc (Nat.mul n n))
def b_natRec (n : Nat) : Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat) (fun acc => acc) (fun k ih acc => ih (Nat.add acc (Nat.mul k k))) n
""")
# C: Horner List.rec vs unrolled
L.append(M.lean_horner(c.one, c.dcos, "hornU"))
L.append("""def c_listRec (ds : List Nat) (cnt : Nat) : Nat → Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat → Nat) (fun _ acc => acc)
    (fun _ ih m acc => ih (Nat.succ m) (Nat.add acc (ArbEcon.horner 18446744073709551616 (Nat.div (Nat.mul m 18446744073709551616) 12000) ds 18446744073709551616))) cnt
def c_unrolled (cnt : Nat) : Nat → Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat → Nat) (fun _ acc => acc)
    (fun _ ih m acc => ih (Nat.succ m) (Nat.add acc (hornU (Nat.div (Nat.mul m 18446744073709551616) 12000)))) cnt
def dcosList : List Nat := [%s]
""" % ", ".join(map(str, c.dcos)))
# D: Bool == vs xnor
L.append("""def xnor (a b : Bool) : Bool := Bool.rec (Bool.rec true false b) (Bool.rec false true b) a
def d_beq (cnt : Nat) : Nat → Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat → Nat) (fun _ acc => acc)
    (fun _ ih k acc => ih (Nat.succ k) (Nat.add acc (Bool.rec 0 1 ((Nat.beq (Nat.mod k 2) 0) == (Nat.beq (Nat.mod k 3) 0))))) cnt
def d_xnor (cnt : Nat) : Nat → Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat → Nat) (fun _ acc => acc)
    (fun _ ih k acc => ih (Nat.succ k) (Nat.add acc (Bool.rec 0 1 (xnor (Nat.beq (Nat.mod k 2) 0) (Nat.beq (Nat.mod k 3) 0))))) cnt
""")
# E: components
L.append(M.lean_horner(c.one, c.dcos, "hc"))
L.append(M.lean_horner(c.one, c.dsin, "hs"))
L.append(M.lean_lnf(c, "lnf"))
L.append("def cfg : ArbEcon.Cfg := %s" % M.cfg_lean(c, "hc", "hs", "lnf"))
L.append("""def e_log (cnt : Nat) : Nat → Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat → Nat) (fun _ acc => acc)
    (fun _ ih m acc => ih (Nat.succ m) (Nat.add acc (ArbEcon.logInc cfg m).1)) cnt
def e_sqrt (cnt : Nat) : Nat → Nat → Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat → Nat → Nat) (fun _ _ acc => acc)
    (fun _ ih m g acc => let g2 := ArbEcon.isqrt cfg m (Nat.div cfg.oneSq m) g; ih (Nat.succ m) g2 (Nat.add acc g2)) cnt
def e_trig (cnt : Nat) : Nat → Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat → Nat) (fun _ acc => acc)
    (fun _ ih m acc =>
      let th := Nat.div (Nat.mul (Nat.mul cfg.one m) 1000) 7
      let tr := ArbEcon.trig cfg th (Nat.add th 5)
      ih (Nat.succ m) (Nat.add acc (Nat.add (Nat.add tr.cm tr.sm) tr.cr))) cnt
def e_horner (cnt : Nat) : Nat → Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat → Nat) (fun _ acc => acc)
    (fun _ ih m acc => ih (Nat.succ m) (Nat.add acc (cfg.hc (Nat.div (Nat.mul m cfg.one) 24000)))) cnt
def e_empty (cnt : Nat) : Nat → Nat → Nat :=
  Nat.rec (motive := fun _ => Nat → Nat → Nat) (fun _ acc => acc)
    (fun _ ih m acc => ih (Nat.succ m) (Nat.add acc m)) cnt
""")
L.append("end")
L.append("")


# expected values
def a_nat(n):
    acc = 0
    for k in range(n - 1, -1, -1):
        x = k + 340282366920938463463374607431768211297
        a1 = (x * x) >> 128; a2 = (a1 * x) >> 128; a3 = (a2 * x) >> 128; a4 = (a3 * x) >> 128; a5 = (a4 * x) >> 128
        acc += a1 + a2 + a3 + a4 + a5
    return acc


def a_int(n):
    acc = 0
    for k in range(n - 1, -1, -1):
        x = k - 340282366920938463463374607431768211297
        a1 = (x * x) >> 128; a2 = (a1 * x) >> 128; a3 = (a2 * x) >> 128; a4 = (a3 * x) >> 128; a5 = (a4 * x) >> 128
        acc += a1 + a2 + a3 + a4 + a5
    return acc


NA = 100000
va, vi = a_nat(NA), a_int(NA)
L.append("theorem thm_a_natDirect : Nat.beq (a_natDirect %d 0) %d = true := by decide +kernel" % (NA, va))
L.append("theorem thm_a_natNotation : Nat.beq (a_natNotation %d 0) %d = true := by decide +kernel" % (NA, va))
L.append("theorem thm_a_intDirect : a_intDirect %d 0 = %d := by decide +kernel" % (NA, vi))
L.append("theorem thm_a_intNotation : a_intNotation %d 0 = %d := by decide +kernel" % (NA, vi))
vb = sum(k * k for k in range(NA))
L.append("theorem thm_b_brecOn : Nat.beq (b_brecOn %d 0) %d = true := by decide +kernel" % (NA, vb))
L.append("theorem thm_b_natRec : Nat.beq (b_natRec %d 0) %d = true := by decide +kernel" % (NA, vb))
vc = sum(M.horner(c.one, (m * c.one) // 12000, c.dcos) for m in range(1000, 3000))
L.append("theorem thm_c_listRec : Nat.beq (c_listRec dcosList 2000 1000 0) %d = true := by decide +kernel" % vc)
L.append("theorem thm_c_unrolled : Nat.beq (c_unrolled 2000 1000 0) %d = true := by decide +kernel" % vc)
vd = sum(1 for k in range(20000) if (k % 2 == 0) == (k % 3 == 0))
L.append("theorem thm_d_beq : Nat.beq (d_beq 20000 0 0) %d = true := by decide +kernel" % vd)
L.append("theorem thm_d_xnor : Nat.beq (d_xnor 20000 0 0) %d = true := by decide +kernel" % vd)
B, CNT = 10000, 2000
vl = sum(M.log_inc(c, m)[0] for m in range(B, B + CNT))
g = M.isqrt_loop(c.oneSq // (B - 1), c.one, 64); g0 = g; vq = 0
for m in range(B, B + CNT):
    g = M.isqrt(c, m, c.oneSq // m, g); vq += g
vt = 0
for m in range(B, B + CNT):
    th = (c.one * m * 1000) // 7
    (cm, cs, cr), (sm, ss, sr) = M.trig(c, th, th + 5)
    vt += cm + sm + cr
vh = sum(M.horner(c.one, (m * c.one) // 24000, c.dcos) for m in range(B, B + CNT))
L.append("theorem thm_e_log : Nat.beq (e_log %d %d 0) %d = true := by decide +kernel" % (CNT, B, vl))
L.append("theorem thm_e_sqrt : Nat.beq (e_sqrt %d %d %d 0) %d = true := by decide +kernel" % (CNT, B, g0, vq))
L.append("theorem thm_e_trig : Nat.beq (e_trig %d %d 0) %d = true := by decide +kernel" % (CNT, B, vt))
L.append("theorem thm_e_horner : Nat.beq (e_horner %d %d 0) %d = true := by decide +kernel" % (CNT, B, vh))
L.append("theorem thm_e_empty : Nat.beq (e_empty %d %d 0) %d = true := by decide +kernel" % (CNT, B, sum(range(B, B + CNT))))
L.append("")
L.append("end ArbEcon.Micro")
L.append("")
open(out, "w").write("\n".join(L))
print("ok")
