/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node anduril/AND_first_zero_kernel.
   The TYPE below is the registered statement, missions/anduril/lean/Statements/
   AND_first_zero_kernel.lean (header sha256 bbfd85f7b712a585), binders and conclusion verbatim; the
   PROOF is the artifact constant `ForgeFirstZeroKernel.first_zero_kernel` from ForgeFirstZeroKernel. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   The AxiomGuard imports load the whole island, so a vocabulary constant shadowed by
   the artifact is a duplicate declaration here, not a silent substitution. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import ForgeFirstZeroKernel
import AxiomGuardA4
import AxiomGuardAllZerosKernel_h1000
import AxiomGuardArbKernel
import AxiomGuardArgChange
import AxiomGuardBandGlue
import AxiomGuardEMTail
import AxiomGuardEMZetaComplex
import AxiomGuardEMZetaHigh
import AxiomGuardEMZetaOffline
import AxiomGuardFirstZeroKernel
import AxiomGuardH1000Line
import AxiomGuardHeightFloor
import AxiomGuardRSTheta
import AxiomGuardStirling

namespace ForgeFirstZeroKernel

open Complex Real Filter ThetaGap

theorem _root_.MissionJudge.AND_first_zero_kernel :
    ∃ r : ℝ, 14 < r ∧ r < 15 ∧ completedRiemannZeta (1 / 2 + (r : ℂ) * Complex.I) = 0 :=
  ForgeFirstZeroKernel.first_zero_kernel

end ForgeFirstZeroKernel
