/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node mirrormere/MM_nt_brick_conditional.
   The TYPE below is the registered statement, missions/mirrormere/lean/Statements/
   MM_nt_brick_conditional.lean (header sha256 9921b9185d246847), binders and conclusion verbatim; the
   PROOF is the artifact constant `Quasicrystal.zeta_ordinates_not_uniformlyDiscrete_of_unbounded_density` from BoundaryLemmas. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   The AxiomGuard imports load the whole island, so a vocabulary constant shadowed by
   the artifact is a duplicate declaration here, not a silent substitution. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import BoundaryLemmas

namespace Quasicrystal

open Real

theorem _root_.MissionJudge.MM_nt_brick_conditional :
    ∀ {Ordinates : Set ℝ} (hRvM : RvMUnboundedMeanDensity Ordinates), ¬ IsUniformlyDiscrete Ordinates :=
  Quasicrystal.zeta_ordinates_not_uniformlyDiscrete_of_unbounded_density

end Quasicrystal
