"""Generate PetersenCertificate.lean: fully kernel-checked per-instance
degree-4 SOS lower bound witness for the Tseitin contradiction on the
Petersen graph.

Emits: clause masks + signs, the width-4 closure sign table (26 entries,
empty set first), the 121 degree-<=2 index masks, and Lean theorems:

  * refutation_certificate  -- the clauses XOR to 0 with sign product -1
    (the instance is contradictory, kernel-checked);
  * respect_true / constraint_respect -- the closure sign table respects
    every clause within width 4 (the pseudoexpectation honors the instance);
  * pairCheck_true / pairFact -- sign multiplicativity across all
    index-compatible closure pairs (the ONE heavy kernel evaluation,
    engineered for feasibility: Nat-bitmask XOR, fueled popcount,
    short-circuiting Bool guards);
  * petersen_moment_psd -- the 121x121 degree-4 moment matrix has
    nonnegative quadratic form, via Xor3Structure's abstract
    partially-multiplicative-kernel theorem.

ANTI-PHANTOM: the generator re-verifies, in exact Python arithmetic, the
LITERAL semantics of every Bool it asks the kernel to evaluate (including
the guarded pair sweep), and checks a corrupted-sign negative control flips
pairCheck to False, before writing any Lean.

Usage: gen_petersen_cert.py [--out PATH]
"""
from __future__ import annotations

import argparse

from xor3_pseudoexpectation import petersen_tseitin, closure, unsat_gf2, index_sets


def mask(fs) -> int:
    out = 0
    for i in fs:
        out |= 1 << i
    return out


def pop(x: int) -> int:
    return bin(x).count("1")


def build_data():
    inst, n = petersen_tseitin()
    assert n == 15
    assert unsat_gf2(inst, n)
    sgn_map, conflict = closure(inst, 4)
    assert not conflict
    clause_pairs = [(mask(a), e) for a, e in inst]
    lam_pairs = [(mask(u), s) for u, s in sgn_map.items()]
    lam_pairs.sort(key=lambda p: (p[0] != 0, p[0]))  # empty set first
    assert lam_pairs[0] == (0, 1)
    idx = sorted(mask(S) for S in index_sets(n, 2))
    assert len(idx) == 121 and len(set(idx)) == 121
    return clause_pairs, lam_pairs, idx


def sgn_of(lam_pairs, x: int):
    for a, s in lam_pairs:
        if a == x:
            return s
    return 0


def verify_emitted_semantics(clause_pairs, lam_pairs, idx) -> None:
    lam = [a for a, _ in lam_pairs]
    # refutation certificate
    acc, prod = 0, 1
    for c, e in clause_pairs:
        acc ^= c
        prod *= e
    assert acc == 0 and prod == -1, "refutation certificate failed"
    # constraint respect (width 4)
    for c, e in clause_pairs:
        for a in lam:
            if pop(a ^ c) <= 4:
                assert sgn_of(lam_pairs, a ^ c) == e * sgn_of(lam_pairs, a), \
                    (c, a)
    # the heavy pair sweep, literal semantics
    checked = 0
    for a in lam:
        for b in lam:
            for t in idx:
                if pop(a ^ t) <= 2 and pop(b ^ t) <= 2:
                    assert sgn_of(lam_pairs, a ^ b) \
                        == sgn_of(lam_pairs, a) * sgn_of(lam_pairs, b), (a, b, t)
                    checked += 1
    assert checked > 0
    print(f"PASS emitted semantics verified exactly in Python "
          f"({checked} guarded pair-witness triples)")
    # negative control: corrupt one nonzero sign -> sweep must fail
    bad = [(a, (-s if a == lam[5] else s)) for a, s in lam_pairs]
    broken = False
    for a in lam:
        for b in lam:
            for t in idx:
                if pop(a ^ t) <= 2 and pop(b ^ t) <= 2:
                    if sgn_of(bad, a ^ b) != sgn_of(bad, a) * sgn_of(bad, b):
                        broken = True
                        break
            if broken:
                break
        if broken:
            break
    assert broken, "corrupted sign not detected by pair sweep"
    print("PASS negative control: corrupted closure sign flips the pair sweep")


def q(v) -> str:
    return str(v) if v >= 0 else f"(-{-v})"


def emit(clause_pairs, lam_pairs, idx) -> str:
    clauses = ", ".join(f"({c}, {q(e)})" for c, e in clause_pairs)
    lams = ", ".join(f"({a}, {q(s)})" for a, s in lam_pairs)
    idxs = ", ".join(str(t) for t in idx)
    return f'''/- TELPERION-GENERATED by telperion/examples/knapsack_sos/gen_petersen_cert.py.
   DO NOT EDIT BY HAND -- regenerate instead.

   Fully kernel-checked per-instance degree-4 SOS lower-bound witness for
   the Tseitin contradiction on the Petersen graph (15 edge variables, one
   3XOR clause per vertex, odd charge). Sets are Nat bitmasks; symmetric
   difference is XOR (kernel-accelerated). In one file the kernel verifies:
   the instance is contradictory (refutation_certificate), the width-4
   closure sign table respects every clause (constraint_respect), sign
   multiplicativity across all index-compatible closure pairs (pairFact,
   the one heavy evaluation), and PSDness of the 121x121 degree-4 moment
   matrix (petersen_moment_psd) via the abstract structure theorem.

   Python-pinned residual: that idxList is the COMPLETE enumeration of
   masks of popcount <= 2 (idx_valid checks soundness of each entry, not
   completeness -- restricting the index set only weakens the statement),
   and the standard moment/SOS duality. -/
import Mathlib
import Xor3Structure

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000

namespace PetersenCertificate

open Xor3Structure

/-- Fueled popcount: structural in fuel, hence kernel-reducible. -/
def pop : ℕ → ℕ → ℕ
  | 0, _ => 0
  | f + 1, n => if n = 0 then 0 else n % 2 + pop f (n / 2)

/-- The ten Tseitin clauses: (edge-incidence mask of a vertex, charge).
Signs live in ℤ so every fact below is kernel-decidable (ℚ arithmetic does
not reduce definitionally -- Rat.normalize bottoms out in well-founded
Nat.gcd); they are cast into ℚ only at the PSD statement. -/
def clausePairs : List (ℕ × ℤ) := [{clauses}]

/-- The width-4 closure sign table (empty set first, sign 1). -/
def lamPairs : List (ℕ × ℤ) := [{lams}]

def lam : List ℕ := lamPairs.map Prod.fst

/-- All degree-<=2 index masks over 15 variables. -/
def idxList : List ℕ := [{idxs}]

/-- The pseudoexpectation sign: table lookup, 0 off the closure. -/
def sgn (x : ℕ) : ℤ := (((lamPairs.find? (fun p => p.1 == x)).map Prod.snd).getD 0)

theorem sgn_zero : sgn 0 = 1 := rfl

/-- The instance is contradictory: all clauses XOR to the empty set while
their charges multiply to -1. Kernel-checked nonvacuity. -/
theorem refutation_certificate :
    (clausePairs.foldl (fun acc p => acc ^^^ p.1) 0 = 0) ∧
    (clausePairs.foldl (fun acc p => acc * p.2) 1 = -1) := by
  constructor <;> decide

/-- Every index mask has popcount <= 2. -/
theorem idx_valid : ∀ t ∈ idxList, pop 16 t ≤ 2 := by decide

/-- The closure sign table respects every clause within width 4: the
pseudoexpectation honors the instance's constraints. Decidable guarded
Prop; the instance short-circuits on failed guards. -/
theorem constraint_respect :
    ∀ c ∈ clausePairs, ∀ a ∈ lam, pop 16 (a ^^^ c.1) ≤ 4 →
      sgn (a ^^^ c.1) = c.2 * sgn a := by decide

/-- Sign multiplicativity across index-compatible closure pairs. THE heavy
kernel evaluation (26 x 26 x 121 guarded triples; guards are two fueled
popcounts over kernel-accelerated Nat XOR, so failed guards are cheap). -/
theorem pairFact : ∀ a ∈ lam, ∀ b ∈ lam, ∀ t ∈ idxList,
    pop 16 (a ^^^ t) ≤ 2 → pop 16 (b ^^^ t) ≤ 2 →
      sgn (a ^^^ b) = sgn a * sgn b := by decide

/-- Off the closure the sign vanishes. -/
theorem sgn_ne_zero_mem {{x : ℕ}} (h : sgn x ≠ 0) : x ∈ lam := by
  by_contra hx
  apply h
  have hfind : lamPairs.find? (fun p => p.1 == x) = none := by
    rw [List.find?_eq_none]
    intro p hp
    simp only [beq_iff_eq]
    intro hpx
    exact hx (hpx ▸ List.mem_map_of_mem hp)
  simp [sgn, hfind]

/-- The index map (out-of-range default 0 is never hit at Fin 121). -/
def m (i : Fin 121) : ℕ := idxList.getD i.val 0

theorem m_mem : ∀ i : Fin 121, m i ∈ idxList := by decide

theorem m_pop : ∀ i : Fin 121, pop 16 (m i) ≤ 2 := by decide

/-- The degree-4 moment matrix of the Petersen pseudoexpectation, in mask
coordinates: D i j = sgn(m i XOR m j), cast into ℚ. -/
def D (i j : Fin 121) : ℚ := (sgn (m i ^^^ m j) : ℚ)

/-- THE CERTIFIED INSTANCE: the degree-4 moment matrix of the width-4
Petersen Tseitin pseudoexpectation has nonnegative quadratic form. With
refutation_certificate (the instance IS contradictory) and
constraint_respect, this is a kernel-checked degree-4 SOS lower bound for
a canonical unsatisfiable instance. -/
theorem petersen_moment_psd (x : Fin 121 → ℚ) :
    0 ≤ ∑ i, ∑ j, x i * D i j * x j := by
  refine consistent_kernel_quadform_nonneg D ?_ ?_ ?_ x
  · intro i
    simp [D, sgn_zero]
  · intro i j
    simp [D, Nat.xor_comm]
  · intro i j k hij hjk
    have ha : sgn (m i ^^^ m j) ≠ 0 := Int.cast_ne_zero.mp hij
    have hb : sgn (m j ^^^ m k) ≠ 0 := Int.cast_ne_zero.mp hjk
    have hxor : (m i ^^^ m j) ^^^ (m j ^^^ m k) = m i ^^^ m k := by
      rw [Nat.xor_assoc, ← Nat.xor_assoc (m j), Nat.xor_self, Nat.zero_xor]
    have hg1 : pop 16 ((m i ^^^ m j) ^^^ m j) ≤ 2 := by
      rw [Nat.xor_assoc, Nat.xor_self, Nat.xor_zero]
      exact m_pop i
    have hg2 : pop 16 ((m j ^^^ m k) ^^^ m j) ≤ 2 := by
      rw [Nat.xor_comm (m j) (m k), Nat.xor_assoc, Nat.xor_self, Nat.xor_zero]
      exact m_pop k
    have key := pairFact _ (sgn_ne_zero_mem ha) _ (sgn_ne_zero_mem hb)
      (m j) (m_mem j) hg1 hg2
    show D i k = D i j * D j k
    simp only [D]
    rw [← hxor]
    exact_mod_cast key

end PetersenCertificate

#print axioms PetersenCertificate.refutation_certificate
#print axioms PetersenCertificate.constraint_respect
#print axioms PetersenCertificate.pairFact
#print axioms PetersenCertificate.petersen_moment_psd
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="../g1_floors/lean/PetersenCertificate.lean")
    args = parser.parse_args()
    clause_pairs, lam_pairs, idx = build_data()
    verify_emitted_semantics(clause_pairs, lam_pairs, idx)
    with open(args.out, "w") as fh:
        fh.write(emit(clause_pairs, lam_pairs, idx))
    print(f"wrote {args.out} (clauses=10, closure={len(lam_pairs)}, idx={len(idx)})")


if __name__ == "__main__":
    main()
