"""Generate BridgeD4.lean: all 35 Gram-bridge entry identities for d = 4.

For each block level k <= 4 and entry (i, j) with k <= j <= i <= 4, emits the
Lean theorem that the COMBINATORIAL Gram formula

    G_k[i,j] = 2^k sum_{s<=k} (-1)^(k-s) C(k,s)
               sum_t C(m,t) C(m-t, i-k-t) C(m-i+k, j-k-t) f(i+j-s-t),
    m = n - 2k,

equals the rank-1 prediction  g_k(n) * v(i-k) * v(j-k).  Binomials in the
symbolic m = n - 2k are expanded to explicit rational-coefficient polynomials
in n, so each identity is field_simp/ring-shaped over Q(n).

ANTI-PHANTOM GATE: every constructed sympy expression is validated EXACTLY
(Fraction arithmetic, several odd n) against gram_block_fast AND against the
rank-1 form g_scalar * v * v BEFORE any Lean text is written; the Lean kernel
is the final gate.  A corrupted-coefficient negative control must be caught.

Usage: gen_bridge_d4.py [--out PATH]
"""
from __future__ import annotations

import argparse
from fractions import Fraction
from math import comb, factorial

import sympy as sp

from knapsack_pseudoexpectation import f_moment, g_scalar, gram_block_fast, v_direction

D = 4
NSYM = sp.symbols("n")
FSYMS = {q: sp.symbols(f"fq{q}") for q in range(2 * D + 1)}


def binom_poly(mexpr, t: int):
    """C(mexpr, t) as an explicit polynomial (t a literal)."""
    out = sp.Rational(1, factorial(t))
    for u in range(t):
        out *= (mexpr - u)
    return sp.expand(out)


def entry_expr(k: int, i: int, j: int):
    """Symbolic combinatorial formula for G_k[i,j], i >= j, over n and fq_*."""
    m = NSYM - 2 * k
    acc = sp.Integer(0)
    for s in range(k + 1):
        sign = (-1) ** (k - s) * comb(k, s)
        for t in range(0, j - k + 1):
            coeff = binom_poly(m, t) * binom_poly(m - t, i - k - t) \
                * binom_poly(m - i + k, j - k - t)
            acc += sign * coeff * FSYMS[i + j - s - t]
    return sp.expand(2 ** k * acc)


def validate_entry(k: int, i: int, j: int, expr) -> None:
    for nv in (9, 11, 13, 15):
        r = Fraction(nv, 2)
        subs = {NSYM: sp.Integer(nv)}
        for q, sym in FSYMS.items():
            fv = f_moment(r, nv, q)
            subs[sym] = sp.Rational(fv.numerator, fv.denominator)
        got = expr.subs(subs)
        G = gram_block_fast(r, nv, k, D)
        want = G[i - k][j - k]
        want_r = sp.Rational(want.numerator, want.denominator)
        assert got == want_r, f"formula mismatch k={k} ({i},{j}) n={nv}"
        g = g_scalar(r, nv, k)
        v = v_direction(r, k, D)
        rank1 = g * v[i - k] * v[j - k]
        assert want == rank1, f"rank-1 mismatch k={k} ({i},{j}) n={nv}"


def lean_poly(expr) -> str:
    """Render a rational-coefficient polynomial in n as Lean-parsable text."""
    s = str(sp.expand(expr))
    return s.replace("**", "^")


def lean_lhs(expr) -> str:
    """Render the entry expression as sum of (poly) * f n q, q descending."""
    terms = []
    poly = sp.Poly(expr, *[FSYMS[q] for q in sorted(FSYMS)])
    coeffs = {}
    for mono, c in poly.terms():
        idx = [q for q, e in zip(sorted(FSYMS), mono) if e]
        assert sum(mono) <= 1, "nonlinear in f -- impossible"
        q = idx[0] if idx else None
        coeffs[q] = coeffs.get(q, 0) + c
    parts = []
    for q in sorted((x for x in coeffs if x is not None), reverse=True):
        c = sp.expand(coeffs[q])
        if c == 0:
            continue
        parts.append(f"({lean_poly(c)}) * f n {q}")
    const = coeffs.get(None, 0)
    if const != 0 or not parts:
        parts.append(f"({lean_poly(const)})")
    return " + ".join(parts)


HEADER = '''/- TELPERION-GENERATED by telperion/examples/knapsack_sos/gen_bridge_d4.py.
   DO NOT EDIT BY HAND -- regenerate instead.

   All 35 Gram-bridge entry identities for the degree-8 (d = 4) knapsack
   pseudoexpectation: the combinatorial Gram formula equals the rank-1 form
   g_k * v(i-k) * v(j-k) for every block k <= 4 and entry k <= j <= i <= 4.
   With KnapsackSOS.block0_psd..block4_psd this makes the d = 4 Gram bridge
   fully kernel-checked; the residual Python-pinned layer is only the
   z-vector Gram derivation (harmonic completeness, validated by 130x130
   spectral reconstruction) and the standard moment/SOS duality.

   Every emitted identity was validated in exact Fraction arithmetic against
   gram_block_fast AND g_scalar * v * v before emission (anti-phantom gate);
   the Lean kernel is the final gate. -/
import Mathlib
import KnapsackSOS

set_option maxHeartbeats 1600000
set_option linter.unusedTactic false

namespace KnapsackSOS
namespace BridgeD4

'''

PROOF = '''  have h0 : n ≠ 0 := ne_of_gt (by linarith)
  have h1 : n - 1 ≠ 0 := ne_of_gt (by linarith)
  have h2 : n - 2 ≠ 0 := ne_of_gt (by linarith)
  have h3 : n - 3 ≠ 0 := ne_of_gt (by linarith)
  have h4 : n - 4 ≠ 0 := ne_of_gt (by linarith)
  have h5 : n - 5 ≠ 0 := ne_of_gt (by linarith)
  have h6 : n - 6 ≠ 0 := ne_of_gt (by linarith)
  have h7 : n - 7 ≠ 0 := ne_of_gt (by linarith)
  simp only [g{k}, f, v]
  push_cast
  field_simp
  all_goals ring'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out",
        default="../g1_floors/lean/BridgeD4.lean")
    args = parser.parse_args()

    names = []
    body = []
    for k in range(D + 1):
        for i in range(k, D + 1):
            for j in range(k, i + 1):
                expr = entry_expr(k, i, j)
                validate_entry(k, i, j, expr)
                name = f"entry_k{k}_i{i}_j{j}"
                names.append(name)
                body.append(
                    f"theorem {name} (n : ℚ) (hn : (7 : ℚ) < n) :\n"
                    f"    {lean_lhs(expr)}\n"
                    f"      = g{k} n * v n {k} {i - k} * v n {k} {j - k} := by\n"
                    + PROOF.replace("{k}", str(k)) + "\n")
    assert len(names) == 35, len(names)

    # negative control: a corrupted expression must fail exact validation
    bad = entry_expr(2, 3, 2) + sp.Rational(1, 10 ** 9)
    try:
        validate_entry(2, 3, 2, bad)
        raise SystemExit("negative control FAILED to detect corruption")
    except AssertionError:
        pass
    print("PASS anti-phantom: all 35 entries validated exactly; corruption detected")

    footer = "\nend BridgeD4\nend KnapsackSOS\n\n"
    footer += "\n".join(f"#print axioms KnapsackSOS.BridgeD4.{nm}" for nm in names)
    footer += "\n"
    with open(args.out, "w") as fh:
        fh.write(HEADER + "\n".join(body) + footer)
    print(f"wrote {args.out} ({len(names)} theorems)")


if __name__ == "__main__":
    main()
