/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node mirrormere/MM_gaussian_positivity_small_lam.
   The TYPE below is the registered statement, missions/mirrormere/lean/Statements/
   MM_gaussian_positivity_small_lam.lean (header sha256 3606a5176a49cbb0), binders and conclusion verbatim; the
   PROOF is the artifact constant `RvMBridge13.gaussian_positivity_small_lam` from E6Bridge13. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   The AxiomGuard imports load the whole island, so a vocabulary constant shadowed by
   the artifact is a duplicate declaration here, not a silent substitution. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import E6Bridge13
import AxiomGuardRvMBridge

namespace RvMBridge13

open WeilExplicit

theorem _root_.MissionJudge.MM_gaussian_positivity_small_lam :
    ∀ (c lam : ℝ) (hlam : 0 < lam)
    (hle : lam ≤ RvMBridge11.lam₀), 0 ≤ (RvMBridge6.zeroSide (RvMBridge6.gaussTest c lam)).re :=
  RvMBridge13.gaussian_positivity_small_lam

end RvMBridge13
