/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node mirrormere/MM_rh_iff_gaussian_positivity.
   The TYPE below is the registered statement, missions/mirrormere/lean/Statements/
   MM_rh_iff_gaussian_positivity.lean (header sha256 2f27f0e075533583), binders and conclusion verbatim; the
   PROOF is the artifact constant `RvMBridge10.rh_iff_gaussian_positivity` from E6Bridge10. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   The AxiomGuard imports load the whole island, so a vocabulary constant shadowed by
   the artifact is a duplicate declaration here, not a silent substitution. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import E6Bridge10
import AxiomGuardRvMBridge

namespace RvMBridge10

open Zeta23 Complex MeasureTheory Filter Topology
open scoped ComplexConjugate
open WeilExplicit RvMBridge6 RvMBridge8 RvMBridgeGauss

theorem _root_.MissionJudge.MM_rh_iff_gaussian_positivity :
    RiemannHypothesis ↔ GaussianPositivity :=
  RvMBridge10.rh_iff_gaussian_positivity

end RvMBridge10
