/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node mirrormere/MM_theta_heat_monotone.
   The TYPE below is the registered statement, missions/mirrormere/lean/Statements/
   MM_theta_heat_monotone.lean (header sha256 7d0ffca212d584fb), binders and conclusion verbatim; the
   PROOF is the artifact constant `RvMBridge17.theta_pos_mono` from E6Bridge17. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   The AxiomGuard imports load the whole island, so a vocabulary constant shadowed by
   the artifact is a duplicate declaration here, not a silent substitution. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import E6Bridge17
import AxiomGuardRvMBridge

namespace RvMBridge17

open Zeta23 Complex MeasureTheory Filter Topology
open scoped ComplexConjugate
open WeilExplicit RvMBridge6 RvMBridge7 RvMBridge12 RvMBridge14 RvMBridgeGauss

theorem _root_.MissionJudge.MM_theta_heat_monotone :
    ∀ {lam' lam : ℝ} (h0 : 0 < lam') (hlt : lam' < lam)
    (hpos : ∀ c : ℝ, 0 ≤ Theta c lam) (c : ℝ), 0 ≤ Theta c lam' :=
  RvMBridge17.theta_pos_mono

end RvMBridge17
