/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node rh/RH_bl_closed_form_five_nonneg.
   The TYPE below is the registered statement, missions/rh/lean/Statements/
   RH_bl_closed_form_five_nonneg.lean (header sha256 dc811b3b33a5d61d), binders and conclusion verbatim; the
   PROOF is the artifact constant `RvMBridge28.archSide_add_finiteSide_five_re_nonneg` from E6Bridge28. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   The AxiomGuard imports load the whole island, so a vocabulary constant shadowed by
   the artifact is a duplicate declaration here, not a silent substitution. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import E6Bridge28
import AxiomGuardRvMBridge

namespace RvMBridge28

open Zeta23 Complex MeasureTheory Filter Topology Set
open scoped ComplexConjugate
open RvMBridge15 RvMBridge15.BombieriLagarias

theorem _root_.MissionJudge.RH_bl_closed_form_five_nonneg :
    0 ≤ (archSide 5 + finiteSide 5).re :=
  RvMBridge28.archSide_add_finiteSide_five_re_nonneg

end RvMBridge28
