-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_bl_finite_multiset
-- AUTHORED statement (NOT a verbatim island extract): the Bombieri-Lagarias
-- positivity criterion restricted to FINITE symmetric configurations — the
-- algebraic core of the B7 bridge (J. Number Theory 77 (1999) 274-287, Thm 1
-- specialized to finite multisets, where the convergence condition is vacuous).
-- Deliberately zeta-free: the statement quantifies over abstract finite sets.
-- Flagged for the blind read-back audit cycle.
import Mathlib

theorem bl_finite_multiset (S : Finset ℂ)
    (h0 : (0 : ℂ) ∉ S) (h1 : (1 : ℂ) ∉ S)
    (hsym : ∀ ρ ∈ S, 1 - (starRingEnd ℂ) ρ ∈ S) :
    (∀ n : ℕ, 0 < n →
        0 ≤ (∑ ρ ∈ S, (1 - ((1 - 1 / ρ)⁻¹) ^ n)).re)
      ↔ ∀ ρ ∈ S, ρ.re = 1 / 2 := by sorry
