-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_dbn_rh_iff_H0_real_zeros; sha256 b89ad0154569e665
import Statements.RHDefs

theorem dbn_rh_iff_H0_real_zeros :
    (∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.re → ρ.re < 1 → ρ.re = 1 / 2)
      ↔ ∀ z : ℂ, DBN.H 0 z = 0 → z.im = 0 := by sorry
