-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_dbn_selberg_newman_sharp; sha256 af3c642290803e0f
import Statements.RHDefs

theorem selberg_newman_sharp (S : DBNSelberg.SelbergSharp) :
    ∀ t : ℝ, t < 0 → ∃ z : ℂ, S.sharpFlow t z = 0 ∧ z.im ≠ 0 := by sorry
