-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_li_zero_sums_converge; sha256 ba44ae3b58386720
import Mathlib
import Statements.RHDefs
open Filter Topology BombieriLagarias RvMBridge15

theorem liZeroSum_tendsto (n : ℕ) : Tendsto (liZeroSum n) atTop (𝓝 (liLimit n)) := by sorry
