-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_li_ladder_height; sha256 f0c5b46cd97556e9
import Mathlib
import Statements.RHDefs
open LiCriterion
open scoped Real

theorem li_rung_of_zeros_on_line_below (T : ℝ) (hT : 1 ≤ T)
    (hline : ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.re → ρ.re < 1 → |ρ.im| ≤ T → ρ.re = 1 / 2)
    (n : ℕ) (hn : (n + 1 : ℝ) ≤ 3 * π * T / 2) :
    0 ≤ (taylorCoeff riemannXi n).re := by sorry
