-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_li_rungs_lt_five; sha256 6743e10ff3813519
import Mathlib
import Statements.RHDefs
open LiCriterion

theorem li_rungs_lt_five : ∀ n : ℕ, n < 5 → 0 ≤ (taylorCoeff riemannXi n).re := by sorry
