-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_xi_logDeriv_deriv_decay; sha256 033eae1add2a3b0b
import Mathlib
import Statements.RHDefs

theorem xi_logDeriv_deriv_decay : RvMBridge18.XiLogDerivDerivDecay := by sorry
