-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_xi_derivative_partial_fraction; sha256 32e6c25d5afaf72f
import Mathlib
import Statements.RHDefs

theorem xi_logDeriv_deriv_eq : RvMBridge18.XiLogDerivDerivEq := by sorry
