"""UNTRUSTED emitter (lane H11K): the zero-free slab above the top edge, H11K_Slab_U11004.lean."""
import sys, pickle, os
sys.path.insert(0, '/Users/peterwmurphy/arda-h11k/telperion/examples/zeta_reflection')
import Arb4_emit_seg as ES
from fractions import Fraction as Fr
ISL = '/Users/peterwmurphy/arda-h11k/telperion/examples/zeta_reflection/lean'
T1 = Fr(11004); cap = Fr(3, 1000)
sd = pickle.load(open('slab_U11004.pkl', 'rb'))
sd['alean'], sd['blean'] = ES.upper_forms(T1, cap)
sd['lo_q'], sd['lo_cv'] = ES.qc(T1)
sd['hi_q'], sd['hi_cv'] = ES.qc_add(T1, cap)
mod, path = ES.emit_slabs_file(11004, 0, [sd], '.', 'H11K.Slab')
src = open(path).read()
os.remove(path)
src = src.replace('Arb4_H11004Slabs_0.lean -- lane Arb4: COMPACT kernel certificates of 1 zero-free edge-clearance slabs',
                  'H11K_Slab_U11004.lean -- lane H11K: the zero-free edge-clearance slab above the top edge T = 11004')
src = src.replace('(GENERATED by ../Arb4_emit_seg.py; do not edit).',
                  '(GENERATED by scratchpad h11k/emit_slab.py via Arb4_emit_seg.emit_slabs_file, UNTRUSTED; re-checked here).')
assert 'Arb4_H11004' not in src
open(os.path.join(ISL, 'H11K_Slab_U11004.lean'), 'w').write(src)
print(src[:1500]); print('...'); print(src[-900:])
