/-  Probes/BandGlue_Capstone_h280000.lean -- PROBE: brick K0 (+ K1) against the FULL h280000
    capstone `AllZeros_h280000_Indexed.all_nontrivial_zeros_up_to_height_280000`.

    NOT a lean_lib.  The capstone lives in the zeta_zero_localization monolith (10,379 band modules,
    280 segment modules), which this island cannot build.  Elaborated with plain `lean` against the
    monolith build (`arda-million` `.lake`, plus the olean of `AllZeros_h280000_Indexed` elaborated
    from this worktree's source, sha256 prefix 4934eebd8c5132b8), with `BandGlue`, `EdgeClearGlue`,
    `BandGlue_h1000` and `Probes.BandGlue_h280000` elaborated against that same build.

    WHAT IT PROVES.
      * `all_nontrivial_zeros_up_to_height_280000_of_band_certs`: the capstone conclusion with
        `hbands` REPLACED by one band certificate per box (`BandGlue.BoxCert`: a Turing band covering
        the box, its band statement, and its per-band Arb inputs `hLine`/`hArbT`).  So the 10,379
        box claims are no longer assumed: they are composed, in the kernel, from band certificates.
        A future evaluator fills `hcert` (with the emitted `rh_in_box_*` theorems via
        `BoxCert.of_stmt`, or with its own band parameters via `BoxCert.of_valid`), and K1 lets it
        supply the reduced inputs (`BoxCert.of_reduced`).
      * `segBandHyp_0_of_inputs`, `segBandHyp_279_of_inputs` (+ `_of_reduced`): the capstone's
        bottom segment `[1, 1000]` (25 bands) and top segment `[279000, 280000]` (40 bands) from the
        per-band inputs of their REAL `rh_in_box_*` theorems (the fixed-table form, generated by
        `emit_band_glue.py`); `seg0_certs`, `seg279_certs` feed the certificate form.
      * `all_nontrivial_zeros_up_to_height_280000_of_ends`: the capstone with those two segments
        discharged into per-band inputs, the other 278 segments' box claims still assumed.

    What is still ASSUMED everywhere: the per-band inputs (the Arb trust boundary) and the height
    floor `hγ`.  Nothing here evaluates zeta.  Axioms [propext, Classical.choice, Quot.sound];
    no `sorry`.  conjecture1_proved = False: a finite verification to a finite height, conditional
    on the inputs above; says nothing about zeros above height 280000.
-/
import AllZeros_h280000_Indexed
import BandGlue
import BandGlue_h1000
import Probes.BandGlue_h280000

open Complex

namespace BandGlue_Capstone_h280000

open AllZeros_h280000_Indexed

/-- **K0 against the full h280000 capstone (certificate form).**  Every zero of ζ with
    `0 < Im ρ ≤ 280000` is on the line, given one band certificate per box of every segment and
    the height floor.  The 280 `SegBandHyp` binders of the capstone are no longer assumed. -/
theorem all_nontrivial_zeros_up_to_height_280000_of_band_certs
    (hcert : ∀ k, k < 280 → ∀ i, i < segCount k →
      BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (segLo k i) (segHi k i))
    (hγ : ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 280000 → 55 / 16 ≤ |ρ.im|) :
    ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 280000 → ρ.re = 1 / 2 :=
  all_nontrivial_zeros_up_to_height_280000 (BandGlue.ladder_of_certs hcert) hγ

/-- The capstone's segment 0 from the per-band inputs of its 25 real band theorems. -/
theorem segBandHyp_0_of_inputs (hin : ∀ i, i < 25 → (BandGlue_h1000.seg i).Inputs) :
    SegBandHyp 0 :=
  BandGlue_h1000.bandHyp_of_inputs hin

/-- The capstone's segment 0 from the K1-reduced per-band inputs. -/
theorem segBandHyp_0_of_reduced
    (hin : ∀ i, i < 25 →
      (BandGlue_h1000.seg i).ReducedInputs (BandGlue_h1000.capLo i) (BandGlue_h1000.capHi i)) :
    SegBandHyp 0 :=
  BandGlue_h1000.bandHyp_of_reduced hin

/-- The capstone's top segment 279 (`[279000, 280000]`) from the per-band inputs of its 40 real
    band theorems. -/
theorem segBandHyp_279_of_inputs (hin : ∀ i, i < 40 → (BandGlue_h280000.seg i).Inputs) :
    SegBandHyp 279 :=
  BandGlue_h280000.bandHyp_of_inputs hin

/-- The capstone's top segment 279 from the K1-reduced per-band inputs. -/
theorem segBandHyp_279_of_reduced
    (hin : ∀ i, i < 40 →
      (BandGlue_h280000.seg i).ReducedInputs (BandGlue_h280000.capLo i) (BandGlue_h280000.capHi i)) :
    SegBandHyp 279 :=
  BandGlue_h280000.bandHyp_of_reduced hin

/-- Segment 0's box certificates, at the capstone's own box edges (they plug into `hcert`). -/
theorem seg0_certs (hin : ∀ i, i < 25 → (BandGlue_h1000.seg i).Inputs) :
    ∀ i, i < segCount 0 →
      BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (segLo 0 i) (segHi 0 i) :=
  fun i hi => BandGlue_h1000.boxCert_of_inputs i hi (hin i hi)

/-- Segment 279's box certificates, at the capstone's own box edges. -/
theorem seg279_certs (hin : ∀ i, i < 40 → (BandGlue_h280000.seg i).Inputs) :
    ∀ i, i < segCount 279 →
      BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (segLo 279 i) (segHi 279 i) :=
  fun i hi => BandGlue_h280000.boxCert_of_inputs i hi (hin i hi)

/-- The capstone with its bottom and top segments discharged into the per-band inputs of their
    real band theorems; the box claims of the 278 segments in between are still assumed. -/
theorem all_nontrivial_zeros_up_to_height_280000_of_ends
    (hin0 : ∀ i, i < 25 → (BandGlue_h1000.seg i).Inputs)
    (hin279 : ∀ i, i < 40 → (BandGlue_h280000.seg i).Inputs)
    (hmid : ∀ k, 0 < k → k < 279 → SegBandHyp k)
    (hγ : ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 280000 → 55 / 16 ≤ |ρ.im|) :
    ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 280000 → ρ.re = 1 / 2 := by
  refine all_nontrivial_zeros_up_to_height_280000 (fun k hk => ?_) hγ
  rcases Nat.eq_zero_or_pos k with rfl | hpos
  · exact segBandHyp_0_of_inputs hin0
  · rcases Nat.lt_or_ge k 279 with hlt | hge
    · exact hmid k hpos hlt
    · obtain rfl : k = 279 := by omega
      exact segBandHyp_279_of_inputs hin279

end BandGlue_Capstone_h280000

#print axioms BandGlue_Capstone_h280000.all_nontrivial_zeros_up_to_height_280000_of_band_certs
#print axioms BandGlue_Capstone_h280000.segBandHyp_0_of_inputs
#print axioms BandGlue_Capstone_h280000.segBandHyp_0_of_reduced
#print axioms BandGlue_Capstone_h280000.segBandHyp_279_of_inputs
#print axioms BandGlue_Capstone_h280000.segBandHyp_279_of_reduced
#print axioms BandGlue_Capstone_h280000.seg0_certs
#print axioms BandGlue_Capstone_h280000.seg279_certs
#print axioms BandGlue_Capstone_h280000.all_nontrivial_zeros_up_to_height_280000_of_ends
#print axioms BandGlue_h280000.seg_stmt
#print axioms BandGlue_h280000.seg_geom
