"""Single honest status map for the 1984 Brualdi-Goldwasser problem (Conjecture 1: the maximizer of the
Laplacian ratio pi(T) over large n-vertex trees is a de-loaded cherry-bundle star).

This aggregates, in one place, exactly what is PROVEN, what is a CERTIFIED CANDIDATE, and what remains
OPEN for Conjecture 1 -- and calls the underlying certificates so the status is checkable, not asserted.

THE REDUCTION.  For a large-n maximizer, Conjecture 1 follows from:
  (R1) rate: a branching cherry-bundle star has growth rate rho_B and beats every spider for large n.
  (R2) legs are cherries: non-cherry legs are rate-suboptimal.
  (R3) branches are cherry-ARMS: no rooted branch beats the five-cherry arm  <=>  Phi<=1.
  (R4) backbone is a star at fixed center count.
  (R5) a SINGLE hub (not two, not m): the constant-order tiebreak.
  (R6) cherry distribution: arms balanced at 5, hub de-loaded.
  (R7) global assembly: every tree is dominated by a cherry-bundle star (R1-R6 combine, with the
       exotic competitors -- multi-hub backbones, non-cherry-arm-branch trees, spiders -- each ruled out).

STATUS OF EACH PIECE (checked below):
  (R1) PROVEN  -- thm:growth (spiders.py, N0=412; rate gap rho_S<rho_B).
  (R2) PROVEN  -- prop:cherries (legs.py: rho_ell<rho_B for ell != 2, exact).
  (R3) CERTIFIED CANDIDATE -- Phi<=1 (gap_interval_certification.py: ALL_INTERVAL_CERTIFIED; the exact
       binding corner 132 rho^2+4 rho^3<=207; theorem pending independent lemma-statement review).
  (R4) PROVEN  -- thm:kelmans (psi_close.py: exact bilinear identity + nonnegative corner certificates +
       STRICTNESS closed for all N via certify_corners_strict: each corner numerator = (pos)*u + nonneg,
       so Phi>0 for da>1).  [This SUBSUMES the "Psi-ratio bound for all N"; NOT a separate open gap.]
  (R5) PROVEN (constant order) -- rem_tie.py: surface constant C_m=Psi_m/rho_B^m -> C_1^m with
       C_1=(26/23)/rho_B<1 the exact rational (26/23)^11<621/64, so the single hub strictly wins.
  (R6) PROVEN  -- arm balancing (distribution.py, Polya), hub de-loading (hub.py/arm_bound.py, transfer
       monotonicity), arm level = 5 (rate + transfer).
  (R7) OPEN    -- the global structural reduction.  Empirically the exotic local maxima are exactly
       multi-hub backbones (ruled out by R5) and non-cherry-arm trees (ruled out by R3); hill-climbing from
       random starts always tops out at a single-hub cherry-bundle star (maximizer_structure.py confirms the
       exact shape and hub de-loading 5->0 up to n=240).  But assembling R1-R6 into a rigorous "every tree
       is dominated" theorem -- in particular making the branch-replacement of R3 globally well-defined and
       non-decreasing -- is not done, and depends on R3 (Phi<=1) being promoted to a theorem.

CONCLUSION: Conjecture 1 -- the 1984 problem -- is NOT proved.  The residual is exactly (R3) as a theorem
(a lemma-statement review away) plus (R7) the global assembly.  Everything else (R1,R2,R4,R5,R6) is proven.

Requires the sibling modules; heavy certificates are optional (guarded).
"""
from __future__ import annotations

from fractions import Fraction as Fr


def status(run_heavy=False):
    from verification import rem_tie, maximizer_structure
    from verification import psi_close

    rt = rem_tie.certify()
    R5 = rt["rem_tie_resolved_constant_order"]
    kel = psi_close.verify_identity_and_bounds()
    corners = psi_close.certify_corners_nonneg()
    corners_strict = psi_close.certify_corners_strict()
    R4 = kel["identity_exact"] and kel["pi_increasing"] and all(
        c["num_nonneg"] and c["den_positive"] for c in corners.values())
    R4_strict = corners_strict["all_corners_strict_all_N"]     # Kelmans strictness closed for ALL N
    ms = maximizer_structure.certify()
    shape_ok = ms["matches_conjecture1_shape"]

    R3 = None
    if run_heavy:
        from verification import gap_interval_certification as gic
        R3 = gic.certify(nc=400, smax=64, jmax=200)["ALL_INTERVAL_CERTIFIED"]

    return {
        "R1_rate_branching_beats_spiders": "PROVEN (thm:growth, N0=412)",
        "R2_legs_are_cherries": "PROVEN (prop:cherries)",
        "R3_branches_are_cherry_arms_Phi_le_1": ("CERTIFIED CANDIDATE -- E0/E1/E2/E3/DEC now theorems; "
                                                 "adversary sweep reduced by Jensen lemma to a finite interval "
                                                 "certificate. HONEST SCOPE: the s-tail / far-cavity regimes "
                                                 "have no open math idea, but the BRANCHING TAIL (the uniform "
                                                 "per-node/valid-potential existence) is genuinely OPEN, and the "
                                                 "finite s<=64 SweepBound core is verified for only 1302 of the "
                                                 "~340k cells (the uniform monotonicity lemma replacing the "
                                                 "infeasible literal grid is unwritten). NOT a closed proof"
                                                 + ("" if R3 is None else f" (interval-recheck={R3})")),
        "R4_backbone_is_star_all_N": ("PROVEN (thm:kelmans; strictness closed for all N)" if (R4 and R4_strict)
                                      else "CHECK FAILED"),
        "R4_kelmans_strictness_all_N": R4_strict,   # corner numerator = (pos)*u + nonneg => Phi>0 for da>1
        "R4_subsumes_Psi_ratio_bound": True,      # the "Psi-ratio bound for all N" is not a separate gap
        "R5_single_hub_tiebreak": ("PROVEN constant-order (rem:tie)" if R5 else "CHECK FAILED"),
        "R5_exact_crux": "(26/23)^11 < 621/64  <=>  C_1<1",
        "R5_crux_holds": Fr(26, 23) ** 11 < Fr(621, 64),
        "R6_cherry_distribution": "PROVEN (arm-balancing, hub de-loading, arm level 5)",
        "R3_near_star_family_lean": ("PROVEN in Lean (TieHarmonic.lean + NearStar.lean, CI-green): "
                                     "logPhi(N(c,k)) = gVal(c+k) <= 0 for ALL c,k (split-invariant, tie on "
                                     "c+k=5) -- the near-tie envelope family, a proven INSTANCE of the "
                                     "tree-induction conclusion logPhi B<=0, NOT the general-children crux"),
        "R3_bridge_lean": ("SUBSTANTIALLY DONE in Lean (RECONCILED 2026-08-22 vs main; this entry previously "
                           "predated BridgeStep4i/4j and R47Tree and OVERSTATED the bridge as open -- see "
                           "BRIDGE_AUDIT_20260822.md). The Branch->RTree->matching-sum->per(L) glue: STEP 1 "
                           "cav=z(d,c)*rho0 (cavity structure); STEP 2 cherry-folding q_realize_eq_rho0; STEP 3 "
                           "Ztot_eq_msum (RTree.Ztot = explicit weighted matching sum; validated 200/200); STEP 4 "
                           "hub_rho0_limit (cherry-hub decoupling Tendsto). The STEP-4 capstones are now "
                           "UNCONDITIONAL (BridgeStep4j discharges the last acyclicity hypothesis via "
                           "aGraph_realize_isAcyclic): pi_litHub' (per L / prod deg = Ztot, single hub) and "
                           "amplitude_bridge_real' (the REAL-Laplacian hub amplitude ratio -> exp(logPhi b)*"
                           "rhoB^(Vb b), a completed Tendsto). GENERALIZED to ALL rooted trees by R47Tree.pi_utree "
                           "(per L(T)/prod deg = Aobj t = Ztot(dtRealize t) for EVERY UTree -- the permanent-to-"
                           "rational-recursion identity, not litHub-only). The 'uniform O(1/p^2) error constant' "
                           "the old text called the hardest gap is a PHANTOM: BridgeStep4b/4d/4j state explicitly "
                           "no O(1/p^2) (or O(1/p)) envelope is needed -- the bridge is a LIMIT, Tendsto algebra "
                           "on exact rational closed forms suffices. RESIDUAL (re-pointed): the bridge no longer "
                           "gates the proof; what remains to a FORMAL Conjecture 1 is (a) R7/G7 assembly composing "
                           "Aobj-maximization down to the hub-amplitude form where amplitude_bridge_logPhi + "
                           "phi_le_one bite, and (b) root-invariance (R47Tree Aobj is on ROOTED trees; unrooted "
                           "objective deferred to P2) -- both are the R7_global_reduction / G7 item below, NOT a "
                           "bridge-limit gap. Nice-to-have missing brick: the one-line le_of_tendsto corollary "
                           "exp(logPhi b)*rhoB^(Vb b) <= rhoB^(Vb b) (amplitude_bridge_logPhi + phi_le_one) is "
                           "not yet stated. And the bridge assumes phi_le_one, so Gap 1 (R3 master inequality) is "
                           "untouched by any of this"),
        "R3_chain_margin_lean": ("PROVEN in Lean (ChainMargin.lean, CI-green): the pure-depth c=0 chain "
                                 "logPhi(chainB n) <= 0 for ALL n, UNCONDITIONALLY -- the first fully-proven "
                                 "far-regime margin. Via seventeen_14_lt_rhoB (17/14<rhoB) + rhoB_sq_ge "
                                 "(3/2<=rhoB^2): base -2Lval+log(3/2)<=0, per-node depth increment <=0 once "
                                 "cav<=3/7 (chain cavities invariant in [1/3,3/7]). Depth tail closed"),
        "R3_locality_lean": ("PROVEN in Lean (Locality.lean, CI-green): cavity-locality -- eroot_congr, "
                             "logPhi_child_replace (equal-cavity child swap shifts logPhi by exactly the child "
                             "amplitude change), logPhi_child_mono. The rearrangement primitive for the "
                             "depth-collapse; reduces depth-collapse to Psi<=0 (the circular crux)"),
        "R3_bush_bound_lean": ("PARTIAL in Lean (BushBound.lean, CI-green): the branching-tail maximiser is "
                               "the depth-2 cherry-bush (root c cherries + k c'-cherry leaves). Proved: "
                               "logPhi_cherryLeaf (c'-leaf = gVal c', the global-maximiser family), "
                               "cherryBush_logPhi_eq (logPhi = k*gVal c' + eroot), cherryBush_nonpos_of "
                               "(bush<=0 GIVEN the per-node condition eroot<=-(k*gVal c') -- isolates the "
                               "branching crux), cherryBush_zero (k=0 = bare c-leaf, unconditionally <=0). "
                               "The uniform per-node condition (all c,k,c') is the OPEN branching tail"),
        "R7_global_reduction": "SUPERSEDED 2026-08-14 by the R7' architecture (formalization/"
                               "R7_ARCHITECTURE.md, MR !69, verify_20260814.py all-GREEN): stages I-IV with "
                               "exact anchors A1 (pi = Z*R, R<=4/3, on the CI-green Lean phi_le_one + bridge), "
                               "A2 (star value C_1 exact), A3 (ledger identity). STAGE I unconditional "
                               "(amortized hub bound); STAGE II CLOSED (unified topped-up merge 36/36, G34 "
                               "residual/multi/deep discharged, interpolation lemma exact); STAGE III/IV "
                               "discharged via G5/G6 (de-loading schedule, n0=421) + R5/R6. Named residuals: "
                               "G1 (symbolic hardening of interval-float floors), G7 (Lean formalization = "
                               "the R47 campaign), independent review. R3 is now a machine-checked theorem "
                               "in the Branch model (phi_le_one + the per(L) bridge, reviewed PASS).",
        "large_n_shape_confirmed": shape_ok,      # single-hub star, hub de-loads 5->0, to n=240
        "conjecture1_proved": False,
        "residual": "The ENTIRE 1984 problem reduces to ONE item: Phi<=1 (R3) as a fully formal theorem. "
                    "PYTHON: E0/E1/E2/E3/DEC are theorems (E2 closed in the Pell register, e2_closure.py); the "
                    "adversary sweep is Jensen-reduced to a finite interval certificate (adversary_sweep.py / "
                    "gap_interval_certification.py, ALL_INTERVAL_CERTIFIED) -- no open idea for the FAR/TAIL "
                    "regimes, but the BRANCHING TAIL (uniform per-node condition / valid-potential existence, "
                    "Reach.ValidPotential) is genuinely OPEN and this is an exact/interval NUMERIC certificate, "
                    "not yet a proof-assistant term. "
                    "LEAN (R3Cert, machine-checked, no sorry): the exact-arithmetic cruxes (ExactCruxes.lean), "
                    "the s-tail and D2 j-tail (Sweep.lean/JTail.lean, threshold j>=96), the DEC real-log "
                    "identity (DEC.lean), and the matching/permanent identities -- H1 (per L(T) = matching "
                    "sum, Matching.permanent_eq_matching_sum, on the REAL SimpleGraph Laplacian), H2a (pi = "
                    "weighted matching sum, pi_eq_weighted_matching_sum), the H2b cavity-recursion NODE STEP "
                    "(cavity_recursion), AND the H2b TREE-INDUCTION WRAPPER (CavityTree.lean: inductive RTree + "
                    "division-free matching partition functions Zopen/Ztot + tree_cavity_recursion, the "
                    "end-to-end node identity by structural induction) -- resting on the involution crux "
                    "(Involution.lean) + permanent reindexing + per-term degree evaluation. IMPORTANT SCOPE "
                    "(the bridge is NOT end-to-end): these live in THREE disjoint type-universes -- SimpleGraph "
                    "V (H1/H2a, real permanent), RTree (H2b, Zopen/Ztot), and Branch (Reach.lean, where the "
                    "capstone's logPhi/cav/eroot actually live). There is currently NO machine-checked theorem "
                    "connecting RTree.Ztot to the SimpleGraph matching sum, NOR Branch.logPhi to either -- "
                    "Branch.logPhi is a standalone recursive DEFINITION, so nothing verified yet ties the "
                    "capstone bound logPhi B<=0 back to per(L(T))/prod deg. Those realization bridges "
                    "(Branch -> RTree -> SimpleGraph) are the remaining structural glue -- IN PROGRESS: STEP 1 "
                    "(Bridge.lean, CI-green) cav = z(d,c)*rho0, rho0 = 1/(1+z*S) the DEC cavity structure; "
                    "STEP 2 (BridgeStep2.lean, CI-green) the CHERRY-FOLDING -- realize a Branch as a DEC-dressed "
                    "RTree (cherries folded into z(d,c)=3/(3d+c), edge weight z(d,c)*z(d_child,c_child)) and "
                    "PROVED q_realize_eq_rho0: Zopen(realize b)/Ztot(realize b) = rho0 b (via "
                    "CavityTree.tree_cavity_recursion), so Branch.rho0/cav IS a DEC-weighted matching cavity "
                    "connecting the Branch capstone to the RTree matching partition functions. STEP 3 "
                    "(RTree.Ztot = weighted matching sum) DONE (BridgeStep3.lean, CI-green): Ztot_eq_msum: Ztot t = "
                    "msum(realize t), realizing the RTree as an address-vertex edge list and proving Ztot "
                    "equals the explicit include/exclude matching sum via a mutual induction (msum_pull + "
                    "root-edge conditioning). STEP 4 CORE DONE (BridgeStep4.lean, CI-green): hub_rho0_limit -- the "
                    "cherry-hub decoupling limit rho0(hub_p) -> 1/(1+cav arm) as p->inf INDEPENDENT of "
                    "branches (real Mathlib Tendsto limit; the mechanism defining Phi as the p->inf hub "
                    "limit). Full Step 4 (logPhi<=0 -> per(L(T)) via amplitude ratio + uniform O(1/p^2)) "
                    "remains OPEN -- last + hardest bridge gap. "
                    "The Jensen reduction is a THEOREM "
                    "(node_jensen_reduction, Jensen.lean: multi-child DEC node <= all-equal node at the mean "
                    "cavity, via a machine-checked Jensen inequality), and the per-node CAPSTONE is now a REAL "
                    "conditional theorem (Structure.node_le_omega / node_amp_neg: GIVEN a concave menu hull H, "
                    "child-envelope ell_i<=H(mu_i), and the sweep bound Qeq<=omega, the actual amplitude bound "
                    "nodeAmp<=omega<0 -- replacing the former hollow phi_le_one_step whose hypotheses were "
                    "false-as-written/vacuous and whose conclusion used none of them). Correctly-typed leaves. "
                    "SweepBound's s-TAIL is now PROVED in Lean (Structure.Qeq_stail: for s>=65, m in [0,1], "
                    "H m<=0, Qeq s j H m<=omega, via the j-uniform node_head_le + coupling_le (coupling<=3/2 on "
                    "m<=1) + s_tail_ge_65), and Structure.sweepBound_of_core REDUCES SweepBound to the finite "
                    "s<=64 core (given H<=0 on [0,1]). For that core, the interval-cell reduction has its "
                    "monotonicity lemma in Lean (Structure.coupling_mono). The CONCRETE menu hull H is now "
                    "DEFINED in Lean (Structure.menuHull bL bR = Hull.hullOf [tent segs through the tie (3/23,0)] "
                    "(0,0)) with its keystone properties PROVED: menuHull_concave (the Jensen premise, free from "
                    "hullOf_concave), menuHull_nonpos (<=0 via the zero-line seed + Hull.hullOf_le_seed), "
                    "menuHull_tie (=0 at mu=3/23); and WIRED to the capstone (menuHull_Qeq_stail, "
                    "menuHull_sweepBound_of_core reducing the sweep to the s<=64 core, menuHull_node_le_omega). "
                    "The finite-core CELL REDUCTION is now a Lean lemma: Structure.menuHull_cell_le (with "
                    "Hull.hullOf_le_of_mem + menuHull_le_left/right for the per-cell hull upper bound) reduces "
                    "each (s,j) x m-cell to a single RATIONAL inequality gub - j*L + j*hub + cub <= L via "
                    "node_interval_le + coupling_mono -- the finite-core analogue of node_ns_le. The certified "
                    "data pipeline is now PROVED end-to-end: Structure.gVal_le_lin_rat supplies the rational "
                    "gub uniformly (gVal n <= -77n/10000 + 238/1000), and a WORKED cell is machine-checked "
                    "(example: Qeq 0 2 (menuHull 5 (-1)) 0 <= omega via menuHull_cell_le on concrete rationals, "
                    "the finite-core analogue of Sweep.node_4_2_2). The cell reduction is now ALSO available "
                    "HULL-AGNOSTIC (Structure.Qeq_cell_le: identical to menuHull_cell_le but generic in H), so "
                    "the same finite-core machinery applies to ANY concave menu upper bound; a mid-cavity cell "
                    "on the DOMINATING hull is machine-checked (example: Qeq 0 2 menuHullRat (3/19) <= omega, "
                    "with the hub supplied by menuHullRat's sp=4 tangent through Hull.hullOf_le_of_mem). "
                    "A RATIONAL CONSERVATIVE HULL is now defined "
                    "and its DOMINATION of the near-star menu is PROVED: Structure.menuHullRat (3 exact-Fraction "
                    "tangent segments through the proven amplitude bounds gVal0_le..gVal4_le+gVal_nonpos, "
                    "concave+<=0) with menuHullRat_dominates_nearstar (gVal sp <= menuHullRat(3/(4sp+3)) for ALL "
                    "sp: sp>=5 via a clean left-of-tie lemma + gVal_nonpos, sp=0..4 by norm_num on the certified "
                    "rationals). The exported certified hull has 40 segments with IRRATIONAL coefficients (tie "
                    "at 3/23), hence the rational over-approximation. DEEP-LEFT: a uniform rational bound is now "
                    "proved (Structure.gVal_le_Rval: gVal n <= (Rval n - 1)/11, Rval n exact rational; strictly "
                    "negative for sp>=6, e.g. gVal 6<=-1/1000, gVal 8<=-1/200 by norm_num). But a STRUCTURAL "
                    "finding: the deep left CANNOT be tightened by a global rational concave hull -- ghat(sp)= "
                    "(Rval sp-1)/11 saturates at -1/11 while real g(sp)->-inf (cavity->0), so the menu is "
                    "unbounded below near cavity 0 and no concave inf-of-affines can follow it while dominating "
                    "(an accumulation boundary at cavity 0, the analogue of the tie). So the deep-left cells use "
                    "the DIRECT per-child bound. This is now WIRED: Structure.nodeAmp_deepleft_le bounds the RAW "
                    "node (Sum ell_i <= j*hub directly, no Jensen) by the same rational check as node_interval_le, "
                    "and a WORKED deep-left node is machine-checked (nodeAmp 0 2 with two sp=6 children <= omega "
                    "via gVal_le_Rval). So BOTH finite-core regimes are wired end-to-end on concrete data: "
                    "mid-cavity via menuHull_cell_le (Jensen hull), deep-left via nodeAmp_deepleft_le (direct "
                    "per-child). The E2 CHAIN (cavity in (2/5,1/2), amp<=-7/100) and E3 SHOULDER (cavity in "
                    "(1/4,1/3), amp<=-9/100) regions are ALSO covered by the same nodeAmp_deepleft_le -- worked "
                    "chain and shoulder nodes are machine-checked (amplitude bounds supplied as the E2/E3 "
                    "certificates, as Sweep.node_chain_0_2). So EVERY finite-core cavity band now has a "
                    "machine-checked node bound on concrete data: mid via the Jensen hull, deep-left/chain/"
                    "shoulder via the direct per-child bound. GRID INSTANTIATION now begun in Lean: the point "
                    "lemma Qeq_cell_le cannot tile the mean-cavity CONTINUUM, so added Structure.Qeq_interval_le "
                    "(for-all m in [ml,mr], one rational check gives Qeq<=omega) resting on Hull."
                    "affineFn_le_max_endpoints + hullOf_le_max_endpoints (a concave hull's sup over a cell is the "
                    "active-tangent endpoint-max, a RATIONAL) and Structure.menuHullRat_le_cell. A GENERATOR "
                    "grid_gen.py emits these interval cells, each SELF-VERIFIED in exact Fraction arithmetic "
                    "before emission; Grid.lean (on menuHullFull + gVal_le_lin_tight) LOOPED ACROSS THE GRID = "
                    "1302 machine-checked cells over 8 columns j in {12,24,36,48,60,72,84,95} (spanning j=12..95) "
                    "EACH at full s-depth s=0..64, per-(s,j) MERGED minimal partition of [3/95,1] (adaptive, fine "
                    "near the tie 3/23), 0 skipped -- the generator looped across BOTH axes at full s-depth, "
                    "closing the tie-adjacent/binding cells via tight gub + fine near-tie subdivision. Wired into "
                    "the R3Cert root. FULL-GRID SCALE (measured, honest): the literal full linear grid is ~14,713 "
                    "merged cells (~47 min compile) -- CI-INFEASIBLE as one job; 55 small-s+j pairs (s<=9,j<=11) "
                    "are the exact-Rval regime (node_ns_le/grid_nodes), NOT gaps. The correct closed form is a "
                    "UNIFORM monotonicity lemma (s-range bound + concave-in-m), not a bigger literal loop. "
                    "MEASURED SCALE (honest): "
                    "the full sweep is ~340k (s<=64 x j<=95 x ~56-seg) cells with a ~1e-4 margin and 966 cells "
                    "that even need the fine stationary treatment -- a literal flat emission is neither CI-feasible "
                    "nor the right formalization. The 3-segment menuHullRat is tight only on the mid/right band; "
                    "the near-tie BINDING cells (worst node (0,36), margin 1e-4) need the EXTENDED many-segment "
                    "rational hull (the certificate uses 56), and the s-axis does not collapse (64 interior "
                    "maxima). HULL NOW EXTENDED (HullFull.lean, generated by hull_gen.py, CI-green): "
                    "menuHullFull = the full upper concave hull of the near-star points sp=0..23 (17 rational "
                    "segments, cavity [3/95,1]) with menuHullFull_concave (free) + menuHullFull_nonpos (free) + "
                    "menuHullFull_dominates_nearstar (gVal sp <= menuHullFull(cavity sp) machine-checked for EVERY "
                    "sp=0..23, via gVal_le_Rval then hullOf_dominates) + menuHullFull_le_cell. sp<=23 is the "
                    "norm_num-provable range (11*24=264>256 exceeds the exponent guard), so the hull spans cavity "
                    ">=3/95; the deeper band (sp>23, cavity<3/95) stays on the direct per-child route -- the "
                    "cavity-0 accumulation obstruction. KEY STRUCTURAL FINDING: the certified 56-segment hull is "
                    "overwhelmingly DEEP-LEFT; the right band [3/23,1] is nearly linear (2-3 segments). The "
                    "extended hull closes the mid/deep grid cells AWAY from the tie, but the tie-adjacent cells "
                    "(incl. the binding (0,36)) are blocked by the g-BOUND not the hull: at the tie menuHullFull~0 "
                    "(it must, to dominate the tie), so the node needs a TIGHT g(s+j). TIGHT G-BOUND NOW ADDED "
                    "(Structure.gVal_le_lin_tight, CI-green): gVal n <= -77n/10000 + 1633/20000 for ALL n. The "
                    "linear FORM gVal n <= n*omega + lambda (gVal_le_linear) is only ~log(1+1/(4n+3)) slack "
                    "(~0.007 at n=36); the earlier ~0.16 looseness of gVal_le_lin_rat was ENTIRELY the rational "
                    "rounding lambda<=238/1000. Tight: lambda = log(4/3)-Lval <= 288/1000 - (405/1000+77/10000)/2 "
                    "= 1633/20000, using Lval=(log(3/2)-omega)/2 >= 4127/20000 (log_three_half_enclosure + "
                    "omega_enclosure). Loose by only ~0.0075 at n=36 (real g(36)=-0.2031, bound -0.1956). VERIFIED "
                    "(Python): this closes the WHOLE binding column j=36 for ALL s=0..64 at N=16 cavity "
                    "subdivision (0 unclosed); the loose bound never closes the tie cell even at N=64. So the "
                    "tie-adjacent/binding cells are now closable (tight gub + fine subdivision). UNIFORM "
                    "MONOTONICITY FOUNDATION now proved (Structure.gVal_antitone, CI-green): gVal (n+1) <= gVal n "
                    "for n>=5 -- the near-star amplitude peaks at the tie n=5 and decreases thereafter. Exact "
                    "difference telescopes to a single log: gVal(n+1)-gVal(n) = omega + log((4n^2+11n+7)/"
                    "(4n^2+11n+6)) <= omega + 1/161 < 0 (via log x<=x-1 + omega<=-77/10000). Uniform in n, no "
                    "enumeration. (Decision: do NOT emit the full 14,713-cell literal grid -- brute-force artifact, "
                    "~44min permanent CI tax, obsoleted by this uniform route.) S-AXIS COLLAPSE for m>=1/3 now "
                    "PROVED (Structure.Qeq_s_antitone + Qeq_s_collapse, CI-green): for cavity m>=1/3 and s+j>=5, "
                    "Qeq is ANTITONE in s -- gVal(s+j) decreases (gVal_antitone) and the coupling "
                    "(4s+3j+3+3jm)/(4(s+j)+3) decreases in s (cross-multiplied s-difference is exactly 4j(1-3m)<=0). "
                    "Qeq_s_collapse iterates it (Nat.le_induction): Qeq s j H m <= Qeq s0 j H m for all s>=s0 with "
                    "s0+j>=5. So the ENTIRE s-tail of the sweep, in the m>=1/3 regime, reduces to the single base s0 "
                    "-- one uniform theorem replacing the literal grid's s-enumeration there (no s-loop). "
                    "CONCAVE-MAX-IN-M for the near-tie now PROVED (Structure.Qeq_affine_cell_le, CI-green): on a "
                    "hull SEGMENT, menuHullFull m <= affineFn ab m is AFFINE in m (hullOf_le_of_mem), the coupling "
                    "is AFFINE in m, and log(coupling)<=coupling-1 (log tangent) -- so the whole Qeq upper bound is "
                    "AFFINE in m, hence its max over a cell is at an ENDPOINT (affineFn_le_max_endpoints). One "
                    "rational check per endpoint closes an ENTIRE near-tie cell -- NO ConcaveOn machinery, NO "
                    "stationary point, NO subdivision. Generic in H. WORKED (HullFull.lean): the wide tie cell "
                    "[3/23,8/23] at the binding (0,36) -- which the subdivided grid needed several cells for -- "
                    "closes in ONE shot via the sp=5 tangent. So the near-tie m<1/3 regime that the s-collapse "
                    "could not reach is now closable cell-by-cell without subdivision (the certificate's 966 fine "
                    "cells become one-endpoint-check-each). E-SERIES AMPLITUDE BOUNDS promoted from certificates: "
                    "E3 shoulder was ALREADY a theorem (e3_reduces_to_crux : 3/2 <= rhoB^2, from e3_crux); E2 now "
                    "PROVED (Structure.E2_binding_negative_holds, CI-green): the E2 binding value T = -4 log(rhoB) "
                    "+ log(3/2)+log(17/14)+log(7/6) < 0 -- the three logs combine to log(17/8) and 4 log rhoB = "
                    "(4/11) log(621/64), so T<0 reduces to the EXACT RATIONAL (17/8)^11 < (621/64)^4 (3989.77 < "
                    "8864.34, norm_num). T = -0.0726 = chainB_max is the E2 chain-amplitude binding value, now a "
                    "machine-checked real-log theorem not a numeric certificate. REACHABLE-CAVITY PREDICATE + "
                    "E0/E1 now PROVED (Reach.lean, CI-green): defined the DEC branch (inductive: c cherries + list "
                    "of children), the cavity recursion mu = 3/(3 + 3*n_ch + 4c + 3S) (S = sum of child cavities, "
                    "mutual cav/cavSum), and proved E0_holds (mu in {1} u (0,1/2); =1 iff bare leaf, t=3) and "
                    "E1_holds (mu not in (1/3,2/5], i.e. no branch has t in [15/2,9)) by STRUCTURAL INDUCTION -- "
                    "E1's chain case (1,0) needs the child cavity in [1/2,1) which E0 forbids on the CHILD (a "
                    "genuine induction, not a depth scan), exactly lemma_proofs.prove_E0/prove_E1. Instantiated "
                    "the abstract E0_cavity_classification / E1_forbidden_band on the concrete Reachable(mu):=exists "
                    "branch with cav=mu. So E0/E1 are no longer abstract Prop-parameters -- the reachable-cavity "
                    "item is CLOSED. TREE-INDUCTION ASSEMBLY now MACHINE-CHECKED as a CONDITIONAL theorem "
                    "(Reach.lean, CI-green): the branch log-amplitude telescopes logPhi(node)=Sum logPhi(child)+ "
                    "eroot (eroot=log a(d,c)+log(1+z*S), z=3/(3d+c), a=(3/2)^c(1+c/3d)/rhoB^(1+2c), d=n_ch+1+c); "
                    "defined ValidPotential P := P>=0 AND the per-vertex ineq eroot <= Sum_children P(cav child) - "
                    "P(cav node); proved (mutual strong induction, no sorry) logPhi_le_of_potential : logPhi B <= "
                    "-P(cav B), hence phi_le_one_of_potential : ValidPotential P => logPhi B <= 0 = Phi<=1 for the "
                    "WHOLE tree. So Phi<=1 reduces EXACTLY to `exists P, ValidPotential P`. The strong-induction "
                    "SKELETON is now complete + machine-checked; the ENTIRE residual is the single open crux = the "
                    "EXISTENCE of a valid potential = the general-children Brualdi-Goldwasser crux, which CANNOT be "
                    "closed trivially (tightest P*=-Psi has P*>=0 iff the conjecture = circular; no smooth/fixed- "
                    "complexity P works [marginal tie]; proven child families don't capture Psi [optimal child "
                    "non-monotone]). This is the genuinely open problem nobody has solved (incl the refuted "
                    "Wu-Dong-Lai). The small s+j exact-Rval one-liners are now DONE too (NodesSmall.lean, "
                    "CI-green): 104 node_ns_le nodes covering the small box s in [0,9], j in [2,4], sp in "
                    "{2,3,4,5} (near-tie hull vertices) beyond grid_nodes' 16-node binding box -- where the linear "
                    "g-bound is loose but the exact Rval bound is norm_num-evaluable (all exponents < 256); each is "
                    "node_ns_le s j sp (by unfold Rval Romval cpl; norm_num), reducing Q<=omega to the exact "
                    "rational Rval(s+j)*Rval(sp)^j*cpl^11 <= Romval^(j+1). So the near-star-child part of the "
                    "finite sweep is fully discharged on concrete data (grid_nodes + NodesSmall + linear Grid + "
                    "tails). REMAINING (the ONLY open item, no reduction idea exists): exists P, ValidPotential P "
                    "= the general-children crux. "
                    "NEAR-STAR FAMILY ARITHMETIC BOUND now a Lean theorem (TieHarmonic.lean + NearStar.lean, "
                    "CI-green). The near-tie asymptotics (near_tie_asymptotics.py) pin the tie to the ARITHMETIC "
                    "statement f(c)<=0 at INTEGER c, f(c) = -(2c+3)L + (c+1)log(3/2) + log(4c+7) - log(3(c+2)) "
                    "(the tie-harmonic family G(c)=(c,[ARM]), root cavity 3/(4c+7), tie c=4 <=> m=3/23; the "
                    "CONTINUOUS relaxation max at c*=3.82 has Phi=1.00004>1, so this is INTEGRALITY not "
                    "smoothness). KEY IDENTITY f(c)=gVal(c+1), so f(c)<=0 IS the already-proven gVal_nonpos(c+1) "
                    "and the tie f(4)=0 IS gVal 5=0 (Rval 5=1 exactly, the integer tie identity) -- fHarm/"
                    "fHarm_eq_gVal/fHarm_nonpos/gVal_five_zero/fHarm_tie. EXTENDED to the FULL near-star family "
                    "N(c,k)=c cherries+k cherry-arms (NearStar.lean): formalized as the CONCRETE Reach.Branch "
                    "gadget nearStarB c k = node c (replicate k armB), armB=node 0 [node 0 []], and PROVED the "
                    "split-invariance/reduction logPhi(N(c,k))=gVal(c+k) (depends ONLY on s=c+k, not the split) "
                    "via the exact cavity telescoping -- eroot's ac*(1+z*S) collapses (the (3k+3+4c) factors in "
                    "ac and (1+z*S) cancel) to c*log(3/2)-(1+2c)L+log(4(c+k)+3)-log(3(c+k+1)), and "
                    "logPhi(armB)=-2L+log(3/2), summed = gVal(c+k). Hence nearStar_nonpos: logPhi(N(c,k))<=0 for "
                    "ALL c,k (from gVal_nonpos), equality exactly on the tie diagonal c+k=5 (all 6 ties, via "
                    "gVal_five_zero). This is a PROVEN INSTANCE of the tree-induction conclusion logPhi B<=0 on a "
                    "real 2-parameter gadget family (the near-tie envelope) -- it does NOT construct a "
                    "ValidPotential for arbitrary children, so `exists P, ValidPotential P` remains the SOLE open "
                    "item and conjecture1_proved stays False. GENERAL-CHILDREN CRUX LOCATED + SHARPENED "
                    "(general_children_crux.py, self-verifying): the crux is the EXACT RATIONAL matching-poly "
                    "inequality (prodF(C)*f(C))^11 <= (621/64)^V(C) for ALL rooted trees (rational_reduction.py; "
                    "f = matching polynomial with activities z_v, prodF = prod F(d_v,c_v), V = sum(1+2c_v)); "
                    "Phi factors per-node Phi = prod_v phi_v with g_v = 1 + z_v sum_i z_i/g_i (matching ratio, "
                    "cav = z/g) -- VERIFIED. NEW FINDING: over ALL 192,888 trees (<=5 nodes, cherries<=7) max "
                    "logPhi = 0 exactly and the EQUALITY variety {logPhi=0} is EXACTLY the near-star tie family "
                    "N(c,k), c+k=5 (all cavity 3/23, V=11: (5,[]),(4,[ARM]),(3,[ARM,ARM]),...) -- i.e. the "
                    "GLOBAL MAXIMISER VARIETY IS the nearStarB gadgets already formalised (Lean nearStar_tie "
                    "proves them =0). So the open crux sharpens to: the near-star tie variety is the global "
                    "maximiser over ALL trees (every other tree strictly < 0). The obstruction is "
                    "arithmetic/integrality and COORDINATE-FREE (Psi pokes above every chord of the cherry-leaf "
                    "points; the continuous relaxation exceeds 0, so no smooth certificate works in any "
                    "coordinate) -- the proof must be the 23-adic Rval<=1 route, exactly as the near-star proof. "
                    "DOMINATION-REDUCTION ATTEMPT (measured): near-star-at-fixed-V domination is REFUTED (for "
                    "V>=21 bushy trees beat the near-star; gVal((V-1)/2) dives to -inf while real trees stay "
                    "near 0 by branching), BUT DEPTH-<=2 BUSH domination HOLDS empirically (the depth-2 bush "
                    "family achieves the per-V max at EVERY V, 0 misses). So Phi<=1 factors into (i) a depth-"
                    "COLLAPSE lemma (every tree <= best depth-2 bush at its V) + (ii) the BUSH BOUND (every "
                    "depth-2 bush <=0). Piece (ii)'s REDUCTION is now formalised (BushBound.lean, CI-green): "
                    "cherryLeafB/cherryBushB gadgets, logPhi_cherryLeaf (c'-leaf = gVal c', the global-"
                    "maximiser family), cherryBush_logPhi_eq (logPhi(bush)=k*gVal c'+eroot), cherryBush_nonpos_of "
                    "(bush<=0 GIVEN the per-node condition eroot<=-(k*gVal c'), isolating the branching crux "
                    "exactly as phi_le_one_of_potential isolates the general one), and the UNCONDITIONAL k=0 "
                    "case cherryBush_zero(_nonpos) (bare c-cherry leaf <=0, contains the tie (5,[])). The "
                    "uniform per-node condition (all c,k,c') and the collapse lemma remain OPEN. "
                    "BUSH-BOUND ARITHMETIC ATTACK (bush_bound_arithmetic_proof.py, self-verifying exact-Fraction): "
                    "genuine NEW rigorous ground on piece (ii), following the near-star template. PROVEN for ALL "
                    "integers c,k>=1,t>=0: (R0) the exact reduction logPhi(B(c,k,t))=c*log(3/2)-(1+2c)L+log(arg)+ "
                    "k*g(t) with g(t)=gVal(t)=near-star value, g<=0 tie only at t=5; (R1) the exact k-increment "
                    "e^{11 Delta_k}=e^{11g(t)}((A(k+1)+B)/(Ak+B))^11((k+1+c)/(k+2+c))^11, A=6(2t+3),B=(4t+3)(4c+3); "
                    "(R2) the EASY-REGION k-MONOTONICITY LEMMA -- whenever 4ct-6c-9>=0 (<=>A(1+c)<=B) the two "
                    "middle factors multiply to <=1 so Delta_k<=g(t)<=0 for EVERY k (logPhi non-increasing in k, "
                    "<=logPhi(B(c,1,t))); (R3) CONFINEMENT -- c>=1,t>=4 => 4ct-6c-9>=1 easy, so the c>=1 residual "
                    "is confined to the finite strip t in {0,1,2,3}. REDUCED but NOT CLOSED: the bush bound "
                    "remains open on three explicit NEAR-TIE boxes -- k=1 slice, c=0 star, c>=1&t<=3 -- each a "
                    "genuine two-parameter near-tie inequality (verified exactly on finite ranges, not all values). "
                    "Every natural single-variable reduction is REFUTED by the non-monotone near-tie structure: "
                    "arg maxes at t=0 where g most-negative (dropping k*g via g<=0 gives K1UP(0)=+0.199>0); t=5 "
                    "does NOT max logPhi over t (ARM B(0,1,0) beats it); crude f(1)-bound drops (k+1+c)/(k+2+c) and "
                    "fails for c>=1. So the residual is the SAME marginal-tie / 23-adic obstruction, now localised "
                    "to small boxes. "
                    "*** BUSH BOUND NOW CLOSED (2026-08-11, MR !67 merged): bush_bound_proved=True. *** The "
                    "residual boxes were NOT a marginal tie -- the whole bush family has a UNIFORM positive "
                    "gap (max logPhi=omega<0 at the ARM; the Phi=1 tie lives only on the near-star ARM "
                    "family N(c,k) c+k=5, a DIFFERENT depth-2 object), so a crude bound + geometric escape + "
                    "finite core closes it (the earlier 'same obstruction' diagnosis was WRONG). "
                    "bush_k1_slice_proof.py PROVES Q1 (k=1 slice) for ALL c,t: bs1=K rho^(c+t)(D/N)^11, exact "
                    "identity 16D-9N=72t+36c+45>0 => D/N>9/16, escape g(s)>=1 for s>=22, finite core c+t<22. "
                    "bush_bound_closed.py PROVES the full unconditional bush bound via a 3-piece cover (c=0 "
                    "star; c>=1 easy via R2->Q1; c>=1 non-easy via the exact identity arg<arg_sup(t)<=>non-easy "
                    "+ monotone escape rho>1,r(t)>1 + finite core), ground-truth cross-checked. "
                    "mixed_bush_bound_closed.py PROVES the CORRECTED piece (ii) -- the MIXED bush (leaf "
                    "children of DIFFERING cherry-counts = the true per-V maximiser, per depth_collapse_probe) "
                    "-- via a separable bound logPhi(G)<=log a(d,c)+k*max_t[gVal(t)+z m(t)]<=0 uniform over "
                    "the multiset (float tails w/ clear margins; exact near-tie core + Q1). This DISCHARGES "
                    "cherryBush_nonpos_of (BushBound.lean) for the bush. Structural probes (depth_collapse, "
                    "flatten_nogo, nonlinear_jsr, invariant_measure, smoothing_transform) are honest negatives "
                    "pinning the SOLE remaining crux = the DEPTH-COLLAPSE lemma (piece i: every tree logPhi <= "
                    "a mixed bush at its V) + R7 assembly. Phi<=1 / conjecture1_proved=False stand. "
                    "DEPTH-COLLAPSE cavity-monotone-flatten route REFUTED (depth_collapse_cavity_ceiling_probe.py, "
                    "exact): the Locality decomposition logPhi(T)=logPhi(b)+Env(cav(b)) has Env STRICTLY "
                    "INCREASING in cav(b) (E1, verified), so a same-V bush b* with logPhi(b*)>=logPhi(b) AND "
                    "cav(b*)>=cav(b) would give a globally non-decreasing flatten -- BUT no such b* exists for "
                    "high-cavity deep subtrees: max cav over ALL trees at V = (2V-3)/(4V-5) -> 1/2 (attained by "
                    "the LOLLIPOP = stem + (V-2)-leaf star, a depth-2 object), whereas depth-1 mixed bushes at "
                    "ODD V cap near 0.27-0.29 (parity forces even leaf-count k) -- an exact gap ~0.20 at every "
                    "odd V>=5. So 34% of depth>=2 subtrees (2835/8427, V<=11) have NO cav>= same-V depth-1 bush; "
                    "the cavity-non-decreasing flatten to depth-1 is IMPOSSIBLE, not merely lossy. The collapse "
                    "target must reach cav->1/2 (a deeper caterpillar/lollipop family, needing its own bound) or "
                    "the argument must be NON-LOCAL (smoothing-transform boundary / global integrality). "
                    "CATERPILLAR/LOLLIPOP FAMILY (caterpillar_bound.py, the high-cavity spine family): the "
                    "exact SPINE MECHANISM is PROVEN for all values -- a c=0 stem node has cavity map "
                    "g(k)=1/(2+k), logPhi increment -L+log(1+k/2) (<=0 iff k<=m*=2(rho_B-1)~0.459), telescoping "
                    "1+k/2=1/(2g(k)), and a TWO-STEP CONTRACTION g^2([0,1])=[2/5,3/7]<=m* -- giving the rigorous "
                    "SPINE-DECAY lemma logPhi(L_s(B))<=logPhi(L_2(B)) for s>=2 (at most the first two spine "
                    "increments can be positive). This REDUCES the lollipop bound logPhi(L_s(B))<=0 to L_0=B "
                    "(bush bound, PROVEN) + L_1=(0,[B]),L_2=(0,[(0,[B])]) <=0 (uniform gap omega at the ARM; "
                    "finite-verified V<=22, escape-closable, not yet independently escape-proved). General "
                    "caterpillars (mixed spine cherries+pendant leaves) verified <=0 (19607 cases). Extends "
                    "ChainMargin (pure chains) to lollipops. BUT this is a BUILDING BLOCK, NOT the depth-collapse: "
                    "the per-CAVITY logPhi-maximiser is NOT a caterpillar -- over all trees V<=13 it is a deep "
                    "BRANCHY tree (typical depth 5-7) for ~80% of cavities, so the value-function-via-caterpillars "
                    "route is refuted; the true collapse target is a deep branchy family. caterpillar_bound_proved=False "
                    "(mechanism proven; L1/L2 finite-verified). "
                    "PLAIN-TREE REDUCTION (plain_tree_reduction.py): characterised the per-cavity extremal exactly -- "
                    "over ALL trees V<=15 (133858 cavities, 0 exceptions) the maximiser argmax{logPhi: cav=kappa} is "
                    "always a PLAIN tree (c_v=0 at every node, every leaf bare -- no cherries, no t>=1 cherry-leaves). "
                    "Hence Psi(kappa)=max logPhi at cavity kappa is attained by a plain tree, giving the REDUCTION "
                    "*** Phi<=1 <=> every PLAIN rooted tree has logPhi<=0 ***. FAITHFUL (not lossy): the tie "
                    "N(0,5)=root+5 ARMs is ITSELF plain with logPhi=0, so the marginal-tie obstruction survives -- the "
                    "reduction removes the cherry-count and leaf-cherry-count parameters but keeps the hard core. Exact "
                    "PLAIN FORMULA (rigorous): plain node cav=1/(k+1+S), eroot=-L+log(1+S/(k+1))=-L-log(k+1)-log(cav), "
                    "so the conjecture becomes the PARAMETER-FREE statement sum_v[-L+log(1+S_v/(k_v+1))]<=0 over all "
                    "finite rooted trees (k_v=#children, S_v=sum of children cavities, cav=1/(k+1+S)). The formula is "
                    "exact/ground-truth-verified. "
                    "*** REDUCTION NOW PROVEN (plainification_theorem.py): *** the exact MOVE B identity "
                    "(c,K)==(c-1,K+[ARM]) preserves BOTH cavity (both = 3/(3k+3+4c+3S)) and logPhi (eroot shifts by "
                    "exactly omega=logPhi(ARM): the (3/2)^c and (621/64)^{-(1+2c)/11} factors give log(3/2)-2L=omega and "
                    "the remaining factor (1+c/3d)(1+zS) cancels, both sides =(3d+c+3S)/(3d)). A cherry is EXACTLY an "
                    "ARM child. Iterating (plainify: replace every cherry by an ARM, every t-leaf by N(0,t)) maps any "
                    "tree to a PLAIN tree with IDENTICAL cavity and logPhi -- so logPhi(T)=logPhi(plainify(T)) EXACTLY. "
                    "Hence Phi<=1 <=> every plain tree <=0 is a THEOREM (verified symbolically for all (c,k,S) + on all "
                    "trees V<=12, 0 failures). The WHOLE conjecture now equals the parameter-free plain-tree inequality "
                    "sum_v[-L+log(1+S_v/(k_v+1))]<=0 (equality at N(0,5)). plain_tree_bound_proved=False (this residual "
                    "inequality is the sole remaining crux, = the depth-collapse piece i). "
                    "REDUCTION NOW FORMALIZED IN LEAN (formalization/R3Cert/Plainify.lean, lean-verify CI GREEN, no sorry, "
                    "no True-placeholder): cav_cherry_step/eroot_cherry_step/logPhi_cherry_step (atomic MOVE B, eroot shift "
                    "via cleared identity ac*(1+zS)*rhoB^2=(3/2)*ac'*(1+z'S')), cav_cherriesToArms/logPhi_cherriesToArms, "
                    "plainify (mutual) + cav_plainify/logPhi_plainify, plainify_isPlain, and phi_le_one_of_plain: "
                    "(forall plain b, logPhi b<=0) -> forall b, logPhi b<=0. HONEST: the capstone takes the plain-tree bound "
                    "as a genuine HYPOTHESIS (not vacuous); the residual = Reach.ValidPotential existence stays open. Also machine-checked (CI-green): phi_le_one_iff_plain -- (forall b, logPhi b<=0) <-> PlainConjecture (the parameter-free plain-tree bound), stating the reduction as an EQUIVALENCE that isolates the crux exactly. PLAIN-TREE CLOSED FORM also ported to Lean (PlainFormula.lean, CI-green, no sorry): cav_plain_node (cav(node 0 ch)=1/(k+1+S)), eroot_plain_node/eroot_plain_node' (eroot 0 ch = -L+log(1+S/(k+1)) = -L-log(k+1)-log(cav)). "
                    "INTER-PEAK CONTROL of the plain value function psi (psi_envelope.py + plain_value_function.py): "
                    "psi<=0 with a SINGLE zero at 3/23 (tie N(0,5)); the PEAKS of psi are the near-star family "
                    "psi(3/(4k+3))=g(k) (argmax N(0,k)), PROVEN <=0. The inter-peak profile is CONTROLLED by a "
                    "DISCRETE near-star envelope psi(kappa)<=max(g(k),g(k+1)) for the bracketing index k=floor((3/kappa"
                    "-3)/4) -- holds at ALL 133858 plain-tree cavities (n<=15) with a SINGLE exception, the ARM "
                    "(kappa=1/3, psi=omega<=0); every RHS is <=0 so the discrete envelope => psi<=0. CRUCIALLY the "
                    "SMOOTH version of the same envelope FAILS: max over REAL s of g(s) = +4.17e-5>0 at s*~4.82 (the "
                    "integer max is g(5)=0), so no smooth/coordinate-free certificate can prove psi<=0 -- the +4.17e-5 "
                    "smooth-vs-discrete gap IS the integrality that makes Phi<=1 true (confirms the arithmetic "
                    "obstruction in the cleanest plain coordinates). REMAINING CRUX = prove the discrete envelope "
                    "psi(kappa)<=max(g(k),g(k+1)) (a domination of every plain tree by a near-star at a BRACKETING "
                    "cavity, RHS = the already-closed near-star family). This is the sharpest current localisation of "
                    "the open 1984 problem. "
                    "DISCRETE-ENVELOPE INDUCTION ATTACK -- HONEST NEGATIVE (psi_envelope_induction_nogo.py): the "
                    "natural induction on tree size needs E=max(g(k),g(k+1)) to be a SUPER-SOLUTION "
                    "-L+log(1+S/(m+1))+sum E(mu_i)<=E(1/(m+1+S)); it FAILS (21032/56828 plain trees, worst at "
                    "kappa=1/5 with two bare-leaf children: LHS +0.184 vs E -0.001). Root cause: E is loose "
                    "(E(1)=g(1)=-0.06 vs true bare-leaf logPhi=-L=-0.207; median slack ~0.53, tight at only ~3-4 "
                    "cavities incl. the tie), so it cannot propagate through the recursion; excluding bare-leaf "
                    "children cuts violations to 304 but not 0. The only TIGHT super-solution is psi itself, whose "
                    "<=0 proof is the marginal-tie ACCUMULATION wall (potential_nonsmooth_lp LP residual +0.0006; "
                    "smooth envelope pokes +4.17e-5>0). So attacking E directly returns to the genuine 1984 crux -- "
                    "the discrete envelope is a valid CHARACTERISATION (psi<=E<=0) but NOT inductively self-propagating. "
                    "INTEGRALITY / 23-ADIC ROUTE -- STRUCTURALLY INAPPLICABLE (integrality_route_assessment.py): "
                    "clearing the 11th root gives the exact PER-NODE factorisation W(T)=Phi^{-11}=prod_v w_v, "
                    "w_v=(621/64)((k_v+1)cav_v)^11, with Phi<=1 <=> W>=1 and the tie N(0,5) giving W=1 exactly "
                    "(64*243*23=621*576). But W>=1 is an ARCHIMEDEAN (magnitude) statement: v23(W) is UNCORRELATED "
                    "with whether W>=1 (near-tie trees have W just above 1 with v23(W) in {1,2,5,7,9,10,12} and "
                    "v23(W-1)=0, no pattern; trees with the SAME v23(W) span W from ~10 to ~97000). p-adic valuations "
                    "order Q by divisibility never by size, so NO 23-adic argument can prove W>=1 -- the tie identity "
                    "is a boundary EQUALITY, not a proof mechanism. The near-star proof was NOT p-adic; it was 1-D "
                    "REAL-ANALYTIC monotonicity (R(s+1)/R(s) single-crossing) + a boundary integer identity, which "
                    "the multivariate NON-unimodal plain value function does not admit. NET: BOTH flagged non-inductive "
                    "routes are dead -- SMOOTH pokes +4.17e-5>0 (provably blocked); p-ADIC structurally inapplicable "
                    "(archimedean). The genuine need is a valid REAL potential tight at the tie = the accumulating-LP / "
                    "marginal-tie open 1984 crux; no shortcut through smoothness or p-adics exists. "
                    "DEPTH-COLLAPSE ATTEMPT: robustly CONFIRMED (656 deep random trees depth<=6, 0 violations of "
                    "logPhi(tree) <= per-V bush max), and its rearrangement PRIMITIVE is now formalised "
                    "(Locality.lean, CI-green): eroot_congr (eroot depends on children only via length+cavSum), "
                    "logPhi_child_replace (swapping a child b->b' with cav b'=cav b shifts total logPhi by "
                    "EXACTLY logPhi b'-logPhi b -- ancestors' increments unchanged since cavity is preserved up "
                    "the spine), logPhi_child_mono (equal-cavity >=-amplitude swap does not lower logPhi). So "
                    "logPhi(C) is bounded by replacing each subtree with the max-amplitude tree of the SAME "
                    "cavity = Psi(cav); the depth-collapse thus REDUCES to Psi<=0 (the circular crux). The two "
                    "framings are both blocked: 'same V' by PARITY (V-parity=node-count parity, no single "
                    "leaf<->cherry swap preserves V), 'same cavity' by CIRCULARITY. So BOTH the bush bound and "
                    "the depth-collapse are pinned to the SAME obstruction Psi<=0 (arithmetic/23-adic), not "
                    "independent unknowns. Neither closes it. "
                    "PSI<=0 ATTEMPT (general_children_crux.tail_decomposition, self-verifying): the value-"
                    "function bound Psi<=0 DECOMPOSES into a region-free FAR regime + a marginal core. FAR "
                    "regime is region-free NEGATIVE: (a) DEPTH -- the c=0 chain per-node increment -> "
                    "-L+log((1+sqrt2)/2)<0, negative EXACTLY because 1+sqrt2<2*rhoB (the ALREADY-PROVEN E2 crux "
                    "e2_two_rhoB_gt), so pure depth decays linearly to -inf; (b) BRANCHING -- node(0)+j amp-0 "
                    "children -> -L+log(1+3/23)=-0.084<0 bounded; (c) CHERRIES -- a_leaf region-free bounded "
                    "(proven). MARGINAL CORE: the only logPhi=0 gadgets are the near-star tie variety c+k=5, "
                    "PROVEN =0 (NearStar.lean). So Psi<=0's OPEN part is the QUANTITATIVE far-regime margins + "
                    "boundary matching; the marginal core is closed and NO smooth/localization argument reaches "
                    "it (the tie variety is approached by infinite near-tie families with no uniform margin -- "
                    "integrality). Psi<=0 itself NOT closed; it is the open 1984 problem. FIRST FAR-REGIME "
                    "MARGIN NOW FORMALISED UNCONDITIONALLY (ChainMargin.lean, CI-green): the pure-depth c=0 "
                    "chain chainB n has logPhi(chainB n) <= 0 for ALL n, no hypothesis -- eroot_c0_one "
                    "(increment = -Lval+log(1+cav/2)), seventeen_14_lt_rhoB (17/14<rhoB from (17/14)^11<621/64), "
                    "chain_incr_nonpos (cav<=3/7 => increment<=0), cav_chainB_bound (chain cavities invariant "
                    "in [1/3,3/7]), logPhi_chainB (base -2Lval+log(3/2)<=0 via PROVEN rhoB_sq_ge, step adds a "
                    "<=0 increment). So the depth tail is CLOSED unconditionally, connecting two rhoB cruxes -- "
                    "stronger than the conditional bush bound. The branching direction and the marginal "
                    "near-tie core remain open. "
                    "BRANCHING-DIRECTION PROBES (three honest negatives, all self-verifying exact-Fraction, "
                    "conjecture1_proved stays False): (1) bush_star_probe -- exact rational BUSH-STAR form for "
                    "the depth-2 maximiser B(c,k,t) (3^(11P)2^(6Q)N^11 <= 2^(11P)3^(3Q)23^Q D^11, EXACTLY "
                    "logPhi(B)<=0), max = omega=logPhi(ARM)=-0.0077 with NO exact ties for k>=1 (bounded off the "
                    "tie), BUT logPhi is NON-MONOTONE in k (witness logPhi(0,1,2)<logPhi(0,2,2)), so the near-star "
                    "single-variable unimodal-R reduction does NOT extend -- a genuinely multivariate integer "
                    "argument is needed; and the per-node margins are ENTANGLED (eroot(c=0, k children at cav 3/7) "
                    "<=0 at k=1 but OVERSHOOTS >0 for k>=2, so a depth bound alone gives no per-node sign). "
                    "(2) armification_probe -- the arm-ification rearrangement (replace a non-{ARM,bare} child by "
                    "ARM never lowers logPhi) is REFUTED by exact counterexample: it holds on ALL trees N<=6 "
                    "(2.85M replacements, 0 decreases) ONLY because that sweep never replaces the 11-node tie "
                    "N(0,5) (logPhi=0>omega); plug the tie into a WIDE parent (0,[N(0,5)]+[ARM]*k) and arm-ifying "
                    "it DECREASES logPhi (k=20: -2.7e-3). Lesson: node-count-bounded exhaustive checks silently "
                    "exclude large extremal subtrees; the tie variety cannot be locally improved toward a single "
                    "ARM (sharp-Psi wall again). (3) discharging_probe -- the classic charge-conservation setup "
                    "(logPhi=sum_v eroot(v), +charge at high-cavity internal nodes, -L at leaves, tie balances "
                    "EXACTLY to 0): OPTIMAL routing is CIRCULAR (feasible iff every subtree absorbs its own charge "
                    "= the conjecture restated), and a FIXED local push-down rule OVERLOADS a leaf on ~14% of "
                    "random trees though logPhi<=0 there. NET: three more natural routes (multivariate "
                    "unimodality, monotone rearrangement, local discharging) all fail on the SAME marginal-tie "
                    "obstruction; the crux needs a global 23-adic/integrality argument, not a local certificate. "
                    "R7's Kelmans strictness is CLOSED for all N (certify_corners_strict) and "
                    "branch-multiplicativity is PROVEN (z_H->0, O(1/p^2)), so R7 rests only on R3. "
                    "GAP CHARACTERIZATION (gap_characterization.py, exhaustive plain-trees N<=17 + defect-family "
                    "scans, self-verifying): the near-stars are the UNIQUE approach to Phi=1 -- they alone climb "
                    "to the tie (logPhi->0 at k=5); EVERY non-near-star tree is bounded away, the global "
                    "non-near-star champion is EXACTLY omega=-0.0077 achieved UNIQUELY by the N=2 edge, and every "
                    "non-near-star with N>=3 has logPhi<=-0.0145. 'Defect' families root=(k arms)+(one thick "
                    "child) have INTERIOR maxima strictly below 0 (thick=(a,a):-0.0216; (a):-0.0385; (a,a,a):"
                    "-0.0153; N(0,5):-0.0166; most-dangerous 2-param root+near-star(m): -0.0145 at (k,m)=(5,4)) "
                    "-- they do NOT asymptote to the tie. Composing two subtree-relocations dissolves the mid-size "
                    "single-move traps, leaving exactly this interior-maximum defect family. So a >=0.0077 logPhi "
                    "gap separates the entire near-star family from every other tree, reducing the crux to 'no "
                    "non-near-star exceeds omega' -- still an infinite-family inequality subject to the SAME "
                    "exact-finite-AND-global barrier (smooth certs overshoot the tie by +4.17e-5; per-vertex/"
                    "potential bounds circular or impossible). Sharpens the target, does not close it. Everything "
                    "else (R1,R2,R4,R5,R6, amplitude reduction) proven. conjecture1_proved=False.",
    }


if __name__ == "__main__":
    for k, v in status().items():
        print(f"  {k}: {v}")
