#!/usr/bin/env python3
"""forge_band22_phi.py -- emit lean/ForgePhi22.lean: the theta phase at t = 22 (x = 1/4, y = 11) from the Euler route
   imLnVal (1/4) 11 128 + ForgeRate.rate_at, as kernel-checked brackets.

   Per term k = 0..128 of  sum_k arctan(11/(1/4+k)):
     k <= 4   (v > 1, u = 1/v <= 0.41):  arctan v = pi/2 - arctan u          [reflA]
     5..10    (v > 1, u > 0.41):         arctan v = pi/4 + arctan w, w=(1-u)/(1+u) [shiftA]
     11..26   (v <= 1, v > 0.41):        arctan v = pi/4 - arctan w, w=(1-v)/(1+v) [shiftB]
     >= 27    (v <= 0.41):               direct Taylor                    [direct]
   every Taylor argument is <= 0.41; N is the least order with remainder <= 2^-26.
   mpmath is the untrusted candidate producer; every emitted bound is re-checked here with exact
   Fractions before emission and then by the Lean kernel (norm_num)."""
from fractions import Fraction as F
import math, sys
import mpmath as mp
from pathlib import Path
mp.mp.dps = 60

LEAN = str(Path(__file__).resolve().parent / "lean")
K = 128
GRID = 1 << 28
REM = F(1, 1 << 26)

def fl(x): return F(math.floor(x * GRID), GRID)
def ce(x): return F(math.ceil(x * GRID), GRID)
def fs(x):
    return str(x.numerator) if x.denominator == 1 else f"{x.numerator}/{x.denominator}"
def lit(x):
    """Lean real literal for a Fraction, parenthesised."""
    if x.denominator == 1:
        return f"({x.numerator} : ℝ)"
    return f"(({x.numerator} : ℝ) / {x.denominator})"

def atanPS(u, N):
    return sum(F((-1) ** j) * u ** (2 * j + 1) / (2 * j + 1) for j in range(N))

def order(u):
    N = 1
    while u ** (2 * N + 1) / (2 * N + 1) > REM:
        N += 1
    return N

terms = []   # (k, kind, arg, N, lo, hi, c)  c = multiple of pi/4
for k in range(K + 1):
    v = F(44, 4 * k + 1)
    if v > 1:
        u = F(4 * k + 1, 44)
        if u <= F(41, 100):
            x = u; N = order(x); P = atanPS(x, N); E = x ** (2 * N + 1) / (2 * N + 1)
            lo, hi = fl(-(P + E)), ce(-(P - E)); kind = "reflA"; c = 2
        else:
            w = (1 - u) / (1 + u); x = w; N = order(x); P = atanPS(x, N); E = x ** (2 * N + 1) / (2 * N + 1)
            lo, hi = fl(P - E), ce(P + E); kind = "shiftA"; c = 1
    else:
        if v > F(41, 100):
            w = (1 - v) / (1 + v); x = w; N = order(x); P = atanPS(x, N); E = x ** (2 * N + 1) / (2 * N + 1)
            lo, hi = fl(-(P + E)), ce(-(P - E)); kind = "shiftB"; c = 1
        else:
            x = v; N = order(x); P = atanPS(x, N); E = x ** (2 * N + 1) / (2 * N + 1)
            lo, hi = fl(P - E), ce(P + E); kind = "direct"; c = 0
    # numeric validation against mpmath
    true = mp.atan(mp.mpf(44) / (4 * k + 1))
    cpi = c * mp.pi / 4
    assert cpi + mp.mpf(lo.numerator) / lo.denominator <= true <= cpi + mp.mpf(hi.numerator) / hi.denominator, k
    terms.append((k, kind, x, N, lo, hi, c, u if kind in ("reflA", "shiftA") else v))

C = sum(t[6] for t in terms)
assert C % 4 == 0
Cpi = C // 4          # total pi multiple
DLO = sum(t[4] for t in terms)
DHI = sum(t[5] for t in terms)
print("pi multiple:", Cpi, " DLO=", float(DLO), " DHI=", float(DHI), " width=", float(DHI - DLO))
S_true = mp.fsum(mp.atan(mp.mpf(11) / (mp.mpf(1)/4 + k)) for k in range(K + 1))
print("true sum", S_true, " bracket", float(Cpi * mp.pi + DLO), float(Cpi * mp.pi + DHI))

# ---- imLnVal and phi brackets (all exact rationals) ----
L2LO, L2HI = F("0.6931471803"), F("0.6931471808")
PILO, PIHI = F("3.141592"), F("3.141593")
LPLO, LPHI = F(153643043, 134217728), F(307286091, 268435456)   # ForgeThetaBox.logpibox
RATE = 2 * (F(11) * (F(1, 4) + 1) + F(11) ** 3 / (3 * K)) / K
IM_LO = 77 * L2LO - (Cpi * PIHI + DHI)
IM_HI = 77 * L2HI - (Cpi * PILO + DLO)
PH_LO_EX = IM_LO - RATE - 11 * LPHI
PH_HI_EX = IM_HI + RATE - 11 * LPLO
PH_LO = F(math.floor(PH_LO_EX * 1000), 1000)
PH_HI = F(math.ceil(PH_HI_EX * 1000), 1000)
print("imLnVal in", float(IM_LO), float(IM_HI), " rate", float(RATE), " phi in", float(PH_LO), float(PH_HI))
assert PH_LO > PIHI / 2 and PH_HI < PILO
SIN_LO_EX = F(2) / PIHI * (PILO - PH_HI)       # Jordan: sin(pi - phi) >= (2/pi)(pi - phi)
SIN_LO = F(math.floor(SIN_LO_EX * 100), 100)
print("sin phi >=", float(SIN_LO))

L = []
L.append('''/-  ForgePhi22.lean -- ANDURIL G2 kernel discharge: the theta phase at t = 22.

    AUTO-GENERATED by ../forge_band22_phi.py (mpmath is the untrusted candidate producer,
    every emitted bound is re-checked with exact rationals before emission and then by the kernel).

    The phase of `Gamma_R(1/2 + 22 i)` is `phi = Lam - 11 log pi`, `Lam = lim imLnVal (1/4) 11`
    (`ThetaConverge.convergence_obligation`).  This file boxes

        imLnVal (1/4) 11 128 = 11 log 128 - sum_{k=0}^{128} arctan(11/(1/4+k))

    term by term (every Taylor argument is <= 0.41 after the reflections
    `arctan v = pi/2 - arctan(1/v)` and `arctan u + arctan((1-u)/(1+u)) = pi/4`), adds the Euler-route
    rate `ForgeRate.rate_at` at n0 = 128 (<= 0.269) and the `log pi` box `ForgeThetaBox.logpibox`, and
    concludes `pi/2 < phi < pi` with explicit margins, hence `cos phi <= 0` and
    `sin phi >= ''' + fs(SIN_LO) + '''` (Jordan's inequality).  That is all the sign of `gLine 22` needs.

    conjecture1_proved = False.
-/
import ArctanTaylor
import ForgeRate
import ForgeThetaBox
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Arctan
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Bounds
import Mathlib.Analysis.Complex.ExponentialBounds

open Real ThetaGap

namespace ForgePhi22

set_option maxHeartbeats 4000000
set_option maxRecDepth 20000

/-! ## Generic per-term brackets (proved once) -/

/-- `arctan u + arctan((1-u)/(1+u)) = pi/4` for `u >= 0`. -/
theorem arctan_add_quarter {u : ℝ} (hu : 0 ≤ u) :
    Real.arctan u + Real.arctan ((1 - u) / (1 + u)) = Real.pi / 4 := by
  have h1u : 0 < 1 + u := by linarith
  set w : ℝ := (1 - u) / (1 + u) with hw
  have hwu : w * (1 + u) = 1 - u := by rw [hw]; field_simp
  have hsum : (u + w) * (1 + u) = 1 + u ^ 2 := by linear_combination hwu
  have hpos : 0 < u + w := by
    by_contra hneg
    have hneg' : u + w ≤ 0 := not_lt.mp hneg
    have : (u + w) * (1 + u) ≤ 0 := mul_nonpos_of_nonpos_of_nonneg hneg' (le_of_lt h1u)
    nlinarith [sq_nonneg u]
  have hprod : u * w < 1 := by nlinarith [hwu, hpos]
  rw [Real.arctan_add hprod]
  have hden : 1 - u * w = u + w := by linear_combination -hwu
  rw [hden, div_self (ne_of_gt hpos), Real.arctan_one]

/-- Direct Taylor bracket for a term `arctan(11/(1/4+k))` with argument `u <= 1`. -/
theorem at_direct {k : ℕ} {u lo hi : ℝ} (N : ℕ)
    (hu : (11:ℝ) / (1/4 + (k:ℝ)) = u) (hu0 : 0 ≤ u)
    (hlo : lo ≤ ArctanTaylor.atanPS u N - u^(2*N+1)/(2*N+1))
    (hhi : ArctanTaylor.atanPS u N + u^(2*N+1)/(2*N+1) ≤ hi) :
    lo ≤ Real.arctan (11 / (1/4 + (k:ℝ))) ∧ Real.arctan (11 / (1/4 + (k:ℝ))) ≤ hi := by
  rw [hu]
  have h := ArctanTaylor.arctan_bracket u hu0 N
  rw [abs_le] at h
  constructor <;> linarith [h.1, h.2]

/-- Reflected bracket: `arctan(11/(1/4+k)) = pi/2 - arctan u`, `u = (1/4+k)/11`. -/
theorem at_reflA {k : ℕ} {u lo hi : ℝ} (N : ℕ)
    (hu : (1/4 + (k:ℝ)) / 11 = u) (hu0 : 0 < u)
    (hlo : lo ≤ -(ArctanTaylor.atanPS u N + u^(2*N+1)/(2*N+1)))
    (hhi : -(ArctanTaylor.atanPS u N - u^(2*N+1)/(2*N+1)) ≤ hi) :
    Real.pi / 2 + lo ≤ Real.arctan (11 / (1/4 + (k:ℝ)))
      ∧ Real.arctan (11 / (1/4 + (k:ℝ))) ≤ Real.pi / 2 + hi := by
  have hinv : (11:ℝ) / (1/4 + (k:ℝ)) = u⁻¹ := by rw [← hu, inv_div]
  rw [hinv, Real.arctan_inv_of_pos hu0]
  have h := ArctanTaylor.arctan_bracket u (le_of_lt hu0) N
  rw [abs_le] at h
  constructor <;> linarith [h.1, h.2]

/-- Reflected + quarter-shifted bracket: `arctan(11/(1/4+k)) = pi/4 + arctan w`,
    `u = (1/4+k)/11`, `w = (1-u)/(1+u)`. -/
theorem at_shiftA {k : ℕ} {u w lo hi : ℝ} (N : ℕ)
    (hu : (1/4 + (k:ℝ)) / 11 = u) (hu0 : 0 < u) (hw : (1 - u) / (1 + u) = w) (hw0 : 0 ≤ w)
    (hlo : lo ≤ ArctanTaylor.atanPS w N - w^(2*N+1)/(2*N+1))
    (hhi : ArctanTaylor.atanPS w N + w^(2*N+1)/(2*N+1) ≤ hi) :
    Real.pi / 4 + lo ≤ Real.arctan (11 / (1/4 + (k:ℝ)))
      ∧ Real.arctan (11 / (1/4 + (k:ℝ))) ≤ Real.pi / 4 + hi := by
  have hinv : (11:ℝ) / (1/4 + (k:ℝ)) = u⁻¹ := by rw [← hu, inv_div]
  rw [hinv, Real.arctan_inv_of_pos hu0]
  have hq := arctan_add_quarter (le_of_lt hu0)
  rw [hw] at hq
  have h := ArctanTaylor.arctan_bracket w hw0 N
  rw [abs_le] at h
  constructor <;> linarith [h.1, h.2]

/-- Quarter-shifted bracket: `arctan(11/(1/4+k)) = pi/4 - arctan w`, `v = 11/(1/4+k)`,
    `w = (1-v)/(1+v)`. -/
theorem at_shiftB {k : ℕ} {v w lo hi : ℝ} (N : ℕ)
    (hv : (11:ℝ) / (1/4 + (k:ℝ)) = v) (hv0 : 0 ≤ v) (hw : (1 - v) / (1 + v) = w) (hw0 : 0 ≤ w)
    (hlo : lo ≤ -(ArctanTaylor.atanPS w N + w^(2*N+1)/(2*N+1)))
    (hhi : -(ArctanTaylor.atanPS w N - w^(2*N+1)/(2*N+1)) ≤ hi) :
    Real.pi / 4 + lo ≤ Real.arctan (11 / (1/4 + (k:ℝ)))
      ∧ Real.arctan (11 / (1/4 + (k:ℝ))) ≤ Real.pi / 4 + hi := by
  rw [hv]
  have hq := arctan_add_quarter hv0
  rw [hw] at hq
  have h := ArctanTaylor.arctan_bracket w hw0 N
  rw [abs_le] at h
  constructor <;> linarith [h.1, h.2]

/-- Enclosure addition. -/
theorem encl_add {S f A B a b : ℝ} (hS : A ≤ S ∧ S ≤ B) (hf : a ≤ f ∧ f ≤ b) :
    A + a ≤ S + f ∧ S + f ≤ B + b :=
  ⟨add_le_add hS.1 hf.1, add_le_add hS.2 hf.2⟩

/-- The fold step on `Finset.range` sums (keeps the partial sum as a `Finset.sum`, so no large
    syntactic sum has to be matched against the goal). -/
theorem sum_encl_succ (f : ℕ → ℝ) (n : ℕ) {A B a b : ℝ}
    (hS : A ≤ ∑ k ∈ Finset.range n, f k ∧ ∑ k ∈ Finset.range n, f k ≤ B)
    (hf : a ≤ f n ∧ f n ≤ b) :
    A + a ≤ ∑ k ∈ Finset.range (n + 1), f k ∧ ∑ k ∈ Finset.range (n + 1), f k ≤ B + b := by
  rw [Finset.sum_range_succ]
  exact encl_add hS hf

/-! ## The 129 term brackets -/
''')

PS = "(by norm_num [ArctanTaylor.atanPS, Finset.sum_range_succ])"
for (k, kind, x, N, lo, hi, c, a) in terms:
    tgt = f"Real.arctan (11 / (1/4 + (({k}:ℕ):ℝ)))"
    pre = {0: "", 1: "Real.pi / 4 + ", 2: "Real.pi / 2 + "}[c]
    L.append(f"theorem aterm_{k} :")
    L.append(f"    {pre}{lit(lo)} ≤ {tgt} ∧ {tgt} ≤ {pre}{lit(hi)} :=")
    if kind == "direct":
        L.append(f"  at_direct (k := {k}) (u := {lit(x)}) (lo := {lit(lo)}) (hi := {lit(hi)}) {N}")
        L.append(f"    (by norm_num) (by norm_num) {PS} {PS}")
    elif kind == "reflA":
        L.append(f"  at_reflA (k := {k}) (u := {lit(x)}) (lo := {lit(lo)}) (hi := {lit(hi)}) {N}")
        L.append(f"    (by norm_num) (by norm_num) {PS} {PS}")
    elif kind == "shiftA":
        L.append(f"  at_shiftA (k := {k}) (u := {lit(a)}) (w := {lit(x)}) (lo := {lit(lo)}) (hi := {lit(hi)}) {N}")
        L.append(f"    (by norm_num) (by norm_num) (by norm_num) (by norm_num) {PS} {PS}")
    else:
        L.append(f"  at_shiftB (k := {k}) (v := {lit(a)}) (w := {lit(x)}) (lo := {lit(lo)}) (hi := {lit(hi)}) {N}")
        L.append(f"    (by norm_num) (by norm_num) (by norm_num) (by norm_num) {PS} {PS}")
    L.append("")

L.append(f'''/-! ## The fold: `{Cpi} pi + DLO <= sum_(k<=128) arctan(11/(1/4+k)) <= {Cpi} pi + DHI` -/

theorem sumbox :
    ({Cpi} : ℝ) * Real.pi + {lit(DLO)} ≤ ∑ k ∈ Finset.range (128 + 1), Real.arctan (11 / (1/4 + (k:ℝ)))
      ∧ ∑ k ∈ Finset.range (128 + 1), Real.arctan (11 / (1/4 + (k:ℝ)))
          ≤ ({Cpi} : ℝ) * Real.pi + {lit(DHI)} := by''')
FL = "(fun k : ℕ => Real.arctan (11 / (1/4 + (k:ℝ))))"
L.append(f"  have c0 := sum_encl_succ {FL} 0 (A := 0) (B := 0) (by simp) aterm_0")
for k in range(1, K + 1):
    L.append(f"  have c{k} := sum_encl_succ {FL} {k} c{k-1} aterm_{k}")
L.append(f"  refine ⟨le_trans ?_ c{K}.1, le_trans c{K}.2 ?_⟩ <;> linarith only []")
L.append("")

L.append(f'''/-! ## imLnVal (1/4) 11 128, the phase box, and the two sign facts -/

/-- `log 128 = 7 log 2` bracket from the Mathlib d9 constants. -/
theorem log128box : ({lit(7*L2LO)}) ≤ Real.log ((128:ℕ):ℝ) ∧ Real.log ((128:ℕ):ℝ) ≤ ({lit(7*L2HI)}) := by
  have h : Real.log ((128:ℕ):ℝ) = 7 * Real.log 2 := by
    rw [show ((128:ℕ):ℝ) = (2:ℝ) ^ 7 by norm_num, Real.log_pow]; norm_num
  rw [h]
  constructor <;> linarith [Real.log_two_gt_d9, Real.log_two_lt_d9]

/-- **The Euler-route partial value** `imLnVal (1/4) 11 128`. -/
theorem imbox : {lit(IM_LO)} ≤ imLnVal (1/4) 11 128 ∧ imLnVal (1/4) 11 128 ≤ {lit(IM_HI)} := by
  obtain ⟨hs1, hs2⟩ := sumbox
  obtain ⟨hl1, hl2⟩ := log128box
  have hp1 := Real.pi_gt_d6
  have hp2 := Real.pi_lt_d6
  have hexp : imLnVal (1/4) 11 128
      = 11 * Real.log ((128:ℕ):ℝ) - ∑ k ∈ Finset.range (128 + 1), Real.arctan (11 / (1/4 + (k:ℝ))) := by
    unfold imLnVal; rfl
  rw [hexp]
  constructor <;> linarith

/-- **The phase box at `t = 22`.**  For the theta-limit `Lam` of `imLnVal (1/4) 11`,
    `{fs(PH_LO)} <= Lam - 11 log pi <= {fs(PH_HI)}`  (rate `<= {float(RATE):.4f}` at n0 = 128). -/
theorem phibox (Λ : ℝ) (hΛ : Filter.Tendsto (imLnVal (1/4) 11) Filter.atTop (nhds Λ)) :
    {lit(PH_LO)} ≤ Λ - 11 * Real.log Real.pi ∧ Λ - 11 * Real.log Real.pi ≤ {lit(PH_HI)} := by
  have hrate : |Λ - imLnVal (1/4) 11 128| ≤ {lit(RATE)} :=
    le_trans (ForgeRate.rate_at (1/4) 11 (by norm_num) Λ hΛ 128 (by norm_num)) (by norm_num)
  rw [abs_le] at hrate
  obtain ⟨hi1, hi2⟩ := imbox
  obtain ⟨hlp1, hlp2⟩ := ForgeThetaBox.logpibox
  constructor <;> linarith [hrate.1, hrate.2]

/-- **The two sign facts at `t = 22`.**  `cos phi <= 0` and `sin phi >= {fs(SIN_LO)}`, from
    `pi/2 < phi < pi` (the phase box) and Jordan's inequality `sin x >= (2/pi) x` on `[0, pi/2]`. -/
theorem cossin22 (Λ : ℝ) (hΛ : Filter.Tendsto (imLnVal (1/4) 11) Filter.atTop (nhds Λ)) :
    Real.cos (Λ - 11 * Real.log Real.pi) ≤ 0
      ∧ {lit(SIN_LO)} ≤ Real.sin (Λ - 11 * Real.log Real.pi) := by
  obtain ⟨hφlo, hφhi⟩ := phibox Λ hΛ
  set φ : ℝ := Λ - 11 * Real.log Real.pi with hφ
  have hp1 := Real.pi_gt_d6
  have hp2 := Real.pi_lt_d6
  refine ⟨Real.cos_nonpos_of_pi_div_two_le_of_le (by linarith) (by linarith), ?_⟩
  have hx0 : 0 ≤ Real.pi - φ := by linarith
  have hx1 : Real.pi - φ ≤ Real.pi / 2 := by linarith
  have hj := Real.mul_le_sin hx0 hx1
  rw [Real.sin_pi_sub] at hj
  have hpipos : 0 < Real.pi := Real.pi_pos
  have h2pi : (2 : ℝ) / 3.141593 ≤ 2 / Real.pi :=
    div_le_div_of_nonneg_left (by norm_num) hpipos (le_of_lt hp2)
  have hxlo : {lit(PILO - PH_HI)} ≤ Real.pi - φ := by linarith
  have hprod : (2 : ℝ) / 3.141593 * {lit(PILO - PH_HI)} ≤ 2 / Real.pi * (Real.pi - φ) :=
    mul_le_mul h2pi hxlo (by norm_num) (by positivity)
  have hnum : {lit(SIN_LO)} ≤ (2 : ℝ) / 3.141593 * {lit(PILO - PH_HI)} := by norm_num
  linarith

end ForgePhi22
''')
open(f"{LEAN}/ForgePhi22.lean", "w").write("\n".join(L) + "\n")
print("wrote ForgePhi22.lean", sum(len(x) for x in L), "chars")
