#!/usr/bin/env python3
"""A0 spike point generator.

Emits the 1000-point literal list for Spike/Toy.lean: dyadic points straddling
sqrt(2) ALTERNATELY (below, above, below, ...) so that p(x) = x^2 - 2 has strictly
alternating sign along the list.  Points are (mantissa, exponent) at ~128-bit
mantissa scale (exponent e = -128), i.e. the real value is mantissa * 2^e.

We also emit:
  * Toy.lean      : DIntv-evaluated checker `toy_ok : checkAlt pts = true := rfl`
  * ToyRat.lean   : identical checker over Rat (measures GCD tax)
  * ToyLit.lean   : 100k Int literals + trivial fold (isolates elaboration cost)

conjecture1_proved = False.
"""
from pathlib import Path

E = -128                      # exponent: value = mantissa * 2^E  (128-bit mantissa)
SCALE = 1 << (-E)             # 2^128
N_POINTS = 1000

# sqrt(2) as an integer numerator over 2^128, floor.  isqrt(2 * 2^256) / 2^128.
import math
sqrt2_num = math.isqrt(2 * (1 << (2 * -E)))   # floor(sqrt(2) * 2^128)


def gen_points():
    """Return list of (mantissa, exponent) alternately below/above sqrt(2).

    Below points: sqrt2_num - k*step_lo  (p < 0).  Above: sqrt2_num + k*step_hi (p > 0).
    Distinct offsets so no two points coincide; offsets large enough that the
    128-bit-mantissa square is cleanly signed (no straddle of 0)."""
    pts = []
    for i in range(N_POINTS):
        k = i // 2 + 1
        if i % 2 == 0:
            m = sqrt2_num - k * 3          # strictly below sqrt(2) -> x^2 - 2 < 0
        else:
            m = sqrt2_num + k * 3 + 1      # strictly above sqrt(2) -> x^2 - 2 > 0
        pts.append((m, E))
    return pts


def verify(pts):
    """Sanity: confirm sign alternation of x^2 - 2 in exact rationals."""
    two = 2
    prev = None
    for m, e in pts:
        val = (m * m, 2 * e)              # x^2 = m^2 * 2^(2e)
        # compare m^2 * 2^(2e) vs 2  <=>  m^2 vs 2 * 2^(-2e)
        lhs = m * m
        rhs = two * (1 << (-2 * e))
        sign = 1 if lhs > rhs else (-1 if lhs < rhs else 0)
        assert sign != 0, f"point straddles 0: {m}"
        if prev is not None:
            assert sign == -prev, "sign did not alternate"
        prev = sign
    return True


HEADER = "-- AUTO-GENERATED by telperion/examples/zeta_reflection/gen_spike.py -- do not edit.\n-- conjecture1_proved = False.\n"


def emit_toy(pts):
    lits = ",\n  ".join(f"({m}, {e})" for m, e in pts)
    return f"""{HEADER}import Spike.DIntvMini
set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Spike

/-- The {N_POINTS} dyadic test points (mantissa, exponent), straddling sqrt(2)
    alternately.  Value of point `(m,e)` is `m * 2^e`. -/
def pts : List (Int × Int) := [
  {lits}
]

/-- Evaluate `p(x) = x^2 - 2` on a dyadic point in DIntv arithmetic and return its
    definite sign (`none` if the interval straddles 0 -- a benchmark failure). -/
@[inline] def evalP (mp : Int × Int) : Option Bool :=
  let x  : DIntv := DIntv.ofDyadic mp.1 mp.2
  let x2 : DIntv := DIntv.mul x x
  let two : DIntv := DIntv.ofDyadic 2 0
  (DIntv.sub x2 two).sign?

/-- Verify strict sign alternation of `p` across the point list, evaluated in DIntv. -/
def checkAlt : List (Int × Int) -> Bool
  | [] => true
  | [p] => (evalP p).isSome
  | p :: q :: rest =>
    match evalP p, evalP q with
    | some sp, some sq => (sp != sq) && checkAlt (q :: rest)
    | _, _ => false

/-- Benchmark theorem: the DIntv checker certifies alternation by kernel reduction. -/
theorem toy_ok : checkAlt pts = true := rfl

end Spike
"""


def emit_toy_decide(pts):
    """Same as Toy but discharged with `by decide` -- measures wrapper overhead."""
    lits = ",\n  ".join(f"({m}, {e})" for m, e in pts)
    return f"""{HEADER}import Spike.DIntvMini
set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Spike

def ptsD : List (Int × Int) := [
  {lits}
]

@[inline] def evalPD (mp : Int × Int) : Option Bool :=
  let x  : DIntv := DIntv.ofDyadic mp.1 mp.2
  let x2 : DIntv := DIntv.mul x x
  let two : DIntv := DIntv.ofDyadic 2 0
  (DIntv.sub x2 two).sign?

def checkAltD : List (Int × Int) -> Bool
  | [] => true
  | [p] => (evalPD p).isSome
  | p :: q :: rest =>
    match evalPD p, evalPD q with
    | some sp, some sq => (sp != sq) && checkAltD (q :: rest)
    | _, _ => false

theorem toy_ok_decide : checkAltD ptsD = true := by decide

end Spike
"""


def emit_rat(pts):
    """Identical checker over Rat -- measures the GCD tax vs dyadic Int."""
    # Represent each point value as an exact Rat: m / 2^(-e)  (e < 0).
    lits = ",\n  ".join(f"({m} / {1 << (-e)} : Rat)" for m, e in pts)
    return f"""{HEADER}set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Spike

/-- The identical {N_POINTS} points as exact `Rat` values (m * 2^e). -/
def ptsQ : List Rat := [
  {lits}
]

/-- `p(x) = x^2 - 2` sign over Rat (exact, GCD-normalizing arithmetic). -/
@[inline] def evalQ (x : Rat) : Option Bool :=
  let v := x * x - 2
  if 0 < v then some true else if v < 0 then some false else none

def checkAltQ : List Rat -> Bool
  | [] => true
  | [p] => (evalQ p).isSome
  | p :: q :: rest =>
    match evalQ p, evalQ q with
    | some sp, some sq => (sp != sq) && checkAltQ (q :: rest)
    | _, _ => false

-- SPIKE FINDING (measured 2026-09-12): the Rat path is NOT kernel-reflectable AT ALL.
--   * `theorem toy_ok_rat : checkAltQ ptsQ = true := rfl`      -- FAILS: `rfl` does not
--       reduce Rat arithmetic (Rat is a structure with a reduced-fraction invariant; its
--       mul/lt normalize via `Nat.gcd`, opaque to definitional unfolding).
--   * `theorem toy_ok_rat : checkAltQ ptsQ = true := by decide` -- ALSO FAILS: the kernel
--       gets stuck at `Rat.instDecidableLt` (GCD via well-founded recursion the kernel
--       will not unfold).  Error: "reduction got stuck at the `Decidable` instance".
-- Conclusion: Rat gives NO finite dyadic/Rat ratio -- it is an infinite wall, not a tax.
-- Both statements are left OUT (they would redden the file); this comment IS the result.
-- The DIntv (pure-Int) path in Toy.lean reduces cleanly by `rfl`.

end Spike
"""


def emit_lit(n=20_000):
    """N Int literals in an ARRAY + a trivial fold -- isolates big-literal ELABORATION
    cost from kernel cost.  Uses `Array` (not `List`) so the trivial `all` check does not
    recurse N-deep (the 100k `List` variant blew `maxRecDepth`; that is itself a finding:
    naive `List` literals do not scale, production BandData must be `Array`/chunked)."""
    # literals: i-th literal is (i*2654435761 mod 2^40) to force large-ish Ints.
    vals = [(i * 2654435761) % (1 << 40) for i in range(n)]
    lits = ",".join(str(v) for v in vals)
    return f"""{HEADER}set_option maxHeartbeats 0
set_option maxRecDepth 1000000

namespace Spike

/-- {n} Int literals in an Array -- ELABORATION-cost isolation (trivial kernel work). -/
def bigLits : Array Int := #[{lits}]

/-- Trivial fold: all literals are < 2^40 (true by construction). -/
def checkLit (xs : Array Int) : Bool := xs.all (fun x => x < 1099511627776)

theorem lit_ok : checkLit bigLits = true := by decide

end Spike
"""


def main():
    here = Path(__file__).parent
    spike = here / "lean" / "Spike"
    spike.mkdir(parents=True, exist_ok=True)
    pts = gen_points()
    verify(pts)
    print(f"verified {len(pts)} points alternate; sqrt2_num={sqrt2_num}")
    (spike / "Toy.lean").write_text(emit_toy(pts))
    (spike / "ToyDecide.lean").write_text(emit_toy_decide(pts))
    (spike / "ToyRat.lean").write_text(emit_rat(pts))
    (spike / "ToyLit.lean").write_text(emit_lit())
    print("wrote Toy.lean, ToyDecide.lean, ToyRat.lean, ToyLit.lean")


if __name__ == "__main__":
    main()
