/-  AllZerosKernel_h1000.lean -- the height-1000 ladder statement, HYPOTHESIS-FREE
    (lane h1000-integrate; GENERATED by ../emit_h1000_offline.py; do not edit).

        all_nontrivial_zeros_up_to_height_1000 :
          ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 1000 → ρ.re = 1 / 2

    Every input of the 25 Turing bands of `BandGlue_h1000.seg` (the [1, 1000] segment of
    `AllZeros_h1000`) is discharged in the kernel:
      * hLine (on-line zeros): `H1000Line.seg_lineHyp` (lane h1000-prep);
      * hγ (height floor 55/16): `HeightFloor.height_floor`;
      * hnzl: `EdgeClearGlue.hnzl_discharged` (K1); hnzb / hnzt / hins: K1 from 50 zero-free
        slabs -- band 0's lower slab `H1000Glue.slab0_band0`, band 24's upper slab
        `ArbEcon.Off.Slab_T1000.band24_top_slabClear` (lane offline), the other 48 `H1000Slab_*`;
      * hAV2: K6a generic `[-249/250, 249/250]` (`ArgZetaTwo`); hAG1 / hAG2: K6b closed-form
        brackets (`ArgGammaR`, the rationals of `ArgChangeH1000.segK_side_i`);
      * hAHt / hAHb: 27 kernel-checked octant certificates `H1000Edge_*.hAH` (K6c + the off-line
        evaluator);
      * the pins `H1000Line.PinOk i (E i)`: `norm_num`.
    The composition is `H1000Line.all_nontrivial_zeros_up_to_height_1000_of_encl`.
    Axioms [propext, Classical.choice, Quot.sound] (AxiomGuardAllZerosKernel_h1000); no `sorry`.
    conjecture1_proved = False.  A FINITE verification up to height 1000; it says nothing about
    the Riemann Hypothesis.
-/
import H1000Line_All
import ArgChangeH1000
import EMZetaOfflineSlabBand
import H1000Edge_T1
import H1000Edge_T41
import H1000Edge_T81
import H1000Edge_T121
import H1000Edge_T161
import H1000Edge_T201
import H1000Edge_T241
import H1000Edge_T965_4
import H1000Edge_T281
import H1000Edge_T321
import H1000Edge_T361
import H1000Edge_T401
import H1000Edge_T441
import H1000Edge_T481
import H1000Edge_T520
import H1000Edge_T560
import H1000Edge_T600
import H1000Edge_T640
import H1000Edge_T680
import H1000Edge_T720
import H1000Edge_T760
import H1000Edge_T800
import H1000Edge_T840
import H1000Edge_T880
import H1000Edge_T920
import H1000Edge_T960
import H1000Edge_T1000
import H1000Slab_U41
import H1000Slab_L41
import H1000Slab_U81
import H1000Slab_L81
import H1000Slab_U121
import H1000Slab_L121
import H1000Slab_U161
import H1000Slab_L161
import H1000Slab_U201
import H1000Slab_L201
import H1000Slab_U965_4
import H1000Slab_L241
import H1000Slab_U281
import H1000Slab_L281
import H1000Slab_U321
import H1000Slab_L321
import H1000Slab_U361
import H1000Slab_L361
import H1000Slab_U401
import H1000Slab_L401
import H1000Slab_U441
import H1000Slab_L441
import H1000Slab_U481
import H1000Slab_L481
import H1000Slab_U520
import H1000Slab_L520
import H1000Slab_U560
import H1000Slab_L560
import H1000Slab_U600
import H1000Slab_L600
import H1000Slab_U640
import H1000Slab_L640
import H1000Slab_U680
import H1000Slab_L680
import H1000Slab_U720
import H1000Slab_L720
import H1000Slab_U760
import H1000Slab_L760
import H1000Slab_U800
import H1000Slab_L800
import H1000Slab_U840
import H1000Slab_L840
import H1000Slab_U880
import H1000Slab_L880
import H1000Slab_U920
import H1000Slab_L920
import H1000Slab_U960
import H1000Slab_L960

open Complex

namespace AllZerosKernel_h1000

/-- The five enclosures of every band: K6a, the two kernel-checked horizontal edges, K6b. -/
noncomputable def E : ℕ → H1000Line.Encl := fun i => match i with
  | 0 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (2695651 / 1000000 : ℝ), (2706101 / 1000000 : ℝ), (-1062039 / 1000000 : ℝ), (-130327 / 125000 : ℝ), (3990463 / 200000 : ℝ), (5053627 / 250000 : ℝ), (3901941 / 200000 : ℝ), (4905473 / 250000 : ℝ)⟩
  | 1 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (132469 / 500000 : ℝ), (55683 / 200000 : ℝ), (2695651 / 1000000 : ℝ), (2706101 / 1000000 : ℝ), (1127307 / 25000 : ℝ), (22555323 / 500000 : ℝ), (22541629 / 500000 : ℝ), (2818851 / 62500 : ℝ)⟩
  | 2 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-3068991 / 1000000 : ℝ), (-3055801 / 1000000 : ℝ), (132469 / 500000 : ℝ), (55683 / 200000 : ℝ), (13852881 / 250000 : ℝ), (5542183 / 100000 : ℝ), (3463029 / 62500 : ℝ), (55418769 / 1000000 : ℝ)⟩
  | 3 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-1266987 / 500000 : ℝ), (-2531201 / 1000000 : ℝ), (-3068991 / 1000000 : ℝ), (-3055801 / 1000000 : ℝ), (7768577 / 125000 : ℝ), (12431171 / 200000 : ℝ), (15536769 / 250000 : ℝ), (12430863 / 200000 : ℝ)⟩
  | 4 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-994753 / 250000 : ℝ), (-39369 / 10000 : ℝ), (-1266987 / 500000 : ℝ), (-2531201 / 1000000 : ℝ), (6716999 / 100000 : ℝ), (2099237 / 31250 : ℝ), (67169063 / 1000000 : ℝ), (67174657 / 1000000 : ℝ)⟩
  | 5 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (2657303 / 1000000 : ℝ), (2680931 / 1000000 : ℝ), (-994753 / 250000 : ℝ), (-39369 / 10000 : ℝ), (2865313 / 40000 : ℝ), (35818693 / 500000 : ℝ), (71632203 / 1000000 : ℝ), (17909191 / 250000 : ℝ)⟩
  | 6 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-290793 / 500000 : ℝ), (-36177 / 62500 : ℝ), (-332373 / 125000 : ℝ), (-1325781 / 500000 : ℝ), (37255961 / 500000 : ℝ), (74515777 / 1000000 : ℝ), (74511479 / 1000000 : ℝ), (37257667 / 500000 : ℝ)⟩
  | 7 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-2102059 / 500000 : ℝ), (-1047229 / 250000 : ℝ), (-290793 / 500000 : ℝ), (-36177 / 62500 : ℝ), (38684351 / 500000 : ℝ), (1934301 / 25000 : ℝ), (7736837 / 100000 : ℝ), (19342927 / 250000 : ℝ)⟩
  | 8 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-1421051 / 1000000 : ℝ), (-1403031 / 1000000 : ℝ), (-2102059 / 500000 : ℝ), (-1047229 / 250000 : ℝ), (79867503 / 1000000 : ℝ), (79870447 / 1000000 : ℝ), (19966811 / 250000 : ℝ), (19967547 / 250000 : ℝ)⟩
  | 9 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-159669 / 125000 : ℝ), (-316199 / 250000 : ℝ), (-1421051 / 1000000 : ℝ), (-1403031 / 1000000 : ℝ), (82088213 / 1000000 : ℝ), (41045423 / 500000 : ℝ), (41044003 / 500000 : ℝ), (82090639 / 1000000 : ℝ)⟩
  | 10 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-158853 / 250000 : ℝ), (-156111 / 250000 : ℝ), (-159669 / 125000 : ℝ), (-316199 / 250000 : ℝ), (84086623 / 1000000 : ℝ), (16817801 / 200000 : ℝ), (84086453 / 1000000 : ℝ), (16817767 / 200000 : ℝ)⟩
  | 11 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-1055897 / 500000 : ℝ), (-526161 / 250000 : ℝ), (-158853 / 250000 : ℝ), (-156111 / 250000 : ℝ), (21475811 / 250000 : ℝ), (42952709 / 500000 : ℝ), (42951551 / 500000 : ℝ), (21476319 / 250000 : ℝ)⟩
  | 12 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-3364219 / 1000000 : ℝ), (-417681 / 125000 : ℝ), (-1055897 / 500000 : ℝ), (-526161 / 250000 : ℝ), (17071993 / 200000 : ℝ), (85361967 / 1000000 : ℝ), (10669981 / 125000 : ℝ), (1707237 / 20000 : ℝ)⟩
  | 13 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-94659 / 500000 : ℝ), (-43803 / 250000 : ℝ), (-3364219 / 1000000 : ℝ), (-417681 / 125000 : ℝ), (89068477 / 1000000 : ℝ), (22267583 / 250000 : ℝ), (44534187 / 500000 : ℝ), (89070229 / 1000000 : ℝ)⟩
  | 14 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (378171 / 200000 : ℝ), (379501 / 200000 : ℝ), (-94659 / 500000 : ℝ), (-43803 / 250000 : ℝ), (90498311 / 1000000 : ℝ), (45250019 / 500000 : ℝ), (45249111 / 500000 : ℝ), (90499949 / 1000000 : ℝ)⟩
  | 15 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-176857 / 1000000 : ℝ), (-85619 / 500000 : ℝ), (378171 / 200000 : ℝ), (379501 / 200000 : ℝ), (3673307 / 40000 : ℝ), (9183429 / 100000 : ℝ), (91832597 / 1000000 : ℝ), (22958553 / 250000 : ℝ)⟩
  | 16 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (98569 / 40000 : ℝ), (493707 / 200000 : ℝ), (-176857 / 1000000 : ℝ), (-85619 / 500000 : ℝ), (93083527 / 1000000 : ℝ), (23271261 / 250000 : ℝ), (46541729 / 500000 : ℝ), (3723399 / 40000 : ℝ)⟩
  | 17 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (1255029 / 500000 : ℝ), (125847 / 50000 : ℝ), (98569 / 40000 : ℝ), (493707 / 200000 : ℝ), (9426071 / 100000 : ℝ), (94262141 / 1000000 : ℝ), (94260649 / 1000000 : ℝ), (94262079 / 1000000 : ℝ)⟩
  | 18 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (-108831 / 250000 : ℝ), (-1308 / 3125 : ℝ), (1255029 / 500000 : ℝ), (125847 / 50000 : ℝ), (95372423 / 1000000 : ℝ), (95373777 / 1000000 : ℝ), (95372369 / 1000000 : ℝ), (47686861 / 500000 : ℝ)⟩
  | 19 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (2399003 / 1000000 : ℝ), (1503 / 625 : ℝ), (-108831 / 250000 : ℝ), (-1308 / 3125 : ℝ), (96425569 / 1000000 : ℝ), (96426853 / 1000000 : ℝ), (1205319 / 12500 : ℝ), (96426803 / 1000000 : ℝ)⟩
  | 20 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (803437 / 500000 : ℝ), (406133 / 250000 : ℝ), (2399003 / 1000000 : ℝ), (1503 / 625 : ℝ), (97426011 / 1000000 : ℝ), (3044601 / 31250 : ℝ), (48712983 / 500000 : ℝ), (24356797 / 250000 : ℝ)⟩
  | 21 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (64269 / 250000 : ℝ), (262987 / 1000000 : ℝ), (803437 / 500000 : ℝ), (406133 / 250000 : ℝ), (3935151 / 40000 : ℝ), (4918997 / 50000 : ℝ), (19675747 / 200000 : ℝ), (98379899 / 1000000 : ℝ)⟩
  | 22 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (2339257 / 1000000 : ℝ), (29339 / 12500 : ℝ), (64269 / 250000 : ℝ), (262987 / 1000000 : ℝ), (99288201 / 1000000 : ℝ), (99289313 / 1000000 : ℝ), (24822041 / 250000 : ℝ), (24822319 / 250000 : ℝ)⟩
  | 23 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (2773761 / 1000000 : ℝ), (696217 / 250000 : ℝ), (2339257 / 1000000 : ℝ), (29339 / 12500 : ℝ), (5007903 / 50000 : ℝ), (801273 / 8000 : ℝ), (50079013 / 500000 : ℝ), (100159091 / 1000000 : ℝ)⟩
  | 24 => ⟨-(249 / 250 : ℝ), (249 / 250 : ℝ), (2640451 / 1000000 : ℝ), (82783 / 31250 : ℝ), (2773761 / 1000000 : ℝ), (696217 / 250000 : ℝ), (25247913 / 250000 : ℝ), (50496337 / 500000 : ℝ), (100991621 / 1000000 : ℝ), (100992643 / 1000000 : ℝ)⟩
  | _ => ⟨0, 0, 0, 0, 0, 0, 0, 0, 0, 0⟩

theorem pin0 : H1000Line.PinOk 0 (E 0) := by
  show 2 * 3.1416 * (((7 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (2695651 / 1000000 : ℝ) - (-130327 / 125000 : ℝ) + (3990463 / 200000 : ℝ) + (3901941 / 200000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (2706101 / 1000000 : ℝ) - (-1062039 / 1000000 : ℝ) + (5053627 / 250000 : ℝ) + (4905473 / 250000 : ℝ) < 2 * 3.14 * (((7 : ℕ) : ℝ) + 1)
  norm_num

theorem pin1 : H1000Line.PinOk 1 (E 1) := by
  show 2 * 3.1416 * (((14 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (132469 / 500000 : ℝ) - (2706101 / 1000000 : ℝ) + (1127307 / 25000 : ℝ) + (22541629 / 500000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (55683 / 200000 : ℝ) - (2695651 / 1000000 : ℝ) + (22555323 / 500000 : ℝ) + (2818851 / 62500 : ℝ) < 2 * 3.14 * (((14 : ℕ) : ℝ) + 1)
  norm_num

theorem pin2 : H1000Line.PinOk 2 (E 2) := by
  show 2 * 3.1416 * (((17 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-3068991 / 1000000 : ℝ) - (55683 / 200000 : ℝ) + (13852881 / 250000 : ℝ) + (3463029 / 62500 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-3055801 / 1000000 : ℝ) - (132469 / 500000 : ℝ) + (5542183 / 100000 : ℝ) + (55418769 / 1000000 : ℝ) < 2 * 3.14 * (((17 : ℕ) : ℝ) + 1)
  norm_num

theorem pin3 : H1000Line.PinOk 3 (E 3) := by
  show 2 * 3.1416 * (((20 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-1266987 / 500000 : ℝ) - (-3055801 / 1000000 : ℝ) + (7768577 / 125000 : ℝ) + (15536769 / 250000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-2531201 / 1000000 : ℝ) - (-3068991 / 1000000 : ℝ) + (12431171 / 200000 : ℝ) + (12430863 / 200000 : ℝ) < 2 * 3.14 * (((20 : ℕ) : ℝ) + 1)
  norm_num

theorem pin4 : H1000Line.PinOk 4 (E 4) := by
  show 2 * 3.1416 * (((21 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-994753 / 250000 : ℝ) - (-2531201 / 1000000 : ℝ) + (6716999 / 100000 : ℝ) + (67169063 / 1000000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-39369 / 10000 : ℝ) - (-1266987 / 500000 : ℝ) + (2099237 / 31250 : ℝ) + (67174657 / 1000000 : ℝ) < 2 * 3.14 * (((21 : ℕ) : ℝ) + 1)
  norm_num

theorem pin5 : H1000Line.PinOk 5 (E 5) := by
  show 2 * 3.1416 * (((24 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (2657303 / 1000000 : ℝ) - (-39369 / 10000 : ℝ) + (2865313 / 40000 : ℝ) + (71632203 / 1000000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (2680931 / 1000000 : ℝ) - (-994753 / 250000 : ℝ) + (35818693 / 500000 : ℝ) + (17909191 / 250000 : ℝ) < 2 * 3.14 * (((24 : ℕ) : ℝ) + 1)
  norm_num

theorem pin6 : H1000Line.PinOk 6 (E 6) := by
  show 2 * 3.1416 * (((24 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-290793 / 500000 : ℝ) - (-1325781 / 500000 : ℝ) + (37255961 / 500000 : ℝ) + (74511479 / 1000000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-36177 / 62500 : ℝ) - (-332373 / 125000 : ℝ) + (74515777 / 1000000 : ℝ) + (37257667 / 500000 : ℝ) < 2 * 3.14 * (((24 : ℕ) : ℝ) + 1)
  norm_num

theorem pin7 : H1000Line.PinOk 7 (E 7) := by
  show 2 * 3.1416 * (((24 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-2102059 / 500000 : ℝ) - (-36177 / 62500 : ℝ) + (38684351 / 500000 : ℝ) + (7736837 / 100000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-1047229 / 250000 : ℝ) - (-290793 / 500000 : ℝ) + (1934301 / 25000 : ℝ) + (19342927 / 250000 : ℝ) < 2 * 3.14 * (((24 : ℕ) : ℝ) + 1)
  norm_num

theorem pin8 : H1000Line.PinOk 8 (E 8) := by
  show 2 * 3.1416 * (((26 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-1421051 / 1000000 : ℝ) - (-1047229 / 250000 : ℝ) + (79867503 / 1000000 : ℝ) + (19966811 / 250000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-1403031 / 1000000 : ℝ) - (-2102059 / 500000 : ℝ) + (79870447 / 1000000 : ℝ) + (19967547 / 250000 : ℝ) < 2 * 3.14 * (((26 : ℕ) : ℝ) + 1)
  norm_num

theorem pin9 : H1000Line.PinOk 9 (E 9) := by
  show 2 * 3.1416 * (((26 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-159669 / 125000 : ℝ) - (-1403031 / 1000000 : ℝ) + (82088213 / 1000000 : ℝ) + (41044003 / 500000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-316199 / 250000 : ℝ) - (-1421051 / 1000000 : ℝ) + (41045423 / 500000 : ℝ) + (82090639 / 1000000 : ℝ) < 2 * 3.14 * (((26 : ℕ) : ℝ) + 1)
  norm_num

theorem pin10 : H1000Line.PinOk 10 (E 10) := by
  show 2 * 3.1416 * (((27 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-158853 / 250000 : ℝ) - (-316199 / 250000 : ℝ) + (84086623 / 1000000 : ℝ) + (84086453 / 1000000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-156111 / 250000 : ℝ) - (-159669 / 125000 : ℝ) + (16817801 / 200000 : ℝ) + (16817767 / 200000 : ℝ) < 2 * 3.14 * (((27 : ℕ) : ℝ) + 1)
  norm_num

theorem pin11 : H1000Line.PinOk 11 (E 11) := by
  show 2 * 3.1416 * (((27 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-1055897 / 500000 : ℝ) - (-156111 / 250000 : ℝ) + (21475811 / 250000 : ℝ) + (42951551 / 500000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-526161 / 250000 : ℝ) - (-158853 / 250000 : ℝ) + (42952709 / 500000 : ℝ) + (21476319 / 250000 : ℝ) < 2 * 3.14 * (((27 : ℕ) : ℝ) + 1)
  norm_num

theorem pin12 : H1000Line.PinOk 12 (E 12) := by
  show 2 * 3.1416 * (((27 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-3364219 / 1000000 : ℝ) - (-526161 / 250000 : ℝ) + (17071993 / 200000 : ℝ) + (10669981 / 125000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-417681 / 125000 : ℝ) - (-1055897 / 500000 : ℝ) + (85361967 / 1000000 : ℝ) + (1707237 / 20000 : ℝ) < 2 * 3.14 * (((27 : ℕ) : ℝ) + 1)
  norm_num

theorem pin13 : H1000Line.PinOk 13 (E 13) := by
  show 2 * 3.1416 * (((29 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-94659 / 500000 : ℝ) - (-417681 / 125000 : ℝ) + (89068477 / 1000000 : ℝ) + (44534187 / 500000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-43803 / 250000 : ℝ) - (-3364219 / 1000000 : ℝ) + (22267583 / 250000 : ℝ) + (89070229 / 1000000 : ℝ) < 2 * 3.14 * (((29 : ℕ) : ℝ) + 1)
  norm_num

theorem pin14 : H1000Line.PinOk 14 (E 14) := by
  show 2 * 3.1416 * (((29 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (378171 / 200000 : ℝ) - (-43803 / 250000 : ℝ) + (90498311 / 1000000 : ℝ) + (45249111 / 500000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (379501 / 200000 : ℝ) - (-94659 / 500000 : ℝ) + (45250019 / 500000 : ℝ) + (90499949 / 1000000 : ℝ) < 2 * 3.14 * (((29 : ℕ) : ℝ) + 1)
  norm_num

theorem pin15 : H1000Line.PinOk 15 (E 15) := by
  show 2 * 3.1416 * (((29 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-176857 / 1000000 : ℝ) - (379501 / 200000 : ℝ) + (3673307 / 40000 : ℝ) + (91832597 / 1000000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-85619 / 500000 : ℝ) - (378171 / 200000 : ℝ) + (9183429 / 100000 : ℝ) + (22958553 / 250000 : ℝ) < 2 * 3.14 * (((29 : ℕ) : ℝ) + 1)
  norm_num

theorem pin16 : H1000Line.PinOk 16 (E 16) := by
  show 2 * 3.1416 * (((30 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (98569 / 40000 : ℝ) - (-85619 / 500000 : ℝ) + (93083527 / 1000000 : ℝ) + (46541729 / 500000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (493707 / 200000 : ℝ) - (-176857 / 1000000 : ℝ) + (23271261 / 250000 : ℝ) + (3723399 / 40000 : ℝ) < 2 * 3.14 * (((30 : ℕ) : ℝ) + 1)
  norm_num

theorem pin17 : H1000Line.PinOk 17 (E 17) := by
  show 2 * 3.1416 * (((30 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (1255029 / 500000 : ℝ) - (493707 / 200000 : ℝ) + (9426071 / 100000 : ℝ) + (94260649 / 1000000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (125847 / 50000 : ℝ) - (98569 / 40000 : ℝ) + (94262141 / 1000000 : ℝ) + (94262079 / 1000000 : ℝ) < 2 * 3.14 * (((30 : ℕ) : ℝ) + 1)
  norm_num

theorem pin18 : H1000Line.PinOk 18 (E 18) := by
  show 2 * 3.1416 * (((30 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (-108831 / 250000 : ℝ) - (125847 / 50000 : ℝ) + (95372423 / 1000000 : ℝ) + (95372369 / 1000000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (-1308 / 3125 : ℝ) - (1255029 / 500000 : ℝ) + (95373777 / 1000000 : ℝ) + (47686861 / 500000 : ℝ) < 2 * 3.14 * (((30 : ℕ) : ℝ) + 1)
  norm_num

theorem pin19 : H1000Line.PinOk 19 (E 19) := by
  show 2 * 3.1416 * (((31 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (2399003 / 1000000 : ℝ) - (-1308 / 3125 : ℝ) + (96425569 / 1000000 : ℝ) + (1205319 / 12500 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (1503 / 625 : ℝ) - (-108831 / 250000 : ℝ) + (96426853 / 1000000 : ℝ) + (96426803 / 1000000 : ℝ) < 2 * 3.14 * (((31 : ℕ) : ℝ) + 1)
  norm_num

theorem pin20 : H1000Line.PinOk 20 (E 20) := by
  show 2 * 3.1416 * (((31 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (803437 / 500000 : ℝ) - (1503 / 625 : ℝ) + (97426011 / 1000000 : ℝ) + (48712983 / 500000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (406133 / 250000 : ℝ) - (2399003 / 1000000 : ℝ) + (3044601 / 31250 : ℝ) + (24356797 / 250000 : ℝ) < 2 * 3.14 * (((31 : ℕ) : ℝ) + 1)
  norm_num

theorem pin21 : H1000Line.PinOk 21 (E 21) := by
  show 2 * 3.1416 * (((31 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (64269 / 250000 : ℝ) - (406133 / 250000 : ℝ) + (3935151 / 40000 : ℝ) + (19675747 / 200000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (262987 / 1000000 : ℝ) - (803437 / 500000 : ℝ) + (4918997 / 50000 : ℝ) + (98379899 / 1000000 : ℝ) < 2 * 3.14 * (((31 : ℕ) : ℝ) + 1)
  norm_num

theorem pin22 : H1000Line.PinOk 22 (E 22) := by
  show 2 * 3.1416 * (((32 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (2339257 / 1000000 : ℝ) - (262987 / 1000000 : ℝ) + (99288201 / 1000000 : ℝ) + (24822041 / 250000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (29339 / 12500 : ℝ) - (64269 / 250000 : ℝ) + (99289313 / 1000000 : ℝ) + (24822319 / 250000 : ℝ) < 2 * 3.14 * (((32 : ℕ) : ℝ) + 1)
  norm_num

theorem pin23 : H1000Line.PinOk 23 (E 23) := by
  show 2 * 3.1416 * (((32 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (2773761 / 1000000 : ℝ) - (29339 / 12500 : ℝ) + (5007903 / 50000 : ℝ) + (50079013 / 500000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (696217 / 250000 : ℝ) - (2339257 / 1000000 : ℝ) + (801273 / 8000 : ℝ) + (100159091 / 1000000 : ℝ) < 2 * 3.14 * (((32 : ℕ) : ℝ) + 1)
  norm_num

theorem pin24 : H1000Line.PinOk 24 (E 24) := by
  show 2 * 3.1416 * (((32 : ℕ) : ℝ) - 1) < 2 * -(249 / 250 : ℝ) + (2640451 / 1000000 : ℝ) - (696217 / 250000 : ℝ) + (25247913 / 250000 : ℝ) + (100991621 / 1000000 : ℝ) ∧
    2 * (249 / 250 : ℝ) + (82783 / 31250 : ℝ) - (2773761 / 1000000 : ℝ) + (50496337 / 500000 : ℝ) + (100992643 / 1000000 : ℝ) < 2 * 3.14 * (((32 : ℕ) : ℝ) + 1)
  norm_num

theorem hpin : ∀ i, i < 25 → H1000Line.PinOk i (E i) := by
  intro i hi
  interval_cases i
  · exact pin0
  · exact pin1
  · exact pin2
  · exact pin3
  · exact pin4
  · exact pin5
  · exact pin6
  · exact pin7
  · exact pin8
  · exact pin9
  · exact pin10
  · exact pin11
  · exact pin12
  · exact pin13
  · exact pin14
  · exact pin15
  · exact pin16
  · exact pin17
  · exact pin18
  · exact pin19
  · exact pin20
  · exact pin21
  · exact pin22
  · exact pin23
  · exact pin24

theorem side0 : ArgChangeGlue.K6Side (H1000Line.segWith 0 (E 0)) :=
  ⟨(ArgChangeH1000.segK_side_0).hT0, (ArgChangeH1000.segK_side_0).hT1, (ArgChangeH1000.segK_side_0).hL1,
    (ArgChangeH1000.segK_side_0).hH1, (ArgChangeH1000.segK_side_0).hL4, (ArgChangeH1000.segK_side_0).hH4,
    (ArgChangeH1000.segK_side_0).hL5, (ArgChangeH1000.segK_side_0).hH5⟩
theorem horiz0 : ArgChangeGlue.HorizHyp (H1000Line.segWith 0 (E 0)) :=
  ⟨H1000Edge.T41.hAH, H1000Edge.T1.hAH⟩

theorem side1 : ArgChangeGlue.K6Side (H1000Line.segWith 1 (E 1)) :=
  ⟨(ArgChangeH1000.segK_side_1).hT0, (ArgChangeH1000.segK_side_1).hT1, (ArgChangeH1000.segK_side_1).hL1,
    (ArgChangeH1000.segK_side_1).hH1, (ArgChangeH1000.segK_side_1).hL4, (ArgChangeH1000.segK_side_1).hH4,
    (ArgChangeH1000.segK_side_1).hL5, (ArgChangeH1000.segK_side_1).hH5⟩
theorem horiz1 : ArgChangeGlue.HorizHyp (H1000Line.segWith 1 (E 1)) :=
  ⟨H1000Edge.T81.hAH, H1000Edge.T41.hAH⟩

theorem side2 : ArgChangeGlue.K6Side (H1000Line.segWith 2 (E 2)) :=
  ⟨(ArgChangeH1000.segK_side_2).hT0, (ArgChangeH1000.segK_side_2).hT1, (ArgChangeH1000.segK_side_2).hL1,
    (ArgChangeH1000.segK_side_2).hH1, (ArgChangeH1000.segK_side_2).hL4, (ArgChangeH1000.segK_side_2).hH4,
    (ArgChangeH1000.segK_side_2).hL5, (ArgChangeH1000.segK_side_2).hH5⟩
theorem horiz2 : ArgChangeGlue.HorizHyp (H1000Line.segWith 2 (E 2)) :=
  ⟨H1000Edge.T121.hAH, H1000Edge.T81.hAH⟩

theorem side3 : ArgChangeGlue.K6Side (H1000Line.segWith 3 (E 3)) :=
  ⟨(ArgChangeH1000.segK_side_3).hT0, (ArgChangeH1000.segK_side_3).hT1, (ArgChangeH1000.segK_side_3).hL1,
    (ArgChangeH1000.segK_side_3).hH1, (ArgChangeH1000.segK_side_3).hL4, (ArgChangeH1000.segK_side_3).hH4,
    (ArgChangeH1000.segK_side_3).hL5, (ArgChangeH1000.segK_side_3).hH5⟩
theorem horiz3 : ArgChangeGlue.HorizHyp (H1000Line.segWith 3 (E 3)) :=
  ⟨H1000Edge.T161.hAH, H1000Edge.T121.hAH⟩

theorem side4 : ArgChangeGlue.K6Side (H1000Line.segWith 4 (E 4)) :=
  ⟨(ArgChangeH1000.segK_side_4).hT0, (ArgChangeH1000.segK_side_4).hT1, (ArgChangeH1000.segK_side_4).hL1,
    (ArgChangeH1000.segK_side_4).hH1, (ArgChangeH1000.segK_side_4).hL4, (ArgChangeH1000.segK_side_4).hH4,
    (ArgChangeH1000.segK_side_4).hL5, (ArgChangeH1000.segK_side_4).hH5⟩
theorem horiz4 : ArgChangeGlue.HorizHyp (H1000Line.segWith 4 (E 4)) :=
  ⟨H1000Edge.T201.hAH, H1000Edge.T161.hAH⟩

theorem side5 : ArgChangeGlue.K6Side (H1000Line.segWith 5 (E 5)) :=
  ⟨(ArgChangeH1000.segK_side_5).hT0, (ArgChangeH1000.segK_side_5).hT1, (ArgChangeH1000.segK_side_5).hL1,
    (ArgChangeH1000.segK_side_5).hH1, (ArgChangeH1000.segK_side_5).hL4, (ArgChangeH1000.segK_side_5).hH4,
    (ArgChangeH1000.segK_side_5).hL5, (ArgChangeH1000.segK_side_5).hH5⟩
theorem horiz5 : ArgChangeGlue.HorizHyp (H1000Line.segWith 5 (E 5)) :=
  ⟨H1000Edge.T965_4.hAH, H1000Edge.T201.hAH⟩

theorem side6 : ArgChangeGlue.K6Side (H1000Line.segWith 6 (E 6)) :=
  ⟨(ArgChangeH1000.segK_side_6).hT0, (ArgChangeH1000.segK_side_6).hT1, (ArgChangeH1000.segK_side_6).hL1,
    (ArgChangeH1000.segK_side_6).hH1, (ArgChangeH1000.segK_side_6).hL4, (ArgChangeH1000.segK_side_6).hH4,
    (ArgChangeH1000.segK_side_6).hL5, (ArgChangeH1000.segK_side_6).hH5⟩
theorem horiz6 : ArgChangeGlue.HorizHyp (H1000Line.segWith 6 (E 6)) :=
  ⟨H1000Edge.T281.hAH, H1000Edge.T241.hAH⟩

theorem side7 : ArgChangeGlue.K6Side (H1000Line.segWith 7 (E 7)) :=
  ⟨(ArgChangeH1000.segK_side_7).hT0, (ArgChangeH1000.segK_side_7).hT1, (ArgChangeH1000.segK_side_7).hL1,
    (ArgChangeH1000.segK_side_7).hH1, (ArgChangeH1000.segK_side_7).hL4, (ArgChangeH1000.segK_side_7).hH4,
    (ArgChangeH1000.segK_side_7).hL5, (ArgChangeH1000.segK_side_7).hH5⟩
theorem horiz7 : ArgChangeGlue.HorizHyp (H1000Line.segWith 7 (E 7)) :=
  ⟨H1000Edge.T321.hAH, H1000Edge.T281.hAH⟩

theorem side8 : ArgChangeGlue.K6Side (H1000Line.segWith 8 (E 8)) :=
  ⟨(ArgChangeH1000.segK_side_8).hT0, (ArgChangeH1000.segK_side_8).hT1, (ArgChangeH1000.segK_side_8).hL1,
    (ArgChangeH1000.segK_side_8).hH1, (ArgChangeH1000.segK_side_8).hL4, (ArgChangeH1000.segK_side_8).hH4,
    (ArgChangeH1000.segK_side_8).hL5, (ArgChangeH1000.segK_side_8).hH5⟩
theorem horiz8 : ArgChangeGlue.HorizHyp (H1000Line.segWith 8 (E 8)) :=
  ⟨H1000Edge.T361.hAH, H1000Edge.T321.hAH⟩

theorem side9 : ArgChangeGlue.K6Side (H1000Line.segWith 9 (E 9)) :=
  ⟨(ArgChangeH1000.segK_side_9).hT0, (ArgChangeH1000.segK_side_9).hT1, (ArgChangeH1000.segK_side_9).hL1,
    (ArgChangeH1000.segK_side_9).hH1, (ArgChangeH1000.segK_side_9).hL4, (ArgChangeH1000.segK_side_9).hH4,
    (ArgChangeH1000.segK_side_9).hL5, (ArgChangeH1000.segK_side_9).hH5⟩
theorem horiz9 : ArgChangeGlue.HorizHyp (H1000Line.segWith 9 (E 9)) :=
  ⟨H1000Edge.T401.hAH, H1000Edge.T361.hAH⟩

theorem side10 : ArgChangeGlue.K6Side (H1000Line.segWith 10 (E 10)) :=
  ⟨(ArgChangeH1000.segK_side_10).hT0, (ArgChangeH1000.segK_side_10).hT1, (ArgChangeH1000.segK_side_10).hL1,
    (ArgChangeH1000.segK_side_10).hH1, (ArgChangeH1000.segK_side_10).hL4, (ArgChangeH1000.segK_side_10).hH4,
    (ArgChangeH1000.segK_side_10).hL5, (ArgChangeH1000.segK_side_10).hH5⟩
theorem horiz10 : ArgChangeGlue.HorizHyp (H1000Line.segWith 10 (E 10)) :=
  ⟨H1000Edge.T441.hAH, H1000Edge.T401.hAH⟩

theorem side11 : ArgChangeGlue.K6Side (H1000Line.segWith 11 (E 11)) :=
  ⟨(ArgChangeH1000.segK_side_11).hT0, (ArgChangeH1000.segK_side_11).hT1, (ArgChangeH1000.segK_side_11).hL1,
    (ArgChangeH1000.segK_side_11).hH1, (ArgChangeH1000.segK_side_11).hL4, (ArgChangeH1000.segK_side_11).hH4,
    (ArgChangeH1000.segK_side_11).hL5, (ArgChangeH1000.segK_side_11).hH5⟩
theorem horiz11 : ArgChangeGlue.HorizHyp (H1000Line.segWith 11 (E 11)) :=
  ⟨H1000Edge.T481.hAH, H1000Edge.T441.hAH⟩

theorem side12 : ArgChangeGlue.K6Side (H1000Line.segWith 12 (E 12)) :=
  ⟨(ArgChangeH1000.segK_side_12).hT0, (ArgChangeH1000.segK_side_12).hT1, (ArgChangeH1000.segK_side_12).hL1,
    (ArgChangeH1000.segK_side_12).hH1, (ArgChangeH1000.segK_side_12).hL4, (ArgChangeH1000.segK_side_12).hH4,
    (ArgChangeH1000.segK_side_12).hL5, (ArgChangeH1000.segK_side_12).hH5⟩
theorem horiz12 : ArgChangeGlue.HorizHyp (H1000Line.segWith 12 (E 12)) :=
  ⟨H1000Edge.T520.hAH, H1000Edge.T481.hAH⟩

theorem side13 : ArgChangeGlue.K6Side (H1000Line.segWith 13 (E 13)) :=
  ⟨(ArgChangeH1000.segK_side_13).hT0, (ArgChangeH1000.segK_side_13).hT1, (ArgChangeH1000.segK_side_13).hL1,
    (ArgChangeH1000.segK_side_13).hH1, (ArgChangeH1000.segK_side_13).hL4, (ArgChangeH1000.segK_side_13).hH4,
    (ArgChangeH1000.segK_side_13).hL5, (ArgChangeH1000.segK_side_13).hH5⟩
theorem horiz13 : ArgChangeGlue.HorizHyp (H1000Line.segWith 13 (E 13)) :=
  ⟨H1000Edge.T560.hAH, H1000Edge.T520.hAH⟩

theorem side14 : ArgChangeGlue.K6Side (H1000Line.segWith 14 (E 14)) :=
  ⟨(ArgChangeH1000.segK_side_14).hT0, (ArgChangeH1000.segK_side_14).hT1, (ArgChangeH1000.segK_side_14).hL1,
    (ArgChangeH1000.segK_side_14).hH1, (ArgChangeH1000.segK_side_14).hL4, (ArgChangeH1000.segK_side_14).hH4,
    (ArgChangeH1000.segK_side_14).hL5, (ArgChangeH1000.segK_side_14).hH5⟩
theorem horiz14 : ArgChangeGlue.HorizHyp (H1000Line.segWith 14 (E 14)) :=
  ⟨H1000Edge.T600.hAH, H1000Edge.T560.hAH⟩

theorem side15 : ArgChangeGlue.K6Side (H1000Line.segWith 15 (E 15)) :=
  ⟨(ArgChangeH1000.segK_side_15).hT0, (ArgChangeH1000.segK_side_15).hT1, (ArgChangeH1000.segK_side_15).hL1,
    (ArgChangeH1000.segK_side_15).hH1, (ArgChangeH1000.segK_side_15).hL4, (ArgChangeH1000.segK_side_15).hH4,
    (ArgChangeH1000.segK_side_15).hL5, (ArgChangeH1000.segK_side_15).hH5⟩
theorem horiz15 : ArgChangeGlue.HorizHyp (H1000Line.segWith 15 (E 15)) :=
  ⟨H1000Edge.T640.hAH, H1000Edge.T600.hAH⟩

theorem side16 : ArgChangeGlue.K6Side (H1000Line.segWith 16 (E 16)) :=
  ⟨(ArgChangeH1000.segK_side_16).hT0, (ArgChangeH1000.segK_side_16).hT1, (ArgChangeH1000.segK_side_16).hL1,
    (ArgChangeH1000.segK_side_16).hH1, (ArgChangeH1000.segK_side_16).hL4, (ArgChangeH1000.segK_side_16).hH4,
    (ArgChangeH1000.segK_side_16).hL5, (ArgChangeH1000.segK_side_16).hH5⟩
theorem horiz16 : ArgChangeGlue.HorizHyp (H1000Line.segWith 16 (E 16)) :=
  ⟨H1000Edge.T680.hAH, H1000Edge.T640.hAH⟩

theorem side17 : ArgChangeGlue.K6Side (H1000Line.segWith 17 (E 17)) :=
  ⟨(ArgChangeH1000.segK_side_17).hT0, (ArgChangeH1000.segK_side_17).hT1, (ArgChangeH1000.segK_side_17).hL1,
    (ArgChangeH1000.segK_side_17).hH1, (ArgChangeH1000.segK_side_17).hL4, (ArgChangeH1000.segK_side_17).hH4,
    (ArgChangeH1000.segK_side_17).hL5, (ArgChangeH1000.segK_side_17).hH5⟩
theorem horiz17 : ArgChangeGlue.HorizHyp (H1000Line.segWith 17 (E 17)) :=
  ⟨H1000Edge.T720.hAH, H1000Edge.T680.hAH⟩

theorem side18 : ArgChangeGlue.K6Side (H1000Line.segWith 18 (E 18)) :=
  ⟨(ArgChangeH1000.segK_side_18).hT0, (ArgChangeH1000.segK_side_18).hT1, (ArgChangeH1000.segK_side_18).hL1,
    (ArgChangeH1000.segK_side_18).hH1, (ArgChangeH1000.segK_side_18).hL4, (ArgChangeH1000.segK_side_18).hH4,
    (ArgChangeH1000.segK_side_18).hL5, (ArgChangeH1000.segK_side_18).hH5⟩
theorem horiz18 : ArgChangeGlue.HorizHyp (H1000Line.segWith 18 (E 18)) :=
  ⟨H1000Edge.T760.hAH, H1000Edge.T720.hAH⟩

theorem side19 : ArgChangeGlue.K6Side (H1000Line.segWith 19 (E 19)) :=
  ⟨(ArgChangeH1000.segK_side_19).hT0, (ArgChangeH1000.segK_side_19).hT1, (ArgChangeH1000.segK_side_19).hL1,
    (ArgChangeH1000.segK_side_19).hH1, (ArgChangeH1000.segK_side_19).hL4, (ArgChangeH1000.segK_side_19).hH4,
    (ArgChangeH1000.segK_side_19).hL5, (ArgChangeH1000.segK_side_19).hH5⟩
theorem horiz19 : ArgChangeGlue.HorizHyp (H1000Line.segWith 19 (E 19)) :=
  ⟨H1000Edge.T800.hAH, H1000Edge.T760.hAH⟩

theorem side20 : ArgChangeGlue.K6Side (H1000Line.segWith 20 (E 20)) :=
  ⟨(ArgChangeH1000.segK_side_20).hT0, (ArgChangeH1000.segK_side_20).hT1, (ArgChangeH1000.segK_side_20).hL1,
    (ArgChangeH1000.segK_side_20).hH1, (ArgChangeH1000.segK_side_20).hL4, (ArgChangeH1000.segK_side_20).hH4,
    (ArgChangeH1000.segK_side_20).hL5, (ArgChangeH1000.segK_side_20).hH5⟩
theorem horiz20 : ArgChangeGlue.HorizHyp (H1000Line.segWith 20 (E 20)) :=
  ⟨H1000Edge.T840.hAH, H1000Edge.T800.hAH⟩

theorem side21 : ArgChangeGlue.K6Side (H1000Line.segWith 21 (E 21)) :=
  ⟨(ArgChangeH1000.segK_side_21).hT0, (ArgChangeH1000.segK_side_21).hT1, (ArgChangeH1000.segK_side_21).hL1,
    (ArgChangeH1000.segK_side_21).hH1, (ArgChangeH1000.segK_side_21).hL4, (ArgChangeH1000.segK_side_21).hH4,
    (ArgChangeH1000.segK_side_21).hL5, (ArgChangeH1000.segK_side_21).hH5⟩
theorem horiz21 : ArgChangeGlue.HorizHyp (H1000Line.segWith 21 (E 21)) :=
  ⟨H1000Edge.T880.hAH, H1000Edge.T840.hAH⟩

theorem side22 : ArgChangeGlue.K6Side (H1000Line.segWith 22 (E 22)) :=
  ⟨(ArgChangeH1000.segK_side_22).hT0, (ArgChangeH1000.segK_side_22).hT1, (ArgChangeH1000.segK_side_22).hL1,
    (ArgChangeH1000.segK_side_22).hH1, (ArgChangeH1000.segK_side_22).hL4, (ArgChangeH1000.segK_side_22).hH4,
    (ArgChangeH1000.segK_side_22).hL5, (ArgChangeH1000.segK_side_22).hH5⟩
theorem horiz22 : ArgChangeGlue.HorizHyp (H1000Line.segWith 22 (E 22)) :=
  ⟨H1000Edge.T920.hAH, H1000Edge.T880.hAH⟩

theorem side23 : ArgChangeGlue.K6Side (H1000Line.segWith 23 (E 23)) :=
  ⟨(ArgChangeH1000.segK_side_23).hT0, (ArgChangeH1000.segK_side_23).hT1, (ArgChangeH1000.segK_side_23).hL1,
    (ArgChangeH1000.segK_side_23).hH1, (ArgChangeH1000.segK_side_23).hL4, (ArgChangeH1000.segK_side_23).hH4,
    (ArgChangeH1000.segK_side_23).hL5, (ArgChangeH1000.segK_side_23).hH5⟩
theorem horiz23 : ArgChangeGlue.HorizHyp (H1000Line.segWith 23 (E 23)) :=
  ⟨H1000Edge.T960.hAH, H1000Edge.T920.hAH⟩

theorem side24 : ArgChangeGlue.K6Side (H1000Line.segWith 24 (E 24)) :=
  ⟨(ArgChangeH1000.segK_side_24).hT0, (ArgChangeH1000.segK_side_24).hT1, (ArgChangeH1000.segK_side_24).hL1,
    (ArgChangeH1000.segK_side_24).hH1, (ArgChangeH1000.segK_side_24).hL4, (ArgChangeH1000.segK_side_24).hH4,
    (ArgChangeH1000.segK_side_24).hL5, (ArgChangeH1000.segK_side_24).hH5⟩
theorem horiz24 : ArgChangeGlue.HorizHyp (H1000Line.segWith 24 (E 24)) :=
  ⟨H1000Edge.T1000.hAH, H1000Edge.T960.hAH⟩

theorem henc : ∀ i, i < 25 → (H1000Line.segWith i (E i)).EnclHyp := by
  intro i hi
  interval_cases i
  · exact ArgChangeGlue.enclHyp_of_K6 side0 horiz0
  · exact ArgChangeGlue.enclHyp_of_K6 side1 horiz1
  · exact ArgChangeGlue.enclHyp_of_K6 side2 horiz2
  · exact ArgChangeGlue.enclHyp_of_K6 side3 horiz3
  · exact ArgChangeGlue.enclHyp_of_K6 side4 horiz4
  · exact ArgChangeGlue.enclHyp_of_K6 side5 horiz5
  · exact ArgChangeGlue.enclHyp_of_K6 side6 horiz6
  · exact ArgChangeGlue.enclHyp_of_K6 side7 horiz7
  · exact ArgChangeGlue.enclHyp_of_K6 side8 horiz8
  · exact ArgChangeGlue.enclHyp_of_K6 side9 horiz9
  · exact ArgChangeGlue.enclHyp_of_K6 side10 horiz10
  · exact ArgChangeGlue.enclHyp_of_K6 side11 horiz11
  · exact ArgChangeGlue.enclHyp_of_K6 side12 horiz12
  · exact ArgChangeGlue.enclHyp_of_K6 side13 horiz13
  · exact ArgChangeGlue.enclHyp_of_K6 side14 horiz14
  · exact ArgChangeGlue.enclHyp_of_K6 side15 horiz15
  · exact ArgChangeGlue.enclHyp_of_K6 side16 horiz16
  · exact ArgChangeGlue.enclHyp_of_K6 side17 horiz17
  · exact ArgChangeGlue.enclHyp_of_K6 side18 horiz18
  · exact ArgChangeGlue.enclHyp_of_K6 side19 horiz19
  · exact ArgChangeGlue.enclHyp_of_K6 side20 horiz20
  · exact ArgChangeGlue.enclHyp_of_K6 side21 horiz21
  · exact ArgChangeGlue.enclHyp_of_K6 side22 horiz22
  · exact ArgChangeGlue.enclHyp_of_K6 side23 horiz23
  · exact ArgChangeGlue.enclHyp_of_K6 side24 horiz24

theorem hslab0 : ∀ i, 1 ≤ i → i < 25 → EdgeClearGlue.SlabClear
    ((BandGlue_h1000.seg i).T0 - BandGlue_h1000.capLo i) (BandGlue_h1000.seg i).T0 := by
  intro i h1 hi
  interval_cases i
  · show EdgeClearGlue.SlabClear ((41 : ℝ) - 5773 / 100000) (41 : ℝ)
    exact H1000Slab.L41.slabClear
  · show EdgeClearGlue.SlabClear ((81 : ℝ) - 5773 / 100000) (81 : ℝ)
    exact H1000Slab.L81.slabClear
  · show EdgeClearGlue.SlabClear ((121 : ℝ) - 5773 / 100000) (121 : ℝ)
    exact H1000Slab.L121.slabClear
  · show EdgeClearGlue.SlabClear ((161 : ℝ) - 5773 / 100000) (161 : ℝ)
    exact H1000Slab.L161.slabClear
  · show EdgeClearGlue.SlabClear ((201 : ℝ) - 14343 / 250000) (201 : ℝ)
    exact H1000Slab.L201.slabClear
  · show EdgeClearGlue.SlabClear ((241 : ℝ) - 5773 / 100000) (241 : ℝ)
    exact H1000Slab.L241.slabClear
  · show EdgeClearGlue.SlabClear ((281 : ℝ) - 5773 / 100000) (281 : ℝ)
    exact H1000Slab.L281.slabClear
  · show EdgeClearGlue.SlabClear ((321 : ℝ) - 5773 / 100000) (321 : ℝ)
    exact H1000Slab.L321.slabClear
  · show EdgeClearGlue.SlabClear ((361 : ℝ) - 5773 / 100000) (361 : ℝ)
    exact H1000Slab.L361.slabClear
  · show EdgeClearGlue.SlabClear ((401 : ℝ) - 5773 / 100000) (401 : ℝ)
    exact H1000Slab.L401.slabClear
  · show EdgeClearGlue.SlabClear ((441 : ℝ) - 5773 / 100000) (441 : ℝ)
    exact H1000Slab.L441.slabClear
  · show EdgeClearGlue.SlabClear ((481 : ℝ) - 11841 / 200000) (481 : ℝ)
    exact H1000Slab.L481.slabClear
  · show EdgeClearGlue.SlabClear ((520 : ℝ) - 5773 / 100000) (520 : ℝ)
    exact H1000Slab.L520.slabClear
  · show EdgeClearGlue.SlabClear ((560 : ℝ) - 5773 / 100000) (560 : ℝ)
    exact H1000Slab.L560.slabClear
  · show EdgeClearGlue.SlabClear ((600 : ℝ) - 5773 / 100000) (600 : ℝ)
    exact H1000Slab.L600.slabClear
  · show EdgeClearGlue.SlabClear ((640 : ℝ) - 5773 / 100000) (640 : ℝ)
    exact H1000Slab.L640.slabClear
  · show EdgeClearGlue.SlabClear ((680 : ℝ) - 5773 / 100000) (680 : ℝ)
    exact H1000Slab.L680.slabClear
  · show EdgeClearGlue.SlabClear ((720 : ℝ) - 5773 / 100000) (720 : ℝ)
    exact H1000Slab.L720.slabClear
  · show EdgeClearGlue.SlabClear ((760 : ℝ) - 5773 / 100000) (760 : ℝ)
    exact H1000Slab.L760.slabClear
  · show EdgeClearGlue.SlabClear ((800 : ℝ) - 5773 / 100000) (800 : ℝ)
    exact H1000Slab.L800.slabClear
  · show EdgeClearGlue.SlabClear ((840 : ℝ) - 5773 / 100000) (840 : ℝ)
    exact H1000Slab.L840.slabClear
  · show EdgeClearGlue.SlabClear ((880 : ℝ) - 5773 / 100000) (880 : ℝ)
    exact H1000Slab.L880.slabClear
  · show EdgeClearGlue.SlabClear ((920 : ℝ) - 5773 / 100000) (920 : ℝ)
    exact H1000Slab.L920.slabClear
  · show EdgeClearGlue.SlabClear ((960 : ℝ) - 5773 / 100000) (960 : ℝ)
    exact H1000Slab.L960.slabClear

theorem hslab1 : ∀ i, i < 25 → EdgeClearGlue.SlabClear (BandGlue_h1000.seg i).T1
    ((BandGlue_h1000.seg i).T1 + BandGlue_h1000.capHi i) := by
  intro i hi
  interval_cases i
  · show EdgeClearGlue.SlabClear (41 : ℝ) ((41 : ℝ) + 5773 / 100000)
    exact H1000Slab.U41.slabClear
  · show EdgeClearGlue.SlabClear (81 : ℝ) ((81 : ℝ) + 5773 / 100000)
    exact H1000Slab.U81.slabClear
  · show EdgeClearGlue.SlabClear (121 : ℝ) ((121 : ℝ) + 5773 / 100000)
    exact H1000Slab.U121.slabClear
  · show EdgeClearGlue.SlabClear (161 : ℝ) ((161 : ℝ) + 5773 / 100000)
    exact H1000Slab.U161.slabClear
  · show EdgeClearGlue.SlabClear (201 : ℝ) ((201 : ℝ) + 5773 / 100000)
    exact H1000Slab.U201.slabClear
  · show EdgeClearGlue.SlabClear (965 / 4 : ℝ) ((965 / 4 : ℝ) + 14343 / 250000)
    exact H1000Slab.U965_4.slabClear
  · show EdgeClearGlue.SlabClear (281 : ℝ) ((281 : ℝ) + 5773 / 100000)
    exact H1000Slab.U281.slabClear
  · show EdgeClearGlue.SlabClear (321 : ℝ) ((321 : ℝ) + 5773 / 100000)
    exact H1000Slab.U321.slabClear
  · show EdgeClearGlue.SlabClear (361 : ℝ) ((361 : ℝ) + 5773 / 100000)
    exact H1000Slab.U361.slabClear
  · show EdgeClearGlue.SlabClear (401 : ℝ) ((401 : ℝ) + 5773 / 100000)
    exact H1000Slab.U401.slabClear
  · show EdgeClearGlue.SlabClear (441 : ℝ) ((441 : ℝ) + 5773 / 100000)
    exact H1000Slab.U441.slabClear
  · show EdgeClearGlue.SlabClear (481 : ℝ) ((481 : ℝ) + 5773 / 100000)
    exact H1000Slab.U481.slabClear
  · show EdgeClearGlue.SlabClear (520 : ℝ) ((520 : ℝ) + 11841 / 200000)
    exact H1000Slab.U520.slabClear
  · show EdgeClearGlue.SlabClear (560 : ℝ) ((560 : ℝ) + 5773 / 100000)
    exact H1000Slab.U560.slabClear
  · show EdgeClearGlue.SlabClear (600 : ℝ) ((600 : ℝ) + 5773 / 100000)
    exact H1000Slab.U600.slabClear
  · show EdgeClearGlue.SlabClear (640 : ℝ) ((640 : ℝ) + 5773 / 100000)
    exact H1000Slab.U640.slabClear
  · show EdgeClearGlue.SlabClear (680 : ℝ) ((680 : ℝ) + 5773 / 100000)
    exact H1000Slab.U680.slabClear
  · show EdgeClearGlue.SlabClear (720 : ℝ) ((720 : ℝ) + 5773 / 100000)
    exact H1000Slab.U720.slabClear
  · show EdgeClearGlue.SlabClear (760 : ℝ) ((760 : ℝ) + 5773 / 100000)
    exact H1000Slab.U760.slabClear
  · show EdgeClearGlue.SlabClear (800 : ℝ) ((800 : ℝ) + 5773 / 100000)
    exact H1000Slab.U800.slabClear
  · show EdgeClearGlue.SlabClear (840 : ℝ) ((840 : ℝ) + 5773 / 100000)
    exact H1000Slab.U840.slabClear
  · show EdgeClearGlue.SlabClear (880 : ℝ) ((880 : ℝ) + 5773 / 100000)
    exact H1000Slab.U880.slabClear
  · show EdgeClearGlue.SlabClear (920 : ℝ) ((920 : ℝ) + 5773 / 100000)
    exact H1000Slab.U920.slabClear
  · show EdgeClearGlue.SlabClear (960 : ℝ) ((960 : ℝ) + 5773 / 100000)
    exact H1000Slab.U960.slabClear
  · exact ArbEcon.Off.Slab_T1000.band24_top_slabClear

/-- **Every nontrivial zero of ζ with `0 < Im ρ ≤ 1000` lies on the critical line** -- kernel-checked,
    NO hypotheses (a finite verification; conjecture1_proved = False). -/
theorem all_nontrivial_zeros_up_to_height_1000 :
    ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 1000 → ρ.re = 1 / 2 :=
  H1000Line.all_nontrivial_zeros_up_to_height_1000_of_encl E hpin henc hslab0 hslab1

end AllZerosKernel_h1000
