/-  Arb4_H7000Slabs_5.lean -- lane Arb4: COMPACT kernel certificates of 2 zero-free edge-clearance slabs
    (GENERATED by ../Arb4_emit_seg.py; do not edit).  Each slab: the certificate data
    `Arb4.SlabD` (cells planned by emit_h1000_offline.plan_slab, unchanged) and ONE
    `decide +kernel` of `Arb4.slabOK` (budget, Pochhammer bound, every cell with its evaluator
    run and rectangle geometry), then `Arb4.slabOK_sound`.
    Slabs: L6962, U7000.
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import Arb4_Slab

open Arb4 Arb4.Q

namespace Arb4.H7000

/-- The slab `(0, 1) x [6961939241/1000000, 6962]` (3 cells, N = 2089). -/
noncomputable def S_L6962 : SlabD where
  tq := 14
  N := 2089
  L := (Q.frac 1529 200)
  R := (Q.frac 111 1250)
  lo := (Q.sub (Q.ofNat 6962) (Q.frac 60759 1000000))
  hi := (Q.ofNat 6962)
  U := (Q.frac 6963 1)
  Qr := 90280000000000000000000000000000000000000000000000
  r0 := 45
  FN := 17
  FD := 50
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 114064910, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) },
    { a := 3, b := 0, q := 4, tn := 114064910, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) },
    { a := 11, b := 0, q := 12, tn := 114064910, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) }].getD j { a := 11, b := 0, q := 12, tn := 114064910, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) }

theorem S_L6962_ok : slabOK S_L6962 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((6962 : ℝ) - 60759 / 1000000) (6962 : ℝ)`, hypothesis-free.** -/
theorem S_L6962_clear : EdgeClearGlue.SlabClear ((6962 : ℝ) - 60759 / 1000000) (6962 : ℝ) := by
  have h := slabOK_sound S_L6962 S_L6962_ok
  have hlo : S_L6962.lo.val = ((6962 : ℝ) - 60759 / 1000000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 6962) (Q.cv_frac 60759 1000000))
  have hhi : S_L6962.hi.val = (6962 : ℝ) := (Q.cv_nat 6962)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7000, 7000060759/1000000]` (3 cells, N = 2101). -/
noncomputable def S_U7000 : SlabD where
  tq := 14
  N := 2101
  L := (Q.frac 7651 1000)
  R := (Q.frac 111 1250)
  lo := (Q.ofNat 7000)
  hi := (Q.add (Q.ofNat 7000) (Q.frac 60759 1000000))
  U := (Q.frac 7001 1)
  Qr := 96910000000000000000000000000000000000000000000000
  r0 := 45
  FN := 341
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 114688498, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) },
    { a := 3, b := 0, q := 4, tn := 114688498, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) },
    { a := 11, b := 0, q := 12, tn := 114688498, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) }].getD j { a := 11, b := 0, q := 12, tn := 114688498, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) }

theorem S_U7000_ok : slabOK S_U7000 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7000 : ℝ) ((7000 : ℝ) + 60759 / 1000000)`, hypothesis-free.** -/
theorem S_U7000_clear : EdgeClearGlue.SlabClear (7000 : ℝ) ((7000 : ℝ) + 60759 / 1000000) := by
  have h := slabOK_sound S_U7000 S_U7000_ok
  have hlo : S_U7000.lo.val = (7000 : ℝ) := (Q.cv_nat 7000)
  have hhi : S_U7000.hi.val = ((7000 : ℝ) + 60759 / 1000000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7000) (Q.cv_frac 60759 1000000))
  rw [hlo, hhi] at h
  exact h

end Arb4.H7000
