/-  Arb4_H4000Slabs_3.lean -- lane Arb4: COMPACT kernel certificates of 10 zero-free edge-clearance slabs
    (GENERATED by ../Arb4_emit_seg.py; do not edit).  Each slab: the certificate data
    `Arb4.SlabD` (cells planned by emit_h1000_offline.plan_slab, unchanged) and ONE
    `decide +kernel` of `Arb4.slabOK` (budget, Pochhammer bound, every cell with its evaluator
    run and rectangle geometry), then `Arb4.slabOK_sound`.
    Slabs: L3600, U3640, L3640, U3680, L3680, U3720, L3720, U3760, L3760, U3800.
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import Arb4_Slab

open Arb4 Arb4.Q

namespace Arb4.H4000

/-- The slab `(0, 1) x [359994227/100000, 3600]` (3 cells, N = 1080). -/
noncomputable def S_L3600 : SlabD where
  tq := 14
  N := 1080
  L := (Q.frac 1397 200)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 3600) (Q.frac 5773 100000))
  hi := (Q.ofNat 3600)
  U := (Q.frac 3601 1)
  Qr := 17060000000000000000000000000000000000000000000
  r0 := 32
  FN := 99
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 58981927, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 58981927, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 58981927, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 58981927, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L3600_ok : slabOK S_L3600 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((3600 : ℝ) - 5773 / 100000) (3600 : ℝ)`, hypothesis-free.** -/
theorem S_L3600_clear : EdgeClearGlue.SlabClear ((3600 : ℝ) - 5773 / 100000) (3600 : ℝ) := by
  have h := slabOK_sound S_L3600 S_L3600_ok
  have hlo : S_L3600.lo.val = ((3600 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 3600) (Q.cv_frac 5773 100000))
  have hhi : S_L3600.hi.val = (3600 : ℝ) := (Q.cv_nat 3600)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [3640, 364005773/100000]` (3 cells, N = 1093). -/
noncomputable def S_U3640 : SlabD where
  tq := 14
  N := 1093
  L := (Q.frac 6997 1000)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 3640)
  hi := (Q.add (Q.ofNat 3640) (Q.frac 5773 100000))
  U := (Q.frac 3641 1)
  Qr := 19700000000000000000000000000000000000000000000
  r0 := 33
  FN := 101
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 59638233, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 59638233, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 59638233, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 59638233, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U3640_ok : slabOK S_U3640 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (3640 : ℝ) ((3640 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U3640_clear : EdgeClearGlue.SlabClear (3640 : ℝ) ((3640 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U3640 S_U3640_ok
  have hlo : S_U3640.lo.val = (3640 : ℝ) := (Q.cv_nat 3640)
  have hhi : S_U3640.hi.val = ((3640 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 3640) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [363994227/100000, 3640]` (3 cells, N = 1092). -/
noncomputable def S_L3640 : SlabD where
  tq := 14
  N := 1092
  L := (Q.frac 1749 250)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 3640) (Q.frac 5773 100000))
  hi := (Q.ofNat 3640)
  U := (Q.frac 3641 1)
  Qr := 19700000000000000000000000000000000000000000000
  r0 := 33
  FN := 101
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 59637287, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 59637287, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 59637287, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 59637287, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L3640_ok : slabOK S_L3640 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((3640 : ℝ) - 5773 / 100000) (3640 : ℝ)`, hypothesis-free.** -/
theorem S_L3640_clear : EdgeClearGlue.SlabClear ((3640 : ℝ) - 5773 / 100000) (3640 : ℝ) := by
  have h := slabOK_sound S_L3640 S_L3640_ok
  have hlo : S_L3640.lo.val = ((3640 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 3640) (Q.cv_frac 5773 100000))
  have hhi : S_L3640.hi.val = (3640 : ℝ) := (Q.cv_nat 3640)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [3680, 368005773/100000]` (3 cells, N = 1105). -/
noncomputable def S_U3680 : SlabD where
  tq := 14
  N := 1105
  L := (Q.frac 876 125)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 3680)
  hi := (Q.add (Q.ofNat 3680) (Q.frac 5773 100000))
  U := (Q.frac 3681 1)
  Qr := 22710000000000000000000000000000000000000000000
  r0 := 33
  FN := 103
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 60293593, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 60293593, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 60293593, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 60293593, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U3680_ok : slabOK S_U3680 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (3680 : ℝ) ((3680 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U3680_clear : EdgeClearGlue.SlabClear (3680 : ℝ) ((3680 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U3680 S_U3680_ok
  have hlo : S_U3680.lo.val = (3680 : ℝ) := (Q.cv_nat 3680)
  have hhi : S_U3680.hi.val = ((3680 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 3680) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [367994227/100000, 3680]` (3 cells, N = 1104). -/
noncomputable def S_L3680 : SlabD where
  tq := 14
  N := 1104
  L := (Q.frac 7007 1000)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 3680) (Q.frac 5773 100000))
  hi := (Q.ofNat 3680)
  U := (Q.frac 3681 1)
  Qr := 22710000000000000000000000000000000000000000000
  r0 := 33
  FN := 103
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 60292647, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 60292647, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 60292647, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 60292647, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L3680_ok : slabOK S_L3680 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((3680 : ℝ) - 5773 / 100000) (3680 : ℝ)`, hypothesis-free.** -/
theorem S_L3680_clear : EdgeClearGlue.SlabClear ((3680 : ℝ) - 5773 / 100000) (3680 : ℝ) := by
  have h := slabOK_sound S_L3680 S_L3680_ok
  have hlo : S_L3680.lo.val = ((3680 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 3680) (Q.cv_frac 5773 100000))
  have hhi : S_L3680.hi.val = (3680 : ℝ) := (Q.cv_nat 3680)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [3720, 372005773/100000]` (3 cells, N = 1117). -/
noncomputable def S_U3720 : SlabD where
  tq := 14
  N := 1117
  L := (Q.frac 7019 1000)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 3720)
  hi := (Q.add (Q.ofNat 3720) (Q.frac 5773 100000))
  U := (Q.frac 3721 1)
  Qr := 26140000000000000000000000000000000000000000000
  r0 := 33
  FN := 21
  FD := 200
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 60948953, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 60948953, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 60948953, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 60948953, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U3720_ok : slabOK S_U3720 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (3720 : ℝ) ((3720 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U3720_clear : EdgeClearGlue.SlabClear (3720 : ℝ) ((3720 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U3720 S_U3720_ok
  have hlo : S_U3720.lo.val = (3720 : ℝ) := (Q.cv_nat 3720)
  have hhi : S_U3720.hi.val = ((3720 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 3720) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [371994227/100000, 3720]` (3 cells, N = 1116). -/
noncomputable def S_L3720 : SlabD where
  tq := 14
  N := 1116
  L := (Q.frac 3509 500)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 3720) (Q.frac 5773 100000))
  hi := (Q.ofNat 3720)
  U := (Q.frac 3721 1)
  Qr := 26130000000000000000000000000000000000000000000
  r0 := 33
  FN := 21
  FD := 200
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 60948007, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 60948007, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 60948007, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 60948007, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L3720_ok : slabOK S_L3720 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((3720 : ℝ) - 5773 / 100000) (3720 : ℝ)`, hypothesis-free.** -/
theorem S_L3720_clear : EdgeClearGlue.SlabClear ((3720 : ℝ) - 5773 / 100000) (3720 : ℝ) := by
  have h := slabOK_sound S_L3720 S_L3720_ok
  have hlo : S_L3720.lo.val = ((3720 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 3720) (Q.cv_frac 5773 100000))
  have hhi : S_L3720.hi.val = (3720 : ℝ) := (Q.cv_nat 3720)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [3760, 376005773/100000]` (3 cells, N = 1129). -/
noncomputable def S_U3760 : SlabD where
  tq := 14
  N := 1129
  L := (Q.frac 703 100)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 3760)
  hi := (Q.add (Q.ofNat 3760) (Q.frac 5773 100000))
  U := (Q.frac 3761 1)
  Qr := 30030000000000000000000000000000000000000000000
  r0 := 33
  FN := 107
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 61604313, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 61604313, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 61604313, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 61604313, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U3760_ok : slabOK S_U3760 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (3760 : ℝ) ((3760 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U3760_clear : EdgeClearGlue.SlabClear (3760 : ℝ) ((3760 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U3760 S_U3760_ok
  have hlo : S_U3760.lo.val = (3760 : ℝ) := (Q.cv_nat 3760)
  have hhi : S_U3760.hi.val = ((3760 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 3760) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [375994227/100000, 3760]` (3 cells, N = 1128). -/
noncomputable def S_L3760 : SlabD where
  tq := 14
  N := 1128
  L := (Q.frac 7029 1000)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 3760) (Q.frac 5773 100000))
  hi := (Q.ofNat 3760)
  U := (Q.frac 3761 1)
  Qr := 30030000000000000000000000000000000000000000000
  r0 := 33
  FN := 107
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 61603367, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 61603367, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 61603367, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 61603367, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L3760_ok : slabOK S_L3760 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((3760 : ℝ) - 5773 / 100000) (3760 : ℝ)`, hypothesis-free.** -/
theorem S_L3760_clear : EdgeClearGlue.SlabClear ((3760 : ℝ) - 5773 / 100000) (3760 : ℝ) := by
  have h := slabOK_sound S_L3760 S_L3760_ok
  have hlo : S_L3760.lo.val = ((3760 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 3760) (Q.cv_frac 5773 100000))
  have hhi : S_L3760.hi.val = (3760 : ℝ) := (Q.cv_nat 3760)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [3800, 380005773/100000]` (4 cells, N = 1141). -/
noncomputable def S_U3800 : SlabD where
  tq := 14
  N := 1141
  L := (Q.frac 176 25)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 3800)
  hi := (Q.add (Q.ofNat 3800) (Q.frac 5773 100000))
  U := (Q.frac 3801 1)
  Qr := 34460000000000000000000000000000000000000000000
  r0 := 33
  FN := 109
  FD := 1000
  m := 4
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 62259673, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 5, b := 0, q := 8, tn := 62259673, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 62259673, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 62259673, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 62259673, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U3800_ok : slabOK S_U3800 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (3800 : ℝ) ((3800 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U3800_clear : EdgeClearGlue.SlabClear (3800 : ℝ) ((3800 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U3800 S_U3800_ok
  have hlo : S_U3800.lo.val = (3800 : ℝ) := (Q.cv_nat 3800)
  have hhi : S_U3800.hi.val = ((3800 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 3800) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

end Arb4.H4000
