/-  Arb4_H2000Slabs_2.lean -- lane Arb4: COMPACT kernel certificates of 10 zero-free edge-clearance slabs
    (GENERATED by ../Arb4_emit_seg.py; do not edit).  Each slab: the certificate data
    `Arb4.SlabD` (cells planned by emit_h1000_offline.plan_slab, unchanged) and ONE
    `decide +kernel` of `Arb4.slabOK` (budget, Pochhammer bound, every cell with its evaluator
    run and rectangle geometry), then `Arb4.slabOK_sound`.
    Slabs: L1400, U1440, L1440, U1480, L1480, U1520, L1520, U1560, L1560, U6401_4.
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import Arb4_Slab

open Arb4 Arb4.Q

namespace Arb4.H2000

/-- The slab `(0, 1) x [139994227/100000, 1400]` (3 cells, N = 420). -/
noncomputable def S_L1400 : SlabD where
  tq := 14
  N := 420
  L := (Q.frac 6041 1000)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 1400) (Q.frac 5773 100000))
  hi := (Q.ofNat 1400)
  U := (Q.frac 1401 1)
  Qr := 79390000000000000000000000000000000000000
  r0 := 20
  FN := 21
  FD := 1250
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 22937127, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 22937127, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 22937127, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 22937127, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L1400_ok : slabOK S_L1400 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((1400 : ℝ) - 5773 / 100000) (1400 : ℝ)`, hypothesis-free.** -/
theorem S_L1400_clear : EdgeClearGlue.SlabClear ((1400 : ℝ) - 5773 / 100000) (1400 : ℝ) := by
  have h := slabOK_sound S_L1400 S_L1400_ok
  have hlo : S_L1400.lo.val = ((1400 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 1400) (Q.cv_frac 5773 100000))
  have hhi : S_L1400.hi.val = (1400 : ℝ) := (Q.cv_nat 1400)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1440, 144005773/100000]` (3 cells, N = 433). -/
noncomputable def S_U1440 : SlabD where
  tq := 14
  N := 433
  L := (Q.frac 6071 1000)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 1440)
  hi := (Q.add (Q.ofNat 1440) (Q.frac 5773 100000))
  U := (Q.frac 1441 1)
  Qr := 114600000000000000000000000000000000000000
  r0 := 20
  FN := 89
  FD := 5000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 23593433, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 23593433, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 23593433, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 23593433, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U1440_ok : slabOK S_U1440 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (1440 : ℝ) ((1440 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U1440_clear : EdgeClearGlue.SlabClear (1440 : ℝ) ((1440 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U1440 S_U1440_ok
  have hlo : S_U1440.lo.val = (1440 : ℝ) := (Q.cv_nat 1440)
  have hhi : S_U1440.hi.val = ((1440 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 1440) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [143994227/100000, 1440]` (3 cells, N = 432). -/
noncomputable def S_L1440 : SlabD where
  tq := 14
  N := 432
  L := (Q.frac 6069 1000)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 1440) (Q.frac 5773 100000))
  hi := (Q.ofNat 1440)
  U := (Q.frac 1441 1)
  Qr := 114500000000000000000000000000000000000000
  r0 := 20
  FN := 89
  FD := 5000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 23592487, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 23592487, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 23592487, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 23592487, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L1440_ok : slabOK S_L1440 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((1440 : ℝ) - 5773 / 100000) (1440 : ℝ)`, hypothesis-free.** -/
theorem S_L1440_clear : EdgeClearGlue.SlabClear ((1440 : ℝ) - 5773 / 100000) (1440 : ℝ) := by
  have h := slabOK_sound S_L1440 S_L1440_ok
  have hlo : S_L1440.lo.val = ((1440 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 1440) (Q.cv_frac 5773 100000))
  have hhi : S_L1440.hi.val = (1440 : ℝ) := (Q.cv_nat 1440)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1480, 148005773/100000]` (3 cells, N = 445). -/
noncomputable def S_U1480 : SlabD where
  tq := 14
  N := 445
  L := (Q.frac 6099 1000)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 1480)
  hi := (Q.add (Q.ofNat 1480) (Q.frac 5773 100000))
  U := (Q.frac 1481 1)
  Qr := 163600000000000000000000000000000000000000
  r0 := 21
  FN := 187
  FD := 10000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 24248793, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 24248793, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 24248793, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 24248793, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U1480_ok : slabOK S_U1480 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (1480 : ℝ) ((1480 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U1480_clear : EdgeClearGlue.SlabClear (1480 : ℝ) ((1480 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U1480 S_U1480_ok
  have hlo : S_U1480.lo.val = (1480 : ℝ) := (Q.cv_nat 1480)
  have hhi : S_U1480.hi.val = ((1480 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 1480) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [147994227/100000, 1480]` (3 cells, N = 444). -/
noncomputable def S_L1480 : SlabD where
  tq := 14
  N := 444
  L := (Q.frac 762 125)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 1480) (Q.frac 5773 100000))
  hi := (Q.ofNat 1480)
  U := (Q.frac 1481 1)
  Qr := 163500000000000000000000000000000000000000
  r0 := 21
  FN := 187
  FD := 10000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 24247847, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 24247847, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 24247847, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 24247847, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L1480_ok : slabOK S_L1480 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((1480 : ℝ) - 5773 / 100000) (1480 : ℝ)`, hypothesis-free.** -/
theorem S_L1480_clear : EdgeClearGlue.SlabClear ((1480 : ℝ) - 5773 / 100000) (1480 : ℝ) := by
  have h := slabOK_sound S_L1480 S_L1480_ok
  have hlo : S_L1480.lo.val = ((1480 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 1480) (Q.cv_frac 5773 100000))
  have hhi : S_L1480.hi.val = (1480 : ℝ) := (Q.cv_nat 1480)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1520, 152005773/100000]` (3 cells, N = 457). -/
noncomputable def S_U1520 : SlabD where
  tq := 14
  N := 457
  L := (Q.frac 49 8)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 1520)
  hi := (Q.add (Q.ofNat 1520) (Q.frac 5773 100000))
  U := (Q.frac 1521 1)
  Qr := 231400000000000000000000000000000000000000
  r0 := 21
  FN := 197
  FD := 10000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 24904153, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 24904153, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 24904153, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 24904153, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U1520_ok : slabOK S_U1520 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (1520 : ℝ) ((1520 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U1520_clear : EdgeClearGlue.SlabClear (1520 : ℝ) ((1520 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U1520 S_U1520_ok
  have hlo : S_U1520.lo.val = (1520 : ℝ) := (Q.cv_nat 1520)
  have hhi : S_U1520.hi.val = ((1520 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 1520) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [151994227/100000, 1520]` (3 cells, N = 456). -/
noncomputable def S_L1520 : SlabD where
  tq := 14
  N := 456
  L := (Q.frac 6123 1000)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 1520) (Q.frac 5773 100000))
  hi := (Q.ofNat 1520)
  U := (Q.frac 1521 1)
  Qr := 231300000000000000000000000000000000000000
  r0 := 21
  FN := 49
  FD := 2500
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 24903207, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 24903207, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 24903207, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 24903207, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L1520_ok : slabOK S_L1520 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((1520 : ℝ) - 5773 / 100000) (1520 : ℝ)`, hypothesis-free.** -/
theorem S_L1520_clear : EdgeClearGlue.SlabClear ((1520 : ℝ) - 5773 / 100000) (1520 : ℝ) := by
  have h := slabOK_sound S_L1520 S_L1520_ok
  have hlo : S_L1520.lo.val = ((1520 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 1520) (Q.cv_frac 5773 100000))
  have hhi : S_L1520.hi.val = (1520 : ℝ) := (Q.cv_nat 1520)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1560, 156005773/100000]` (3 cells, N = 469). -/
noncomputable def S_U1560 : SlabD where
  tq := 14
  N := 469
  L := (Q.frac 6151 1000)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 1560)
  hi := (Q.add (Q.ofNat 1560) (Q.frac 5773 100000))
  U := (Q.frac 1561 1)
  Qr := 324300000000000000000000000000000000000000
  r0 := 21
  FN := 207
  FD := 10000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 25559513, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 25559513, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 25559513, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 25559513, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U1560_ok : slabOK S_U1560 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (1560 : ℝ) ((1560 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U1560_clear : EdgeClearGlue.SlabClear (1560 : ℝ) ((1560 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U1560 S_U1560_ok
  have hlo : S_U1560.lo.val = (1560 : ℝ) := (Q.cv_nat 1560)
  have hhi : S_U1560.hi.val = ((1560 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 1560) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [389985657/250000, 1560]` (3 cells, N = 468). -/
noncomputable def S_L1560 : SlabD where
  tq := 14
  N := 468
  L := (Q.frac 6149 1000)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 1560) (Q.frac 14343 250000))
  hi := (Q.ofNat 1560)
  U := (Q.frac 1561 1)
  Qr := 324200000000000000000000000000000000000000
  r0 := 21
  FN := 103
  FD := 5000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 25558570, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) },
    { a := 3, b := 0, q := 4, tn := 25558570, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) },
    { a := 11, b := 0, q := 12, tn := 25558570, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) }].getD j { a := 11, b := 0, q := 12, tn := 25558570, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) }

theorem S_L1560_ok : slabOK S_L1560 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((1560 : ℝ) - 14343 / 250000) (1560 : ℝ)`, hypothesis-free.** -/
theorem S_L1560_clear : EdgeClearGlue.SlabClear ((1560 : ℝ) - 14343 / 250000) (1560 : ℝ) := by
  have h := slabOK_sound S_L1560 S_L1560_ok
  have hlo : S_L1560.lo.val = ((1560 : ℝ) - 14343 / 250000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 1560) (Q.cv_frac 14343 250000))
  have hhi : S_L1560.hi.val = (1560 : ℝ) := (Q.cv_nat 1560)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [6401/4, 400076843/250000]` (3 cells, N = 481). -/
noncomputable def S_U6401_4 : SlabD where
  tq := 14
  N := 481
  L := (Q.frac 772 125)
  R := (Q.frac 441 5000)
  lo := (Q.frac 6401 4)
  hi := (Q.add (Q.frac 6401 4) (Q.frac 14343 250000))
  U := (Q.frac 1601 1)
  Qr := 451600000000000000000000000000000000000000
  r0 := 21
  FN := 217
  FD := 10000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 26218966, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) },
    { a := 3, b := 0, q := 4, tn := 26218966, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) },
    { a := 11, b := 0, q := 12, tn := 26218966, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) }].getD j { a := 11, b := 0, q := 12, tn := 26218966, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) }

theorem S_U6401_4_ok : slabOK S_U6401_4 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (6401 / 4 : ℝ) ((6401 / 4 : ℝ) + 14343 / 250000)`, hypothesis-free.** -/
theorem S_U6401_4_clear : EdgeClearGlue.SlabClear (6401 / 4 : ℝ) ((6401 / 4 : ℝ) + 14343 / 250000) := by
  have h := slabOK_sound S_U6401_4 S_U6401_4_ok
  have hlo : S_U6401_4.lo.val = (6401 / 4 : ℝ) := (Q.cv_frac 6401 4)
  have hhi : S_U6401_4.hi.val = ((6401 / 4 : ℝ) + 14343 / 250000) := (Q.cv_add _ _ _ _ (Q.cv_frac 6401 4) (Q.cv_frac 14343 250000))
  rw [hlo, hhi] at h
  exact h

end Arb4.H2000
