/-  Arb4_H6000Slabs_3.lean -- lane Arb4: COMPACT kernel certificates of 10 zero-free edge-clearance slabs
    (GENERATED by ../Arb4_emit_seg.py; do not edit).  Each slab: the certificate data
    `Arb4.SlabD` (cells planned by emit_h1000_offline.plan_slab, unchanged) and ONE
    `decide +kernel` of `Arb4.slabOK` (budget, Pochhammer bound, every cell with its evaluator
    run and rectangle geometry), then `Arb4.slabOK_sound`.
    Slabs: L5600, U5640, L5640, U5680, L5680, U5720, L5720, U5760, L5760, U23201_4.
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import Arb4_Slab

open Arb4 Arb4.Q

namespace Arb4.H6000

/-- The slab `(0, 1) x [559994227/100000, 5600]` (4 cells, N = 1680). -/
noncomputable def S_L5600 : SlabD where
  tq := 14
  N := 1680
  L := (Q.frac 7427 1000)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 5600) (Q.frac 5773 100000))
  hi := (Q.ofNat 5600)
  U := (Q.frac 5601 1)
  Qr := 5327000000000000000000000000000000000000000000000
  r0 := 40
  FN := 11
  FD := 50
  m := 4
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 91749927, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 5, b := 0, q := 8, tn := 91749927, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 91749927, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 91749927, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 91749927, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L5600_ok : slabOK S_L5600 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((5600 : ℝ) - 5773 / 100000) (5600 : ℝ)`, hypothesis-free.** -/
theorem S_L5600_clear : EdgeClearGlue.SlabClear ((5600 : ℝ) - 5773 / 100000) (5600 : ℝ) := by
  have h := slabOK_sound S_L5600 S_L5600_ok
  have hlo : S_L5600.lo.val = ((5600 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 5600) (Q.cv_frac 5773 100000))
  have hhi : S_L5600.hi.val = (5600 : ℝ) := (Q.cv_nat 5600)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [5640, 564005773/100000]` (6 cells, N = 1693). -/
noncomputable def S_U5640 : SlabD where
  tq := 14
  N := 1693
  L := (Q.frac 1487 200)
  R := (Q.frac 507 10000)
  lo := (Q.ofNat 5640)
  hi := (Q.add (Q.ofNat 5640) (Q.frac 5773 100000))
  U := (Q.frac 5641 1)
  Qr := 5844000000000000000000000000000000000000000000000
  r0 := 41
  FN := 49
  FD := 5000
  m := 6
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 3 4), (Q.frac 5 6), (Q.frac 11 12), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 92406233, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 5, b := 0, q := 8, tn := 92406233, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 17, b := 0, q := 24, tn := 92406233, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 19, b := 0, q := 24, tn := 92406233, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 7, b := 0, q := 8, tn := 92406233, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 23, b := 0, q := 24, tn := 92406233, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) }].getD j { a := 23, b := 0, q := 24, tn := 92406233, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) }

theorem S_U5640_ok : slabOK S_U5640 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (5640 : ℝ) ((5640 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U5640_clear : EdgeClearGlue.SlabClear (5640 : ℝ) ((5640 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U5640 S_U5640_ok
  have hlo : S_U5640.lo.val = (5640 : ℝ) := (Q.cv_nat 5640)
  have hhi : S_U5640.hi.val = ((5640 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 5640) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [563994227/100000, 5640]` (4 cells, N = 1692). -/
noncomputable def S_L5640 : SlabD where
  tq := 14
  N := 1692
  L := (Q.frac 3717 500)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 5640) (Q.frac 5773 100000))
  hi := (Q.ofNat 5640)
  U := (Q.frac 5641 1)
  Qr := 5843000000000000000000000000000000000000000000000
  r0 := 41
  FN := 111
  FD := 500
  m := 4
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 92405287, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 5, b := 0, q := 8, tn := 92405287, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 92405287, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 92405287, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 92405287, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L5640_ok : slabOK S_L5640 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((5640 : ℝ) - 5773 / 100000) (5640 : ℝ)`, hypothesis-free.** -/
theorem S_L5640_clear : EdgeClearGlue.SlabClear ((5640 : ℝ) - 5773 / 100000) (5640 : ℝ) := by
  have h := slabOK_sound S_L5640 S_L5640_ok
  have hlo : S_L5640.lo.val = ((5640 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 5640) (Q.cv_frac 5773 100000))
  have hhi : S_L5640.hi.val = (5640 : ℝ) := (Q.cv_nat 5640)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [5680, 568005773/100000]` (3 cells, N = 1705). -/
noncomputable def S_U5680 : SlabD where
  tq := 14
  N := 1705
  L := (Q.frac 3721 500)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 5680)
  hi := (Q.add (Q.ofNat 5680) (Q.frac 5773 100000))
  U := (Q.frac 5681 1)
  Qr := 6407000000000000000000000000000000000000000000000
  r0 := 41
  FN := 9
  FD := 40
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 93061593, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 93061593, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 93061593, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 93061593, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U5680_ok : slabOK S_U5680 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (5680 : ℝ) ((5680 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U5680_clear : EdgeClearGlue.SlabClear (5680 : ℝ) ((5680 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U5680 S_U5680_ok
  have hlo : S_U5680.lo.val = (5680 : ℝ) := (Q.cv_nat 5680)
  have hhi : S_U5680.hi.val = ((5680 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 5680) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [567994227/100000, 5680]` (3 cells, N = 1704). -/
noncomputable def S_L5680 : SlabD where
  tq := 14
  N := 1704
  L := (Q.frac 7441 1000)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 5680) (Q.frac 5773 100000))
  hi := (Q.ofNat 5680)
  U := (Q.frac 5681 1)
  Qr := 6406000000000000000000000000000000000000000000000
  r0 := 41
  FN := 9
  FD := 40
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 93060647, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 93060647, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 93060647, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 93060647, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L5680_ok : slabOK S_L5680 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((5680 : ℝ) - 5773 / 100000) (5680 : ℝ)`, hypothesis-free.** -/
theorem S_L5680_clear : EdgeClearGlue.SlabClear ((5680 : ℝ) - 5773 / 100000) (5680 : ℝ) := by
  have h := slabOK_sound S_L5680 S_L5680_ok
  have hlo : S_L5680.lo.val = ((5680 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 5680) (Q.cv_frac 5773 100000))
  have hhi : S_L5680.hi.val = (5680 : ℝ) := (Q.cv_nat 5680)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [5720, 572005773/100000]` (3 cells, N = 1717). -/
noncomputable def S_U5720 : SlabD where
  tq := 14
  N := 1717
  L := (Q.frac 7449 1000)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 5720)
  hi := (Q.add (Q.ofNat 5720) (Q.frac 5773 100000))
  U := (Q.frac 5721 1)
  Qr := 7018000000000000000000000000000000000000000000000
  r0 := 41
  FN := 23
  FD := 100
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 93716953, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 93716953, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 93716953, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 93716953, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U5720_ok : slabOK S_U5720 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (5720 : ℝ) ((5720 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U5720_clear : EdgeClearGlue.SlabClear (5720 : ℝ) ((5720 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U5720 S_U5720_ok
  have hlo : S_U5720.lo.val = (5720 : ℝ) := (Q.cv_nat 5720)
  have hhi : S_U5720.hi.val = ((5720 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 5720) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [571994227/100000, 5720]` (3 cells, N = 1716). -/
noncomputable def S_L5720 : SlabD where
  tq := 14
  N := 1716
  L := (Q.frac 931 125)
  R := (Q.frac 441 5000)
  lo := (Q.sub (Q.ofNat 5720) (Q.frac 5773 100000))
  hi := (Q.ofNat 5720)
  U := (Q.frac 5721 1)
  Qr := 7018000000000000000000000000000000000000000000000
  r0 := 41
  FN := 57
  FD := 250
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 93716007, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 93716007, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 93716007, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 93716007, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_L5720_ok : slabOK S_L5720 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((5720 : ℝ) - 5773 / 100000) (5720 : ℝ)`, hypothesis-free.** -/
theorem S_L5720_clear : EdgeClearGlue.SlabClear ((5720 : ℝ) - 5773 / 100000) (5720 : ℝ) := by
  have h := slabOK_sound S_L5720 S_L5720_ok
  have hlo : S_L5720.lo.val = ((5720 : ℝ) - 5773 / 100000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 5720) (Q.cv_frac 5773 100000))
  have hhi : S_L5720.hi.val = (5720 : ℝ) := (Q.cv_nat 5720)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [5760, 576005773/100000]` (4 cells, N = 1729). -/
noncomputable def S_U5760 : SlabD where
  tq := 14
  N := 1729
  L := (Q.frac 932 125)
  R := (Q.frac 441 5000)
  lo := (Q.ofNat 5760)
  hi := (Q.add (Q.ofNat 5760) (Q.frac 5773 100000))
  U := (Q.frac 5761 1)
  Qr := 7684000000000000000000000000000000000000000000000
  r0 := 41
  FN := 231
  FD := 1000
  m := 4
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 94372313, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 5, b := 0, q := 8, tn := 94372313, rn := 507, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 473 16384) },
    { a := 3, b := 0, q := 4, tn := 94372313, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) },
    { a := 11, b := 0, q := 12, tn := 94372313, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }].getD j { a := 11, b := 0, q := 12, tn := 94372313, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 473 16384) }

theorem S_U5760_ok : slabOK S_U5760 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (5760 : ℝ) ((5760 : ℝ) + 5773 / 100000)`, hypothesis-free.** -/
theorem S_U5760_clear : EdgeClearGlue.SlabClear (5760 : ℝ) ((5760 : ℝ) + 5773 / 100000) := by
  have h := slabOK_sound S_U5760 S_U5760_ok
  have hlo : S_U5760.lo.val = (5760 : ℝ) := (Q.cv_nat 5760)
  have hhi : S_U5760.hi.val = ((5760 : ℝ) + 5773 / 100000) := (Q.cv_add _ _ _ _ (Q.cv_nat 5760) (Q.cv_frac 5773 100000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1439985657/250000, 5760]` (6 cells, N = 1728). -/
noncomputable def S_L5760 : SlabD where
  tq := 14
  N := 1728
  L := (Q.frac 1491 200)
  R := (Q.frac 253 5000)
  lo := (Q.sub (Q.ofNat 5760) (Q.frac 14343 250000))
  hi := (Q.ofNat 5760)
  U := (Q.frac 5761 1)
  Qr := 7683000000000000000000000000000000000000000000000
  r0 := 41
  FN := 1
  FD := 100
  m := 6
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 3 4), (Q.frac 5 6), (Q.frac 11 12), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 94371370, rn := 506, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 235 8192) },
    { a := 5, b := 0, q := 8, tn := 94371370, rn := 506, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 235 8192) },
    { a := 17, b := 0, q := 24, tn := 94371370, rn := 506, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 235 8192) },
    { a := 19, b := 0, q := 24, tn := 94371370, rn := 506, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 235 8192) },
    { a := 7, b := 0, q := 8, tn := 94371370, rn := 506, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 235 8192) },
    { a := 23, b := 0, q := 24, tn := 94371370, rn := 506, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 235 8192) }].getD j { a := 23, b := 0, q := 24, tn := 94371370, rn := 506, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 235 8192) }

theorem S_L5760_ok : slabOK S_L5760 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((5760 : ℝ) - 14343 / 250000) (5760 : ℝ)`, hypothesis-free.** -/
theorem S_L5760_clear : EdgeClearGlue.SlabClear ((5760 : ℝ) - 14343 / 250000) (5760 : ℝ) := by
  have h := slabOK_sound S_L5760 S_L5760_ok
  have hlo : S_L5760.lo.val = ((5760 : ℝ) - 14343 / 250000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 5760) (Q.cv_frac 14343 250000))
  have hhi : S_L5760.hi.val = (5760 : ℝ) := (Q.cv_nat 5760)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [23201/4, 1450076843/250000]` (3 cells, N = 1741). -/
noncomputable def S_U23201_4 : SlabD where
  tq := 14
  N := 1741
  L := (Q.frac 7463 1000)
  R := (Q.frac 441 5000)
  lo := (Q.frac 23201 4)
  hi := (Q.add (Q.frac 23201 4) (Q.frac 14343 250000))
  U := (Q.frac 5801 1)
  Qr := 8412000000000000000000000000000000000000000000000
  r0 := 41
  FN := 117
  FD := 500
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 95031766, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) },
    { a := 3, b := 0, q := 4, tn := 95031766, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) },
    { a := 11, b := 0, q := 12, tn := 95031766, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) }].getD j { a := 11, b := 0, q := 12, tn := 95031766, rn := 882, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 235 8192) }

theorem S_U23201_4_ok : slabOK S_U23201_4 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (23201 / 4 : ℝ) ((23201 / 4 : ℝ) + 14343 / 250000)`, hypothesis-free.** -/
theorem S_U23201_4_clear : EdgeClearGlue.SlabClear (23201 / 4 : ℝ) ((23201 / 4 : ℝ) + 14343 / 250000) := by
  have h := slabOK_sound S_U23201_4 S_U23201_4_ok
  have hlo : S_U23201_4.lo.val = (23201 / 4 : ℝ) := (Q.cv_frac 23201 4)
  have hhi : S_U23201_4.hi.val = ((23201 / 4 : ℝ) + 14343 / 250000) := (Q.cv_add _ _ _ _ (Q.cv_frac 23201 4) (Q.cv_frac 14343 250000))
  rw [hlo, hhi] at h
  exact h

end Arb4.H6000
