/-  Arb4_H8000Slabs_0.lean -- lane Arb4: COMPACT kernel certificates of 10 zero-free edge-clearance slabs
    (GENERATED by ../Arb4_emit_seg.py; do not edit).  Each slab: the certificate data
    `Arb4.SlabD` (cells planned by emit_h1000_offline.plan_slab, unchanged) and ONE
    `decide +kernel` of `Arb4.slabOK` (budget, Pochhammer bound, every cell with its evaluator
    run and rectangle geometry), then `Arb4.slabOK_sound`.
    Slabs: L7000, U7037, L7037, U7074, L7074, U7111, L7111, U7148, L7148, U7185.
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import Arb4_Slab

open Arb4 Arb4.Q

namespace Arb4.H8000

/-- The slab `(0, 1) x [1399987521/200000, 7000]` (3 cells, N = 2100). -/
noncomputable def S_L7000 : SlabD where
  tq := 14
  N := 2100
  L := (Q.frac 153 20)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7000) (Q.frac 12479 200000))
  hi := (Q.ofNat 7000)
  U := (Q.frac 7001 1)
  Qr := 96890000000000000000000000000000000000000000000000
  r0 := 45
  FN := 69
  FD := 200
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 114687489, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 114687489, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 114687489, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 114687489, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7000_ok : slabOK S_L7000 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7000 : ℝ) - 12479 / 200000) (7000 : ℝ)`, hypothesis-free.** -/
theorem S_L7000_clear : EdgeClearGlue.SlabClear ((7000 : ℝ) - 12479 / 200000) (7000 : ℝ) := by
  have h := slabOK_sound S_L7000 S_L7000_ok
  have hlo : S_L7000.lo.val = ((7000 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7000) (Q.cv_frac 12479 200000))
  have hhi : S_L7000.hi.val = (7000 : ℝ) := (Q.cv_nat 7000)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7037, 1407412479/200000]` (10 cells, N = 2112). -/
noncomputable def S_U7037 : SlabD where
  tq := 14
  N := 2112
  L := (Q.frac 957 125)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7037)
  hi := (Q.add (Q.ofNat 7037) (Q.frac 12479 200000))
  U := (Q.frac 7038 1)
  Qr := 103800000000000000000000000000000000000000000000000
  r0 := 45
  FN := 7
  FD := 20
  m := 10
  xs := fun j => [(Q.frac 1 2), (Q.frac 13 24), (Q.frac 7 12), (Q.frac 5 8), (Q.frac 31 48), (Q.frac 2 3), (Q.frac 11 16), (Q.frac 17 24), (Q.frac 3 4), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 25, b := 0, q := 48, tn := 115294719, rn := 376, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 1597749 51200000) },
    { a := 9, b := 0, q := 16, tn := 115294719, rn := 376, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 1597749 51200000) },
    { a := 29, b := 0, q := 48, tn := 115294719, rn := 376, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 1597749 51200000) },
    { a := 61, b := 0, q := 96, tn := 115294719, rn := 329, rd := 10000, w := (Q.frac 1 96), hh := (Q.frac 1597749 51200000) },
    { a := 21, b := 0, q := 32, tn := 115294719, rn := 329, rd := 10000, w := (Q.frac 1 96), hh := (Q.frac 1597749 51200000) },
    { a := 65, b := 0, q := 96, tn := 115294719, rn := 329, rd := 10000, w := (Q.frac 1 96), hh := (Q.frac 1597749 51200000) },
    { a := 67, b := 0, q := 96, tn := 115294719, rn := 329, rd := 10000, w := (Q.frac 1 96), hh := (Q.frac 1597749 51200000) },
    { a := 35, b := 0, q := 48, tn := 115294719, rn := 376, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 1597749 51200000) },
    { a := 19, b := 0, q := 24, tn := 115294719, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 115294719, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 115294719, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7037_ok : slabOK S_U7037 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7037 : ℝ) ((7037 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7037_clear : EdgeClearGlue.SlabClear (7037 : ℝ) ((7037 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7037 S_U7037_ok
  have hlo : S_U7037.lo.val = (7037 : ℝ) := (Q.cv_nat 7037)
  have hhi : S_U7037.hi.val = ((7037 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7037) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1407387521/200000, 7037]` (4 cells, N = 2112). -/
noncomputable def S_L7037 : SlabD where
  tq := 14
  N := 2112
  L := (Q.frac 957 125)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7037) (Q.frac 12479 200000))
  hi := (Q.ofNat 7037)
  U := (Q.frac 7038 1)
  Qr := 103800000000000000000000000000000000000000000000000
  r0 := 45
  FN := 7
  FD := 20
  m := 4
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 115293697, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 5, b := 0, q := 8, tn := 115293697, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 115293697, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 115293697, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 115293697, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7037_ok : slabOK S_L7037 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7037 : ℝ) - 12479 / 200000) (7037 : ℝ)`, hypothesis-free.** -/
theorem S_L7037_clear : EdgeClearGlue.SlabClear ((7037 : ℝ) - 12479 / 200000) (7037 : ℝ) := by
  have h := slabOK_sound S_L7037 S_L7037_ok
  have hlo : S_L7037.lo.val = ((7037 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7037) (Q.cv_frac 12479 200000))
  have hhi : S_L7037.hi.val = (7037 : ℝ) := (Q.cv_nat 7037)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7074, 1414812479/200000]` (3 cells, N = 2123). -/
noncomputable def S_U7074 : SlabD where
  tq := 14
  N := 2123
  L := (Q.frac 7661 1000)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7074)
  hi := (Q.add (Q.ofNat 7074) (Q.frac 12479 200000))
  U := (Q.frac 7075 1)
  Qr := 111100000000000000000000000000000000000000000000000
  r0 := 46
  FN := 44
  FD := 125
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 115900927, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 115900927, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 115900927, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 115900927, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7074_ok : slabOK S_U7074 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7074 : ℝ) ((7074 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7074_clear : EdgeClearGlue.SlabClear (7074 : ℝ) ((7074 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7074 S_U7074_ok
  have hlo : S_U7074.lo.val = (7074 : ℝ) := (Q.cv_nat 7074)
  have hhi : S_U7074.hi.val = ((7074 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7074) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1414787521/200000, 7074]` (3 cells, N = 2123). -/
noncomputable def S_L7074 : SlabD where
  tq := 14
  N := 2123
  L := (Q.frac 7661 1000)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7074) (Q.frac 12479 200000))
  hi := (Q.ofNat 7074)
  U := (Q.frac 7075 1)
  Qr := 111100000000000000000000000000000000000000000000000
  r0 := 46
  FN := 44
  FD := 125
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 115899905, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 115899905, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 115899905, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 115899905, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7074_ok : slabOK S_L7074 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7074 : ℝ) - 12479 / 200000) (7074 : ℝ)`, hypothesis-free.** -/
theorem S_L7074_clear : EdgeClearGlue.SlabClear ((7074 : ℝ) - 12479 / 200000) (7074 : ℝ) := by
  have h := slabOK_sound S_L7074 S_L7074_ok
  have hlo : S_L7074.lo.val = ((7074 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7074) (Q.cv_frac 12479 200000))
  have hhi : S_L7074.hi.val = (7074 : ℝ) := (Q.cv_nat 7074)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7111, 1422212479/200000]` (6 cells, N = 2134). -/
noncomputable def S_U7111 : SlabD where
  tq := 14
  N := 2134
  L := (Q.frac 3833 500)
  R := (Q.frac 521 10000)
  lo := (Q.ofNat 7111)
  hi := (Q.add (Q.ofNat 7111) (Q.frac 12479 200000))
  U := (Q.frac 7112 1)
  Qr := 118900000000000000000000000000000000000000000000000
  r0 := 46
  FN := 81
  FD := 5000
  m := 6
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 3 4), (Q.frac 5 6), (Q.frac 11 12), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 116507135, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 5, b := 0, q := 8, tn := 116507135, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 17, b := 0, q := 24, tn := 116507135, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 19, b := 0, q := 24, tn := 116507135, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 7, b := 0, q := 8, tn := 116507135, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 23, b := 0, q := 24, tn := 116507135, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) }].getD j { a := 23, b := 0, q := 24, tn := 116507135, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) }

theorem S_U7111_ok : slabOK S_U7111 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7111 : ℝ) ((7111 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7111_clear : EdgeClearGlue.SlabClear (7111 : ℝ) ((7111 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7111 S_U7111_ok
  have hlo : S_U7111.lo.val = (7111 : ℝ) := (Q.cv_nat 7111)
  have hhi : S_U7111.hi.val = ((7111 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7111) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1422187521/200000, 7111]` (6 cells, N = 2134). -/
noncomputable def S_L7111 : SlabD where
  tq := 14
  N := 2134
  L := (Q.frac 3833 500)
  R := (Q.frac 521 10000)
  lo := (Q.sub (Q.ofNat 7111) (Q.frac 12479 200000))
  hi := (Q.ofNat 7111)
  U := (Q.frac 7112 1)
  Qr := 118900000000000000000000000000000000000000000000000
  r0 := 46
  FN := 81
  FD := 5000
  m := 6
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 3 4), (Q.frac 5 6), (Q.frac 11 12), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 116506113, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 5, b := 0, q := 8, tn := 116506113, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 17, b := 0, q := 24, tn := 116506113, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 19, b := 0, q := 24, tn := 116506113, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 7, b := 0, q := 8, tn := 116506113, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 23, b := 0, q := 24, tn := 116506113, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) }].getD j { a := 23, b := 0, q := 24, tn := 116506113, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) }

theorem S_L7111_ok : slabOK S_L7111 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7111 : ℝ) - 12479 / 200000) (7111 : ℝ)`, hypothesis-free.** -/
theorem S_L7111_clear : EdgeClearGlue.SlabClear ((7111 : ℝ) - 12479 / 200000) (7111 : ℝ) := by
  have h := slabOK_sound S_L7111 S_L7111_ok
  have hlo : S_L7111.lo.val = ((7111 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7111) (Q.cv_frac 12479 200000))
  have hhi : S_L7111.hi.val = (7111 : ℝ) := (Q.cv_nat 7111)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7148, 1429612479/200000]` (3 cells, N = 2145). -/
noncomputable def S_U7148 : SlabD where
  tq := 14
  N := 2145
  L := (Q.frac 7671 1000)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7148)
  hi := (Q.add (Q.ofNat 7148) (Q.frac 12479 200000))
  U := (Q.frac 7149 1)
  Qr := 127200000000000000000000000000000000000000000000000
  r0 := 46
  FN := 9
  FD := 25
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 117113343, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 117113343, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 117113343, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 117113343, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7148_ok : slabOK S_U7148 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7148 : ℝ) ((7148 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7148_clear : EdgeClearGlue.SlabClear (7148 : ℝ) ((7148 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7148 S_U7148_ok
  have hlo : S_U7148.lo.val = (7148 : ℝ) := (Q.cv_nat 7148)
  have hhi : S_U7148.hi.val = ((7148 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7148) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1429587521/200000, 7148]` (3 cells, N = 2145). -/
noncomputable def S_L7148 : SlabD where
  tq := 14
  N := 2145
  L := (Q.frac 7671 1000)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7148) (Q.frac 12479 200000))
  hi := (Q.ofNat 7148)
  U := (Q.frac 7149 1)
  Qr := 127200000000000000000000000000000000000000000000000
  r0 := 46
  FN := 9
  FD := 25
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 117112321, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 117112321, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 117112321, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 117112321, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7148_ok : slabOK S_L7148 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7148 : ℝ) - 12479 / 200000) (7148 : ℝ)`, hypothesis-free.** -/
theorem S_L7148_clear : EdgeClearGlue.SlabClear ((7148 : ℝ) - 12479 / 200000) (7148 : ℝ) := by
  have h := slabOK_sound S_L7148 S_L7148_ok
  have hlo : S_L7148.lo.val = ((7148 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7148) (Q.cv_frac 12479 200000))
  have hhi : S_L7148.hi.val = (7148 : ℝ) := (Q.cv_nat 7148)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7185, 1437012479/200000]` (3 cells, N = 2156). -/
noncomputable def S_U7185 : SlabD where
  tq := 14
  N := 2156
  L := (Q.frac 7677 1000)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7185)
  hi := (Q.add (Q.ofNat 7185) (Q.frac 12479 200000))
  U := (Q.frac 7186 1)
  Qr := 136100000000000000000000000000000000000000000000000
  r0 := 46
  FN := 181
  FD := 500
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 117719551, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 117719551, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 117719551, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 117719551, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7185_ok : slabOK S_U7185 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7185 : ℝ) ((7185 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7185_clear : EdgeClearGlue.SlabClear (7185 : ℝ) ((7185 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7185 S_U7185_ok
  have hlo : S_U7185.lo.val = (7185 : ℝ) := (Q.cv_nat 7185)
  have hhi : S_U7185.hi.val = ((7185 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7185) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

end Arb4.H8000
