/-  Arb4_h4000.lean -- lane Arb4: the height-4000 ladder statement, HYPOTHESIS-FREE, from COMPACT
    certificates (GENERATED by ../Arb4_emit_seg.py; do not edit).

        all_nontrivial_zeros_up_to_height_4000 :
          ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 4000 → ρ.re = 1 / 2

    Every input of the 25 Turing bands of `Arb4.BandGlue_h4000.seg` (the band plan of `AllZeros_h4000`) is
    discharged in the kernel by ONE Boolean checker per certificate (lane Arb4):
      * hLine: `Arb4.bandC` per band (`ptCheckC` chunks + `bandOk`; modules Arb4_H4000Lines_*);
      * the edge-clearance slabs: `Arb4.slabOK` (Arb4_H4000Slabs_*);
      * the horizontal argument changes: `Arb4.edgeOK` (Arb4_H4000Edges_*; the edge at 3000 is Arb4_H3000Edges);
      * K6a (`[-249/250, 249/250]`), K6b (`Arb4.k6B`: S2 / Sm1 brackets), the ball cover and the
        pins of `Valid`: ONE `decide +kernel` of `Arb4.validB && Arb4.k6sideB` per band;
      * hnzl, hnzb, hnzt, hins: K1 (`BandGlue.BandData.inputs_of_reduced`); hγ: `HeightFloor`.
    Composition: `Arb4.boxCert_of_parts` per band, then `AllZerosUpToHeight.height_chain (Arb4_h3000 + AllZeros_h4000.segment_3000_4000)`.
    Axioms [propext, Classical.choice, Quot.sound] (Arb4_AxiomGuard_h4000); no `sorry`.
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import Arb4_Seg
import Arb4_BandGlue_h4000
import HeightFloor
import H1000Glue
import Arb4_h3000
import Arb4_H4000Edges_0
import Arb4_H4000Edges_1
import Arb4_H4000Edges_2
import Arb4_H4000Edges_3
import Arb4_H4000Edges_4
import Arb4_H4000Edges_5
import Arb4_H4000Slabs_0
import Arb4_H4000Slabs_1
import Arb4_H4000Slabs_2
import Arb4_H4000Slabs_3
import Arb4_H4000Slabs_4
import Arb4_H4000Lines_0
import Arb4_H4000Lines_1
import Arb4_H4000Lines_2
import Arb4_H4000Lines_3
import Arb4_H4000Lines_4

open Complex Arb4 Arb4.Q

namespace Arb4_h4000

/-! ## The K6b certificates at the band edges -/

noncomputable def G_T3000 : GamD := ⟨(Q.ofNat 3000), 22, 39, 22, 39, 1, 2, 1, 2⟩
noncomputable def G_T3040 : GamD := ⟨(Q.ofNat 3040), 22, 38, 22, 38, 1, 2, 1, 2⟩
noncomputable def G_T3080 : GamD := ⟨(Q.ofNat 3080), 22, 36, 22, 36, 1, 2, 1, 2⟩
noncomputable def G_T12479_4 : GamD := ⟨(Q.frac 12479 4), 22, 35, 22, 35, 1, 2, 1, 2⟩
noncomputable def G_T3120 : GamD := ⟨(Q.ofNat 3120), 22, 35, 22, 35, 1, 2, 1, 2⟩
noncomputable def G_T3160 : GamD := ⟨(Q.ofNat 3160), 22, 33, 22, 33, 1, 2, 1, 2⟩
noncomputable def G_T3200 : GamD := ⟨(Q.ofNat 3200), 22, 32, 22, 32, 1, 2, 1, 2⟩
noncomputable def G_T3240 : GamD := ⟨(Q.ofNat 3240), 22, 30, 22, 30, 1, 2, 1, 2⟩
noncomputable def G_T3280 : GamD := ⟨(Q.ofNat 3280), 22, 29, 22, 29, 1, 2, 1, 2⟩
noncomputable def G_T3320 : GamD := ⟨(Q.ofNat 3320), 22, 28, 22, 28, 1, 2, 1, 2⟩
noncomputable def G_T3360 : GamD := ⟨(Q.ofNat 3360), 22, 27, 22, 27, 1, 2, 1, 2⟩
noncomputable def G_T3400 : GamD := ⟨(Q.ofNat 3400), 22, 25, 22, 25, 1, 2, 1, 2⟩
noncomputable def G_T3440 : GamD := ⟨(Q.ofNat 3440), 22, 24, 22, 24, 1, 2, 1, 2⟩
noncomputable def G_T3480 : GamD := ⟨(Q.ofNat 3480), 22, 23, 22, 23, 1, 2, 1, 2⟩
noncomputable def G_T3520 : GamD := ⟨(Q.ofNat 3520), 22, 22, 22, 22, 1, 2, 1, 2⟩
noncomputable def G_T3560 : GamD := ⟨(Q.ofNat 3560), 22, 21, 22, 21, 1, 2, 1, 2⟩
noncomputable def G_T14241_4 : GamD := ⟨(Q.frac 14241 4), 22, 21, 22, 21, 1, 2, 1, 2⟩
noncomputable def G_T3600 : GamD := ⟨(Q.ofNat 3600), 22, 20, 22, 20, 1, 2, 1, 2⟩
noncomputable def G_T3640 : GamD := ⟨(Q.ofNat 3640), 22, 19, 22, 19, 1, 2, 1, 2⟩
noncomputable def G_T3680 : GamD := ⟨(Q.ofNat 3680), 22, 18, 22, 18, 1, 2, 1, 2⟩
noncomputable def G_T3720 : GamD := ⟨(Q.ofNat 3720), 22, 17, 22, 17, 1, 2, 1, 2⟩
noncomputable def G_T3760 : GamD := ⟨(Q.ofNat 3760), 22, 16, 22, 16, 1, 2, 1, 2⟩
noncomputable def G_T3800 : GamD := ⟨(Q.ofNat 3800), 22, 15, 22, 15, 1, 2, 1, 2⟩
noncomputable def G_T15359_4 : GamD := ⟨(Q.frac 15359 4), 22, 14, 22, 14, 1, 2, 1, 2⟩
noncomputable def G_T3840 : GamD := ⟨(Q.ofNat 3840), 22, 14, 22, 14, 1, 2, 1, 2⟩
noncomputable def G_T3880 : GamD := ⟨(Q.ofNat 3880), 22, 13, 22, 13, 1, 2, 1, 2⟩
noncomputable def G_T3920 : GamD := ⟨(Q.ofNat 3920), 22, 12, 22, 12, 1, 2, 1, 2⟩
noncomputable def G_T3960 : GamD := ⟨(Q.ofNat 3960), 22, 10, 22, 10, 1, 2, 1, 2⟩
noncomputable def G_T15841_4 : GamD := ⟨(Q.frac 15841 4), 22, 10, 22, 10, 1, 2, 1, 2⟩
noncomputable def G_T16001_4 : GamD := ⟨(Q.frac 16001 4), 22, 9, 22, 9, 1, 2, 1, 2⟩

/-! ### Band 0: `[3000, 3040]`, 39 zeros -/

/-- The five enclosures of band 0: K6a, the edges at 3040 and 3000, K6b. -/
noncomputable def E0 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3040.Lo, Arb4.H4000.E_T3040.Hi, Arb4.H3000.E_T3000.Lo, Arb4.H3000.E_T3000.Hi,
  (Q.frac 247004787 2000000), (Q.frac 61751362321 500000000), (Q.frac 12350239021 100000000), (Q.frac 15437840169 125000000)⟩

theorem chk0 : (validB (Q.ofNat 3000) (Q.ofNat 3040) (Q.ofNat 3020) (Q.frac 6437 16) 39 E0 && k6sideB G_T3000 G_T3040 E0) = true := by decide +kernel

theorem box0 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 0) (AllZeros_h4000.bHi 0) := by
  have hc := chk0
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 0).T0 = (Q.ofNat 3000).val := (Q.cv_nat 3000).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 0).T1 = (Q.ofNat 3040).val := (Q.cv_nat 3040).symm
  have hcc : (Arb4.BandGlue_h4000.seg 0).c = (⟨1 / 2, (Q.ofNat 3020).val⟩ : ℂ) := by rw [(Q.cv_nat 3020)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 0).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 0) E0 (Arb4.BandGlue_h4000.seg_edge 0 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 0 (by norm_num)).2 (valid_of_B _ _ _ _ _ E0 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 0 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3000 G_T3040 E0 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B00_line
  · show EdgeClearGlue.SlabClear ((3000 : ℝ) - 5773 / 100000) (3000 : ℝ)
    exact Arb4.H4000.S_L3000_clear
  · show EdgeClearGlue.SlabClear (3040 : ℝ) ((3040 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3040_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3040 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3040.Lo).val (Arb4.H4000.E_T3040.Hi).val
    exact Arb4.H4000.E_T3040_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3000 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H3000.E_T3000.Lo).val (Arb4.H3000.E_T3000.Hi).val
    exact Arb4.H3000.E_T3000_hAH

/-! ### Band 1: `[3040, 3080]`, 40 zeros -/

/-- The five enclosures of band 1: K6a, the edges at 3080 and 3040, K6b. -/
noncomputable def E1 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3080.Lo, Arb4.H4000.E_T3080.Hi, Arb4.H4000.E_T3040.Lo, Arb4.H4000.E_T3040.Hi,
  (Q.frac 123765561039 1000000000), (Q.frac 30941471963 250000000), (Q.frac 24753111567 200000000), (Q.frac 15470735581 125000000)⟩

theorem chk1 : (validB (Q.ofNat 3040) (Q.ofNat 3080) (Q.ofNat 3060) (Q.frac 6437 16) 40 E1 && k6sideB G_T3040 G_T3080 E1) = true := by decide +kernel

theorem box1 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 1) (AllZeros_h4000.bHi 1) := by
  have hc := chk1
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 1).T0 = (Q.ofNat 3040).val := (Q.cv_nat 3040).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 1).T1 = (Q.ofNat 3080).val := (Q.cv_nat 3080).symm
  have hcc : (Arb4.BandGlue_h4000.seg 1).c = (⟨1 / 2, (Q.ofNat 3060).val⟩ : ℂ) := by rw [(Q.cv_nat 3060)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 1).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 1) E1 (Arb4.BandGlue_h4000.seg_edge 1 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 1 (by norm_num)).2 (valid_of_B _ _ _ _ _ E1 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 1 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3040 G_T3080 E1 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B01_line
  · show EdgeClearGlue.SlabClear ((3040 : ℝ) - 5773 / 100000) (3040 : ℝ)
    exact Arb4.H4000.S_L3040_clear
  · show EdgeClearGlue.SlabClear (3080 : ℝ) ((3080 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3080_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3080 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3080.Lo).val (Arb4.H4000.E_T3080.Hi).val
    exact Arb4.H4000.E_T3080_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3040 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3040.Lo).val (Arb4.H4000.E_T3040.Hi).val
    exact Arb4.H4000.E_T3040_hAH

/-! ### Band 2: `[3080, 3120]`, 39 zeros -/

/-- The five enclosures of band 2: K6a, the edges at 3120 and 3080, K6b. -/
noncomputable def E2 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3120.Lo, Arb4.H4000.E_T3120.Hi, Arb4.H4000.E_T3080.Lo, Arb4.H4000.E_T3080.Hi,
  (Q.frac 620126553 5000000), (Q.frac 31006408299 250000000), (Q.frac 62012653739 500000000), (Q.frac 62012815037 500000000)⟩

theorem chk2 : (validB (Q.ofNat 3080) (Q.ofNat 3120) (Q.ofNat 3100) (Q.frac 6437 16) 39 E2 && k6sideB G_T3080 G_T3120 E2) = true := by decide +kernel

theorem box2 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 2) (AllZeros_h4000.bHi 2) := by
  have hc := chk2
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 2).T0 = (Q.ofNat 3080).val := (Q.cv_nat 3080).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 2).T1 = (Q.ofNat 3120).val := (Q.cv_nat 3120).symm
  have hcc : (Arb4.BandGlue_h4000.seg 2).c = (⟨1 / 2, (Q.ofNat 3100).val⟩ : ℂ) := by rw [(Q.cv_nat 3100)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 2).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 2) E2 (Arb4.BandGlue_h4000.seg_edge 2 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 2 (by norm_num)).2 (valid_of_B _ _ _ _ _ E2 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 2 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3080 G_T3120 E2 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B02_line
  · show EdgeClearGlue.SlabClear ((3080 : ℝ) - 5773 / 100000) (3080 : ℝ)
    exact Arb4.H4000.S_L3080_clear
  · show EdgeClearGlue.SlabClear (3120 : ℝ) ((3120 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3120_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3120 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3120.Lo).val (Arb4.H4000.E_T3120.Hi).val
    exact Arb4.H4000.E_T3120_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3080 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3080.Lo).val (Arb4.H4000.E_T3080.Hi).val
    exact Arb4.H4000.E_T3080_hAH

/-! ### Band 3: `[12479/4, 3160]`, 41 zeros -/

/-- The five enclosures of band 3: K6a, the edges at 3160 and 12479/4, K6b. -/
noncomputable def E3 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3160.Lo, Arb4.H4000.E_T3160.Hi, Arb4.H4000.E_T12479_4.Lo, Arb4.H4000.E_T12479_4.Hi,
  (Q.frac 125057688743 1000000000), (Q.frac 62529003621 500000000), (Q.frac 125057685681 1000000000), (Q.frac 6252900209 50000000)⟩

theorem chk3 : (validB (Q.frac 12479 4) (Q.ofNat 3160) (Q.frac 25119 8) (Q.frac 26069 64) 41 E3 && k6sideB G_T12479_4 G_T3160 E3) = true := by decide +kernel

theorem box3 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 3) (AllZeros_h4000.bHi 3) := by
  have hc := chk3
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 3).T0 = (Q.frac 12479 4).val := (Q.cv_frac 12479 4).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 3).T1 = (Q.ofNat 3160).val := (Q.cv_nat 3160).symm
  have hcc : (Arb4.BandGlue_h4000.seg 3).c = (⟨1 / 2, (Q.frac 25119 8).val⟩ : ℂ) := by rw [(Q.cv_frac 25119 8)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 3).R = Real.sqrt (Q.frac 26069 64).val := by rw [(Q.cv_frac 26069 64)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 3) E3 (Arb4.BandGlue_h4000.seg_edge 3 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 3 (by norm_num)).2 (valid_of_B _ _ _ _ _ E3 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 3 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T12479_4 G_T3160 E3 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B03_line
  · show EdgeClearGlue.SlabClear ((12479 / 4 : ℝ) - 14343 / 250000) (12479 / 4 : ℝ)
    exact Arb4.H4000.S_L12479_4_clear
  · show EdgeClearGlue.SlabClear (3160 : ℝ) ((3160 : ℝ) + 14343 / 250000)
    exact Arb4.H4000.S_U3160_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3160 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3160.Lo).val (Arb4.H4000.E_T3160.Hi).val
    exact Arb4.H4000.E_T3160_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (12479 / 4 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T12479_4.Lo).val (Arb4.H4000.E_T12479_4.Hi).val
    exact Arb4.H4000.E_T12479_4_hAH

/-! ### Band 4: `[3160, 3200]`, 39 zeros -/

/-- The five enclosures of band 4: K6a, the edges at 3200 and 3160, K6b. -/
noncomputable def E4 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3200.Lo, Arb4.H4000.E_T3200.Hi, Arb4.H4000.E_T3160.Lo, Arb4.H4000.E_T3160.Hi,
  (Q.frac 2490698061 20000000), (Q.frac 12453521753 100000000), (Q.frac 31133725021 250000000), (Q.frac 124535214563 1000000000)⟩

theorem chk4 : (validB (Q.ofNat 3160) (Q.ofNat 3200) (Q.ofNat 3180) (Q.frac 6437 16) 39 E4 && k6sideB G_T3160 G_T3200 E4) = true := by decide +kernel

theorem box4 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 4) (AllZeros_h4000.bHi 4) := by
  have hc := chk4
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 4).T0 = (Q.ofNat 3160).val := (Q.cv_nat 3160).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 4).T1 = (Q.ofNat 3200).val := (Q.cv_nat 3200).symm
  have hcc : (Arb4.BandGlue_h4000.seg 4).c = (⟨1 / 2, (Q.ofNat 3180).val⟩ : ℂ) := by rw [(Q.cv_nat 3180)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 4).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 4) E4 (Arb4.BandGlue_h4000.seg_edge 4 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 4 (by norm_num)).2 (valid_of_B _ _ _ _ _ E4 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 4 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3160 G_T3200 E4 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B04_line
  · show EdgeClearGlue.SlabClear ((3160 : ℝ) - 5773 / 100000) (3160 : ℝ)
    exact Arb4.H4000.S_L3160_clear
  · show EdgeClearGlue.SlabClear (3200 : ℝ) ((3200 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3200_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3200 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3200.Lo).val (Arb4.H4000.E_T3200.Hi).val
    exact Arb4.H4000.E_T3200_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3160 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3160.Lo).val (Arb4.H4000.E_T3160.Hi).val
    exact Arb4.H4000.E_T3160_hAH

/-! ### Band 5: `[3200, 3240]`, 40 zeros -/

/-- The five enclosures of band 5: K6a, the edges at 3240 and 3200, K6b. -/
noncomputable def E5 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3240.Lo, Arb4.H4000.E_T3240.Hi, Arb4.H4000.E_T3200.Lo, Arb4.H4000.E_T3200.Hi,
  (Q.frac 124784911417 1000000000), (Q.frac 12478522199 100000000), (Q.frac 124784908523 1000000000), (Q.frac 15598152387 125000000)⟩

theorem chk5 : (validB (Q.ofNat 3200) (Q.ofNat 3240) (Q.ofNat 3220) (Q.frac 6437 16) 40 E5 && k6sideB G_T3200 G_T3240 E5) = true := by decide +kernel

theorem box5 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 5) (AllZeros_h4000.bHi 5) := by
  have hc := chk5
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 5).T0 = (Q.ofNat 3200).val := (Q.cv_nat 3200).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 5).T1 = (Q.ofNat 3240).val := (Q.cv_nat 3240).symm
  have hcc : (Arb4.BandGlue_h4000.seg 5).c = (⟨1 / 2, (Q.ofNat 3220).val⟩ : ℂ) := by rw [(Q.cv_nat 3220)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 5).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 5) E5 (Arb4.BandGlue_h4000.seg_edge 5 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 5 (by norm_num)).2 (valid_of_B _ _ _ _ _ E5 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 5 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3200 G_T3240 E5 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B05_line
  · show EdgeClearGlue.SlabClear ((3200 : ℝ) - 5773 / 100000) (3200 : ℝ)
    exact Arb4.H4000.S_L3200_clear
  · show EdgeClearGlue.SlabClear (3240 : ℝ) ((3240 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3240_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3240 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3240.Lo).val (Arb4.H4000.E_T3240.Hi).val
    exact Arb4.H4000.E_T3240_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3200 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3200.Lo).val (Arb4.H4000.E_T3200.Hi).val
    exact Arb4.H4000.E_T3200_hAH

/-! ### Band 6: `[3240, 3280]`, 40 zeros -/

/-- The five enclosures of band 6: K6a, the edges at 3280 and 3240, K6b. -/
noncomputable def E6 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3280.Lo, Arb4.H4000.E_T3280.Hi, Arb4.H4000.E_T3240.Lo, Arb4.H4000.E_T3240.Hi,
  (Q.frac 125031833081 1000000000), (Q.frac 125032139843 1000000000), (Q.frac 62515915129 500000000), (Q.frac 6251606851 50000000)⟩

theorem chk6 : (validB (Q.ofNat 3240) (Q.ofNat 3280) (Q.ofNat 3260) (Q.frac 6437 16) 40 E6 && k6sideB G_T3240 G_T3280 E6) = true := by decide +kernel

theorem box6 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 6) (AllZeros_h4000.bHi 6) := by
  have hc := chk6
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 6).T0 = (Q.ofNat 3240).val := (Q.cv_nat 3240).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 6).T1 = (Q.ofNat 3280).val := (Q.cv_nat 3280).symm
  have hcc : (Arb4.BandGlue_h4000.seg 6).c = (⟨1 / 2, (Q.ofNat 3260).val⟩ : ℂ) := by rw [(Q.cv_nat 3260)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 6).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 6) E6 (Arb4.BandGlue_h4000.seg_edge 6 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 6 (by norm_num)).2 (valid_of_B _ _ _ _ _ E6 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 6 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3240 G_T3280 E6 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B06_line
  · show EdgeClearGlue.SlabClear ((3240 : ℝ) - 5773 / 100000) (3240 : ℝ)
    exact Arb4.H4000.S_L3240_clear
  · show EdgeClearGlue.SlabClear (3280 : ℝ) ((3280 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3280_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3280 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3280.Lo).val (Arb4.H4000.E_T3280.Hi).val
    exact Arb4.H4000.E_T3280_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3240 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3240.Lo).val (Arb4.H4000.E_T3240.Hi).val
    exact Arb4.H4000.E_T3240_hAH

/-! ### Band 7: `[3280, 3320]`, 39 zeros -/

/-- The five enclosures of band 7: K6a, the edges at 3320 and 3280, K6b. -/
noncomputable def E7 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3320.Lo, Arb4.H4000.E_T3320.Hi, Arb4.H4000.E_T3280.Lo, Arb4.H4000.E_T3280.Hi,
  (Q.frac 25055148667 200000000), (Q.frac 62638023189 500000000), (Q.frac 6263787029 50000000), (Q.frac 125276043623 1000000000)⟩

theorem chk7 : (validB (Q.ofNat 3280) (Q.ofNat 3320) (Q.ofNat 3300) (Q.frac 6437 16) 39 E7 && k6sideB G_T3280 G_T3320 E7) = true := by decide +kernel

theorem box7 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 7) (AllZeros_h4000.bHi 7) := by
  have hc := chk7
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 7).T0 = (Q.ofNat 3280).val := (Q.cv_nat 3280).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 7).T1 = (Q.ofNat 3320).val := (Q.cv_nat 3320).symm
  have hcc : (Arb4.BandGlue_h4000.seg 7).c = (⟨1 / 2, (Q.ofNat 3300).val⟩ : ℂ) := by rw [(Q.cv_nat 3300)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 7).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 7) E7 (Arb4.BandGlue_h4000.seg_edge 7 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 7 (by norm_num)).2 (valid_of_B _ _ _ _ _ E7 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 7 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3280 G_T3320 E7 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B07_line
  · show EdgeClearGlue.SlabClear ((3280 : ℝ) - 5773 / 100000) (3280 : ℝ)
    exact Arb4.H4000.S_L3280_clear
  · show EdgeClearGlue.SlabClear (3320 : ℝ) ((3320 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3320_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3320 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3320.Lo).val (Arb4.H4000.E_T3320.Hi).val
    exact Arb4.H4000.E_T3320_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3280 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3280.Lo).val (Arb4.H4000.E_T3280.Hi).val
    exact Arb4.H4000.E_T3280_hAH

/-! ### Band 8: `[3320, 3360]`, 41 zeros -/

/-- The five enclosures of band 8: K6a, the edges at 3360 and 3320, K6b. -/
noncomputable def E8 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3360.Lo, Arb4.H4000.E_T3360.Hi, Arb4.H4000.E_T3320.Lo, Arb4.H4000.E_T3320.Hi,
  (Q.frac 125516714747 1000000000), (Q.frac 125517014161 1000000000), (Q.frac 62758356029 500000000), (Q.frac 7844813217 62500000)⟩

theorem chk8 : (validB (Q.ofNat 3320) (Q.ofNat 3360) (Q.ofNat 3340) (Q.frac 6437 16) 41 E8 && k6sideB G_T3320 G_T3360 E8) = true := by decide +kernel

theorem box8 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 8) (AllZeros_h4000.bHi 8) := by
  have hc := chk8
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 8).T0 = (Q.ofNat 3320).val := (Q.cv_nat 3320).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 8).T1 = (Q.ofNat 3360).val := (Q.cv_nat 3360).symm
  have hcc : (Arb4.BandGlue_h4000.seg 8).c = (⟨1 / 2, (Q.ofNat 3340).val⟩ : ℂ) := by rw [(Q.cv_nat 3340)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 8).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 8) E8 (Arb4.BandGlue_h4000.seg_edge 8 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 8 (by norm_num)).2 (valid_of_B _ _ _ _ _ E8 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 8 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3320 G_T3360 E8 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B08_line
  · show EdgeClearGlue.SlabClear ((3320 : ℝ) - 5773 / 100000) (3320 : ℝ)
    exact Arb4.H4000.S_L3320_clear
  · show EdgeClearGlue.SlabClear (3360 : ℝ) ((3360 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3360_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3360 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3360.Lo).val (Arb4.H4000.E_T3360.Hi).val
    exact Arb4.H4000.E_T3360_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3320 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3320.Lo).val (Arb4.H4000.E_T3320.Hi).val
    exact Arb4.H4000.E_T3320_hAH

/-! ### Band 9: `[3360, 3400]`, 39 zeros -/

/-- The five enclosures of band 9: K6a, the edges at 3400 and 3360, K6b. -/
noncomputable def E9 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3400.Lo, Arb4.H4000.E_T3400.Hi, Arb4.H4000.E_T3360.Lo, Arb4.H4000.E_T3360.Hi,
  (Q.frac 125754817297 1000000000), (Q.frac 125755113167 1000000000), (Q.frac 125754814671 1000000000), (Q.frac 125755110541 1000000000)⟩

theorem chk9 : (validB (Q.ofNat 3360) (Q.ofNat 3400) (Q.ofNat 3380) (Q.frac 6437 16) 39 E9 && k6sideB G_T3360 G_T3400 E9) = true := by decide +kernel

theorem box9 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 9) (AllZeros_h4000.bHi 9) := by
  have hc := chk9
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 9).T0 = (Q.ofNat 3360).val := (Q.cv_nat 3360).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 9).T1 = (Q.ofNat 3400).val := (Q.cv_nat 3400).symm
  have hcc : (Arb4.BandGlue_h4000.seg 9).c = (⟨1 / 2, (Q.ofNat 3380).val⟩ : ℂ) := by rw [(Q.cv_nat 3380)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 9).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 9) E9 (Arb4.BandGlue_h4000.seg_edge 9 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 9 (by norm_num)).2 (valid_of_B _ _ _ _ _ E9 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 9 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3360 G_T3400 E9 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B09_line
  · show EdgeClearGlue.SlabClear ((3360 : ℝ) - 5773 / 100000) (3360 : ℝ)
    exact Arb4.H4000.S_L3360_clear
  · show EdgeClearGlue.SlabClear (3400 : ℝ) ((3400 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3400_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3400 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3400.Lo).val (Arb4.H4000.E_T3400.Hi).val
    exact Arb4.H4000.E_T3400_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3360 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3360.Lo).val (Arb4.H4000.E_T3360.Hi).val
    exact Arb4.H4000.E_T3360_hAH

/-! ### Band 10: `[3400, 3440]`, 40 zeros -/

/-- The five enclosures of band 10: K6a, the edges at 3440 and 3400, K6b. -/
noncomputable def E10 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3440.Lo, Arb4.H4000.E_T3440.Hi, Arb4.H4000.E_T3400.Lo, Arb4.H4000.E_T3400.Hi,
  (Q.frac 31497529623 250000000), (Q.frac 125990410901 1000000000), (Q.frac 125990115927 1000000000), (Q.frac 7874400521 62500000)⟩

theorem chk10 : (validB (Q.ofNat 3400) (Q.ofNat 3440) (Q.ofNat 3420) (Q.frac 6437 16) 40 E10 && k6sideB G_T3400 G_T3440 E10) = true := by decide +kernel

theorem box10 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 10) (AllZeros_h4000.bHi 10) := by
  have hc := chk10
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 10).T0 = (Q.ofNat 3400).val := (Q.cv_nat 3400).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 10).T1 = (Q.ofNat 3440).val := (Q.cv_nat 3440).symm
  have hcc : (Arb4.BandGlue_h4000.seg 10).c = (⟨1 / 2, (Q.ofNat 3420).val⟩ : ℂ) := by rw [(Q.cv_nat 3420)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 10).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 10) E10 (Arb4.BandGlue_h4000.seg_edge 10 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 10 (by norm_num)).2 (valid_of_B _ _ _ _ _ E10 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 10 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3400 G_T3440 E10 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B10_line
  · show EdgeClearGlue.SlabClear ((3400 : ℝ) - 5773 / 100000) (3400 : ℝ)
    exact Arb4.H4000.S_L3400_clear
  · show EdgeClearGlue.SlabClear (3440 : ℝ) ((3440 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3440_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3440 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3440.Lo).val (Arb4.H4000.E_T3440.Hi).val
    exact Arb4.H4000.E_T3440_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3400 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3400.Lo).val (Arb4.H4000.E_T3400.Hi).val
    exact Arb4.H4000.E_T3400_hAH

/-! ### Band 11: `[3440, 3480]`, 41 zeros -/

/-- The five enclosures of band 11: K6a, the edges at 3480 and 3440, K6b. -/
noncomputable def E11 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3480.Lo, Arb4.H4000.E_T3480.Hi, Arb4.H4000.E_T3440.Lo, Arb4.H4000.E_T3440.Hi,
  (Q.frac 31555670871 250000000), (Q.frac 126222972513 1000000000), (Q.frac 63111340489 500000000), (Q.frac 126222970007 1000000000)⟩

theorem chk11 : (validB (Q.ofNat 3440) (Q.ofNat 3480) (Q.ofNat 3460) (Q.frac 6437 16) 41 E11 && k6sideB G_T3440 G_T3480 E11) = true := by decide +kernel

theorem box11 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 11) (AllZeros_h4000.bHi 11) := by
  have hc := chk11
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 11).T0 = (Q.ofNat 3440).val := (Q.cv_nat 3440).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 11).T1 = (Q.ofNat 3480).val := (Q.cv_nat 3480).symm
  have hcc : (Arb4.BandGlue_h4000.seg 11).c = (⟨1 / 2, (Q.ofNat 3460).val⟩ : ℂ) := by rw [(Q.cv_nat 3460)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 11).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 11) E11 (Arb4.BandGlue_h4000.seg_edge 11 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 11 (by norm_num)).2 (valid_of_B _ _ _ _ _ E11 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 11 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3440 G_T3480 E11 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B11_line
  · show EdgeClearGlue.SlabClear ((3440 : ℝ) - 5773 / 100000) (3440 : ℝ)
    exact Arb4.H4000.S_L3440_clear
  · show EdgeClearGlue.SlabClear (3480 : ℝ) ((3480 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3480_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3480 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3480.Lo).val (Arb4.H4000.E_T3480.Hi).val
    exact Arb4.H4000.E_T3480_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3440 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3440.Lo).val (Arb4.H4000.E_T3440.Hi).val
    exact Arb4.H4000.E_T3440_hAH

/-! ### Band 12: `[3480, 3520]`, 40 zeros -/

/-- The five enclosures of band 12: K6a, the edges at 3520 and 3480, K6b. -/
noncomputable def E12 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3520.Lo, Arb4.H4000.E_T3520.Hi, Arb4.H4000.E_T3480.Lo, Arb4.H4000.E_T3480.Hi,
  (Q.frac 126452575179 1000000000), (Q.frac 25290572181 200000000), (Q.frac 12645257273 100000000), (Q.frac 15806607307 125000000)⟩

theorem chk12 : (validB (Q.ofNat 3480) (Q.ofNat 3520) (Q.ofNat 3500) (Q.frac 6437 16) 40 E12 && k6sideB G_T3480 G_T3520 E12) = true := by decide +kernel

theorem box12 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 12) (AllZeros_h4000.bHi 12) := by
  have hc := chk12
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 12).T0 = (Q.ofNat 3480).val := (Q.cv_nat 3480).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 12).T1 = (Q.ofNat 3520).val := (Q.cv_nat 3520).symm
  have hcc : (Arb4.BandGlue_h4000.seg 12).c = (⟨1 / 2, (Q.ofNat 3500).val⟩ : ℂ) := by rw [(Q.cv_nat 3500)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 12).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 12) E12 (Arb4.BandGlue_h4000.seg_edge 12 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 12 (by norm_num)).2 (valid_of_B _ _ _ _ _ E12 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 12 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3480 G_T3520 E12 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B12_line
  · show EdgeClearGlue.SlabClear ((3480 : ℝ) - 5773 / 100000) (3480 : ℝ)
    exact Arb4.H4000.S_L3480_clear
  · show EdgeClearGlue.SlabClear (3520 : ℝ) ((3520 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3520_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3520 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3520.Lo).val (Arb4.H4000.E_T3520.Hi).val
    exact Arb4.H4000.E_T3520_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3480 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3480.Lo).val (Arb4.H4000.E_T3480.Hi).val
    exact Arb4.H4000.E_T3480_hAH

/-! ### Band 13: `[3520, 14241/4]`, 41 zeros -/

/-- The five enclosures of band 13: K6a, the edges at 14241/4 and 3520, K6b. -/
noncomputable def E13 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T14241_4.Lo, Arb4.H4000.E_T14241_4.Hi, Arb4.H4000.E_T3520.Lo, Arb4.H4000.E_T3520.Hi,
  (Q.frac 63736156799 500000000), (Q.frac 25494519217 200000000), (Q.frac 127472311189 1000000000), (Q.frac 31868148419 250000000)⟩

theorem chk13 : (validB (Q.ofNat 3520) (Q.frac 14241 4) (Q.frac 28321 8) (Q.frac 26069 64) 41 E13 && k6sideB G_T3520 G_T14241_4 E13) = true := by decide +kernel

theorem box13 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 13) (AllZeros_h4000.bHi 13) := by
  have hc := chk13
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 13).T0 = (Q.ofNat 3520).val := (Q.cv_nat 3520).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 13).T1 = (Q.frac 14241 4).val := (Q.cv_frac 14241 4).symm
  have hcc : (Arb4.BandGlue_h4000.seg 13).c = (⟨1 / 2, (Q.frac 28321 8).val⟩ : ℂ) := by rw [(Q.cv_frac 28321 8)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 13).R = Real.sqrt (Q.frac 26069 64).val := by rw [(Q.cv_frac 26069 64)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 13) E13 (Arb4.BandGlue_h4000.seg_edge 13 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 13 (by norm_num)).2 (valid_of_B _ _ _ _ _ E13 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 13 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3520 G_T14241_4 E13 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B13_line
  · show EdgeClearGlue.SlabClear ((3520 : ℝ) - 14343 / 250000) (3520 : ℝ)
    exact Arb4.H4000.S_L3520_clear
  · show EdgeClearGlue.SlabClear (14241 / 4 : ℝ) ((14241 / 4 : ℝ) + 14343 / 250000)
    exact Arb4.H4000.S_U14241_4_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (14241 / 4 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T14241_4.Lo).val (Arb4.H4000.E_T14241_4.Hi).val
    exact Arb4.H4000.E_T14241_4_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3520 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3520.Lo).val (Arb4.H4000.E_T3520.Hi).val
    exact Arb4.H4000.E_T3520_hAH

/-! ### Band 14: `[3560, 3600]`, 40 zeros -/

/-- The five enclosures of band 14: K6a, the edges at 3600 and 3560, K6b. -/
noncomputable def E14 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3600.Lo, Arb4.H4000.E_T3600.Hi, Arb4.H4000.E_T3560.Lo, Arb4.H4000.E_T3560.Hi,
  (Q.frac 31726144919 250000000), (Q.frac 126904859017 1000000000), (Q.frac 15863072167 125000000), (Q.frac 31726214169 250000000)⟩

theorem chk14 : (validB (Q.ofNat 3560) (Q.ofNat 3600) (Q.ofNat 3580) (Q.frac 6437 16) 40 E14 && k6sideB G_T3560 G_T3600 E14) = true := by decide +kernel

theorem box14 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 14) (AllZeros_h4000.bHi 14) := by
  have hc := chk14
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 14).T0 = (Q.ofNat 3560).val := (Q.cv_nat 3560).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 14).T1 = (Q.ofNat 3600).val := (Q.cv_nat 3600).symm
  have hcc : (Arb4.BandGlue_h4000.seg 14).c = (⟨1 / 2, (Q.ofNat 3580).val⟩ : ℂ) := by rw [(Q.cv_nat 3580)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 14).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 14) E14 (Arb4.BandGlue_h4000.seg_edge 14 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 14 (by norm_num)).2 (valid_of_B _ _ _ _ _ E14 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 14 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3560 G_T3600 E14 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B14_line
  · show EdgeClearGlue.SlabClear ((3560 : ℝ) - 5773 / 100000) (3560 : ℝ)
    exact Arb4.H4000.S_L3560_clear
  · show EdgeClearGlue.SlabClear (3600 : ℝ) ((3600 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3600_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3600 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3600.Lo).val (Arb4.H4000.E_T3600.Hi).val
    exact Arb4.H4000.E_T3600_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3560 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3560.Lo).val (Arb4.H4000.E_T3560.Hi).val
    exact Arb4.H4000.E_T3560_hAH

/-! ### Band 15: `[3600, 3640]`, 41 zeros -/

/-- The five enclosures of band 15: K6a, the edges at 3640 and 3600, K6b. -/
noncomputable def E15 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3640.Lo, Arb4.H4000.E_T3640.Hi, Arb4.H4000.E_T3600.Lo, Arb4.H4000.E_T3600.Hi,
  (Q.frac 63563403973 500000000), (Q.frac 635635421 5000000), (Q.frac 127126805657 1000000000), (Q.frac 12712708191 100000000)⟩

theorem chk15 : (validB (Q.ofNat 3600) (Q.ofNat 3640) (Q.ofNat 3620) (Q.frac 6437 16) 41 E15 && k6sideB G_T3600 G_T3640 E15) = true := by decide +kernel

theorem box15 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 15) (AllZeros_h4000.bHi 15) := by
  have hc := chk15
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 15).T0 = (Q.ofNat 3600).val := (Q.cv_nat 3600).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 15).T1 = (Q.ofNat 3640).val := (Q.cv_nat 3640).symm
  have hcc : (Arb4.BandGlue_h4000.seg 15).c = (⟨1 / 2, (Q.ofNat 3620).val⟩ : ℂ) := by rw [(Q.cv_nat 3620)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 15).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 15) E15 (Arb4.BandGlue_h4000.seg_edge 15 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 15 (by norm_num)).2 (valid_of_B _ _ _ _ _ E15 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 15 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3600 G_T3640 E15 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B15_line
  · show EdgeClearGlue.SlabClear ((3600 : ℝ) - 5773 / 100000) (3600 : ℝ)
    exact Arb4.H4000.S_L3600_clear
  · show EdgeClearGlue.SlabClear (3640 : ℝ) ((3640 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3640_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3640 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3640.Lo).val (Arb4.H4000.E_T3640.Hi).val
    exact Arb4.H4000.E_T3640_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3600 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3600.Lo).val (Arb4.H4000.E_T3600.Hi).val
    exact Arb4.H4000.E_T3600_hAH

/-! ### Band 16: `[3640, 3680]`, 41 zeros -/

/-- The five enclosures of band 16: K6a, the edges at 3680 and 3640, K6b. -/
noncomputable def E16 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3680.Lo, Arb4.H4000.E_T3680.Hi, Arb4.H4000.E_T3640.Lo, Arb4.H4000.E_T3640.Hi,
  (Q.frac 127346594033 1000000000), (Q.frac 127346867267 1000000000), (Q.frac 127346591793 1000000000), (Q.frac 127346865027 1000000000)⟩

theorem chk16 : (validB (Q.ofNat 3640) (Q.ofNat 3680) (Q.ofNat 3660) (Q.frac 6437 16) 41 E16 && k6sideB G_T3640 G_T3680 E16) = true := by decide +kernel

theorem box16 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 16) (AllZeros_h4000.bHi 16) := by
  have hc := chk16
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 16).T0 = (Q.ofNat 3640).val := (Q.cv_nat 3640).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 16).T1 = (Q.ofNat 3680).val := (Q.cv_nat 3680).symm
  have hcc : (Arb4.BandGlue_h4000.seg 16).c = (⟨1 / 2, (Q.ofNat 3660).val⟩ : ℂ) := by rw [(Q.cv_nat 3660)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 16).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 16) E16 (Arb4.BandGlue_h4000.seg_edge 16 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 16 (by norm_num)).2 (valid_of_B _ _ _ _ _ E16 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 16 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3640 G_T3680 E16 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B16_line
  · show EdgeClearGlue.SlabClear ((3640 : ℝ) - 5773 / 100000) (3640 : ℝ)
    exact Arb4.H4000.S_L3640_clear
  · show EdgeClearGlue.SlabClear (3680 : ℝ) ((3680 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3680_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3680 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3680.Lo).val (Arb4.H4000.E_T3680.Hi).val
    exact Arb4.H4000.E_T3680_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3640 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3640.Lo).val (Arb4.H4000.E_T3640.Hi).val
    exact Arb4.H4000.E_T3640_hAH

/-! ### Band 17: `[3680, 3720]`, 40 zeros -/

/-- The five enclosures of band 17: K6a, the edges at 3720 and 3680, K6b. -/
noncomputable def E17 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3720.Lo, Arb4.H4000.E_T3720.Hi, Arb4.H4000.E_T3680.Lo, Arb4.H4000.E_T3680.Hi,
  (Q.frac 127563991031 1000000000), (Q.frac 127564261311 1000000000), (Q.frac 127563988839 1000000000), (Q.frac 127564259119 1000000000)⟩

theorem chk17 : (validB (Q.ofNat 3680) (Q.ofNat 3720) (Q.ofNat 3700) (Q.frac 6437 16) 40 E17 && k6sideB G_T3680 G_T3720 E17) = true := by decide +kernel

theorem box17 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 17) (AllZeros_h4000.bHi 17) := by
  have hc := chk17
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 17).T0 = (Q.ofNat 3680).val := (Q.cv_nat 3680).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 17).T1 = (Q.ofNat 3720).val := (Q.cv_nat 3720).symm
  have hcc : (Arb4.BandGlue_h4000.seg 17).c = (⟨1 / 2, (Q.ofNat 3700).val⟩ : ℂ) := by rw [(Q.cv_nat 3700)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 17).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 17) E17 (Arb4.BandGlue_h4000.seg_edge 17 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 17 (by norm_num)).2 (valid_of_B _ _ _ _ _ E17 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 17 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3680 G_T3720 E17 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B17_line
  · show EdgeClearGlue.SlabClear ((3680 : ℝ) - 5773 / 100000) (3680 : ℝ)
    exact Arb4.H4000.S_L3680_clear
  · show EdgeClearGlue.SlabClear (3720 : ℝ) ((3720 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3720_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3720 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3720.Lo).val (Arb4.H4000.E_T3720.Hi).val
    exact Arb4.H4000.E_T3720_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3680 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3680.Lo).val (Arb4.H4000.E_T3680.Hi).val
    exact Arb4.H4000.E_T3680_hAH

/-! ### Band 18: `[3720, 3760]`, 41 zeros -/

/-- The five enclosures of band 18: K6a, the edges at 3760 and 3720, K6b. -/
noncomputable def E18 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3760.Lo, Arb4.H4000.E_T3760.Hi, Arb4.H4000.E_T3720.Lo, Arb4.H4000.E_T3720.Hi,
  (Q.frac 63889525161 500000000), (Q.frac 127779317711 1000000000), (Q.frac 127779048177 1000000000), (Q.frac 63889657783 500000000)⟩

theorem chk18 : (validB (Q.ofNat 3720) (Q.ofNat 3760) (Q.ofNat 3740) (Q.frac 6437 16) 41 E18 && k6sideB G_T3720 G_T3760 E18) = true := by decide +kernel

theorem box18 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 18) (AllZeros_h4000.bHi 18) := by
  have hc := chk18
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 18).T0 = (Q.ofNat 3720).val := (Q.cv_nat 3720).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 18).T1 = (Q.ofNat 3760).val := (Q.cv_nat 3760).symm
  have hcc : (Arb4.BandGlue_h4000.seg 18).c = (⟨1 / 2, (Q.ofNat 3740).val⟩ : ℂ) := by rw [(Q.cv_nat 3740)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 18).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 18) E18 (Arb4.BandGlue_h4000.seg_edge 18 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 18 (by norm_num)).2 (valid_of_B _ _ _ _ _ E18 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 18 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3720 G_T3760 E18 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B18_line
  · show EdgeClearGlue.SlabClear ((3720 : ℝ) - 5773 / 100000) (3720 : ℝ)
    exact Arb4.H4000.S_L3720_clear
  · show EdgeClearGlue.SlabClear (3760 : ℝ) ((3760 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3760_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3760 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3760.Lo).val (Arb4.H4000.E_T3760.Hi).val
    exact Arb4.H4000.E_T3760_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3720 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3720.Lo).val (Arb4.H4000.E_T3720.Hi).val
    exact Arb4.H4000.E_T3720_hAH

/-! ### Band 19: `[3760, 3800]`, 40 zeros -/

/-- The five enclosures of band 19: K6a, the edges at 3800 and 3760, K6b. -/
noncomputable def E19 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3800.Lo, Arb4.H4000.E_T3800.Hi, Arb4.H4000.E_T3760.Lo, Arb4.H4000.E_T3760.Hi,
  (Q.frac 127991821647 1000000000), (Q.frac 127992086207 1000000000), (Q.frac 31997954887 250000000), (Q.frac 127992084107 1000000000)⟩

theorem chk19 : (validB (Q.ofNat 3760) (Q.ofNat 3800) (Q.ofNat 3780) (Q.frac 6437 16) 40 E19 && k6sideB G_T3760 G_T3800 E19) = true := by decide +kernel

theorem box19 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 19) (AllZeros_h4000.bHi 19) := by
  have hc := chk19
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 19).T0 = (Q.ofNat 3760).val := (Q.cv_nat 3760).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 19).T1 = (Q.ofNat 3800).val := (Q.cv_nat 3800).symm
  have hcc : (Arb4.BandGlue_h4000.seg 19).c = (⟨1 / 2, (Q.ofNat 3780).val⟩ : ℂ) := by rw [(Q.cv_nat 3780)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 19).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 19) E19 (Arb4.BandGlue_h4000.seg_edge 19 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 19 (by norm_num)).2 (valid_of_B _ _ _ _ _ E19 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 19 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3760 G_T3800 E19 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B19_line
  · show EdgeClearGlue.SlabClear ((3760 : ℝ) - 5773 / 100000) (3760 : ℝ)
    exact Arb4.H4000.S_L3760_clear
  · show EdgeClearGlue.SlabClear (3800 : ℝ) ((3800 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3800_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3800 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3800.Lo).val (Arb4.H4000.E_T3800.Hi).val
    exact Arb4.H4000.E_T3800_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3760 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3760.Lo).val (Arb4.H4000.E_T3760.Hi).val
    exact Arb4.H4000.E_T3760_hAH

/-! ### Band 20: `[3800, 3840]`, 42 zeros -/

/-- The five enclosures of band 20: K6a, the edges at 3840 and 3800, K6b. -/
noncomputable def E20 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3840.Lo, Arb4.H4000.E_T3840.Hi, Arb4.H4000.E_T3800.Lo, Arb4.H4000.E_T3800.Hi,
  (Q.frac 64101176589 500000000), (Q.frac 128202614967 1000000000), (Q.frac 64101175561 500000000), (Q.frac 128202612911 1000000000)⟩

theorem chk20 : (validB (Q.ofNat 3800) (Q.ofNat 3840) (Q.ofNat 3820) (Q.frac 6437 16) 42 E20 && k6sideB G_T3800 G_T3840 E20) = true := by decide +kernel

theorem box20 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 20) (AllZeros_h4000.bHi 20) := by
  have hc := chk20
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 20).T0 = (Q.ofNat 3800).val := (Q.cv_nat 3800).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 20).T1 = (Q.ofNat 3840).val := (Q.cv_nat 3840).symm
  have hcc : (Arb4.BandGlue_h4000.seg 20).c = (⟨1 / 2, (Q.ofNat 3820).val⟩ : ℂ) := by rw [(Q.cv_nat 3820)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 20).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 20) E20 (Arb4.BandGlue_h4000.seg_edge 20 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 20 (by norm_num)).2 (valid_of_B _ _ _ _ _ E20 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 20 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3800 G_T3840 E20 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B20_line
  · show EdgeClearGlue.SlabClear ((3800 : ℝ) - 5773 / 100000) (3800 : ℝ)
    exact Arb4.H4000.S_L3800_clear
  · show EdgeClearGlue.SlabClear (3840 : ℝ) ((3840 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3840_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3840 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3840.Lo).val (Arb4.H4000.E_T3840.Hi).val
    exact Arb4.H4000.E_T3840_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3800 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3800.Lo).val (Arb4.H4000.E_T3800.Hi).val
    exact Arb4.H4000.E_T3800_hAH

/-! ### Band 21: `[15359/4, 3880]`, 41 zeros -/

/-- The five enclosures of band 21: K6a, the edges at 3880 and 15359/4, K6b. -/
noncomputable def E21 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3880.Lo, Arb4.H4000.E_T3880.Hi, Arb4.H4000.E_T15359_4.Lo, Arb4.H4000.E_T15359_4.Hi,
  (Q.frac 25842521269 200000000), (Q.frac 12921286543 100000000), (Q.frac 129212604319 1000000000), (Q.frac 129212863403 1000000000)⟩

theorem chk21 : (validB (Q.frac 15359 4) (Q.ofNat 3880) (Q.frac 30879 8) (Q.frac 26069 64) 41 E21 && k6sideB G_T15359_4 G_T3880 E21) = true := by decide +kernel

theorem box21 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 21) (AllZeros_h4000.bHi 21) := by
  have hc := chk21
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 21).T0 = (Q.frac 15359 4).val := (Q.cv_frac 15359 4).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 21).T1 = (Q.ofNat 3880).val := (Q.cv_nat 3880).symm
  have hcc : (Arb4.BandGlue_h4000.seg 21).c = (⟨1 / 2, (Q.frac 30879 8).val⟩ : ℂ) := by rw [(Q.cv_frac 30879 8)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 21).R = Real.sqrt (Q.frac 26069 64).val := by rw [(Q.cv_frac 26069 64)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 21) E21 (Arb4.BandGlue_h4000.seg_edge 21 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 21 (by norm_num)).2 (valid_of_B _ _ _ _ _ E21 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 21 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T15359_4 G_T3880 E21 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B21_line
  · show EdgeClearGlue.SlabClear ((15359 / 4 : ℝ) - 14343 / 250000) (15359 / 4 : ℝ)
    exact Arb4.H4000.S_L15359_4_clear
  · show EdgeClearGlue.SlabClear (3880 : ℝ) ((3880 : ℝ) + 14343 / 250000)
    exact Arb4.H4000.S_U3880_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3880 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3880.Lo).val (Arb4.H4000.E_T3880.Hi).val
    exact Arb4.H4000.E_T3880_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (15359 / 4 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T15359_4.Lo).val (Arb4.H4000.E_T15359_4.Hi).val
    exact Arb4.H4000.E_T15359_4_hAH

/-! ### Band 22: `[3880, 3920]`, 41 zeros -/

/-- The five enclosures of band 22: K6a, the edges at 3920 and 3880, K6b. -/
noncomputable def E22 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T3920.Lo, Arb4.H4000.E_T3920.Hi, Arb4.H4000.E_T3880.Lo, Arb4.H4000.E_T3880.Hi,
  (Q.frac 16077110259 125000000), (Q.frac 128617138491 1000000000), (Q.frac 1286168801 10000000), (Q.frac 128617136519 1000000000)⟩

theorem chk22 : (validB (Q.ofNat 3880) (Q.ofNat 3920) (Q.ofNat 3900) (Q.frac 6437 16) 41 E22 && k6sideB G_T3880 G_T3920 E22) = true := by decide +kernel

theorem box22 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 22) (AllZeros_h4000.bHi 22) := by
  have hc := chk22
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 22).T0 = (Q.ofNat 3880).val := (Q.cv_nat 3880).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 22).T1 = (Q.ofNat 3920).val := (Q.cv_nat 3920).symm
  have hcc : (Arb4.BandGlue_h4000.seg 22).c = (⟨1 / 2, (Q.ofNat 3900).val⟩ : ℂ) := by rw [(Q.cv_nat 3900)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 22).R = Real.sqrt (Q.frac 6437 16).val := by rw [(Q.cv_frac 6437 16)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 22) E22 (Arb4.BandGlue_h4000.seg_edge 22 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 22 (by norm_num)).2 (valid_of_B _ _ _ _ _ E22 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 22 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3880 G_T3920 E22 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B22_line
  · show EdgeClearGlue.SlabClear ((3880 : ℝ) - 5773 / 100000) (3880 : ℝ)
    exact Arb4.H4000.S_L3880_clear
  · show EdgeClearGlue.SlabClear (3920 : ℝ) ((3920 : ℝ) + 5773 / 100000)
    exact Arb4.H4000.S_U3920_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (3920 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3920.Lo).val (Arb4.H4000.E_T3920.Hi).val
    exact Arb4.H4000.E_T3920_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3880 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3880.Lo).val (Arb4.H4000.E_T3880.Hi).val
    exact Arb4.H4000.E_T3880_hAH

/-! ### Band 23: `[3920, 15841/4]`, 42 zeros -/

/-- The five enclosures of band 23: K6a, the edges at 15841/4 and 3920, K6b. -/
noncomputable def E23 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T15841_4.Lo, Arb4.H4000.E_T15841_4.Hi, Arb4.H4000.E_T3920.Lo, Arb4.H4000.E_T3920.Hi,
  (Q.frac 6481336887 50000000), (Q.frac 32406747887 250000000), (Q.frac 32406683949 250000000), (Q.frac 32406747401 250000000)⟩

theorem chk23 : (validB (Q.ofNat 3920) (Q.frac 15841 4) (Q.frac 31521 8) (Q.frac 26069 64) 42 E23 && k6sideB G_T3920 G_T15841_4 E23) = true := by decide +kernel

theorem box23 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 23) (AllZeros_h4000.bHi 23) := by
  have hc := chk23
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 23).T0 = (Q.ofNat 3920).val := (Q.cv_nat 3920).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 23).T1 = (Q.frac 15841 4).val := (Q.cv_frac 15841 4).symm
  have hcc : (Arb4.BandGlue_h4000.seg 23).c = (⟨1 / 2, (Q.frac 31521 8).val⟩ : ℂ) := by rw [(Q.cv_frac 31521 8)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 23).R = Real.sqrt (Q.frac 26069 64).val := by rw [(Q.cv_frac 26069 64)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 23) E23 (Arb4.BandGlue_h4000.seg_edge 23 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 23 (by norm_num)).2 (valid_of_B _ _ _ _ _ E23 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 23 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3920 G_T15841_4 E23 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B23_line
  · show EdgeClearGlue.SlabClear ((3920 : ℝ) - 14343 / 250000) (3920 : ℝ)
    exact Arb4.H4000.S_L3920_clear
  · show EdgeClearGlue.SlabClear (15841 / 4 : ℝ) ((15841 / 4 : ℝ) + 14343 / 250000)
    exact Arb4.H4000.S_U15841_4_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (15841 / 4 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T15841_4.Lo).val (Arb4.H4000.E_T15841_4.Hi).val
    exact Arb4.H4000.E_T15841_4_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3920 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3920.Lo).val (Arb4.H4000.E_T3920.Hi).val
    exact Arb4.H4000.E_T3920_hAH

/-! ### Band 24: `[3960, 16001/4]`, 42 zeros -/

/-- The five enclosures of band 24: K6a, the edges at 16001/4 and 3960, K6b. -/
noncomputable def E24 : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, Arb4.H4000.E_T16001_4.Lo, Arb4.H4000.E_T16001_4.Hi, Arb4.H4000.E_T3960.Lo, Arb4.H4000.E_T3960.Hi,
  (Q.frac 64915009427 500000000), (Q.frac 129830270111 1000000000), (Q.frac 32457504237 250000000), (Q.frac 25966053641 200000000)⟩

theorem chk24 : (validB (Q.ofNat 3960) (Q.frac 16001 4) (Q.frac 31841 8) (Q.frac 26069 64) 42 E24 && k6sideB G_T3960 G_T16001_4 E24) = true := by decide +kernel

theorem box24 : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h4000.bLo 24) (AllZeros_h4000.bHi 24) := by
  have hc := chk24
  rw [Bool.and_eq_true] at hc
  have hT0 : (Arb4.BandGlue_h4000.seg 24).T0 = (Q.ofNat 3960).val := (Q.cv_nat 3960).symm
  have hT1 : (Arb4.BandGlue_h4000.seg 24).T1 = (Q.frac 16001 4).val := (Q.cv_frac 16001 4).symm
  have hcc : (Arb4.BandGlue_h4000.seg 24).c = (⟨1 / 2, (Q.frac 31841 8).val⟩ : ℂ) := by rw [(Q.cv_frac 31841 8)]; rfl
  have hR : (Arb4.BandGlue_h4000.seg 24).R = Real.sqrt (Q.frac 26069 64).val := by rw [(Q.cv_frac 26069 64)]; rfl
  refine boxCert_of_parts (Arb4.BandGlue_h4000.seg 24) E24 (Arb4.BandGlue_h4000.seg_edge 24 (by norm_num)).1
    (Arb4.BandGlue_h4000.seg_edge 24 (by norm_num)).2 (valid_of_B _ _ _ _ _ E24 hT0 hT1 hcc hR hc.1)
    (Arb4.BandGlue_h4000.seg_geom 24 (by norm_num)) ?_ ?_ ?_ (k6side_of_B _ G_T3960 G_T16001_4 E24 hT0 hT1 hc.2) ?_ ?_
  · exact Arb4.H4000.B24_line
  · show EdgeClearGlue.SlabClear ((3960 : ℝ) - 14343 / 250000) (3960 : ℝ)
    exact Arb4.H4000.S_L3960_clear
  · show EdgeClearGlue.SlabClear (16001 / 4 : ℝ) ((16001 / 4 : ℝ) + 14343 / 250000)
    exact Arb4.H4000.S_U16001_4_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (16001 / 4 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T16001_4.Lo).val (Arb4.H4000.E_T16001_4.Hi).val
    exact Arb4.H4000.E_T16001_4_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (3960 : ℝ) 2 (-1) ∈ Set.Icc (Arb4.H4000.E_T3960.Lo).val (Arb4.H4000.E_T3960.Hi).val
    exact Arb4.H4000.E_T3960_hAH

/-- The segment's band hypothesis, kernel-checked. -/
theorem hbands : AllZeros_h4000.BandHyp := by
  intro i hi
  interval_cases i
  · exact (box0).box
  · exact (box1).box
  · exact (box2).box
  · exact (box3).box
  · exact (box4).box
  · exact (box5).box
  · exact (box6).box
  · exact (box7).box
  · exact (box8).box
  · exact (box9).box
  · exact (box10).box
  · exact (box11).box
  · exact (box12).box
  · exact (box13).box
  · exact (box14).box
  · exact (box15).box
  · exact (box16).box
  · exact (box17).box
  · exact (box18).box
  · exact (box19).box
  · exact (box20).box
  · exact (box21).box
  · exact (box22).box
  · exact (box23).box
  · exact (box24).box

/-- **Every nontrivial zero of ζ with `0 < Im ρ ≤ 4000` lies on the critical line** -- kernel-checked,
    NO hypotheses (a finite verification; conjecture1_proved = False). -/
theorem all_nontrivial_zeros_up_to_height_4000 :
    ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 4000 → ρ.re = 1 / 2 :=
  AllZerosUpToHeight.height_chain 3000 4000 Arb4_h3000.all_nontrivial_zeros_up_to_height_3000
    (AllZeros_h4000.segment_3000_4000 hbands (HeightFloor.height_floor 4000))

end Arb4_h4000
