/-  Arb4_H8000Slabs_2.lean -- lane Arb4: COMPACT kernel certificates of 10 zero-free edge-clearance slabs
    (GENERATED by ../Arb4_emit_seg.py; do not edit).  Each slab: the certificate data
    `Arb4.SlabD` (cells planned by emit_h1000_offline.plan_slab, unchanged) and ONE
    `decide +kernel` of `Arb4.slabOK` (budget, Pochhammer bound, every cell with its evaluator
    run and rectangle geometry), then `Arb4.slabOK_sound`.
    Slabs: L7370, U7407, L7407, U7444, L7444, U7481, L7481, U7519, L30075_4, U7556.
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import Arb4_Slab

open Arb4 Arb4.Q

namespace Arb4.H8000

/-- The slab `(0, 1) x [1473987521/200000, 7370]` (3 cells, N = 2211). -/
noncomputable def S_L7370 : SlabD where
  tq := 14
  N := 2211
  L := (Q.frac 3851 500)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7370) (Q.frac 12479 200000))
  hi := (Q.ofNat 7370)
  U := (Q.frac 7371 1)
  Qr := 189300000000000000000000000000000000000000000000000
  r0 := 47
  FN := 19
  FD := 50
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 120749569, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 120749569, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 120749569, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 120749569, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7370_ok : slabOK S_L7370 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7370 : ℝ) - 12479 / 200000) (7370 : ℝ)`, hypothesis-free.** -/
theorem S_L7370_clear : EdgeClearGlue.SlabClear ((7370 : ℝ) - 12479 / 200000) (7370 : ℝ) := by
  have h := slabOK_sound S_L7370 S_L7370_ok
  have hlo : S_L7370.lo.val = ((7370 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7370) (Q.cv_frac 12479 200000))
  have hhi : S_L7370.hi.val = (7370 : ℝ) := (Q.cv_nat 7370)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7407, 1481412479/200000]` (3 cells, N = 2223). -/
noncomputable def S_U7407 : SlabD where
  tq := 14
  N := 2223
  L := (Q.frac 7707 1000)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7407)
  hi := (Q.add (Q.ofNat 7407) (Q.frac 12479 200000))
  U := (Q.frac 7408 1)
  Qr := 202100000000000000000000000000000000000000000000000
  r0 := 47
  FN := 381
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 121356799, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 121356799, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 121356799, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 121356799, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7407_ok : slabOK S_U7407 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7407 : ℝ) ((7407 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7407_clear : EdgeClearGlue.SlabClear (7407 : ℝ) ((7407 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7407 S_U7407_ok
  have hlo : S_U7407.lo.val = (7407 : ℝ) := (Q.cv_nat 7407)
  have hhi : S_U7407.hi.val = ((7407 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7407) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1481387521/200000, 7407]` (3 cells, N = 2223). -/
noncomputable def S_L7407 : SlabD where
  tq := 14
  N := 2223
  L := (Q.frac 7707 1000)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7407) (Q.frac 12479 200000))
  hi := (Q.ofNat 7407)
  U := (Q.frac 7408 1)
  Qr := 202100000000000000000000000000000000000000000000000
  r0 := 47
  FN := 381
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 121355777, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 121355777, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 121355777, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 121355777, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7407_ok : slabOK S_L7407 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7407 : ℝ) - 12479 / 200000) (7407 : ℝ)`, hypothesis-free.** -/
theorem S_L7407_clear : EdgeClearGlue.SlabClear ((7407 : ℝ) - 12479 / 200000) (7407 : ℝ) := by
  have h := slabOK_sound S_L7407 S_L7407_ok
  have hlo : S_L7407.lo.val = ((7407 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7407) (Q.cv_frac 12479 200000))
  have hhi : S_L7407.hi.val = (7407 : ℝ) := (Q.cv_nat 7407)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7444, 1488812479/200000]` (3 cells, N = 2234). -/
noncomputable def S_U7444 : SlabD where
  tq := 14
  N := 2234
  L := (Q.frac 964 125)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7444)
  hi := (Q.add (Q.ofNat 7444) (Q.frac 12479 200000))
  U := (Q.frac 7445 1)
  Qr := 215600000000000000000000000000000000000000000000000
  r0 := 47
  FN := 77
  FD := 200
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 121963007, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 121963007, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 121963007, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 121963007, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7444_ok : slabOK S_U7444 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7444 : ℝ) ((7444 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7444_clear : EdgeClearGlue.SlabClear (7444 : ℝ) ((7444 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7444 S_U7444_ok
  have hlo : S_U7444.lo.val = (7444 : ℝ) := (Q.cv_nat 7444)
  have hhi : S_U7444.hi.val = ((7444 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7444) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1488787521/200000, 7444]` (3 cells, N = 2234). -/
noncomputable def S_L7444 : SlabD where
  tq := 14
  N := 2234
  L := (Q.frac 964 125)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7444) (Q.frac 12479 200000))
  hi := (Q.ofNat 7444)
  U := (Q.frac 7445 1)
  Qr := 215600000000000000000000000000000000000000000000000
  r0 := 47
  FN := 77
  FD := 200
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 121961985, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 121961985, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 121961985, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 121961985, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7444_ok : slabOK S_L7444 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7444 : ℝ) - 12479 / 200000) (7444 : ℝ)`, hypothesis-free.** -/
theorem S_L7444_clear : EdgeClearGlue.SlabClear ((7444 : ℝ) - 12479 / 200000) (7444 : ℝ) := by
  have h := slabOK_sound S_L7444 S_L7444_ok
  have hlo : S_L7444.lo.val = ((7444 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7444) (Q.cv_frac 12479 200000))
  have hhi : S_L7444.hi.val = (7444 : ℝ) := (Q.cv_nat 7444)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7481, 1496212479/200000]` (3 cells, N = 2245). -/
noncomputable def S_U7481 : SlabD where
  tq := 14
  N := 2245
  L := (Q.frac 7717 1000)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7481)
  hi := (Q.add (Q.ofNat 7481) (Q.frac 12479 200000))
  U := (Q.frac 7482 1)
  Qr := 229900000000000000000000000000000000000000000000000
  r0 := 47
  FN := 39
  FD := 100
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 122569215, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 122569215, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 122569215, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 122569215, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7481_ok : slabOK S_U7481 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7481 : ℝ) ((7481 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7481_clear : EdgeClearGlue.SlabClear (7481 : ℝ) ((7481 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7481 S_U7481_ok
  have hlo : S_U7481.lo.val = (7481 : ℝ) := (Q.cv_nat 7481)
  have hhi : S_U7481.hi.val = ((7481 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7481) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7480939241/1000000, 7481]` (3 cells, N = 2245). -/
noncomputable def S_L7481 : SlabD where
  tq := 14
  N := 2245
  L := (Q.frac 7717 1000)
  R := (Q.frac 111 1250)
  lo := (Q.sub (Q.ofNat 7481) (Q.frac 60759 1000000))
  hi := (Q.ofNat 7481)
  U := (Q.frac 7482 1)
  Qr := 229900000000000000000000000000000000000000000000000
  r0 := 47
  FN := 383
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 122568206, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) },
    { a := 3, b := 0, q := 4, tn := 122568206, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) },
    { a := 11, b := 0, q := 12, tn := 122568206, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) }].getD j { a := 11, b := 0, q := 12, tn := 122568206, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) }

theorem S_L7481_ok : slabOK S_L7481 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7481 : ℝ) - 60759 / 1000000) (7481 : ℝ)`, hypothesis-free.** -/
theorem S_L7481_clear : EdgeClearGlue.SlabClear ((7481 : ℝ) - 60759 / 1000000) (7481 : ℝ) := by
  have h := slabOK_sound S_L7481 S_L7481_ok
  have hlo : S_L7481.lo.val = ((7481 : ℝ) - 60759 / 1000000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7481) (Q.cv_frac 60759 1000000))
  have hhi : S_L7481.hi.val = (7481 : ℝ) := (Q.cv_nat 7481)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7519, 7519060759/1000000]` (12 cells, N = 2256). -/
noncomputable def S_U7519 : SlabD where
  tq := 14
  N := 2256
  L := (Q.frac 3861 500)
  R := (Q.frac 369 10000)
  lo := (Q.ofNat 7519)
  hi := (Q.add (Q.ofNat 7519) (Q.frac 60759 1000000))
  U := (Q.frac 7520 1)
  Qr := 245600000000000000000000000000000000000000000000000
  r0 := 47
  FN := 101
  FD := 25000
  m := 12
  xs := fun j => [(Q.frac 1 2), (Q.frac 13 24), (Q.frac 7 12), (Q.frac 5 8), (Q.frac 2 3), (Q.frac 17 24), (Q.frac 3 4), (Q.frac 19 24), (Q.frac 5 6), (Q.frac 7 8), (Q.frac 11 12), (Q.frac 23 24), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 25, b := 0, q := 48, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 9, b := 0, q := 16, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 29, b := 0, q := 48, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 31, b := 0, q := 48, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 11, b := 0, q := 16, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 35, b := 0, q := 48, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 37, b := 0, q := 48, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 13, b := 0, q := 16, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 41, b := 0, q := 48, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 43, b := 0, q := 48, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 15, b := 0, q := 16, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 47, b := 0, q := 48, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) }].getD j { a := 47, b := 0, q := 48, tn := 123191794, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) }

theorem S_U7519_ok : slabOK S_U7519 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7519 : ℝ) ((7519 : ℝ) + 60759 / 1000000)`, hypothesis-free.** -/
theorem S_U7519_clear : EdgeClearGlue.SlabClear (7519 : ℝ) ((7519 : ℝ) + 60759 / 1000000) := by
  have h := slabOK_sound S_U7519 S_U7519_ok
  have hlo : S_U7519.lo.val = (7519 : ℝ) := (Q.cv_nat 7519)
  have hhi : S_U7519.hi.val = ((7519 : ℝ) + 60759 / 1000000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7519) (Q.cv_frac 60759 1000000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [3759344011/500000, 30075/4]` (4 cells, N = 2256). -/
noncomputable def S_L30075_4 : SlabD where
  tq := 14
  N := 2256
  L := (Q.frac 3861 500)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.frac 30075 4) (Q.frac 30989 500000))
  hi := (Q.frac 30075 4)
  U := (Q.frac 7519 1)
  Qr := 245500000000000000000000000000000000000000000000000
  r0 := 47
  FN := 49
  FD := 125
  m := 4
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 123186692, rn := 520, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 127 4096) },
    { a := 5, b := 0, q := 8, tn := 123186692, rn := 520, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 127 4096) },
    { a := 3, b := 0, q := 4, tn := 123186692, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 127 4096) },
    { a := 11, b := 0, q := 12, tn := 123186692, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 127 4096) }].getD j { a := 11, b := 0, q := 12, tn := 123186692, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 127 4096) }

theorem S_L30075_4_ok : slabOK S_L30075_4 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((30075 / 4 : ℝ) - 30989 / 500000) (30075 / 4 : ℝ)`, hypothesis-free.** -/
theorem S_L30075_4_clear : EdgeClearGlue.SlabClear ((30075 / 4 : ℝ) - 30989 / 500000) (30075 / 4 : ℝ) := by
  have h := slabOK_sound S_L30075_4 S_L30075_4_ok
  have hlo : S_L30075_4.lo.val = ((30075 / 4 : ℝ) - 30989 / 500000) := (Q.cv_sub _ _ _ _ (Q.cv_frac 30075 4) (Q.cv_frac 30989 500000))
  have hhi : S_L30075_4.hi.val = (30075 / 4 : ℝ) := (Q.cv_frac 30075 4)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7556, 3778030989/500000]` (6 cells, N = 2267). -/
noncomputable def S_U7556 : SlabD where
  tq := 14
  N := 2267
  L := (Q.frac 7727 1000)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7556)
  hi := (Q.add (Q.ofNat 7556) (Q.frac 30989 500000))
  U := (Q.frac 7557 1)
  Qr := 261800000000000000000000000000000000000000000000000
  r0 := 47
  FN := 79
  FD := 200
  m := 6
  xs := fun j => [(Q.frac 1 2), (Q.frac 13 24), (Q.frac 7 12), (Q.frac 5 8), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 25, b := 0, q := 48, tn := 123798012, rn := 374, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 127 4096) },
    { a := 9, b := 0, q := 16, tn := 123798012, rn := 374, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 127 4096) },
    { a := 29, b := 0, q := 48, tn := 123798012, rn := 374, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 127 4096) },
    { a := 31, b := 0, q := 48, tn := 123798012, rn := 374, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 127 4096) },
    { a := 3, b := 0, q := 4, tn := 123798012, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 127 4096) },
    { a := 11, b := 0, q := 12, tn := 123798012, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 127 4096) }].getD j { a := 11, b := 0, q := 12, tn := 123798012, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 127 4096) }

theorem S_U7556_ok : slabOK S_U7556 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7556 : ℝ) ((7556 : ℝ) + 30989 / 500000)`, hypothesis-free.** -/
theorem S_U7556_clear : EdgeClearGlue.SlabClear (7556 : ℝ) ((7556 : ℝ) + 30989 / 500000) := by
  have h := slabOK_sound S_U7556 S_U7556_ok
  have hlo : S_U7556.lo.val = (7556 : ℝ) := (Q.cv_nat 7556)
  have hhi : S_U7556.hi.val = ((7556 : ℝ) + 30989 / 500000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7556) (Q.cv_frac 30989 500000))
  rw [hlo, hhi] at h
  exact h

end Arb4.H8000
