/-  Arb4_H8000Slabs_3.lean -- lane Arb4: COMPACT kernel certificates of 10 zero-free edge-clearance slabs
    (GENERATED by ../Arb4_emit_seg.py; do not edit).  Each slab: the certificate data
    `Arb4.SlabD` (cells planned by emit_h1000_offline.plan_slab, unchanged) and ONE
    `decide +kernel` of `Arb4.slabOK` (budget, Pochhammer bound, every cell with its evaluator
    run and rectangle geometry), then `Arb4.slabOK_sound`.
    Slabs: L7556, U7593, L7593, U7630, L7630, U7667, L7667, U7704, L7704, U7741.
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import Arb4_Slab

open Arb4 Arb4.Q

namespace Arb4.H8000

/-- The slab `(0, 1) x [1511187521/200000, 7556]` (4 cells, N = 2267). -/
noncomputable def S_L7556 : SlabD where
  tq := 14
  N := 2267
  L := (Q.frac 7727 1000)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7556) (Q.frac 12479 200000))
  hi := (Q.ofNat 7556)
  U := (Q.frac 7557 1)
  Qr := 261700000000000000000000000000000000000000000000000
  r0 := 47
  FN := 79
  FD := 200
  m := 4
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 123796993, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 5, b := 0, q := 8, tn := 123796993, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 123796993, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 123796993, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 123796993, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7556_ok : slabOK S_L7556 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7556 : ℝ) - 12479 / 200000) (7556 : ℝ)`, hypothesis-free.** -/
theorem S_L7556_clear : EdgeClearGlue.SlabClear ((7556 : ℝ) - 12479 / 200000) (7556 : ℝ) := by
  have h := slabOK_sound S_L7556 S_L7556_ok
  have hlo : S_L7556.lo.val = ((7556 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7556) (Q.cv_frac 12479 200000))
  have hhi : S_L7556.hi.val = (7556 : ℝ) := (Q.cv_nat 7556)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7593, 1518612479/200000]` (6 cells, N = 2278). -/
noncomputable def S_U7593 : SlabD where
  tq := 14
  N := 2278
  L := (Q.frac 1933 250)
  R := (Q.frac 521 10000)
  lo := (Q.ofNat 7593)
  hi := (Q.add (Q.ofNat 7593) (Q.frac 12479 200000))
  U := (Q.frac 7594 1)
  Qr := 278900000000000000000000000000000000000000000000000
  r0 := 47
  FN := 181
  FD := 10000
  m := 6
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 3 4), (Q.frac 5 6), (Q.frac 11 12), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 124404223, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 5, b := 0, q := 8, tn := 124404223, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 17, b := 0, q := 24, tn := 124404223, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 19, b := 0, q := 24, tn := 124404223, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 7, b := 0, q := 8, tn := 124404223, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 23, b := 0, q := 24, tn := 124404223, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) }].getD j { a := 23, b := 0, q := 24, tn := 124404223, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) }

theorem S_U7593_ok : slabOK S_U7593 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7593 : ℝ) ((7593 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7593_clear : EdgeClearGlue.SlabClear (7593 : ℝ) ((7593 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7593 S_U7593_ok
  have hlo : S_U7593.lo.val = (7593 : ℝ) := (Q.cv_nat 7593)
  have hhi : S_U7593.hi.val = ((7593 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7593) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1518587521/200000, 7593]` (6 cells, N = 2278). -/
noncomputable def S_L7593 : SlabD where
  tq := 14
  N := 2278
  L := (Q.frac 1933 250)
  R := (Q.frac 521 10000)
  lo := (Q.sub (Q.ofNat 7593) (Q.frac 12479 200000))
  hi := (Q.ofNat 7593)
  U := (Q.frac 7594 1)
  Qr := 278900000000000000000000000000000000000000000000000
  r0 := 47
  FN := 181
  FD := 10000
  m := 6
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 3 4), (Q.frac 5 6), (Q.frac 11 12), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 124403201, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 5, b := 0, q := 8, tn := 124403201, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 17, b := 0, q := 24, tn := 124403201, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 19, b := 0, q := 24, tn := 124403201, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 7, b := 0, q := 8, tn := 124403201, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 23, b := 0, q := 24, tn := 124403201, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) }].getD j { a := 23, b := 0, q := 24, tn := 124403201, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) }

theorem S_L7593_ok : slabOK S_L7593 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7593 : ℝ) - 12479 / 200000) (7593 : ℝ)`, hypothesis-free.** -/
theorem S_L7593_clear : EdgeClearGlue.SlabClear ((7593 : ℝ) - 12479 / 200000) (7593 : ℝ) := by
  have h := slabOK_sound S_L7593 S_L7593_ok
  have hlo : S_L7593.lo.val = ((7593 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7593) (Q.cv_frac 12479 200000))
  have hhi : S_L7593.hi.val = (7593 : ℝ) := (Q.cv_nat 7593)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7630, 1526012479/200000]` (3 cells, N = 2290). -/
noncomputable def S_U7630 : SlabD where
  tq := 14
  N := 2290
  L := (Q.frac 7737 1000)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7630)
  hi := (Q.add (Q.ofNat 7630) (Q.frac 12479 200000))
  U := (Q.frac 7631 1)
  Qr := 297100000000000000000000000000000000000000000000000
  r0 := 47
  FN := 201
  FD := 500
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 125010431, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 125010431, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 125010431, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 125010431, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7630_ok : slabOK S_U7630 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7630 : ℝ) ((7630 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7630_clear : EdgeClearGlue.SlabClear (7630 : ℝ) ((7630 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7630 S_U7630_ok
  have hlo : S_U7630.lo.val = (7630 : ℝ) := (Q.cv_nat 7630)
  have hhi : S_U7630.hi.val = ((7630 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7630) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1525987521/200000, 7630]` (3 cells, N = 2289). -/
noncomputable def S_L7630 : SlabD where
  tq := 14
  N := 2289
  L := (Q.frac 967 125)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7630) (Q.frac 12479 200000))
  hi := (Q.ofNat 7630)
  U := (Q.frac 7631 1)
  Qr := 297100000000000000000000000000000000000000000000000
  r0 := 47
  FN := 201
  FD := 500
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 125009409, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 125009409, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 125009409, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 125009409, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7630_ok : slabOK S_L7630 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7630 : ℝ) - 12479 / 200000) (7630 : ℝ)`, hypothesis-free.** -/
theorem S_L7630_clear : EdgeClearGlue.SlabClear ((7630 : ℝ) - 12479 / 200000) (7630 : ℝ) := by
  have h := slabOK_sound S_L7630 S_L7630_ok
  have hlo : S_L7630.lo.val = ((7630 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7630) (Q.cv_frac 12479 200000))
  have hhi : S_L7630.hi.val = (7630 : ℝ) := (Q.cv_nat 7630)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7667, 1533412479/200000]` (3 cells, N = 2301). -/
noncomputable def S_U7667 : SlabD where
  tq := 14
  N := 2301
  L := (Q.frac 3871 500)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7667)
  hi := (Q.add (Q.ofNat 7667) (Q.frac 12479 200000))
  U := (Q.frac 7668 1)
  Qr := 316400000000000000000000000000000000000000000000000
  r0 := 47
  FN := 203
  FD := 500
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 125616639, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 125616639, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 125616639, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 125616639, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7667_ok : slabOK S_U7667 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7667 : ℝ) ((7667 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7667_clear : EdgeClearGlue.SlabClear (7667 : ℝ) ((7667 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7667 S_U7667_ok
  have hlo : S_U7667.lo.val = (7667 : ℝ) := (Q.cv_nat 7667)
  have hhi : S_U7667.hi.val = ((7667 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7667) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1533387521/200000, 7667]` (3 cells, N = 2301). -/
noncomputable def S_L7667 : SlabD where
  tq := 14
  N := 2301
  L := (Q.frac 3871 500)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7667) (Q.frac 12479 200000))
  hi := (Q.ofNat 7667)
  U := (Q.frac 7668 1)
  Qr := 316400000000000000000000000000000000000000000000000
  r0 := 47
  FN := 203
  FD := 500
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 125615617, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 125615617, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 125615617, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 125615617, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7667_ok : slabOK S_L7667 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7667 : ℝ) - 12479 / 200000) (7667 : ℝ)`, hypothesis-free.** -/
theorem S_L7667_clear : EdgeClearGlue.SlabClear ((7667 : ℝ) - 12479 / 200000) (7667 : ℝ) := by
  have h := slabOK_sound S_L7667 S_L7667_ok
  have hlo : S_L7667.lo.val = ((7667 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7667) (Q.cv_frac 12479 200000))
  have hhi : S_L7667.hi.val = (7667 : ℝ) := (Q.cv_nat 7667)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7704, 1540812479/200000]` (3 cells, N = 2312). -/
noncomputable def S_U7704 : SlabD where
  tq := 14
  N := 2312
  L := (Q.frac 3873 500)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7704)
  hi := (Q.add (Q.ofNat 7704) (Q.frac 12479 200000))
  U := (Q.frac 7705 1)
  Qr := 336800000000000000000000000000000000000000000000000
  r0 := 48
  FN := 41
  FD := 100
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 126222847, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 126222847, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 126222847, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 126222847, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7704_ok : slabOK S_U7704 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7704 : ℝ) ((7704 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7704_clear : EdgeClearGlue.SlabClear (7704 : ℝ) ((7704 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7704 S_U7704_ok
  have hlo : S_U7704.lo.val = (7704 : ℝ) := (Q.cv_nat 7704)
  have hhi : S_U7704.hi.val = ((7704 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7704) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1540787521/200000, 7704]` (4 cells, N = 2312). -/
noncomputable def S_L7704 : SlabD where
  tq := 14
  N := 2312
  L := (Q.frac 3873 500)
  R := (Q.frac 89 1000)
  lo := (Q.sub (Q.ofNat 7704) (Q.frac 12479 200000))
  hi := (Q.ofNat 7704)
  U := (Q.frac 7705 1)
  Qr := 336800000000000000000000000000000000000000000000000
  r0 := 48
  FN := 41
  FD := 100
  m := 4
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 126221825, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 5, b := 0, q := 8, tn := 126221825, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 126221825, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 126221825, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 126221825, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_L7704_ok : slabOK S_L7704 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((7704 : ℝ) - 12479 / 200000) (7704 : ℝ)`, hypothesis-free.** -/
theorem S_L7704_clear : EdgeClearGlue.SlabClear ((7704 : ℝ) - 12479 / 200000) (7704 : ℝ) := by
  have h := slabOK_sound S_L7704 S_L7704_ok
  have hlo : S_L7704.lo.val = ((7704 : ℝ) - 12479 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 7704) (Q.cv_frac 12479 200000))
  have hhi : S_L7704.hi.val = (7704 : ℝ) := (Q.cv_nat 7704)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [7741, 1548212479/200000]` (5 cells, N = 2323). -/
noncomputable def S_U7741 : SlabD where
  tq := 14
  N := 2323
  L := (Q.frac 7751 1000)
  R := (Q.frac 89 1000)
  lo := (Q.ofNat 7741)
  hi := (Q.add (Q.ofNat 7741) (Q.frac 12479 200000))
  U := (Q.frac 7742 1)
  Qr := 358500000000000000000000000000000000000000000000000
  r0 := 48
  FN := 103
  FD := 250
  m := 5
  xs := fun j => [(Q.frac 1 2), (Q.frac 13 24), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 25, b := 0, q := 48, tn := 126829055, rn := 376, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 1597749 51200000) },
    { a := 9, b := 0, q := 16, tn := 126829055, rn := 376, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 1597749 51200000) },
    { a := 5, b := 0, q := 8, tn := 126829055, rn := 521, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 1597749 51200000) },
    { a := 3, b := 0, q := 4, tn := 126829055, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) },
    { a := 11, b := 0, q := 12, tn := 126829055, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 126829055, rn := 890, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1597749 51200000) }

theorem S_U7741_ok : slabOK S_U7741 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (7741 : ℝ) ((7741 : ℝ) + 12479 / 200000)`, hypothesis-free.** -/
theorem S_U7741_clear : EdgeClearGlue.SlabClear (7741 : ℝ) ((7741 : ℝ) + 12479 / 200000) := by
  have h := slabOK_sound S_U7741 S_U7741_ok
  have hlo : S_U7741.lo.val = (7741 : ℝ) := (Q.cv_nat 7741)
  have hhi : S_U7741.hi.val = ((7741 : ℝ) + 12479 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 7741) (Q.cv_frac 12479 200000))
  rw [hlo, hhi] at h
  exact h

end Arb4.H8000
