/-  Arb4_H7000Slabs_2.lean -- lane Arb4: COMPACT kernel certificates of 10 zero-free edge-clearance slabs
    (GENERATED by ../Arb4_emit_seg.py; do not edit).  Each slab: the certificate data
    `Arb4.SlabD` (cells planned by emit_h1000_offline.plan_slab, unchanged) and ONE
    `decide +kernel` of `Arb4.slabOK` (budget, Pochhammer bound, every cell with its evaluator
    run and rectangle geometry), then `Arb4.slabOK_sound`.
    Slabs: L25539_4, U6423, L6423, U6462, L6462, U26001_4, L6500, U6538, L6538, U6577.
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import Arb4_Slab

open Arb4 Arb4.Q

namespace Arb4.H7000

/-- The slab `(0, 1) x [6384689637/1000000, 25539/4]` (6 cells, N = 1916). -/
noncomputable def S_L25539_4 : SlabD where
  tq := 14
  N := 1916
  L := (Q.frac 3779 500)
  R := (Q.frac 103 2000)
  lo := (Q.sub (Q.frac 25539 4) (Q.frac 60363 1000000))
  hi := (Q.frac 25539 4)
  U := (Q.frac 6385 1)
  Qr := 29310000000000000000000000000000000000000000000000
  r0 := 43
  FN := 129
  FD := 10000
  m := 6
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 3 4), (Q.frac 5 6), (Q.frac 11 12), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 104607250, rn := 515, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 3867089 128000000) },
    { a := 5, b := 0, q := 8, tn := 104607250, rn := 515, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 3867089 128000000) },
    { a := 17, b := 0, q := 24, tn := 104607250, rn := 515, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 3867089 128000000) },
    { a := 19, b := 0, q := 24, tn := 104607250, rn := 515, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 3867089 128000000) },
    { a := 7, b := 0, q := 8, tn := 104607250, rn := 515, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 3867089 128000000) },
    { a := 23, b := 0, q := 24, tn := 104607250, rn := 515, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 3867089 128000000) }].getD j { a := 23, b := 0, q := 24, tn := 104607250, rn := 515, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 3867089 128000000) }

theorem S_L25539_4_ok : slabOK S_L25539_4 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((25539 / 4 : ℝ) - 60363 / 1000000) (25539 / 4 : ℝ)`, hypothesis-free.** -/
theorem S_L25539_4_clear : EdgeClearGlue.SlabClear ((25539 / 4 : ℝ) - 60363 / 1000000) (25539 / 4 : ℝ) := by
  have h := slabOK_sound S_L25539_4 S_L25539_4_ok
  have hlo : S_L25539_4.lo.val = ((25539 / 4 : ℝ) - 60363 / 1000000) := (Q.cv_sub _ _ _ _ (Q.cv_frac 25539 4) (Q.cv_frac 60363 1000000))
  have hhi : S_L25539_4.hi.val = (25539 / 4 : ℝ) := (Q.cv_frac 25539 4)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [6423, 6423060363/1000000]` (3 cells, N = 1927). -/
noncomputable def S_U6423 : SlabD where
  tq := 14
  N := 1927
  L := (Q.frac 1891 250)
  R := (Q.frac 887 10000)
  lo := (Q.ofNat 6423)
  hi := (Q.add (Q.ofNat 6423) (Q.frac 60363 1000000))
  U := (Q.frac 6424 1)
  Qr := 31680000000000000000000000000000000000000000000000
  r0 := 43
  FN := 29
  FD := 100
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 105234926, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) },
    { a := 3, b := 0, q := 4, tn := 105234926, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) },
    { a := 11, b := 0, q := 12, tn := 105234926, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) }].getD j { a := 11, b := 0, q := 12, tn := 105234926, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) }

theorem S_U6423_ok : slabOK S_U6423 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (6423 : ℝ) ((6423 : ℝ) + 60363 / 1000000)`, hypothesis-free.** -/
theorem S_U6423_clear : EdgeClearGlue.SlabClear (6423 : ℝ) ((6423 : ℝ) + 60363 / 1000000) := by
  have h := slabOK_sound S_U6423 S_U6423_ok
  have hlo : S_U6423.lo.val = (6423 : ℝ) := (Q.cv_nat 6423)
  have hhi : S_U6423.hi.val = ((6423 : ℝ) + 60363 / 1000000) := (Q.cv_add _ _ _ _ (Q.cv_nat 6423) (Q.cv_frac 60363 1000000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1284588159/200000, 6423]` (3 cells, N = 1927). -/
noncomputable def S_L6423 : SlabD where
  tq := 14
  N := 1927
  L := (Q.frac 1891 250)
  R := (Q.frac 177 2000)
  lo := (Q.sub (Q.ofNat 6423) (Q.frac 11841 200000))
  hi := (Q.ofNat 6423)
  U := (Q.frac 6424 1)
  Qr := 31670000000000000000000000000000000000000000000000
  r0 := 43
  FN := 143
  FD := 500
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 105233947, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) },
    { a := 3, b := 0, q := 4, tn := 105233947, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) },
    { a := 11, b := 0, q := 12, tn := 105233947, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 105233947, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) }

theorem S_L6423_ok : slabOK S_L6423 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((6423 : ℝ) - 11841 / 200000) (6423 : ℝ)`, hypothesis-free.** -/
theorem S_L6423_clear : EdgeClearGlue.SlabClear ((6423 : ℝ) - 11841 / 200000) (6423 : ℝ) := by
  have h := slabOK_sound S_L6423 S_L6423_ok
  have hlo : S_L6423.lo.val = ((6423 : ℝ) - 11841 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 6423) (Q.cv_frac 11841 200000))
  have hhi : S_L6423.hi.val = (6423 : ℝ) := (Q.cv_nat 6423)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [6462, 1292411841/200000]` (3 cells, N = 1939). -/
noncomputable def S_U6462 : SlabD where
  tq := 14
  N := 1939
  L := (Q.frac 757 100)
  R := (Q.frac 177 2000)
  lo := (Q.ofNat 6462)
  hi := (Q.add (Q.ofNat 6462) (Q.frac 11841 200000))
  U := (Q.frac 6463 1)
  Qr := 34270000000000000000000000000000000000000000000000
  r0 := 44
  FN := 29
  FD := 100
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 105873893, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) },
    { a := 3, b := 0, q := 4, tn := 105873893, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) },
    { a := 11, b := 0, q := 12, tn := 105873893, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 105873893, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) }

theorem S_U6462_ok : slabOK S_U6462 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (6462 : ℝ) ((6462 : ℝ) + 11841 / 200000)`, hypothesis-free.** -/
theorem S_U6462_clear : EdgeClearGlue.SlabClear (6462 : ℝ) ((6462 : ℝ) + 11841 / 200000) := by
  have h := slabOK_sound S_U6462 S_U6462_ok
  have hlo : S_U6462.lo.val = (6462 : ℝ) := (Q.cv_nat 6462)
  have hhi : S_U6462.hi.val = ((6462 : ℝ) + 11841 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 6462) (Q.cv_frac 11841 200000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [6461939637/1000000, 6462]` (3 cells, N = 1939). -/
noncomputable def S_L6462 : SlabD where
  tq := 14
  N := 1939
  L := (Q.frac 757 100)
  R := (Q.frac 887 10000)
  lo := (Q.sub (Q.ofNat 6462) (Q.frac 60363 1000000))
  hi := (Q.ofNat 6462)
  U := (Q.frac 6463 1)
  Qr := 34260000000000000000000000000000000000000000000000
  r0 := 44
  FN := 293
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 105872914, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) },
    { a := 3, b := 0, q := 4, tn := 105872914, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) },
    { a := 11, b := 0, q := 12, tn := 105872914, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) }].getD j { a := 11, b := 0, q := 12, tn := 105872914, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) }

theorem S_L6462_ok : slabOK S_L6462 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((6462 : ℝ) - 60363 / 1000000) (6462 : ℝ)`, hypothesis-free.** -/
theorem S_L6462_clear : EdgeClearGlue.SlabClear ((6462 : ℝ) - 60363 / 1000000) (6462 : ℝ) := by
  have h := slabOK_sound S_L6462 S_L6462_ok
  have hlo : S_L6462.lo.val = ((6462 : ℝ) - 60363 / 1000000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 6462) (Q.cv_frac 60363 1000000))
  have hhi : S_L6462.hi.val = (6462 : ℝ) := (Q.cv_nat 6462)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [26001/4, 6500310363/1000000]` (3 cells, N = 1951). -/
noncomputable def S_U26001_4 : SlabD where
  tq := 14
  N := 1951
  L := (Q.frac 7577 1000)
  R := (Q.frac 887 10000)
  lo := (Q.frac 26001 4)
  hi := (Q.add (Q.frac 26001 4) (Q.frac 60363 1000000))
  U := (Q.frac 6501 1)
  Qr := 37000000000000000000000000000000000000000000000000
  r0 := 44
  FN := 297
  FD := 1000
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 106500590, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) },
    { a := 3, b := 0, q := 4, tn := 106500590, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) },
    { a := 11, b := 0, q := 12, tn := 106500590, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) }].getD j { a := 11, b := 0, q := 12, tn := 106500590, rn := 887, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 3867089 128000000) }

theorem S_U26001_4_ok : slabOK S_U26001_4 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (26001 / 4 : ℝ) ((26001 / 4 : ℝ) + 60363 / 1000000)`, hypothesis-free.** -/
theorem S_U26001_4_clear : EdgeClearGlue.SlabClear (26001 / 4 : ℝ) ((26001 / 4 : ℝ) + 60363 / 1000000) := by
  have h := slabOK_sound S_U26001_4 S_U26001_4_ok
  have hlo : S_U26001_4.lo.val = (26001 / 4 : ℝ) := (Q.cv_frac 26001 4)
  have hhi : S_U26001_4.hi.val = ((26001 / 4 : ℝ) + 60363 / 1000000) := (Q.cv_add _ _ _ _ (Q.cv_frac 26001 4) (Q.cv_frac 60363 1000000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [6499939241/1000000, 6500]` (7 cells, N = 1950). -/
noncomputable def S_L6500 : SlabD where
  tq := 14
  N := 1950
  L := (Q.frac 947 125)
  R := (Q.frac 111 1250)
  lo := (Q.sub (Q.ofNat 6500) (Q.frac 60759 1000000))
  hi := (Q.ofNat 6500)
  U := (Q.frac 6501 1)
  Qr := 36980000000000000000000000000000000000000000000000
  r0 := 44
  FN := 3
  FD := 10
  m := 7
  xs := fun j => [(Q.frac 1 2), (Q.frac 49 96), (Q.frac 25 48), (Q.frac 13 24), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 97, b := 0, q := 192, tn := 106495502, rn := 309, rd := 10000, w := (Q.frac 1 192), hh := (Q.frac 249 8192) },
    { a := 33, b := 0, q := 64, tn := 106495502, rn := 309, rd := 10000, w := (Q.frac 1 192), hh := (Q.frac 249 8192) },
    { a := 17, b := 0, q := 32, tn := 106495502, rn := 322, rd := 10000, w := (Q.frac 1 96), hh := (Q.frac 249 8192) },
    { a := 9, b := 0, q := 16, tn := 106495502, rn := 369, rd := 10000, w := (Q.frac 1 48), hh := (Q.frac 249 8192) },
    { a := 5, b := 0, q := 8, tn := 106495502, rn := 516, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 249 8192) },
    { a := 3, b := 0, q := 4, tn := 106495502, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) },
    { a := 11, b := 0, q := 12, tn := 106495502, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) }].getD j { a := 11, b := 0, q := 12, tn := 106495502, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) }

theorem S_L6500_ok : slabOK S_L6500 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((6500 : ℝ) - 60759 / 1000000) (6500 : ℝ)`, hypothesis-free.** -/
theorem S_L6500_clear : EdgeClearGlue.SlabClear ((6500 : ℝ) - 60759 / 1000000) (6500 : ℝ) := by
  have h := slabOK_sound S_L6500 S_L6500_ok
  have hlo : S_L6500.lo.val = ((6500 : ℝ) - 60759 / 1000000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 6500) (Q.cv_frac 60759 1000000))
  have hhi : S_L6500.hi.val = (6500 : ℝ) := (Q.cv_nat 6500)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [6538, 6538060759/1000000]` (4 cells, N = 1962). -/
noncomputable def S_U6538 : SlabD where
  tq := 14
  N := 1962
  L := (Q.frac 3791 500)
  R := (Q.frac 111 1250)
  lo := (Q.ofNat 6538)
  hi := (Q.add (Q.ofNat 6538) (Q.frac 60759 1000000))
  U := (Q.frac 6539 1)
  Qr := 39890000000000000000000000000000000000000000000000
  r0 := 44
  FN := 151
  FD := 500
  m := 4
  xs := fun j => [(Q.frac 1 2), (Q.frac 7 12), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 13, b := 0, q := 24, tn := 107119090, rn := 516, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 249 8192) },
    { a := 5, b := 0, q := 8, tn := 107119090, rn := 516, rd := 10000, w := (Q.frac 1 24), hh := (Q.frac 249 8192) },
    { a := 3, b := 0, q := 4, tn := 107119090, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) },
    { a := 11, b := 0, q := 12, tn := 107119090, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) }].getD j { a := 11, b := 0, q := 12, tn := 107119090, rn := 888, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 249 8192) }

theorem S_U6538_ok : slabOK S_U6538 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (6538 : ℝ) ((6538 : ℝ) + 60759 / 1000000)`, hypothesis-free.** -/
theorem S_U6538_clear : EdgeClearGlue.SlabClear (6538 : ℝ) ((6538 : ℝ) + 60759 / 1000000) := by
  have h := slabOK_sound S_U6538 S_U6538_ok
  have hlo : S_U6538.lo.val = (6538 : ℝ) := (Q.cv_nat 6538)
  have hhi : S_U6538.hi.val = ((6538 : ℝ) + 60759 / 1000000) := (Q.cv_add _ _ _ _ (Q.cv_nat 6538) (Q.cv_frac 60759 1000000))
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [1307588159/200000, 6538]` (3 cells, N = 1962). -/
noncomputable def S_L6538 : SlabD where
  tq := 14
  N := 1962
  L := (Q.frac 3791 500)
  R := (Q.frac 177 2000)
  lo := (Q.sub (Q.ofNat 6538) (Q.frac 11841 200000))
  hi := (Q.ofNat 6538)
  U := (Q.frac 6539 1)
  Qr := 39890000000000000000000000000000000000000000000000
  r0 := 44
  FN := 37
  FD := 125
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 107118107, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) },
    { a := 3, b := 0, q := 4, tn := 107118107, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) },
    { a := 11, b := 0, q := 12, tn := 107118107, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 107118107, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) }

theorem S_L6538_ok : slabOK S_L6538 = true := by decide +kernel

/-- **The zero-free slab `SlabClear ((6538 : ℝ) - 11841 / 200000) (6538 : ℝ)`, hypothesis-free.** -/
theorem S_L6538_clear : EdgeClearGlue.SlabClear ((6538 : ℝ) - 11841 / 200000) (6538 : ℝ) := by
  have h := slabOK_sound S_L6538 S_L6538_ok
  have hlo : S_L6538.lo.val = ((6538 : ℝ) - 11841 / 200000) := (Q.cv_sub _ _ _ _ (Q.cv_nat 6538) (Q.cv_frac 11841 200000))
  have hhi : S_L6538.hi.val = (6538 : ℝ) := (Q.cv_nat 6538)
  rw [hlo, hhi] at h
  exact h

/-- The slab `(0, 1) x [6577, 1315411841/200000]` (3 cells, N = 1974). -/
noncomputable def S_U6577 : SlabD where
  tq := 14
  N := 1974
  L := (Q.frac 1897 250)
  R := (Q.frac 177 2000)
  lo := (Q.ofNat 6577)
  hi := (Q.add (Q.ofNat 6577) (Q.frac 11841 200000))
  U := (Q.frac 6578 1)
  Qr := 43100000000000000000000000000000000000000000000000
  r0 := 44
  FN := 3
  FD := 10
  m := 3
  xs := fun j => [(Q.frac 1 2), (Q.frac 2 3), (Q.frac 5 6), (Q.frac 1 1)].getD j (Q.frac 1 1)
  cell := fun j => [{ a := 7, b := 0, q := 12, tn := 107758053, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) },
    { a := 3, b := 0, q := 4, tn := 107758053, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) },
    { a := 11, b := 0, q := 12, tn := 107758053, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) }].getD j { a := 11, b := 0, q := 12, tn := 107758053, rn := 885, rd := 10000, w := (Q.frac 1 12), hh := (Q.frac 1515671 51200000) }

theorem S_U6577_ok : slabOK S_U6577 = true := by decide +kernel

/-- **The zero-free slab `SlabClear (6577 : ℝ) ((6577 : ℝ) + 11841 / 200000)`, hypothesis-free.** -/
theorem S_U6577_clear : EdgeClearGlue.SlabClear (6577 : ℝ) ((6577 : ℝ) + 11841 / 200000) := by
  have h := slabOK_sound S_U6577 S_U6577_ok
  have hlo : S_U6577.lo.val = (6577 : ℝ) := (Q.cv_nat 6577)
  have hhi : S_U6577.hi.val = ((6577 : ℝ) + 11841 / 200000) := (Q.cv_add _ _ _ _ (Q.cv_nat 6577) (Q.cv_frac 11841 200000))
  rw [hlo, hhi] at h
  exact h

end Arb4.H7000
