/-  Arb4_BandGlue_h2000.lean -- K0 + K1 instantiated on a REAL ladder segment: `AllZeros_h2000`
    (the `[1000, 2000]` segment, 25 Turing bands).
    GENERATED by telperion/examples/zeta_reflection/emit_band_glue.py; DO NOT EDIT BY HAND.
    (Lane Arb4: `emit_band_glue.py ../zeta_zero_localization/lean 2000`, unmodified except the
    module name and the namespace, prefixed `Arb4.` so a later `BandGlue_h2000` cannot clash.)

    `seg` tabulates the segment's 25 bands as `BandGlue.BandData`, parameters copied verbatim
    from each band module's `statement_match`.  The kernel then checks:
      * `seg_edge`: the table's bands cover the segment's boxes (edges equal to `bLo`/`bHi`);
      * `seg_stmt`: every table entry's band statement is the band module's own
        `statement_match` (a mistyped entry would not type-check);
      * `seg_geom`: the K1 ball-cap geometry, with slab heights `capLo i`, `capHi i` (each band's
        own caps rounded up to a multiple of 1e-6; tight on purpose, see emit_band_glue.py).
    and composes them:
      * `boxCert_of_inputs`: a `BandGlue.BoxCert` for box `i` from band `i`'s Arb inputs;
      * `bandHyp_of_inputs`: `AllZeros_h2000.BandHyp` from the per-band Arb inputs (`hLine`, `hArbT`);
      * `bandHyp_of_reduced`: the same from the K1-reduced inputs (on-line zeros, two zero-free
        edge slabs, five enclosures; `hnzl` discharged outright).
    `AllZeros_h2000.BandHyp` is, by the capstone's own definitional check, the segment's
    `AllZeros_h280000_Indexed.SegBandHyp`.

    What is still ASSUMED: the per-band inputs themselves (the Arb trust boundary) and `hγ`.
    Nothing here evaluates zeta.  Axioms [propext, Classical.choice, Quot.sound]; no `sorry`.
    conjecture1_proved = False. -/
import Mathlib
import BandGlue
import AllZeros_h2000

open Complex

namespace Arb4.BandGlue_h2000

open BandGlue BandGlue.BandData

/-- The 25 Turing bands of `AllZeros_h2000`, in box order (parameters verbatim from each band
    module's `statement_match`). -/
noncomputable def seg : ℕ → BandData := fun i => match i with
  | 0 => ⟨(1000), (1040), 32, (52480184173 / 125000000000), (83968294677 / 200000000000), (-718849725111 / 1000000000000), (-71884972511 / 100000000000), (1321807620433 / 500000000000), (2643615240867 / 1000000000000), (101792370347533 / 1000000000000), (50896185173767 / 500000000000), (5089617075071 / 50000000000), (101792341501421 / 1000000000000),
      RHInBoxT_1d4000000_3999999d4000000_1000_1040.cPB, RHInBoxT_1d4000000_3999999d4000000_1000_1040.RPB, RHInBoxT_1d4000000_3999999d4000000_1000_1040.hs1PB⟩
  | 1 => ⟨(1040), (1080), 33, (-79552959 / 195312500), (-407311150079 / 1000000000000), (57933447031 / 25000000000), (2317337881241 / 1000000000000), (-718849725111 / 1000000000000), (-71884972511 / 100000000000), (102561788270049 / 1000000000000), (2051235765401 / 20000000000), (102561761560683 / 1000000000000), (25640440390171 / 250000000000),
      RHInBoxT_1d4000000_3999999d4000000_1040_1080.cPB, RHInBoxT_1d4000000_3999999d4000000_1040_1080.RPB, RHInBoxT_1d4000000_3999999d4000000_1040_1080.hs1PB⟩
  | 2 => ⟨(1080), (1120), 33, (309972555539 / 1000000000000), (15498627777 / 50000000000), (2437140462863 / 1000000000000), (152321278929 / 62500000000), (57933447031 / 25000000000), (2317337881241 / 1000000000000), (10330269612289 / 100000000000), (103302696122891 / 1000000000000), (103302671321333 / 1000000000000), (51651335660667 / 500000000000),
      RHInBoxT_1d4000000_3999999d4000000_1080_1120.cPB, RHInBoxT_1d4000000_3999999d4000000_1080_1120.RPB, RHInBoxT_1d4000000_3999999d4000000_1080_1120.hs1PB⟩
  | 3 => ⟨(1120), (1160), 33, (-75884156769 / 1000000000000), (-2371379899 / 31250000000), (1899783663227 / 1000000000000), (474945915807 / 250000000000), (2437140462863 / 1000000000000), (152321278929 / 62500000000), (104017131670603 / 1000000000000), (26004282917651 / 250000000000), (104017108579497 / 1000000000000), (52008554289749 / 500000000000),
      RHInBoxT_1d4000000_3999999d4000000_1120_1160.cPB, RHInBoxT_1d4000000_3999999d4000000_1120_1160.RPB, RHInBoxT_1d4000000_3999999d4000000_1120_1160.hs1PB⟩
  | 4 => ⟨(1160), (1200), 33, (-176882991019 / 1000000000000), (-88441495509 / 500000000000), (184842933483 / 1000000000000), (46210733371 / 250000000000), (1899783663227 / 1000000000000), (474945915807 / 250000000000), (26176730425051 / 250000000000), (20941384340041 / 200000000000), (104706900148503 / 1000000000000), (13088362518563 / 125000000000),
      RHInBoxT_1d4000000_3999999d4000000_1160_1200.cPB, RHInBoxT_1d4000000_3999999d4000000_1160_1200.RPB, RHInBoxT_1d4000000_3999999d4000000_1160_1200.hs1PB⟩
  | 5 => ⟨(1200), (1240), 34, (51926599507 / 125000000000), (415412796057 / 1000000000000), (558729397113 / 250000000000), (2234917588453 / 1000000000000), (184842933483 / 1000000000000), (46210733371 / 250000000000), (105373710179147 / 1000000000000), (26343427544787 / 250000000000), (105373690017877 / 1000000000000), (52686845008939 / 500000000000),
      RHInBoxT_1d4000000_3999999d4000000_1200_1240.cPB, RHInBoxT_1d4000000_3999999d4000000_1200_1240.RPB, RHInBoxT_1d4000000_3999999d4000000_1200_1240.hs1PB⟩
  | 6 => ⟨(1240), (1280), 33, (-246328315147 / 500000000000), (-492656630293 / 1000000000000), (-736299423009 / 500000000000), (-1472598846017 / 1000000000000), (558729397113 / 250000000000), (2234917588453 / 1000000000000), (106018981866587 / 1000000000000), (26504745466647 / 250000000000), (26504740741349 / 250000000000), (106018962965397 / 1000000000000),
      RHInBoxT_1d4000000_3999999d4000000_1240_1280.cPB, RHInBoxT_1d4000000_3999999d4000000_1240_1280.RPB, RHInBoxT_1d4000000_3999999d4000000_1240_1280.hs1PB⟩
  | 7 => ⟨(1280), (1320), 35, (189008538591 / 500000000000), (378017077183 / 1000000000000), (2197353021767 / 500000000000), (878941208707 / 200000000000), (-736299423009 / 500000000000), (-1472598846017 / 1000000000000), (106644082231517 / 1000000000000), (53322041115759 / 500000000000), (106644064475851 / 1000000000000), (26661016118963 / 250000000000),
      RHInBoxT_1d4000000_3999999d4000000_1280_1320.cPB, RHInBoxT_1d4000000_3999999d4000000_1280_1320.RPB, RHInBoxT_1d4000000_3999999d4000000_1280_1320.hs1PB⟩
  | 8 => ⟨((5279 / 4)), (1360), 34, (-31863463357 / 125000000000), (-50981541371 / 200000000000), (-2218447223959 / 1000000000000), (-1109223611979 / 500000000000), (-519257125913 / 1000000000000), (-64907140739 / 125000000000), (53959330693677 / 500000000000), (21583732277471 / 200000000000), (107918644568507 / 1000000000000), (26979661142127 / 250000000000),
      RHInBoxT_1d4000000_3999999d4000000_5279d4_1360.cPB, RHInBoxT_1d4000000_3999999d4000000_5279d4_1360.RPB, RHInBoxT_1d4000000_3999999d4000000_5279d4_1360.hs1PB⟩
  | 9 => ⟨(1360), (1400), 35, (10077512847 / 125000000000), (80620102777 / 1000000000000), (1854707447297 / 1000000000000), (927353723649 / 500000000000), (-2218447223959 / 1000000000000), (-1109223611979 / 500000000000), (107838553315383 / 1000000000000), (13479819164423 / 125000000000), (26959634389773 / 250000000000), (107838537559093 / 1000000000000),
      RHInBoxT_1d4000000_3999999d4000000_1360_1400.cPB, RHInBoxT_1d4000000_3999999d4000000_1360_1400.RPB, RHInBoxT_1d4000000_3999999d4000000_1360_1400.hs1PB⟩
  | 10 => ⟨(1400), (1440), 35, (319026888607 / 1000000000000), (9969590269 / 31250000000), (861607425373 / 200000000000), (2154018563433 / 500000000000), (1854707447297 / 1000000000000), (927353723649 / 500000000000), (108410058587721 / 1000000000000), (54205029293861 / 500000000000), (5420502185339 / 50000000000), (108410043706781 / 1000000000000),
      RHInBoxT_1d4000000_3999999d4000000_1400_1440.cPB, RHInBoxT_1d4000000_3999999d4000000_1400_1440.RPB, RHInBoxT_1d4000000_3999999d4000000_1400_1440.hs1PB⟩
  | 11 => ⟨(1440), (1480), 34, (-273356748603 / 500000000000), (-109342699441 / 200000000000), (27460234693 / 25000000000), (1098409387721 / 1000000000000), (861607425373 / 200000000000), (2154018563433 / 500000000000), (54482842313557 / 500000000000), (21793136925423 / 200000000000), (108965670550547 / 1000000000000), (27241417637637 / 250000000000),
      RHInBoxT_1d4000000_3999999d4000000_1440_1480.cPB, RHInBoxT_1d4000000_3999999d4000000_1440_1480.RPB, RHInBoxT_1d4000000_3999999d4000000_1440_1480.hs1PB⟩
  | 12 => ⟨(1480), (1520), 35, (459770296969 / 1000000000000), (45977029697 / 100000000000), (1077787703553 / 1000000000000), (538893851777 / 500000000000), (27460234693 / 25000000000), (1098409387721 / 1000000000000), (27376572522151 / 250000000000), (21901258017721 / 200000000000), (109506276752909 / 1000000000000), (10950627675291 / 100000000000),
      RHInBoxT_1d4000000_3999999d4000000_1480_1520.cPB, RHInBoxT_1d4000000_3999999d4000000_1480_1520.RPB, RHInBoxT_1d4000000_3999999d4000000_1480_1520.hs1PB⟩
  | 13 => ⟨(1520), (1560), 35, (-357498174781 / 1000000000000), (-17874908739 / 50000000000), (819475421613 / 500000000000), (1638950843227 / 1000000000000), (1077787703553 / 1000000000000), (538893851777 / 500000000000), (110032665806493 / 1000000000000), (55016332903247 / 500000000000), (110032653154679 / 1000000000000), (2750816328867 / 25000000000),
      RHInBoxT_1d4000000_3999999d4000000_1520_1560.cPB, RHInBoxT_1d4000000_3999999d4000000_1520_1560.RPB, RHInBoxT_1d4000000_3999999d4000000_1520_1560.hs1PB⟩
  | 14 => ⟨(1560), ((6401 / 4)), 36, (64773900167 / 250000000000), (259095600669 / 1000000000000), (4839369114551 / 1000000000000), (604921139319 / 125000000000), (819475421613 / 500000000000), (1638950843227 / 1000000000000), (13904754604891 / 125000000000), (111238036839129 / 1000000000000), (55619012373337 / 500000000000), (4449520989867 / 40000000000),
      RHInBoxT_1d4000000_3999999d4000000_1560_6401d4.cPB, RHInBoxT_1d4000000_3999999d4000000_1560_6401d4.RPB, RHInBoxT_1d4000000_3999999d4000000_1560_6401d4.hs1PB⟩
  | 15 => ⟨(1600), (1640), 36, (4731705783 / 50000000000), (94634115661 / 1000000000000), (1963962203089 / 500000000000), (3927924406179 / 1000000000000), (13696414207 / 1000000000000), (26750809 / 1953125000), (55522796567023 / 500000000000), (111045593134047 / 1000000000000), (888364653609 / 8000000000), (55522790850563 / 500000000000),
      RHInBoxT_1d4000000_3999999d4000000_1600_1640.cPB, RHInBoxT_1d4000000_3999999d4000000_1600_1640.RPB, RHInBoxT_1d4000000_3999999d4000000_1600_1640.hs1PB⟩
  | 16 => ⟨(1640), ((6721 / 4)), 35, (-351741760617 / 1000000000000), (-43967720077 / 125000000000), (3941321199 / 50000000000), (78826423981 / 1000000000000), (1963962203089 / 500000000000), (3927924406179 / 1000000000000), (112232039104817 / 1000000000000), (56116019552409 / 500000000000), (112232028149899 / 1000000000000), (1122320281499 / 10000000000),
      RHInBoxT_1d4000000_3999999d4000000_1640_6721d4.cPB, RHInBoxT_1d4000000_3999999d4000000_1640_6721d4.RPB, RHInBoxT_1d4000000_3999999d4000000_1640_6721d4.hs1PB⟩
  | 17 => ⟨(1680), (1720), 37, (260910573229 / 500000000000), (521821146459 / 1000000000000), (337029632741 / 125000000000), (2696237061929 / 1000000000000), (-4718626229443 / 1000000000000), (-2359313114721 / 500000000000), (22401936116341 / 200000000000), (56004840290853 / 500000000000), (2240193403993 / 20000000000), (112009670199651 / 1000000000000),
      RHInBoxT_1d4000000_3999999d4000000_1680_1720.cPB, RHInBoxT_1d4000000_3999999d4000000_1680_1720.RPB, RHInBoxT_1d4000000_3999999d4000000_1680_1720.hs1PB⟩
  | 18 => ⟨(1720), (1760), 35, (-95303337581 / 200000000000), (-14891146497 / 31250000000), (-1388910337027 / 1000000000000), (-694455168513 / 500000000000), (337029632741 / 125000000000), (2696237061929 / 1000000000000), (7029677388631 / 62500000000), (112474838218097 / 1000000000000), (112474828307953 / 1000000000000), (56237414153977 / 500000000000),
      RHInBoxT_1d4000000_3999999d4000000_1720_1760.cPB, RHInBoxT_1d4000000_3999999d4000000_1720_1760.RPB, RHInBoxT_1d4000000_3999999d4000000_1720_1760.hs1PB⟩
  | 19 => ⟨(1760), ((7201 / 4)), 37, (308788536149 / 1000000000000), (6175770723 / 20000000000), (1599050107999 / 500000000000), (3198100215999 / 1000000000000), (-1388910337027 / 1000000000000), (-694455168513 / 500000000000), (56818319566969 / 500000000000), (113636639133939 / 1000000000000), (113636629606383 / 1000000000000), (7102289350399 / 62500000000),
      RHInBoxT_1d4000000_3999999d4000000_1760_7201d4.cPB, RHInBoxT_1d4000000_3999999d4000000_1760_7201d4.RPB, RHInBoxT_1d4000000_3999999d4000000_1760_7201d4.hs1PB⟩
  | 20 => ⟨(1800), (1840), 36, (-5087231469 / 62500000000), (-81395703503 / 1000000000000), (-2005382445927 / 1000000000000), (-1002691222963 / 500000000000), (-1615048366123 / 1000000000000), (-807524183061 / 500000000000), (113373902801621 / 1000000000000), (56686951400811 / 500000000000), (56686946871827 / 500000000000), (22674778748731 / 200000000000),
      RHInBoxT_1d4000000_3999999d4000000_1800_1840.cPB, RHInBoxT_1d4000000_3999999d4000000_1800_1840.RPB, RHInBoxT_1d4000000_3999999d4000000_1800_1840.hs1PB⟩
  | 21 => ⟨(1840), (1880), 36, (-131791461489 / 1000000000000), (-8236966343 / 62500000000), (-3164558174621 / 1000000000000), (-158227908731 / 50000000000), (-2005382445927 / 1000000000000), (-1002691222963 / 500000000000), (113808719191329 / 1000000000000), (11380871919133 / 100000000000), (113808710518807 / 1000000000000), (14226088814851 / 125000000000),
      RHInBoxT_1d4000000_3999999d4000000_1840_1880.cPB, RHInBoxT_1d4000000_3999999d4000000_1840_1880.RPB, RHInBoxT_1d4000000_3999999d4000000_1840_1880.hs1PB⟩
  | 22 => ⟨(1880), (1920), 38, (451197663147 / 1000000000000), (112799415787 / 250000000000), (6225530930463 / 1000000000000), (194547841577 / 31250000000), (-3164558174621 / 1000000000000), (-158227908731 / 50000000000), (22846856555261 / 200000000000), (57117141388153 / 500000000000), (57117137232569 / 500000000000), (114234274465139 / 1000000000000),
      RHInBoxT_1d4000000_3999999d4000000_1880_1920.cPB, RHInBoxT_1d4000000_3999999d4000000_1880_1920.RPB, RHInBoxT_1d4000000_3999999d4000000_1880_1920.hs1PB⟩
  | 23 => ⟨((7679 / 4)), (1960), 36, (-114983065171 / 200000000000), (-287457662927 / 500000000000), (-1976217796119 / 1000000000000), (-988108898059 / 500000000000), (141176551697 / 100000000000), (1411765516971 / 1000000000000), (57683123261517 / 500000000000), (23073249304607 / 200000000000), (115366238500229 / 1000000000000), (11536623850023 / 100000000000),
      RHInBoxT_1d4000000_3999999d4000000_7679d4_1960.cPB, RHInBoxT_1d4000000_3999999d4000000_7679d4_1960.RPB, RHInBoxT_1d4000000_3999999d4000000_7679d4_1960.hs1PB⟩
  | 24 => ⟨(1960), (2000), 37, (186004705729 / 500000000000), (372009411459 / 1000000000000), (-360713375459 / 1000000000000), (-180356687729 / 500000000000), (-1976217796119 / 1000000000000), (-988108898059 / 500000000000), (57529585193781 / 500000000000), (115059170387563 / 1000000000000), (14382395341813 / 125000000000), (23011832546901 / 200000000000),
      RHInBoxT_1d4000000_3999999d4000000_1960_2000.cPB, RHInBoxT_1d4000000_3999999d4000000_1960_2000.RPB, RHInBoxT_1d4000000_3999999d4000000_1960_2000.hs1PB⟩
  | _ => default

/-- The bottom-edge slab heights: band `i`'s bottom ball cap, rounded up to a multiple of 1e-6. -/
noncomputable def capLo : ℕ → ℝ := fun i => match i with
  | 0 => (5773 / 100000)
  | 1 => (5773 / 100000)
  | 2 => (5773 / 100000)
  | 3 => (5773 / 100000)
  | 4 => (5773 / 100000)
  | 5 => (5773 / 100000)
  | 6 => (5773 / 100000)
  | 7 => (5773 / 100000)
  | 8 => (14343 / 250000)
  | 9 => (5773 / 100000)
  | 10 => (5773 / 100000)
  | 11 => (5773 / 100000)
  | 12 => (5773 / 100000)
  | 13 => (5773 / 100000)
  | 14 => (14343 / 250000)
  | 15 => (5773 / 100000)
  | 16 => (14343 / 250000)
  | 17 => (5773 / 100000)
  | 18 => (5773 / 100000)
  | 19 => (14343 / 250000)
  | 20 => (5773 / 100000)
  | 21 => (5773 / 100000)
  | 22 => (5773 / 100000)
  | 23 => (14343 / 250000)
  | 24 => (5773 / 100000)
  | _ => 0

/-- The top-edge slab heights: band `i`'s top ball cap, rounded up to a multiple of 1e-6. -/
noncomputable def capHi : ℕ → ℝ := fun i => match i with
  | 0 => (5773 / 100000)
  | 1 => (5773 / 100000)
  | 2 => (5773 / 100000)
  | 3 => (5773 / 100000)
  | 4 => (5773 / 100000)
  | 5 => (5773 / 100000)
  | 6 => (5773 / 100000)
  | 7 => (5773 / 100000)
  | 8 => (14343 / 250000)
  | 9 => (5773 / 100000)
  | 10 => (5773 / 100000)
  | 11 => (5773 / 100000)
  | 12 => (5773 / 100000)
  | 13 => (5773 / 100000)
  | 14 => (14343 / 250000)
  | 15 => (5773 / 100000)
  | 16 => (14343 / 250000)
  | 17 => (5773 / 100000)
  | 18 => (5773 / 100000)
  | 19 => (14343 / 250000)
  | 20 => (5773 / 100000)
  | 21 => (5773 / 100000)
  | 22 => (5773 / 100000)
  | 23 => (14343 / 250000)
  | 24 => (5773 / 100000)
  | _ => 0

/-- The table's bands cover the segment's boxes (their edges ARE the box edges `bLo`/`bHi`). -/
theorem seg_edge : ∀ i, i < 25 → (seg i).T0 ≤ AllZeros_h2000.bLo i ∧ AllZeros_h2000.bHi i ≤ (seg i).T1 := by
  intro i hi
  interval_cases i <;> exact ⟨le_rfl, le_rfl⟩

/-- Every table entry's band statement holds: it is the band module's `statement_match`. -/
theorem seg_stmt : ∀ i, i < 25 → (seg i).Stmt (1 / 4000000) (3999999 / 4000000) := by
  intro i hi
  interval_cases i
  · exact RHInBoxT_1d4000000_3999999d4000000_1000_1040.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1040_1080.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1080_1120.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1120_1160.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1160_1200.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1200_1240.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1240_1280.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1280_1320.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_5279d4_1360.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1360_1400.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1400_1440.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1440_1480.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1480_1520.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1520_1560.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1560_6401d4.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1600_1640.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1640_6721d4.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1680_1720.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1720_1760.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1760_7201d4.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1800_1840.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1840_1880.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1880_1920.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_7679d4_1960.statement_match
  · exact RHInBoxT_1d4000000_3999999d4000000_1960_2000.statement_match

/-- The K1 ball-cap geometry of every band, with slab heights `capLo i`, `capHi i`. -/
theorem seg_geom : ∀ i, i < 25 → (seg i).CapGeom (capLo i) (capHi i) := by
  intro i hi
  interval_cases i
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1000) (1040) (1020) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1040) (1080) (1060) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1080) (1120) (1100) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1120) (1160) (1140) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1160) (1200) (1180) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1200) (1240) (1220) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1240) (1280) (1260) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1280) (1320) (1300) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (14343 / 250000)) (δ1 := (14343 / 250000)) ((5279 / 4)) (1360) (10719 / 8) (26069 / 64)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1360) (1400) (1380) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1400) (1440) (1420) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1440) (1480) (1460) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1480) (1520) (1500) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1520) (1560) (1540) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (14343 / 250000)) (δ1 := (14343 / 250000)) (1560) ((6401 / 4)) (12641 / 8) (26069 / 64)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1600) (1640) (1620) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (14343 / 250000)) (δ1 := (14343 / 250000)) (1640) ((6721 / 4)) (13281 / 8) (26069 / 64)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1680) (1720) (1700) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1720) (1760) (1740) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (14343 / 250000)) (δ1 := (14343 / 250000)) (1760) ((7201 / 4)) (14241 / 8) (26069 / 64)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1800) (1840) (1820) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1840) (1880) (1860) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1880) (1920) (1900) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (14343 / 250000)) (δ1 := (14343 / 250000)) ((7679 / 4)) (1960) (15519 / 8) (26069 / 64)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  · exact CapGeom.of_sqrt (δ0 := (5773 / 100000)) (δ1 := (5773 / 100000)) (1960) (2000) (1980) (6437 / 16)
      rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)

/-- Each box of `AllZeros_h2000` has a band certificate once its band's Arb inputs hold (the
    certificate interface of `BandGlue.BoxCert`, filled by the real `rh_in_box_*` theorems). -/
theorem boxCert_of_inputs (i : ℕ) (hi : i < 25) (hin : (seg i).Inputs) :
    BoxCert (1 / 4000000) (3999999 / 4000000) (AllZeros_h2000.bLo i) (AllZeros_h2000.bHi i) :=
  BoxCert.of_stmt (seg i) (seg_edge i hi).1 (seg_edge i hi).2 (seg_stmt i hi) hin

/-- **K0 on `AllZeros_h2000`**: the segment's band hypothesis from the per-band Arb inputs
    (`hLine`, `hArbT` of each band theorem), composed through the real `rh_in_box_*` theorems. -/
theorem bandHyp_of_inputs (hin : ∀ i, i < 25 → (seg i).Inputs) : AllZeros_h2000.BandHyp :=
  segBandHyp_of_bands seg seg_edge seg_stmt hin

/-- **K0 + K1 on `AllZeros_h2000`**: the segment's band hypothesis from the reduced per-band inputs
    (on-line zeros, edge clearance at the two edges, five enclosures). -/
theorem bandHyp_of_reduced (hin : ∀ i, i < 25 → (seg i).ReducedInputs (capLo i) (capHi i)) :
    AllZeros_h2000.BandHyp :=
  segBandHyp_of_reduced seg seg_edge seg_stmt seg_geom hin

end Arb4.BandGlue_h2000
