/-  EMZetaHighK_T30000_P0.lean -- kernel chunks 0..20 (GENERATED by arbecon/gen_emhigh_k.py; do not edit).
    Each `chunk_i` is a kernel `decide +kernel` check that `ArbEcon.run` maps s_i to s_(i+1).
    conjecture1_proved = False.
-/
import EMZetaHighK_T30000_Cfg

namespace ArbEcon.IKK_T30000

theorem chunk_0 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s0) s1 = true := by decide +kernel
theorem chunk_1 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s1) s2 = true := by decide +kernel
theorem chunk_2 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s2) s3 = true := by decide +kernel
theorem chunk_3 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s3) s4 = true := by decide +kernel
theorem chunk_4 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s4) s5 = true := by decide +kernel
theorem chunk_5 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s5) s6 = true := by decide +kernel
theorem chunk_6 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s6) s7 = true := by decide +kernel
theorem chunk_7 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s7) s8 = true := by decide +kernel
theorem chunk_8 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s8) s9 = true := by decide +kernel
theorem chunk_9 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s9) s10 = true := by decide +kernel
theorem chunk_10 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s10) s11 = true := by decide +kernel
theorem chunk_11 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s11) s12 = true := by decide +kernel
theorem chunk_12 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s12) s13 = true := by decide +kernel
theorem chunk_13 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s13) s14 = true := by decide +kernel
theorem chunk_14 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s14) s15 = true := by decide +kernel
theorem chunk_15 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s15) s16 = true := by decide +kernel
theorem chunk_16 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s16) s17 = true := by decide +kernel
theorem chunk_17 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s17) s18 = true := by decide +kernel
theorem chunk_18 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s18) s19 = true := by decide +kernel
theorem chunk_19 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 500 s19) s20 = true := by decide +kernel
theorem chunk_20 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 57 s20) s21 = true := by decide +kernel
theorem chunk_N : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 30000 0) 1 s21) sN = true := by decide +kernel

end ArbEcon.IKK_T30000
