/-  EMZetaOfflineI_SM1_T9995.lean -- KERNEL-CHECKED order-13 Euler-Maclaurin enclosure of zeta(sigma + i t) OFF the
    critical line, sigma = (0 - 1)/1, t = 1999 / 2^1  (GENERATED by arbecon/gen_offline.py; do not edit).

      * the Dirichlet sum over n = 1..999: 2 `decide +kernel` chunks of the off-line evaluator
        `ArbEcon.Off.runO` at `EMZetaHighCfg64.cfg64 1999 1` (amplitude m^(-sigma) by a validated Newton
        root), composed by `ArbEcon.Off.chunkO_sound`, plus one step for the term n = 1000;
      * `check`: ONE `decide +kernel` run of `ArbEcon.Off.checkG` (exact correction factor, the
        order-13 odd-saw remainder valid for sigma > -2K, the four final inequalities, in Int);
      * `zeta_box` = `ArbEcon.Off.checkG_sound` (general, proved once).
    Certified: Re in [69122182, 69122185], Im in [-181643135, -181643132] (denominator 100000); remainder E = 7.6e-06.
    conjecture1_proved = False.  One point, finite interval arithmetic; nothing about RH.
-/
import EMZetaOfflineCheck

namespace ArbEcon.Off.I_SM1_T9995

noncomputable section

def oc : ArbEcon.Off.OCfg := ⟨0, 1, 1, 18446744073709551616, 64⟩
def s1 : ArbEcon.Off.StO := ⟨501, 114676141753773869465, 114676141753773875325, 9241818780928485359616, [⟨760063242740630875796934, 745035353881734188987808, 279119237646, 711340369180562647124181, 739830905737824786455728, 279119248350⟩]⟩
def s2 : ArbEcon.Off.StO := ⟨999, 127407137781600327069, 127407137781600336913, 18428297329635842064384, [⟨2950981586217247352196908, 2957233282245529605572675, 1790779471427, 2906302446679822056161501, 2936868728836440665597387, 1790779468932⟩]⟩
def sN : ArbEcon.Off.StO := ⟨1000, 127425593755199603543, 127425593755199613395, 18446744073709551616000, [⟨2962167981350629824032908, 2957233282245529605572675, 1795711805430, 2920970334422805890901501, 2936868728836440665597387, 1795711801935⟩]⟩

end

theorem chunk_0 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 1999 1) oc 500 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 1999 1) 0)) s1 = true := by decide +kernel
theorem chunk_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 1999 1) oc 498 s1) s2 = true := by decide +kernel
theorem chunk_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 1999 1) oc 1 s2) sN = true := by decide +kernel

theorem ht : (1999 / 2 : ℝ) = ((1999 : ℕ) : ℝ) / 2 ^ (1 : ℕ) := by norm_num
theorem hσ : (-1 : ℝ) = (((0 : ℕ) : ℝ) - ((1 : ℕ) : ℝ)) / ((1 : ℕ) : ℝ) := by norm_num
theorem valid : ArbEcon.Valid (ArbEcon.OrderK.cfg64 1999 1) (1999 / 2 : ℝ) 9 := ArbEcon.OrderK.valid64 1999 1 _ ht
theorem ovalid : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 1999 1) oc (-1 : ℝ) := ⟨by decide +kernel, by decide, hσ⟩

theorem inv_0 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 1999 1) (-1 : ℝ) (1999 / 2 : ℝ) 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 1999 1) 0) :=
  ArbEcon.Off.initO_sound _ _ _ 0 valid.one_eq
theorem inv_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 1999 1) (-1 : ℝ) (1999 / 2 : ℝ) 501 s1 :=
  ArbEcon.Off.chunkO_sound _ oc _ _ 9 valid ovalid 500 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 1999 1) 0) s1 inv_0 chunk_0
theorem inv_2 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 1999 1) (-1 : ℝ) (1999 / 2 : ℝ) 999 s2 :=
  ArbEcon.Off.chunkO_sound _ oc _ _ 9 valid ovalid 498 501 s1 s2 inv_1 chunk_1
theorem inv_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 1999 1) (-1 : ℝ) (1999 / 2 : ℝ) 1000 sN :=
  ArbEcon.Off.chunkO_sound _ oc _ _ 9 valid ovalid 1 999 s2 sN inv_2 chunk_N

/-- The whole order-13 assembly as ONE kernel computation (Int arithmetic). -/
theorem check : ArbEcon.Off.checkG (ArbEcon.OrderK.cfg64 1999 1) oc 6 1000 ⟨2950981586217247352196908, 2957233282245529605572675, 1790779471427, 2906302446679822056161501, 2936868728836440665597387, 1790779468932⟩ ⟨2962167981350629824032908, 2957233282245529605572675, 1795711805430, 2920970334422805890901501, 2936868728836440665597387, 1795711801935⟩ 100000 (69122182) (69122185) (-181643135) (-181643132) 8140976910858721389275241349604784372129738 4294967296000 4294967296 = true := by
  decide +kernel

/-- Negative control: the same data with the real interval collapsed to its lower end is REJECTED
    by the kernel checker. -/
theorem check_neg : ArbEcon.Off.checkG (ArbEcon.OrderK.cfg64 1999 1) oc 6 1000 ⟨2950981586217247352196908, 2957233282245529605572675, 1790779471427, 2906302446679822056161501, 2936868728836440665597387, 1790779468932⟩ ⟨2962167981350629824032908, 2957233282245529605572675, 1795711805430, 2920970334422805890901501, 2936868728836440665597387, 1795711801935⟩ 100000 (69122182) (69122182) (-181643135) (-181643132) 8140976910858721389275241349604784372129738 4294967296000 4294967296 = false := by
  decide +kernel

/-- **Re and Im of zeta(sigma + i t)**, sigma = (0 - 1)/1, t = 1999/2^1: kernel-checked, no hypotheses. -/
theorem zeta_box :
    (((69122182 : ℤ) : ℝ) / ((100000 : ℕ) : ℝ) ≤ (riemannZeta ((((-1 : ℝ) : ℝ) : ℂ) + (((1999 / 2 : ℝ) : ℝ) : ℂ) * Complex.I)).re ∧
      (riemannZeta ((((-1 : ℝ) : ℝ) : ℂ) + (((1999 / 2 : ℝ) : ℝ) : ℂ) * Complex.I)).re ≤ ((69122185 : ℤ) : ℝ) / ((100000 : ℕ) : ℝ)) ∧
    (((-181643135 : ℤ) : ℝ) / ((100000 : ℕ) : ℝ) ≤ (riemannZeta ((((-1 : ℝ) : ℝ) : ℂ) + (((1999 / 2 : ℝ) : ℝ) : ℂ) * Complex.I)).im ∧
      (riemannZeta ((((-1 : ℝ) : ℝ) : ℂ) + (((1999 / 2 : ℝ) : ℝ) : ℂ) * Complex.I)).im ≤ ((-181643132 : ℤ) : ℝ) / ((100000 : ℕ) : ℝ)) :=
  ArbEcon.Off.checkG_sound (ArbEcon.OrderK.cfg64 1999 1) oc _ _ hσ ht 6 1000 _ _
    (ArbEcon.Off.accOK_head _ _ _ _ _ _ _ inv_2 rfl) (ArbEcon.Off.accOK_head _ _ _ _ _ _ _ inv_N rfl)
    100000 (69122182) (69122185) (-181643135) (-181643132) 8140976910858721389275241349604784372129738 4294967296000 4294967296 check

/-- Literal form (cast normalisation only): `zeta(sigma + i t)` with complex literals. -/
theorem zeta_re_im :
    ((69122182 / 100000 : ℝ) ≤ (riemannZeta ((-1 : ℂ) + (1999 / 2 : ℂ) * Complex.I)).re ∧ (riemannZeta ((-1 : ℂ) + (1999 / 2 : ℂ) * Complex.I)).re ≤ (69122185 / 100000 : ℝ)) ∧
    ((-181643135 / 100000 : ℝ) ≤ (riemannZeta ((-1 : ℂ) + (1999 / 2 : ℂ) * Complex.I)).im ∧ (riemannZeta ((-1 : ℂ) + (1999 / 2 : ℂ) * Complex.I)).im ≤ (-181643132 / 100000 : ℝ)) := by
  have h := zeta_box
  push_cast at h
  exact h

end ArbEcon.Off.I_SM1_T9995
