/-  EMZetaHighK_T10000_P0.lean -- kernel chunks 0..6 (GENERATED by arbecon/gen_emhigh_k.py; do not edit).
    Each `chunk_i` is a kernel `decide +kernel` check that `ArbEcon.run` maps s_i to s_(i+1).
    conjecture1_proved = False.
-/
import EMZetaHighK_T10000_Cfg

namespace ArbEcon.IKK_T10000

theorem chunk_0 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 10000 0) 500 s0) s1 = true := by decide +kernel
theorem chunk_1 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 10000 0) 500 s1) s2 = true := by decide +kernel
theorem chunk_2 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 10000 0) 500 s2) s3 = true := by decide +kernel
theorem chunk_3 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 10000 0) 500 s3) s4 = true := by decide +kernel
theorem chunk_4 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 10000 0) 500 s4) s5 = true := by decide +kernel
theorem chunk_5 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 10000 0) 500 s5) s6 = true := by decide +kernel
theorem chunk_6 : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 10000 0) 210 s6) s7 = true := by decide +kernel
theorem chunk_N : ArbEcon.St.beq (ArbEcon.run (ArbEcon.OrderK.cfg64 10000 0) 1 s7) sN = true := by decide +kernel

end ArbEcon.IKK_T10000
