/-  H1000Slab_U720.lean -- a KERNEL-CHECKED zero-free edge slab `SlabClear a b`, a = 720, b = 72005773/100000
    (lane h1000-integrate; GENERATED by ../emit_h1000_offline.py; do not edit).

    3 cells cover [1/2, 1] x [a, b] (the reflection `ArbEcon.Off.slabClear_of_right_half` covers
    (0, 1/2)); each cell: ONE off-line evaluator run at its center (N = 217, 6 accumulators) and ONE
    `ArbEcon.Off.checkCell` (`decide +kernel`), assembled by `H1000Oct.cell_zeta_ne_zero_R` with the
    slab's error budget F = 1/200 at radius R = 441/5000 (`norm_num`).
    conjecture1_proved = False.  A finite zero-free slab; nothing about RH.
-/
import H1000Octant

open Complex ZetaReflection ZetaReflection.EMHigh

namespace H1000Slab.U720

noncomputable section

def oc0 : ArbEcon.Off.OCfg := ⟨7, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s0_1 : ArbEcon.Off.StO := ⟨216, 99156385111486784835, 99156385111486788246, 801964297286697639, [⟨121514795735510386038, 109527874764891021223, 10597255, 134063937506297409221, 118317797183536507695, 10597252⟩, ⟨375350700324562464859, 398667145620678263883, 47251210, 496164240423231548886, 441194870827336343486, 47254100⟩, ⟨1553121853464191143695, 1682460377997662049250, 218679195, 2031824730990777754692, 1822572083223263303917, 218701735⟩, ⟨6876069993135352739934, 7545111875210164401935, 1035931324, 8834327534529665368842, 7958555077845033542772, 1036065309⟩, ⟨31648807686968295658605, 34954642451986021113032, 4988324543, 39911484954256959351440, 36016581724466567200818, 4989047458⟩, ⟨149373492128900136375874, 165385366461765997642820, 24316857108, 185127565077532322949594, 167180953335717969290902, 24320578190⟩]⟩
def s0_N : ArbEcon.Off.StO := ⟨217, 99241589623588171586, 99241589623588175012, 799806405048919904, [⟨121514795735510386038, 110323869484998971814, 10650949, 134141929115573935433, 118317797183536507695, 10650946⟩, ⟨375350700324562464859, 402949515508819206192, 47540228, 496583827275576693819, 441194870827336343486, 47542985⟩, ⟨1553121853464191143695, 1705499088425752859124, 220234880, 2034082065187289771535, 1822572083223263303917, 220255986⟩, ⟨6876069993135352739934, 7669057772471235140864, 1044305030, 8846471760799536748203, 7958555077845033542772, 1044427441⟩, ⟨31648807686968295658605, 35621458656643053291199, 5033397243, 39976819645027036913547, 36016581724466567200818, 5034037127⟩, ⟨149373492128900136375874, 168972769196498258602954, 24559467453, 185479059007500647523584, 167180953335717969290902, 24562630128⟩]⟩
def oc1 : ArbEcon.Off.OCfg := ⟨3, 0, 4, 115792089237316195423570985008687907853269984665640564039457584007913129639936, 64⟩
def s1_1 : ArbEcon.Off.StO := ⟨216, 99156385111486784835, 99156385111486788246, 327400553380347528, [⟨76098428321096597150, 61596739444956138626, 5099121, 73881197442942435019, 64957839712757263327, 5099120⟩, ⟨191703939795984331947, 200647678600559644162, 22020381, 254555618359568290685, 224806243757422208353, 22021883⟩, ⟨751204650777074744370, 804718791802759129435, 99868098, 995101828119057401693, 889228977242631483701, 99879728⟩, ⟨3218341078326138070401, 3509669595244965958140, 466396551, 4194048921744906621654, 3772189013516330579591, 466464724⟩, ⟨14497010380376082896082, 15966417107207670221802, 2221841830, 18535261147246883776284, 16716074865578358182308, 2222205037⟩, ⟨67374119093685761395003, 74558148541982704940569, 10739747235, 84586413908318185837746, 76357257530557731881059, 10741598447⟩]⟩
def s1_N : ArbEcon.Off.StO := ⟨217, 99241589623588171586, 99241589623588175012, 326268331567320428, [⟨76098428321096597150, 61921452860135818633, 5121026, 73913012882371613070, 64957839712757263327, 5121025⟩, ⟨191703939795984331947, 202394603443543889159, 22138290, 254726782157955052474, 224806243757422208353, 22139737⟩, ⟨751204650777074744370, 814117068142364152155, 100502763, 996022671785020274243, 889228977242631483701, 100513804⟩, ⟨3218341078326138070401, 3560231357252248938351, 469812731, 4199002966146444774754, 3772189013516330579591, 469876161⟩, ⟨14497010380376082896082, 16238434196820994487429, 2240229920, 18561913397612040816522, 16716074865578358182308, 2240559140⟩, ⟨67374119093685761395003, 76021572562511206219704, 10838723794, 84729800279523591948631, 76357257530557731881059, 10840346589⟩]⟩
def oc2 : ArbEcon.Off.OCfg := ⟨11, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s2_1 : ArbEcon.Off.StO := ⟨216, 99156385111486784835, 99156385111486788246, 133660716214449606, [⟨52500292189955652296, 37066908937899526358, 2518552, 42555784917277091455, 37395017928132680413, 2518549⟩, ⟨101880727018071699661, 105016137200736000720, 10439260, 135000318211310426931, 118212571857385392630, 10440045⟩, ⟨373007673967162049685, 393789496311650839589, 46171545, 499189242975824134150, 443649688527426128657, 46177619⟩, ⟨1533602715589582492804, 1657660853830291450186, 211953194, 2026692296867394885918, 1818271374392778499567, 211988292⟩, ⟨6727842962297971111435, 7374993066945843396751, 997001843, 8724668738586082858299, 7861102656911139355745, 997186197⟩, ⟨30695778975309380300007, 33903088482886897055352, 4772196623, 39056499204309818980418, 35245982625070922573784, 4773125562⟩]⟩
def s2_N : ArbEcon.Off.StO := ⟨217, 99241589623588171586, 99241589623588175012, 133095988618910718, [⟨52500292189955652296, 37199370623051598629, 2527489, 42568763520943067538, 37395017928132680413, 2527486⟩, ⟨101880727018071699661, 105728767470131143933, 10487367, 135070141766825662168, 118212571857385392630, 10488130⟩, ⟨373007673967162049685, 397623374012022595398, 46430490, 499564886537355333569, 443649688527426128657, 46436326⟩, ⟨1533602715589582492804, 1678286722324319242690, 213347006, 2028713220669951098497, 1818271374392778499567, 213380181⟩, ⟨6727842962297971111435, 7485958122271337064218, 1004504241, 8735541101203161948816, 7861102656911139355745, 1004674794⟩, ⟨30695778975309380300007, 34500069090367991128566, 4812579365, 39114991399180175005692, 35245982625070922573784, 4813415467⟩]⟩

end

theorem budget : ArbEcon.Off.Cp 5 * ((441 / 5000 : ℝ) * (269 / 50 : ℝ)) ^ (5 + 1) * ((((217 : ℕ) : ℝ)) - 1 + ArbEcon.Off.emcB 6 217 (720 : ℝ) (721 : ℝ))
    + 3 * ArbEcon.Off.corrVar 6 217 (441 / 5000 : ℝ) (720 : ℝ) (721 : ℝ)
    + ArbEcon.Off.CK 6 * (14000000000000000000000000000000000000 : ℝ) / ((((217 : ℕ) : ℝ)) ^ (2 * 6) * ((14 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ ((1 : ℕ) : ℝ) / ((200 : ℕ) : ℝ) := by
  have hC := H1000Oct.CK_six_le
  have hC0 := ArbEcon.Off.CK_nonneg 6
  have hm : ArbEcon.Off.CK 6 * (14000000000000000000000000000000000000 : ℝ) / ((((217 : ℕ) : ℝ)) ^ (2 * 6) * ((14 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ (84107 / 1000000000000000 : ℝ) * (14000000000000000000000000000000000000 : ℝ) / ((((217 : ℕ) : ℝ)) ^ (2 * 6) * ((14 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2) := by
    gcongr
  refine le_trans (add_le_add (le_refl _) hm) ?_
  rw [H1000Oct.emcB_betaN 6 217 (by norm_num), H1000Oct.corrVar_betaN 6 217 (by norm_num)]
  unfold ArbEcon.Off.Cp
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, ArbEcon.OrderK.betaN, ArbEcon.OrderK.Lbeta]
  norm_num [Nat.factorial]

theorem hQ : pochNormSq 1 ((720 : ℝ) + 5773 / 100000) (2 * 6 + 1) ≤ (14000000000000000000000000000000000000 : ℝ) ^ 2 := by
  simp only [pochNormSq]
  norm_num

/-! ### Cell 0: [1/2, 2/3] x [720, 72005773/100000] -/

theorem chunk0_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11796953 14) oc0 215 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11796953 14) 5)) s0_1 = true := by
  decide +kernel
theorem chunk0_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11796953 14) oc0 1 s0_1) s0_N = true := by
  decide +kernel
theorem check0 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 11796953 14) oc0 6 217 5 s0_1.acc s0_N.acc 882 10000 1 200 = true := by
  decide +kernel
theorem ht0 : (11796953 / 16384 : ℝ) = ((11796953 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid0 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 11796953 14) (11796953 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 11796953 14 _ ht0
theorem hσ0 : (7 / 12 : ℝ) = (((7 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid0 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 11796953 14) oc0 (7 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ0⟩
theorem inv0_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11796953 14) (7 / 12 : ℝ) (11796953 / 16384 : ℝ) (217 - 1) s0_1 :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 215 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11796953 14) 5) s0_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid0.one_eq) chunk0_1
theorem inv0_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11796953 14) (7 / 12 : ℝ) (11796953 / 16384 : ℝ) 217 s0_N :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 1 216 s0_1 s0_N inv0_1 chunk0_N
theorem cell0 : ∀ x y : ℝ, (1 / 2 : ℝ) ≤ x → x ≤ (2 / 3 : ℝ) → (720 : ℝ) ≤ y → y ≤ (72005773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s0_N.lhi : ℝ) ≤ (269 / 50 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 11796953 14)).P := by
    show ((99241589623588175012 : ℕ) : ℝ) ≤ (269 / 50 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 11796953 14) oc0 (7 / 12 : ℝ) (11796953 / 16384 : ℝ) hσ0 ht0 6 217 5 (by norm_num) (by norm_num)
    s0_1 s0_N inv0_1 inv0_N 882 10000 1 200 check0 (441 / 5000 : ℝ) (269 / 50 : ℝ) (720 : ℝ) (721 : ℝ) ((720 : ℝ) + 5773 / 100000) (14000000000000000000000000000000000000 : ℝ) 14 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (7 / 12 : ℝ) (11796953 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 1: [2/3, 5/6] x [720, 72005773/100000] -/

theorem chunk1_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11796953 14) oc1 215 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11796953 14) 5)) s1_1 = true := by
  decide +kernel
theorem chunk1_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11796953 14) oc1 1 s1_1) s1_N = true := by
  decide +kernel
theorem check1 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 11796953 14) oc1 6 217 5 s1_1.acc s1_N.acc 882 10000 1 200 = true := by
  decide +kernel
theorem ht1 : (11796953 / 16384 : ℝ) = ((11796953 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid1 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 11796953 14) (11796953 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 11796953 14 _ ht1
theorem hσ1 : (3 / 4 : ℝ) = (((3 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((4 : ℕ) : ℝ) := by norm_num
theorem ovalid1 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 11796953 14) oc1 (3 / 4 : ℝ) := ⟨by decide +kernel, by decide, hσ1⟩
theorem inv1_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11796953 14) (3 / 4 : ℝ) (11796953 / 16384 : ℝ) (217 - 1) s1_1 :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 215 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11796953 14) 5) s1_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid1.one_eq) chunk1_1
theorem inv1_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11796953 14) (3 / 4 : ℝ) (11796953 / 16384 : ℝ) 217 s1_N :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 1 216 s1_1 s1_N inv1_1 chunk1_N
theorem cell1 : ∀ x y : ℝ, (2 / 3 : ℝ) ≤ x → x ≤ (5 / 6 : ℝ) → (720 : ℝ) ≤ y → y ≤ (72005773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s1_N.lhi : ℝ) ≤ (269 / 50 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 11796953 14)).P := by
    show ((99241589623588175012 : ℕ) : ℝ) ≤ (269 / 50 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 11796953 14) oc1 (3 / 4 : ℝ) (11796953 / 16384 : ℝ) hσ1 ht1 6 217 5 (by norm_num) (by norm_num)
    s1_1 s1_N inv1_1 inv1_N 882 10000 1 200 check1 (441 / 5000 : ℝ) (269 / 50 : ℝ) (720 : ℝ) (721 : ℝ) ((720 : ℝ) + 5773 / 100000) (14000000000000000000000000000000000000 : ℝ) 14 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (3 / 4 : ℝ) (11796953 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 2: [5/6, 1] x [720, 72005773/100000] -/

theorem chunk2_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11796953 14) oc2 215 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11796953 14) 5)) s2_1 = true := by
  decide +kernel
theorem chunk2_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11796953 14) oc2 1 s2_1) s2_N = true := by
  decide +kernel
theorem check2 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 11796953 14) oc2 6 217 5 s2_1.acc s2_N.acc 882 10000 1 200 = true := by
  decide +kernel
theorem ht2 : (11796953 / 16384 : ℝ) = ((11796953 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid2 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 11796953 14) (11796953 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 11796953 14 _ ht2
theorem hσ2 : (11 / 12 : ℝ) = (((11 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid2 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 11796953 14) oc2 (11 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ2⟩
theorem inv2_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11796953 14) (11 / 12 : ℝ) (11796953 / 16384 : ℝ) (217 - 1) s2_1 :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 215 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11796953 14) 5) s2_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid2.one_eq) chunk2_1
theorem inv2_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11796953 14) (11 / 12 : ℝ) (11796953 / 16384 : ℝ) 217 s2_N :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 1 216 s2_1 s2_N inv2_1 chunk2_N
theorem cell2 : ∀ x y : ℝ, (5 / 6 : ℝ) ≤ x → x ≤ (1 : ℝ) → (720 : ℝ) ≤ y → y ≤ (72005773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s2_N.lhi : ℝ) ≤ (269 / 50 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 11796953 14)).P := by
    show ((99241589623588175012 : ℕ) : ℝ) ≤ (269 / 50 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 11796953 14) oc2 (11 / 12 : ℝ) (11796953 / 16384 : ℝ) hσ2 ht2 6 217 5 (by norm_num) (by norm_num)
    s2_1 s2_N inv2_1 inv2_N 882 10000 1 200 check2 (441 / 5000 : ℝ) (269 / 50 : ℝ) (720 : ℝ) (721 : ℝ) ((720 : ℝ) + 5773 / 100000) (14000000000000000000000000000000000000 : ℝ) 14 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (11 / 12 : ℝ) (11796953 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-- The right half of the slab. -/
theorem right_half : ∀ x y : ℝ, 1 / 2 ≤ x → x < 1 → (720 : ℝ) ≤ y → y ≤ ((720 : ℝ) + 5773 / 100000) →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1
  by_cases h0 : x ≤ (2 / 3 : ℝ)
  · exact cell0 x y (by linarith) h0 (by linarith) (by linarith) (by linarith)
  by_cases h1 : x ≤ (5 / 6 : ℝ)
  · exact cell1 x y (by linarith) h1 (by linarith) (by linarith) (by linarith)
  exact cell2 x y (by linarith) (by linarith) (by linarith) (by linarith) (by linarith)

/-- **The edge-clearance slab `SlabClear 720 72005773/100000`, hypothesis-free.** -/
theorem slabClear : EdgeClearGlue.SlabClear (720 : ℝ) ((720 : ℝ) + 5773 / 100000) :=
  ArbEcon.Off.slabClear_of_right_half _ _ right_half

end H1000Slab.U720
