/-  H1000Slab_U680.lean -- a KERNEL-CHECKED zero-free edge slab `SlabClear a b`, a = 680, b = 68005773/100000
    (lane h1000-integrate; GENERATED by ../emit_h1000_offline.py; do not edit).

    3 cells cover [1/2, 1] x [a, b] (the reflection `ArbEcon.Off.slabClear_of_right_half` covers
    (0, 1/2)); each cell: ONE off-line evaluator run at its center (N = 205, 6 accumulators) and ONE
    `ArbEcon.Off.checkCell` (`decide +kernel`), assembled by `H1000Oct.cell_zeta_ne_zero_R` with the
    slab's error budget F = 113/25000 at radius R = 441/5000 (`norm_num`).
    conjecture1_proved = False.  A finite zero-free slab; nothing about RH.
-/
import H1000Octant

open Complex ZetaReflection ZetaReflection.EMHigh

namespace H1000Slab.U680

noncomputable section

def oc0 : ArbEcon.Off.OCfg := ⟨7, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s0_1 : ArbEcon.Off.StO := ⟨204, 98101998479722074808, 98101998479722078013, 829154492504337699, [⟨139310984948595444657, 113545925929992610689, 9408166, 127059825306472581653, 92593166305972049276, 9408167⟩, ⟨376646350201502081952, 448363548581682469263, 41415655, 479321110692241793715, 354074819135977088963, 41416140⟩, ⟨1465556292077877608284, 1869661496814528580548, 189355324, 1966838452777882520305, 1488056619985611622096, 189361105⟩, ⟨6316787221068844363844, 8129555620607633716423, 886484707, 8496345022609111332045, 6590453328175224850093, 886524861⟩, ⟨28656500621474172385015, 36491312294414334812954, 4219476085, 37977080971581748804018, 30140041933578584635692, 4219705695⟩, ⟨133907841469652168494780, 167828336164238458695057, 20334679822, 173928015521929343461367, 140839738496335255307480, 20335852195⟩]⟩
def s0_N : ArbEcon.Off.StO := ⟨205, 98192202786968234028, 98192202786968237252, 826792706515843950, [⟨139950891025633283370, 113545925929992610689, 9457508, 127059825306472581653, 93116718015087622782, 9457509⟩, ⟨380052576635285808492, 448363548581682469263, 41678416, 479321110692241793715, 356861690108194255900, 41678881⟩, ⟨1483687669376113417387, 1869661496814528580548, 190754601, 1966838452777882520305, 1502891161981294759525, 190760167⟩, ⟨6413300723362877167868, 8129555620607633716423, 893936243, 8496345022609111332045, 6669417743254193989260, 893974676⟩, ⟨29170242957306906662582, 36491312294414334812954, 4259157555, 37977080971581748804018, 30560370303040764766811, 4259374937⟩, ⟨136642497049995688531480, 167828336164238458695057, 20545994473, 173928015521929343461367, 143077150601497415942775, 20547085431⟩]⟩
def oc1 : ArbEcon.Off.OCfg := ⟨3, 0, 4, 115792089237316195423570985008687907853269984665640564039457584007913129639936, 64⟩
def s1_1 : ArbEcon.Off.StO := ⟨204, 98101998479722074808, 98101998479722078013, 341741008654796203, [⟨92812294712875724396, 59527734893594196392, 4569683, 68990606669138424080, 49998831711115130815, 4569684⟩, ⟨201712188346227745479, 226159539263887002873, 19480942, 245041089849128167305, 178240479085077396193, 19481092⟩, ⟨725049558921428664680, 913819263905548373240, 87279516, 966494101575736257962, 718051688181977228096, 87282113⟩, ⟨2993208580043822466939, 3875050427018810611608, 402816001, 4062630933203347985610, 3095998496724978662018, 402835353⟩, ⟨13235257650674365380130, 17053678205513311228941, 1896836593, 17801543734500078912357, 13902465454002075083632, 1896951262⟩, ⟨60810685570433578521345, 77216877566057528548866, 9064455988, 80303009361967819431350, 64104506434565272931144, 9065060441⟩]⟩
def s1_N : ArbEcon.Off.StO := ⟨205, 98192202786968234028, 98192202786968237252, 340489972757168229, [⟨93075820988592314550, 59527734893594196392, 4590004, 68990606669138424080, 50214440902837378291, 4590005⟩, ⟨203114941341632334467, 226159539263887002873, 19589159, 245041089849128167305, 179388168964208885805, 19589300⟩, ⟨732516427114233585660, 913819263905548373240, 87855804, 966494101575736257962, 724160852861550300956, 87858308⟩, ⟨3032954793947034233834, 3875050427018810611608, 405884895, 4062630933203347985610, 3128517641278546025397, 405903514⟩, ⟨13446827143914131361283, 17053678205513311228941, 1913179295, 17801543734500078912357, 14075565184973758578399, 1913288799⟩, ⟨61936872094230108852132, 77216877566057528548866, 9151485332, 80303009361967819431350, 65025918029913717979380, 9152055569⟩]⟩
def oc2 : ArbEcon.Off.OCfg := ⟨11, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s2_1 : ArbEcon.Off.StO := ⟨204, 98101998479722074808, 98101998479722078013, 140850611137207974, [⟨67322141515498819645, 32011487533556466669, 2277712, 38935372765855169574, 28262447309883843373, 2277714⟩, ⟨113915391736689407132, 116662233345490745409, 9319863, 128879861131837735285, 92614463330029473209, 9319874⟩, ⟨370993670840162235030, 455154111251259606517, 40720806, 484930556952018940885, 354007216910414067525, 40721902⟩, ⟨1448861936938046985347, 1875991872815629621596, 184737649, 1973435705000729886067, 1476502298814691150567, 184746711⟩, ⟨6201389043368299180814, 8071199764161199966362, 858987885, 8447417062543301949730, 6484629652802244902702, 859043688⟩, ⟨27904135604570286915920, 35894918849614043457287, 4064914052, 37441719264763304828373, 29431364165358004216939, 4065216173⟩]⟩
def s2_N : ArbEcon.Off.StO := ⟨205, 98192202786968234028, 98192202786968237252, 140220663093083918, [⟨67430666970225748001, 32011487533556466669, 2286082, 38935372765855169574, 28351239539468292768, 2286084⟩, ⟨114493073815191380314, 116662233345490745409, 9364437, 128879861131837735285, 93087105254177445943, 9364445⟩, ⟨374068678308797655642, 455154111251259606517, 40958176, 484930556952018940885, 356523094589212905025, 40959238⟩, ⟨1465230232379518465327, 1875991872815629621596, 186001711, 1973435705000729886067, 1489894340805228937660, 186010494⟩, ⟨6288517643344737587106, 8071199764161199966362, 865719362, 8447417062543301949730, 6555915625958918136714, 865773160⟩, ⟨28367922011713227038728, 35894918849614043457287, 4100761001, 37441719264763304828373, 29810820111843568542248, 4101049680⟩]⟩

end

theorem budget : ArbEcon.Off.Cp 5 * ((441 / 5000 : ℝ) * (1331 / 250 : ℝ)) ^ (5 + 1) * ((((205 : ℕ) : ℝ)) - 1 + ArbEcon.Off.emcB 6 205 (680 : ℝ) (681 : ℝ))
    + 3 * ArbEcon.Off.corrVar 6 205 (441 / 5000 : ℝ) (680 : ℝ) (681 : ℝ)
    + ArbEcon.Off.CK 6 * (6661000000000000000000000000000000000 : ℝ) / ((((205 : ℕ) : ℝ)) ^ (2 * 6) * ((14 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ ((113 : ℕ) : ℝ) / ((25000 : ℕ) : ℝ) := by
  have hC := H1000Oct.CK_six_le
  have hC0 := ArbEcon.Off.CK_nonneg 6
  have hm : ArbEcon.Off.CK 6 * (6661000000000000000000000000000000000 : ℝ) / ((((205 : ℕ) : ℝ)) ^ (2 * 6) * ((14 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ (84107 / 1000000000000000 : ℝ) * (6661000000000000000000000000000000000 : ℝ) / ((((205 : ℕ) : ℝ)) ^ (2 * 6) * ((14 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2) := by
    gcongr
  refine le_trans (add_le_add (le_refl _) hm) ?_
  rw [H1000Oct.emcB_betaN 6 205 (by norm_num), H1000Oct.corrVar_betaN 6 205 (by norm_num)]
  unfold ArbEcon.Off.Cp
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, ArbEcon.OrderK.betaN, ArbEcon.OrderK.Lbeta]
  norm_num [Nat.factorial]

theorem hQ : pochNormSq 1 ((680 : ℝ) + 5773 / 100000) (2 * 6 + 1) ≤ (6661000000000000000000000000000000000 : ℝ) ^ 2 := by
  simp only [pochNormSq]
  norm_num

/-! ### Cell 0: [1/2, 2/3] x [680, 68005773/100000] -/

theorem chunk0_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11141593 14) oc0 203 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11141593 14) 5)) s0_1 = true := by
  decide +kernel
theorem chunk0_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11141593 14) oc0 1 s0_1) s0_N = true := by
  decide +kernel
theorem check0 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 11141593 14) oc0 6 205 5 s0_1.acc s0_N.acc 882 10000 113 25000 = true := by
  decide +kernel
theorem ht0 : (11141593 / 16384 : ℝ) = ((11141593 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid0 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 11141593 14) (11141593 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 11141593 14 _ ht0
theorem hσ0 : (7 / 12 : ℝ) = (((7 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid0 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 11141593 14) oc0 (7 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ0⟩
theorem inv0_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11141593 14) (7 / 12 : ℝ) (11141593 / 16384 : ℝ) (205 - 1) s0_1 :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 203 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11141593 14) 5) s0_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid0.one_eq) chunk0_1
theorem inv0_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11141593 14) (7 / 12 : ℝ) (11141593 / 16384 : ℝ) 205 s0_N :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 1 204 s0_1 s0_N inv0_1 chunk0_N
theorem cell0 : ∀ x y : ℝ, (1 / 2 : ℝ) ≤ x → x ≤ (2 / 3 : ℝ) → (680 : ℝ) ≤ y → y ≤ (68005773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s0_N.lhi : ℝ) ≤ (1331 / 250 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 11141593 14)).P := by
    show ((98192202786968237252 : ℕ) : ℝ) ≤ (1331 / 250 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 11141593 14) oc0 (7 / 12 : ℝ) (11141593 / 16384 : ℝ) hσ0 ht0 6 205 5 (by norm_num) (by norm_num)
    s0_1 s0_N inv0_1 inv0_N 882 10000 113 25000 check0 (441 / 5000 : ℝ) (1331 / 250 : ℝ) (680 : ℝ) (681 : ℝ) ((680 : ℝ) + 5773 / 100000) (6661000000000000000000000000000000000 : ℝ) 14 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (7 / 12 : ℝ) (11141593 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 1: [2/3, 5/6] x [680, 68005773/100000] -/

theorem chunk1_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11141593 14) oc1 203 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11141593 14) 5)) s1_1 = true := by
  decide +kernel
theorem chunk1_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11141593 14) oc1 1 s1_1) s1_N = true := by
  decide +kernel
theorem check1 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 11141593 14) oc1 6 205 5 s1_1.acc s1_N.acc 882 10000 113 25000 = true := by
  decide +kernel
theorem ht1 : (11141593 / 16384 : ℝ) = ((11141593 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid1 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 11141593 14) (11141593 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 11141593 14 _ ht1
theorem hσ1 : (3 / 4 : ℝ) = (((3 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((4 : ℕ) : ℝ) := by norm_num
theorem ovalid1 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 11141593 14) oc1 (3 / 4 : ℝ) := ⟨by decide +kernel, by decide, hσ1⟩
theorem inv1_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11141593 14) (3 / 4 : ℝ) (11141593 / 16384 : ℝ) (205 - 1) s1_1 :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 203 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11141593 14) 5) s1_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid1.one_eq) chunk1_1
theorem inv1_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11141593 14) (3 / 4 : ℝ) (11141593 / 16384 : ℝ) 205 s1_N :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 1 204 s1_1 s1_N inv1_1 chunk1_N
theorem cell1 : ∀ x y : ℝ, (2 / 3 : ℝ) ≤ x → x ≤ (5 / 6 : ℝ) → (680 : ℝ) ≤ y → y ≤ (68005773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s1_N.lhi : ℝ) ≤ (1331 / 250 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 11141593 14)).P := by
    show ((98192202786968237252 : ℕ) : ℝ) ≤ (1331 / 250 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 11141593 14) oc1 (3 / 4 : ℝ) (11141593 / 16384 : ℝ) hσ1 ht1 6 205 5 (by norm_num) (by norm_num)
    s1_1 s1_N inv1_1 inv1_N 882 10000 113 25000 check1 (441 / 5000 : ℝ) (1331 / 250 : ℝ) (680 : ℝ) (681 : ℝ) ((680 : ℝ) + 5773 / 100000) (6661000000000000000000000000000000000 : ℝ) 14 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (3 / 4 : ℝ) (11141593 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 2: [5/6, 1] x [680, 68005773/100000] -/

theorem chunk2_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11141593 14) oc2 203 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11141593 14) 5)) s2_1 = true := by
  decide +kernel
theorem chunk2_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 11141593 14) oc2 1 s2_1) s2_N = true := by
  decide +kernel
theorem check2 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 11141593 14) oc2 6 205 5 s2_1.acc s2_N.acc 882 10000 113 25000 = true := by
  decide +kernel
theorem ht2 : (11141593 / 16384 : ℝ) = ((11141593 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid2 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 11141593 14) (11141593 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 11141593 14 _ ht2
theorem hσ2 : (11 / 12 : ℝ) = (((11 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid2 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 11141593 14) oc2 (11 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ2⟩
theorem inv2_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11141593 14) (11 / 12 : ℝ) (11141593 / 16384 : ℝ) (205 - 1) s2_1 :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 203 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 11141593 14) 5) s2_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid2.one_eq) chunk2_1
theorem inv2_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 11141593 14) (11 / 12 : ℝ) (11141593 / 16384 : ℝ) 205 s2_N :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 1 204 s2_1 s2_N inv2_1 chunk2_N
theorem cell2 : ∀ x y : ℝ, (5 / 6 : ℝ) ≤ x → x ≤ (1 : ℝ) → (680 : ℝ) ≤ y → y ≤ (68005773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s2_N.lhi : ℝ) ≤ (1331 / 250 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 11141593 14)).P := by
    show ((98192202786968237252 : ℕ) : ℝ) ≤ (1331 / 250 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 11141593 14) oc2 (11 / 12 : ℝ) (11141593 / 16384 : ℝ) hσ2 ht2 6 205 5 (by norm_num) (by norm_num)
    s2_1 s2_N inv2_1 inv2_N 882 10000 113 25000 check2 (441 / 5000 : ℝ) (1331 / 250 : ℝ) (680 : ℝ) (681 : ℝ) ((680 : ℝ) + 5773 / 100000) (6661000000000000000000000000000000000 : ℝ) 14 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (11 / 12 : ℝ) (11141593 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-- The right half of the slab. -/
theorem right_half : ∀ x y : ℝ, 1 / 2 ≤ x → x < 1 → (680 : ℝ) ≤ y → y ≤ ((680 : ℝ) + 5773 / 100000) →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1
  by_cases h0 : x ≤ (2 / 3 : ℝ)
  · exact cell0 x y (by linarith) h0 (by linarith) (by linarith) (by linarith)
  by_cases h1 : x ≤ (5 / 6 : ℝ)
  · exact cell1 x y (by linarith) h1 (by linarith) (by linarith) (by linarith)
  exact cell2 x y (by linarith) (by linarith) (by linarith) (by linarith) (by linarith)

/-- **The edge-clearance slab `SlabClear 680 68005773/100000`, hypothesis-free.** -/
theorem slabClear : EdgeClearGlue.SlabClear (680 : ℝ) ((680 : ℝ) + 5773 / 100000) :=
  ArbEcon.Off.slabClear_of_right_half _ _ right_half

end H1000Slab.U680
