/-  H1000Slab_U401.lean -- a KERNEL-CHECKED zero-free edge slab `SlabClear a b`, a = 401, b = 40105773/100000
    (lane h1000-integrate; GENERATED by ../emit_h1000_offline.py; do not edit).

    3 cells cover [1/2, 1] x [a, b] (the reflection `ArbEcon.Off.slabClear_of_right_half` covers
    (0, 1/2)); each cell: ONE off-line evaluator run at its center (N = 121, 6 accumulators) and ONE
    `ArbEcon.Off.checkCell` (`decide +kernel`), assembled by `H1000Oct.cell_zeta_ne_zero_R` with the
    slab's error budget F = 213/100000 at radius R = 441/5000 (`norm_num`).
    conjecture1_proved = False.  A finite zero-free slab; nothing about RH.
-/
import H1000Octant

open Complex ZetaReflection ZetaReflection.EMHigh

namespace H1000Slab.U401

noncomputable section

def oc0 : ArbEcon.Off.OCfg := ⟨7, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s0_1 : ArbEcon.Off.StO := ⟨120, 88313634934098119289, 88313634934098121578, 1129962408459411923, [⟨106166018961445705409, 80428406122570657331, 3160579, 70956719329963220951, 106579496173206903390, 3160580⟩, ⟨293366325401316461005, 275059287461459376311, 12296602, 237717688457899534571, 320706215263551183727, 12296219⟩, ⟨1075059588167650442440, 1033821740198468431313, 50007738, 867319957246030032352, 1149330125414727774060, 50003430⟩, ⟨4155025959992405279199, 4108043205797879654443, 208974747, 3362887353155430195150, 4444798516681720000486, 208944755⟩, ⟨16642518568074676491049, 16885468223906384231809, 889775806, 13602243681009845215342, 17882760910391561748746, 889596839⟩, ⟨68440569587621027713167, 70961922259337452356122, 3841385056, 56669894451584217251861, 73754430651625201399951, 3840387238⟩]⟩
def s0_N : ArbEcon.Off.StO := ⟨121, 88466720825738980154, 88466720825738982458, 1124505515230615820, [⟨107096798812258816576, 80428406122570657331, 3188893, 70956719329963220951, 107210496587711042418, 3188895⟩, ⟨297830150609877924763, 275059287461459376311, 12432509, 237717688457899534571, 323732361085697758469, 12432092⟩, ⟨1096467158900065911683, 1033821740198468431313, 50660079, 867319957246030032352, 1163842886938175394626, 50655428⟩, ⟨4257692185315116890528, 4108043205797879654443, 212105913, 3362887353155430195150, 4514398681186370257369, 212073415⟩, ⟨17134884280829441574400, 16885468223906384231809, 904805048, 13602243681009845215342, 18216548721294941343215, 904609933⟩, ⟨70801852417826330897779, 70961922259337452356122, 3913523651, 56669894451584217251861, 75355207079391062098281, 3912428585⟩]⟩
def oc1 : ArbEcon.Off.OCfg := ⟨3, 0, 4, 115792089237316195423570985008687907853269984665640564039457584007913129639936, 64⟩
def s1_1 : ArbEcon.Off.StO := ⟨120, 88313634934098119289, 88313634934098121578, 508784401353755790, [⟨69466445832647605637, 46249032544965406714, 1670443, 41171479976345089218, 66166003852747273395, 1670442⟩, ⟨160982533748928386722, 148774937243629245662, 6289441, 130967162113540667266, 179161053212436907073, 6289297⟩, ⟨568957379965326157456, 537404814822315940870, 25057636, 458790593529340563577, 608687229928992641480, 25055630⟩, ⟨2144524281453930924318, 2082255778475333209614, 103225242, 1726023975438064314362, 2286763024589987591220, 103210827⟩, ⟨8428239126067596715204, 8415890463828615434703, 434852811, 6829694385179197262828, 9032559775191850122486, 434766621⟩, ⟨34143110567346319320995, 34944651582013664400818, 1861810189, 27999152977581040367539, 36766776922446478214199, 1861332451⟩]⟩
def s1_N : ArbEcon.Off.StO := ⟨121, 88466720825738980154, 88466720825738982458, 505627509886005423, [⟨69884965699241753659, 46249032544965406714, 1683176, 41171479976345089218, 66449729600643968620, 1683175⟩, ⟨162989667368285011195, 148774937243629245662, 6350560, 130967162113540667266, 180521742471742242506, 6350399⟩, ⟨578583172400786025362, 537404814822315940870, 25351002, 458790593529340563577, 615212810614264201725, 25348834⟩, ⟨2190687565809785988241, 2082255778475333209614, 104633368, 1726023975438064314362, 2318058342744941643289, 104617789⟩, ⟨8649628568735100378725, 8415890463828615434703, 441611656, 6829694385179197262828, 9182645566120820815249, 441518027⟩, ⟨35204847963386065165511, 34944651582013664400818, 1894251847, 27999152977581040367539, 37486556939612045000431, 1893729528⟩]⟩
def oc2 : ArbEcon.Off.OCfg := ⟨11, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s2_1 : ArbEcon.Off.StO := ⟨120, 88313634934098119289, 88313634934098121578, 229088653855158690, [⟨49121688958105430957, 27547598730357077995, 903428, 24576649588255238255, 43250465392130189095, 903423⟩, ⟨90400211824364601871, 82616089213045462563, 3265947, 73992402266436270126, 103539943322563654446, 3265908⟩, ⟨306230534601989763936, 284433332708599561227, 12692111, 247675852889711078270, 328938097254744312047, 12691180⟩, ⟨1121563681644235938037, 1068647284334292709716, 51408715, 899907026212666004906, 1192196976233289989468, 51401713⟩, ⟨4314466381072501239412, 4232631280469210871534, 213904645, 3470382934652989853017, 4606436849589253457556, 213862558⟩, ⟨17185508391875614084600, 17327922799849891825066, 907153732, 13960536166176500100841, 18465645020547260760117, 906921719⟩]⟩
def s2_N : ArbEcon.Off.StO := ⟨121, 88466720825738980154, 88466720825738982458, 227352534328025435, [⟨49309874036006470681, 27547598730357077995, 909155, 24576649588255238255, 43378041061130024618, 909150⟩, ⟨91302708041784794409, 82616089213045462563, 3293438, 73992402266436270126, 104151769509801244908, 3293391⟩, ⟨310558717428930344255, 284433332708599561227, 12824067, 247675852889711078270, 331872287499046849931, 12823061⟩, ⟨1142320739925291749315, 1068647284334292709716, 52042091, 899907026212666004906, 1206268738065898292906, 52034555⟩, ⟨4414012884931189243113, 4232631280469210871534, 216944778, 3470382934652989853017, 4673922071945965431569, 216899295⟩, ⟨17662912573928319526578, 17327922799849891825066, 921746009, 13960536166176500100841, 18789290011893073873291, 921493704⟩]⟩

end

theorem budget : ArbEcon.Off.Cp 5 * ((441 / 5000 : ℝ) * (1199 / 250 : ℝ)) ^ (5 + 1) * ((((121 : ℕ) : ℝ)) - 1 + ArbEcon.Off.emcB 6 121 (401 : ℝ) (402 : ℝ))
    + 3 * ArbEcon.Off.corrVar 6 121 (441 / 5000 : ℝ) (401 : ℝ) (402 : ℝ)
    + ArbEcon.Off.CK 6 * (6963000000000000000000000000000000 : ℝ) / ((((121 : ℕ) : ℝ)) ^ (2 * 6) * ((11 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ ((213 : ℕ) : ℝ) / ((100000 : ℕ) : ℝ) := by
  have hC := H1000Oct.CK_six_le
  have hC0 := ArbEcon.Off.CK_nonneg 6
  have hm : ArbEcon.Off.CK 6 * (6963000000000000000000000000000000 : ℝ) / ((((121 : ℕ) : ℝ)) ^ (2 * 6) * ((11 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ (84107 / 1000000000000000 : ℝ) * (6963000000000000000000000000000000 : ℝ) / ((((121 : ℕ) : ℝ)) ^ (2 * 6) * ((11 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2) := by
    gcongr
  refine le_trans (add_le_add (le_refl _) hm) ?_
  rw [H1000Oct.emcB_betaN 6 121 (by norm_num), H1000Oct.corrVar_betaN 6 121 (by norm_num)]
  unfold ArbEcon.Off.Cp
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, ArbEcon.OrderK.betaN, ArbEcon.OrderK.Lbeta]
  norm_num [Nat.factorial]

theorem hQ : pochNormSq 1 ((401 : ℝ) + 5773 / 100000) (2 * 6 + 1) ≤ (6963000000000000000000000000000000 : ℝ) ^ 2 := by
  simp only [pochNormSq]
  norm_num

/-! ### Cell 0: [1/2, 2/3] x [401, 40105773/100000] -/

theorem chunk0_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 6570457 14) oc0 119 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 6570457 14) 5)) s0_1 = true := by
  decide +kernel
theorem chunk0_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 6570457 14) oc0 1 s0_1) s0_N = true := by
  decide +kernel
theorem check0 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 6570457 14) oc0 6 121 5 s0_1.acc s0_N.acc 882 10000 213 100000 = true := by
  decide +kernel
theorem ht0 : (6570457 / 16384 : ℝ) = ((6570457 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid0 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 6570457 14) (6570457 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 6570457 14 _ ht0
theorem hσ0 : (7 / 12 : ℝ) = (((7 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid0 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 6570457 14) oc0 (7 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ0⟩
theorem inv0_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 6570457 14) (7 / 12 : ℝ) (6570457 / 16384 : ℝ) (121 - 1) s0_1 :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 119 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 6570457 14) 5) s0_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid0.one_eq) chunk0_1
theorem inv0_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 6570457 14) (7 / 12 : ℝ) (6570457 / 16384 : ℝ) 121 s0_N :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 1 120 s0_1 s0_N inv0_1 chunk0_N
theorem cell0 : ∀ x y : ℝ, (1 / 2 : ℝ) ≤ x → x ≤ (2 / 3 : ℝ) → (401 : ℝ) ≤ y → y ≤ (40105773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s0_N.lhi : ℝ) ≤ (1199 / 250 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 6570457 14)).P := by
    show ((88466720825738982458 : ℕ) : ℝ) ≤ (1199 / 250 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 6570457 14) oc0 (7 / 12 : ℝ) (6570457 / 16384 : ℝ) hσ0 ht0 6 121 5 (by norm_num) (by norm_num)
    s0_1 s0_N inv0_1 inv0_N 882 10000 213 100000 check0 (441 / 5000 : ℝ) (1199 / 250 : ℝ) (401 : ℝ) (402 : ℝ) ((401 : ℝ) + 5773 / 100000) (6963000000000000000000000000000000 : ℝ) 11 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (7 / 12 : ℝ) (6570457 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 1: [2/3, 5/6] x [401, 40105773/100000] -/

theorem chunk1_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 6570457 14) oc1 119 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 6570457 14) 5)) s1_1 = true := by
  decide +kernel
theorem chunk1_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 6570457 14) oc1 1 s1_1) s1_N = true := by
  decide +kernel
theorem check1 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 6570457 14) oc1 6 121 5 s1_1.acc s1_N.acc 882 10000 213 100000 = true := by
  decide +kernel
theorem ht1 : (6570457 / 16384 : ℝ) = ((6570457 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid1 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 6570457 14) (6570457 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 6570457 14 _ ht1
theorem hσ1 : (3 / 4 : ℝ) = (((3 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((4 : ℕ) : ℝ) := by norm_num
theorem ovalid1 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 6570457 14) oc1 (3 / 4 : ℝ) := ⟨by decide +kernel, by decide, hσ1⟩
theorem inv1_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 6570457 14) (3 / 4 : ℝ) (6570457 / 16384 : ℝ) (121 - 1) s1_1 :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 119 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 6570457 14) 5) s1_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid1.one_eq) chunk1_1
theorem inv1_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 6570457 14) (3 / 4 : ℝ) (6570457 / 16384 : ℝ) 121 s1_N :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 1 120 s1_1 s1_N inv1_1 chunk1_N
theorem cell1 : ∀ x y : ℝ, (2 / 3 : ℝ) ≤ x → x ≤ (5 / 6 : ℝ) → (401 : ℝ) ≤ y → y ≤ (40105773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s1_N.lhi : ℝ) ≤ (1199 / 250 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 6570457 14)).P := by
    show ((88466720825738982458 : ℕ) : ℝ) ≤ (1199 / 250 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 6570457 14) oc1 (3 / 4 : ℝ) (6570457 / 16384 : ℝ) hσ1 ht1 6 121 5 (by norm_num) (by norm_num)
    s1_1 s1_N inv1_1 inv1_N 882 10000 213 100000 check1 (441 / 5000 : ℝ) (1199 / 250 : ℝ) (401 : ℝ) (402 : ℝ) ((401 : ℝ) + 5773 / 100000) (6963000000000000000000000000000000 : ℝ) 11 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (3 / 4 : ℝ) (6570457 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 2: [5/6, 1] x [401, 40105773/100000] -/

theorem chunk2_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 6570457 14) oc2 119 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 6570457 14) 5)) s2_1 = true := by
  decide +kernel
theorem chunk2_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 6570457 14) oc2 1 s2_1) s2_N = true := by
  decide +kernel
theorem check2 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 6570457 14) oc2 6 121 5 s2_1.acc s2_N.acc 882 10000 213 100000 = true := by
  decide +kernel
theorem ht2 : (6570457 / 16384 : ℝ) = ((6570457 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid2 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 6570457 14) (6570457 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 6570457 14 _ ht2
theorem hσ2 : (11 / 12 : ℝ) = (((11 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid2 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 6570457 14) oc2 (11 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ2⟩
theorem inv2_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 6570457 14) (11 / 12 : ℝ) (6570457 / 16384 : ℝ) (121 - 1) s2_1 :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 119 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 6570457 14) 5) s2_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid2.one_eq) chunk2_1
theorem inv2_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 6570457 14) (11 / 12 : ℝ) (6570457 / 16384 : ℝ) 121 s2_N :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 1 120 s2_1 s2_N inv2_1 chunk2_N
theorem cell2 : ∀ x y : ℝ, (5 / 6 : ℝ) ≤ x → x ≤ (1 : ℝ) → (401 : ℝ) ≤ y → y ≤ (40105773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s2_N.lhi : ℝ) ≤ (1199 / 250 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 6570457 14)).P := by
    show ((88466720825738982458 : ℕ) : ℝ) ≤ (1199 / 250 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 6570457 14) oc2 (11 / 12 : ℝ) (6570457 / 16384 : ℝ) hσ2 ht2 6 121 5 (by norm_num) (by norm_num)
    s2_1 s2_N inv2_1 inv2_N 882 10000 213 100000 check2 (441 / 5000 : ℝ) (1199 / 250 : ℝ) (401 : ℝ) (402 : ℝ) ((401 : ℝ) + 5773 / 100000) (6963000000000000000000000000000000 : ℝ) 11 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (11 / 12 : ℝ) (6570457 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-- The right half of the slab. -/
theorem right_half : ∀ x y : ℝ, 1 / 2 ≤ x → x < 1 → (401 : ℝ) ≤ y → y ≤ ((401 : ℝ) + 5773 / 100000) →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1
  by_cases h0 : x ≤ (2 / 3 : ℝ)
  · exact cell0 x y (by linarith) h0 (by linarith) (by linarith) (by linarith)
  by_cases h1 : x ≤ (5 / 6 : ℝ)
  · exact cell1 x y (by linarith) h1 (by linarith) (by linarith) (by linarith)
  exact cell2 x y (by linarith) (by linarith) (by linarith) (by linarith) (by linarith)

/-- **The edge-clearance slab `SlabClear 401 40105773/100000`, hypothesis-free.** -/
theorem slabClear : EdgeClearGlue.SlabClear (401 : ℝ) ((401 : ℝ) + 5773 / 100000) :=
  ArbEcon.Off.slabClear_of_right_half _ _ right_half

end H1000Slab.U401
