/-  H1000Slab_L361.lean -- a KERNEL-CHECKED zero-free edge slab `SlabClear a b`, a = 36094227/100000, b = 361
    (lane h1000-integrate; GENERATED by ../emit_h1000_offline.py; do not edit).

    3 cells cover [1/2, 1] x [a, b] (the reflection `ArbEcon.Off.slabClear_of_right_half` covers
    (0, 1/2)); each cell: ONE off-line evaluator run at its center (N = 109, 6 accumulators) and ONE
    `ArbEcon.Off.checkCell` (`decide +kernel`), assembled by `H1000Oct.cell_zeta_ne_zero_R` with the
    slab's error budget F = 39/20000 at radius R = 441/5000 (`norm_num`).
    conjecture1_proved = False.  A finite zero-free slab; nothing about RH.
-/
import H1000Octant

open Complex ZetaReflection ZetaReflection.EMHigh

namespace H1000Slab.L361

noncomputable section

def oc0 : ArbEcon.Off.OCfg := ⟨7, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s0_1 : ArbEcon.Off.StO := ⟨108, 86370076466284129608, 86370076466284131659, 1201588782027093935, [⟨99728628004494177244, 75786346604245846864, 2544637, 83587023968262026462, 90215972920992854347, 2544629⟩, ⟨256620217973499239105, 242162048172328260747, 9644399, 239345725044376293027, 299973784722315675881, 9644968⟩, ⟨932672982005143624347, 853080253482928196036, 38258078, 822916617170782286195, 1084879757669062338453, 38261821⟩, ⟨3608240363923735930263, 3205363847826898244472, 156058316, 3091572066979599363361, 4125808484620461434340, 156078004⟩, ⟨14433183137854228994482, 12569727859434611179685, 648886324, 12204625633536118142073, 16217512328902286078117, 648982137⟩, ⟨59002237191803785048741, 50772580783402508842325, 2736488757, 49717653771094444556782, 65266752018226787758537, 2736936070⟩]⟩
def s0_N : ArbEcon.Off.StO := ⟨109, 86540093744220311420, 86540093744220313496, 1195145916726809851, [⟨99728628004494177244, 76972506037997162318, 2569055, 83733309852719568684, 90215972920992854347, 2569047⟩, ⟨256620217973499239105, 247726734719843614871, 9759088, 240032003018626200949, 299973784722315675881, 9759540⟩, ⟨932672982005143624347, 879186133932883358270, 38796752, 826136185891900098591, 1084879757669062338453, 38799398⟩, ⟨3608240363923735930263, 3327835614789522601902, 158588363, 3106676183881106605359, 4125808484620461434340, 158600329⟩, ⟨14433183137854228994482, 13144285524007580175524, 660769439, 12275484300374945558846, 16217512328902286078117, 660816943⟩, ⟨59002237191803785048741, 53468030666315429689664, 2792301246, 50050076427706358016486, 65266752018226787758537, 2792465239⟩]⟩
def oc1 : ArbEcon.Off.OCfg := ⟨3, 0, 4, 115792089237316195423570985008687907853269984665640564039457584007913129639936, 64⟩
def s1_1 : ArbEcon.Off.StO := ⟨108, 86370076466284129608, 86370076466284131659, 550619903379233300, [⟨67535671147627476873, 45156441515955522562, 1367336, 53084686296790318435, 52563310006553796683, 1367334⟩, ⟨141814565292200532931, 136233595987304854673, 5015078, 137114586441977451345, 165791705372846185430, 5015420⟩, ⟨493127354387846098520, 460152118606919571938, 19489721, 444617229904743962598, 579659912124972993100, 19491848⟩, ⟨1862024403854056090085, 1678581530960290476120, 78374579, 1612870370830994016900, 2154308769906416776610, 78385409⟩, ⟨7330995287111200485980, 6444574914443736476679, 322439606, 6222315693090326410057, 8327309809189021959204, 322491320⟩, ⟨29618198303287207450565, 25624028669796725714407, 1348598031, 24943511628082195471895, 33085779828956551831373, 1348837430⟩]⟩
def s1_N : ArbEcon.Off.StO := ⟨109, 86540093744220311420, 86540093744220313496, 546826872820514897, [⟨67535671147627476873, 45699156714783456965, 1378510, 53151617917118973280, 52563310006553796683, 1378508⟩, ⟨141814565292200532931, 138779661785979853428, 5067563, 137428585957260451360, 165791705372846185430, 5067851⟩, ⟨493127354387846098520, 472096598999549580891, 19736235, 446090310865787842384, 579659912124972993100, 19737858⟩, ⟨1862024403854056090085, 1734617243754582800401, 79532408, 1619781106077939294180, 2154308769906416776610, 79539695⟩, ⟨7330995287111200485980, 6707457936990440308847, 327877693, 6254736356255729435581, 8327309809189021959204, 327907257⟩, ⟨29618198303287207450565, 26857304380895200992634, 1374139575, 25095608237563673364624, 33085779828956551831373, 1374249125⟩]⟩
def oc2 : ArbEcon.Off.OCfg := ⟨11, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s2_1 : ArbEcon.Off.StO := ⟨108, 86370076466284129608, 86370076466284131659, 252317833298913015, [⟨49519403311127899707, 27729203405082226112, 751344, 35339088016307609700, 31555817341060846198, 751346⟩, ⟨80666844621372385371, 78606125550730402654, 2646490, 81315108645657401913, 93612164149452856122, 2646707⟩, ⟨265187294259409834010, 253068089950846588479, 10033318, 245867470419336043403, 314519898532708854032, 10034589⟩, ⟨971808065808710226037, 891964627464179544913, 39674868, 855157680608241813497, 1137985220678337310097, 39681072⟩, ⟨3755254065531561947711, 3341413063677784306308, 161233947, 3209691659037492851415, 4314805237896129225126, 161262715⟩, ⟨14969322977967007426440, 13046996662148335422560, 668028864, 12623649828902140969868, 16894994736162024173476, 668159718⟩]⟩
def s2_N : ArbEcon.Off.StO := ⟨109, 86540093744220311420, 86540093744220313496, 250195080494940439, [⟨49519403311127899707, 27977517230911980616, 756458, 35369711899236788862, 31555817341060846198, 756460⟩, ⟨80666844621372385371, 79771052091665037907, 2670511, 81458775933982839802, 93612164149452856122, 2670704⟩, ⟨265187294259409834010, 258533165611612811542, 10146142, 246541463648167190235, 314519898532708854032, 10147186⟩, ⟨971808065808710226037, 917603198591537204063, 40204782, 858319617314955596878, 1137985220678337310097, 40209381⟩, ⟨3755254065531561947711, 3461692520039494931882, 163722845, 3224525404110277152384, 4314805237896129225126, 163741554⟩, ⟨14969322977967007426440, 13611269435026519280856, 679718689, 12693240087434874596457, 16894994736162024173476, 679790486⟩]⟩

end

theorem budget : ArbEcon.Off.Cp 5 * ((441 / 5000 : ℝ) * (1173 / 250 : ℝ)) ^ (5 + 1) * ((((109 : ℕ) : ℝ)) - 1 + ArbEcon.Off.emcB 6 109 ((361 : ℝ) - 5773 / 100000) (362 : ℝ))
    + 3 * ArbEcon.Off.corrVar 6 109 (441 / 5000 : ℝ) ((361 : ℝ) - 5773 / 100000) (362 : ℝ)
    + ArbEcon.Off.CK 6 * (1775000000000000000000000000000000 : ℝ) / ((((109 : ℕ) : ℝ)) ^ (2 * 6) * ((10 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ ((39 : ℕ) : ℝ) / ((20000 : ℕ) : ℝ) := by
  have hC := H1000Oct.CK_six_le
  have hC0 := ArbEcon.Off.CK_nonneg 6
  have hm : ArbEcon.Off.CK 6 * (1775000000000000000000000000000000 : ℝ) / ((((109 : ℕ) : ℝ)) ^ (2 * 6) * ((10 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ (84107 / 1000000000000000 : ℝ) * (1775000000000000000000000000000000 : ℝ) / ((((109 : ℕ) : ℝ)) ^ (2 * 6) * ((10 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2) := by
    gcongr
  refine le_trans (add_le_add (le_refl _) hm) ?_
  rw [H1000Oct.emcB_betaN 6 109 (by norm_num), H1000Oct.corrVar_betaN 6 109 (by norm_num)]
  unfold ArbEcon.Off.Cp
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, ArbEcon.OrderK.betaN, ArbEcon.OrderK.Lbeta]
  norm_num [Nat.factorial]

theorem hQ : pochNormSq 1 (361 : ℝ) (2 * 6 + 1) ≤ (1775000000000000000000000000000000 : ℝ) ^ 2 := by
  simp only [pochNormSq]
  norm_num

/-! ### Cell 0: [1/2, 2/3] x [36094227/100000, 361] -/

theorem chunk0_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 5914151 14) oc0 107 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 5914151 14) 5)) s0_1 = true := by
  decide +kernel
theorem chunk0_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 5914151 14) oc0 1 s0_1) s0_N = true := by
  decide +kernel
theorem check0 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 5914151 14) oc0 6 109 5 s0_1.acc s0_N.acc 882 10000 39 20000 = true := by
  decide +kernel
theorem ht0 : (5914151 / 16384 : ℝ) = ((5914151 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid0 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 5914151 14) (5914151 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 5914151 14 _ ht0
theorem hσ0 : (7 / 12 : ℝ) = (((7 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid0 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 5914151 14) oc0 (7 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ0⟩
theorem inv0_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 5914151 14) (7 / 12 : ℝ) (5914151 / 16384 : ℝ) (109 - 1) s0_1 :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 107 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 5914151 14) 5) s0_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid0.one_eq) chunk0_1
theorem inv0_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 5914151 14) (7 / 12 : ℝ) (5914151 / 16384 : ℝ) 109 s0_N :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 1 108 s0_1 s0_N inv0_1 chunk0_N
theorem cell0 : ∀ x y : ℝ, (1 / 2 : ℝ) ≤ x → x ≤ (2 / 3 : ℝ) → (36094227 / 100000 : ℝ) ≤ y → y ≤ (361 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s0_N.lhi : ℝ) ≤ (1173 / 250 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 5914151 14)).P := by
    show ((86540093744220313496 : ℕ) : ℝ) ≤ (1173 / 250 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 5914151 14) oc0 (7 / 12 : ℝ) (5914151 / 16384 : ℝ) hσ0 ht0 6 109 5 (by norm_num) (by norm_num)
    s0_1 s0_N inv0_1 inv0_N 882 10000 39 20000 check0 (441 / 5000 : ℝ) (1173 / 250 : ℝ) ((361 : ℝ) - 5773 / 100000) (362 : ℝ) (361 : ℝ) (1775000000000000000000000000000000 : ℝ) 10 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (7 / 12 : ℝ) (5914151 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 1: [2/3, 5/6] x [36094227/100000, 361] -/

theorem chunk1_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 5914151 14) oc1 107 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 5914151 14) 5)) s1_1 = true := by
  decide +kernel
theorem chunk1_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 5914151 14) oc1 1 s1_1) s1_N = true := by
  decide +kernel
theorem check1 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 5914151 14) oc1 6 109 5 s1_1.acc s1_N.acc 882 10000 39 20000 = true := by
  decide +kernel
theorem ht1 : (5914151 / 16384 : ℝ) = ((5914151 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid1 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 5914151 14) (5914151 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 5914151 14 _ ht1
theorem hσ1 : (3 / 4 : ℝ) = (((3 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((4 : ℕ) : ℝ) := by norm_num
theorem ovalid1 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 5914151 14) oc1 (3 / 4 : ℝ) := ⟨by decide +kernel, by decide, hσ1⟩
theorem inv1_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 5914151 14) (3 / 4 : ℝ) (5914151 / 16384 : ℝ) (109 - 1) s1_1 :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 107 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 5914151 14) 5) s1_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid1.one_eq) chunk1_1
theorem inv1_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 5914151 14) (3 / 4 : ℝ) (5914151 / 16384 : ℝ) 109 s1_N :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 1 108 s1_1 s1_N inv1_1 chunk1_N
theorem cell1 : ∀ x y : ℝ, (2 / 3 : ℝ) ≤ x → x ≤ (5 / 6 : ℝ) → (36094227 / 100000 : ℝ) ≤ y → y ≤ (361 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s1_N.lhi : ℝ) ≤ (1173 / 250 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 5914151 14)).P := by
    show ((86540093744220313496 : ℕ) : ℝ) ≤ (1173 / 250 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 5914151 14) oc1 (3 / 4 : ℝ) (5914151 / 16384 : ℝ) hσ1 ht1 6 109 5 (by norm_num) (by norm_num)
    s1_1 s1_N inv1_1 inv1_N 882 10000 39 20000 check1 (441 / 5000 : ℝ) (1173 / 250 : ℝ) ((361 : ℝ) - 5773 / 100000) (362 : ℝ) (361 : ℝ) (1775000000000000000000000000000000 : ℝ) 10 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (3 / 4 : ℝ) (5914151 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 2: [5/6, 1] x [36094227/100000, 361] -/

theorem chunk2_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 5914151 14) oc2 107 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 5914151 14) 5)) s2_1 = true := by
  decide +kernel
theorem chunk2_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 5914151 14) oc2 1 s2_1) s2_N = true := by
  decide +kernel
theorem check2 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 5914151 14) oc2 6 109 5 s2_1.acc s2_N.acc 882 10000 39 20000 = true := by
  decide +kernel
theorem ht2 : (5914151 / 16384 : ℝ) = ((5914151 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid2 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 5914151 14) (5914151 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 5914151 14 _ ht2
theorem hσ2 : (11 / 12 : ℝ) = (((11 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid2 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 5914151 14) oc2 (11 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ2⟩
theorem inv2_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 5914151 14) (11 / 12 : ℝ) (5914151 / 16384 : ℝ) (109 - 1) s2_1 :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 107 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 5914151 14) 5) s2_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid2.one_eq) chunk2_1
theorem inv2_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 5914151 14) (11 / 12 : ℝ) (5914151 / 16384 : ℝ) 109 s2_N :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 1 108 s2_1 s2_N inv2_1 chunk2_N
theorem cell2 : ∀ x y : ℝ, (5 / 6 : ℝ) ≤ x → x ≤ (1 : ℝ) → (36094227 / 100000 : ℝ) ≤ y → y ≤ (361 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s2_N.lhi : ℝ) ≤ (1173 / 250 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 5914151 14)).P := by
    show ((86540093744220313496 : ℕ) : ℝ) ≤ (1173 / 250 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 5914151 14) oc2 (11 / 12 : ℝ) (5914151 / 16384 : ℝ) hσ2 ht2 6 109 5 (by norm_num) (by norm_num)
    s2_1 s2_N inv2_1 inv2_N 882 10000 39 20000 check2 (441 / 5000 : ℝ) (1173 / 250 : ℝ) ((361 : ℝ) - 5773 / 100000) (362 : ℝ) (361 : ℝ) (1775000000000000000000000000000000 : ℝ) 10 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (11 / 12 : ℝ) (5914151 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-- The right half of the slab. -/
theorem right_half : ∀ x y : ℝ, 1 / 2 ≤ x → x < 1 → ((361 : ℝ) - 5773 / 100000) ≤ y → y ≤ (361 : ℝ) →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1
  by_cases h0 : x ≤ (2 / 3 : ℝ)
  · exact cell0 x y (by linarith) h0 (by linarith) (by linarith) (by linarith)
  by_cases h1 : x ≤ (5 / 6 : ℝ)
  · exact cell1 x y (by linarith) h1 (by linarith) (by linarith) (by linarith)
  exact cell2 x y (by linarith) (by linarith) (by linarith) (by linarith) (by linarith)

/-- **The edge-clearance slab `SlabClear 36094227/100000 361`, hypothesis-free.** -/
theorem slabClear : EdgeClearGlue.SlabClear ((361 : ℝ) - 5773 / 100000) (361 : ℝ) :=
  ArbEcon.Off.slabClear_of_right_half _ _ right_half

end H1000Slab.L361
