/-  H1000Slab_U41.lean -- a KERNEL-CHECKED zero-free edge slab `SlabClear a b`, a = 41, b = 4105773/100000
    (lane h1000-integrate; GENERATED by ../emit_h1000_offline.py; do not edit).

    3 cells cover [1/2, 1] x [a, b] (the reflection `ArbEcon.Off.slabClear_of_right_half` covers
    (0, 1/2)); each cell: ONE off-line evaluator run at its center (N = 13, 6 accumulators) and ONE
    `ArbEcon.Off.checkCell` (`decide +kernel`), assembled by `H1000Oct.cell_zeta_ne_zero_R` with the
    slab's error budget F = 11/2000 at radius R = 441/5000 (`norm_num`).
    conjecture1_proved = False.  A finite zero-free slab; nothing about RH.
-/
import H1000Octant

open Complex ZetaReflection ZetaReflection.EMHigh

namespace H1000Slab.U41

noncomputable section

def oc0 : ArbEcon.Off.OCfg := ⟨7, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s0_1 : ArbEcon.Off.StO := ⟨12, 45838437015698250832, 45838437015698251371, 4329097119783779460, [⟨36030776606015091441, 33205032556371143127, 26460, 20749101301592096625, 20824346422035486594, 26461⟩, ⟨28096136667243600211, 49177383032886581606, 50454, 38822639256565754076, 35465987343545160151, 50437⟩, ⟨49191798444867592973, 86360210094494417764, 102973, 76712736233239076665, 67845613835842471056, 103209⟩, ⟨93799602974304523123, 166300249627013295637, 219394, 156051257362067067389, 141693192220057050003, 220734⟩, ⟨191656120035175214731, 335815796761594744985, 481012, 323648921328458517991, 313297778900463162355, 486117⟩, ⟨411609666375969170161, 696999626568442618438, 1076145, 681954609426925922803, 716752496775320198151, 1092987⟩]⟩
def s0_N : ArbEcon.Off.StO := ⟨13, 47314964359118724938, 47314964359118725498, 4131611082098560578, [⟨36030776606015091441, 33231396614240226243, 29067, 24880628267517929030, 20824346422035486594, 29068⟩, ⟨28096136667243600211, 49245005506177965116, 57143, 49419796693152230378, 35465987343545160151, 57251⟩, ⟨49191798444867592973, 86533658313913111828, 120134, 103893908391130305029, 67845613835842471056, 121010⟩, ⟨93799602974304523123, 166745135525964122619, 263419, 225769587423501586163, 141693192220057050003, 267220⟩, ⟨191656120035175214731, 336956906562252366823, 593949, 502472907222826329524, 313297778900463162355, 607470⟩, ⟨411609666375969170161, 699926515418432447867, 1365859, 1140629077145395553815, 716752496775320198151, 1409682⟩]⟩
def oc1 : ArbEcon.Off.OCfg := ⟨3, 0, 4, 115792089237316195423570985008687907853269984665640564039457584007913129639936, 64⟩
def s1_1 : ArbEcon.Off.StO := ⟨12, 45838437015698250832, 45838437015698251371, 2861104944934494676, [⟨31964676820532558521, 26090022647917056115, 19436, 15233421976113166010, 15755669146378867212, 19438⟩, ⟨21064705581171972286, 36855541682843580662, 36198, 27975284770097446833, 25905966361308985297, 36168⟩, ⟨35930113553499082046, 62813998687630120564, 72714, 54716795562858016808, 48078198033978593979, 72832⟩, ⟨66930467183082144048, 118968842489890346347, 153236, 110551111127064597267, 98258710694214761372, 154060⟩, ⟨134289102785553984891, 237887609175945449033, 333315, 228006518970734454979, 214302201342562971010, 336590⟩, ⟨284744773550025680553, 490402119167936705426, 741250, 477976346678901223616, 486253321532625273971, 752226⟩]⟩
def s1_N : ArbEcon.Off.StO := ⟨13, 47314964359118724938, 47314964359118725498, 2694400858925426521, [⟨31964676820532558521, 26107215781238582682, 21137, 17927767979273239808, 15755669146378867212, 21139⟩, ⟨21064705581171972286, 36899641199109380767, 40563, 34886145819681937811, 25905966361308985297, 40614⟩, ⟨35930113553499082046, 62927111713540449132, 83914, 72442804171495718470, 48078198033978593979, 84447⟩, ⟨66930467183082144048, 119258971673019573766, 181969, 156017425518147539355, 98258710694214761372, 184392⟩, ⟨134289102785553984891, 238631775837793601432, 407024, 344625312854286869213, 214302201342562971010, 415773⟩, ⟨284744773550025680553, 492310868969088420622, 930334, 777097647118458381560, 486253321532625273971, 958869⟩]⟩
def oc2 : ArbEcon.Off.OCfg := ⟨11, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s2_1 : ArbEcon.Off.StO := ⟨12, 45838437015698250832, 45838437015698251371, 1890907336894643477, [⟨28905308006180833971, 20735203870538426817, 14392, 11252375228344961259, 12036344503022526667, 14392⟩, ⟨15910847726519695977, 27870054997837838506, 26126, 20229659420718290022, 19106778995818594895, 26086⟩, ⟨26439181384082698375, 45942396800583116785, 51576, 39120033193584117536, 34336600866782517533, 51618⟩, ⟨48062247737098032482, 85402066731552404715, 107395, 78469711858716795953, 68503077659720454298, 107885⟩, ⟨94543681841891125946, 168924524812900581227, 231595, 160916837815800449438, 147079026808703149768, 233681⟩, ⟨197628808804229029125, 345704939329000294709, 511712, 335591751431096561116, 330562335702770814268, 518850⟩]⟩
def s2_N : ArbEcon.Off.StO := ⟨13, 47314964359118724938, 47314964359118725498, 1757134406971002505, [⟨28905308006180833971, 20746416250471731356, 15502, 13009473861517717412, 12036344503022526667, 15502⟩, ⟨15910847726519695977, 27898814184543382611, 28976, 24736528430871295395, 19106778995818594895, 28989⟩, ⟨26439181384082698375, 46016162658044618507, 58889, 50679923965339380855, 34336600866782517533, 59203⟩, ⟨48062247737098032482, 85591272420250882863, 126157, 108120246266056006886, 68503077659720454298, 127693⟩, ⟨94543681841891125946, 169409827822555810299, 279726, 236968956992296346157, 147079026808703149768, 285390⟩, ⟨197628808804229029125, 346949716971789624487, 635182, 530661585646437929526, 330562335702770814268, 653791⟩]⟩

end

theorem budget : ArbEcon.Off.Cp 5 * ((441 / 5000 : ℝ) * (513 / 200 : ℝ)) ^ (5 + 1) * ((((13 : ℕ) : ℝ)) - 1 + ArbEcon.Off.emcB 6 13 (41 : ℝ) (43 : ℝ))
    + 3 * ArbEcon.Off.corrVar 6 13 (441 / 5000 : ℝ) (41 : ℝ) (43 : ℝ)
    + ArbEcon.Off.CK 6 * (1193000000000000000000 : ℝ) / ((((13 : ℕ) : ℝ)) ^ (2 * 6) * ((3 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ ((11 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ) := by
  have hC := H1000Oct.CK_six_le
  have hC0 := ArbEcon.Off.CK_nonneg 6
  have hm : ArbEcon.Off.CK 6 * (1193000000000000000000 : ℝ) / ((((13 : ℕ) : ℝ)) ^ (2 * 6) * ((3 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ (84107 / 1000000000000000 : ℝ) * (1193000000000000000000 : ℝ) / ((((13 : ℕ) : ℝ)) ^ (2 * 6) * ((3 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2) := by
    gcongr
  refine le_trans (add_le_add (le_refl _) hm) ?_
  rw [H1000Oct.emcB_betaN 6 13 (by norm_num), H1000Oct.corrVar_betaN 6 13 (by norm_num)]
  unfold ArbEcon.Off.Cp
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, ArbEcon.OrderK.betaN, ArbEcon.OrderK.Lbeta]
  norm_num [Nat.factorial]

theorem hQ : pochNormSq 1 ((41 : ℝ) + 5773 / 100000) (2 * 6 + 1) ≤ (1193000000000000000000 : ℝ) ^ 2 := by
  simp only [pochNormSq]
  norm_num

/-! ### Cell 0: [1/2, 2/3] x [41, 4105773/100000] -/

theorem chunk0_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 672217 14) oc0 11 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 672217 14) 5)) s0_1 = true := by
  decide +kernel
theorem chunk0_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 672217 14) oc0 1 s0_1) s0_N = true := by
  decide +kernel
theorem check0 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 672217 14) oc0 6 13 5 s0_1.acc s0_N.acc 882 10000 11 2000 = true := by
  decide +kernel
theorem ht0 : (672217 / 16384 : ℝ) = ((672217 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid0 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 672217 14) (672217 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 672217 14 _ ht0
theorem hσ0 : (7 / 12 : ℝ) = (((7 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid0 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 672217 14) oc0 (7 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ0⟩
theorem inv0_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 672217 14) (7 / 12 : ℝ) (672217 / 16384 : ℝ) (13 - 1) s0_1 :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 11 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 672217 14) 5) s0_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid0.one_eq) chunk0_1
theorem inv0_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 672217 14) (7 / 12 : ℝ) (672217 / 16384 : ℝ) 13 s0_N :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 1 12 s0_1 s0_N inv0_1 chunk0_N
theorem cell0 : ∀ x y : ℝ, (1 / 2 : ℝ) ≤ x → x ≤ (2 / 3 : ℝ) → (41 : ℝ) ≤ y → y ≤ (4105773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s0_N.lhi : ℝ) ≤ (513 / 200 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 672217 14)).P := by
    show ((47314964359118725498 : ℕ) : ℝ) ≤ (513 / 200 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 672217 14) oc0 (7 / 12 : ℝ) (672217 / 16384 : ℝ) hσ0 ht0 6 13 5 (by norm_num) (by norm_num)
    s0_1 s0_N inv0_1 inv0_N 882 10000 11 2000 check0 (441 / 5000 : ℝ) (513 / 200 : ℝ) (41 : ℝ) (43 : ℝ) ((41 : ℝ) + 5773 / 100000) (1193000000000000000000 : ℝ) 3 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (7 / 12 : ℝ) (672217 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 1: [2/3, 5/6] x [41, 4105773/100000] -/

theorem chunk1_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 672217 14) oc1 11 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 672217 14) 5)) s1_1 = true := by
  decide +kernel
theorem chunk1_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 672217 14) oc1 1 s1_1) s1_N = true := by
  decide +kernel
theorem check1 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 672217 14) oc1 6 13 5 s1_1.acc s1_N.acc 882 10000 11 2000 = true := by
  decide +kernel
theorem ht1 : (672217 / 16384 : ℝ) = ((672217 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid1 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 672217 14) (672217 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 672217 14 _ ht1
theorem hσ1 : (3 / 4 : ℝ) = (((3 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((4 : ℕ) : ℝ) := by norm_num
theorem ovalid1 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 672217 14) oc1 (3 / 4 : ℝ) := ⟨by decide +kernel, by decide, hσ1⟩
theorem inv1_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 672217 14) (3 / 4 : ℝ) (672217 / 16384 : ℝ) (13 - 1) s1_1 :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 11 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 672217 14) 5) s1_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid1.one_eq) chunk1_1
theorem inv1_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 672217 14) (3 / 4 : ℝ) (672217 / 16384 : ℝ) 13 s1_N :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 1 12 s1_1 s1_N inv1_1 chunk1_N
theorem cell1 : ∀ x y : ℝ, (2 / 3 : ℝ) ≤ x → x ≤ (5 / 6 : ℝ) → (41 : ℝ) ≤ y → y ≤ (4105773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s1_N.lhi : ℝ) ≤ (513 / 200 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 672217 14)).P := by
    show ((47314964359118725498 : ℕ) : ℝ) ≤ (513 / 200 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 672217 14) oc1 (3 / 4 : ℝ) (672217 / 16384 : ℝ) hσ1 ht1 6 13 5 (by norm_num) (by norm_num)
    s1_1 s1_N inv1_1 inv1_N 882 10000 11 2000 check1 (441 / 5000 : ℝ) (513 / 200 : ℝ) (41 : ℝ) (43 : ℝ) ((41 : ℝ) + 5773 / 100000) (1193000000000000000000 : ℝ) 3 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (3 / 4 : ℝ) (672217 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 2: [5/6, 1] x [41, 4105773/100000] -/

theorem chunk2_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 672217 14) oc2 11 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 672217 14) 5)) s2_1 = true := by
  decide +kernel
theorem chunk2_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 672217 14) oc2 1 s2_1) s2_N = true := by
  decide +kernel
theorem check2 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 672217 14) oc2 6 13 5 s2_1.acc s2_N.acc 882 10000 11 2000 = true := by
  decide +kernel
theorem ht2 : (672217 / 16384 : ℝ) = ((672217 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid2 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 672217 14) (672217 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 672217 14 _ ht2
theorem hσ2 : (11 / 12 : ℝ) = (((11 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid2 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 672217 14) oc2 (11 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ2⟩
theorem inv2_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 672217 14) (11 / 12 : ℝ) (672217 / 16384 : ℝ) (13 - 1) s2_1 :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 11 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 672217 14) 5) s2_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid2.one_eq) chunk2_1
theorem inv2_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 672217 14) (11 / 12 : ℝ) (672217 / 16384 : ℝ) 13 s2_N :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 1 12 s2_1 s2_N inv2_1 chunk2_N
theorem cell2 : ∀ x y : ℝ, (5 / 6 : ℝ) ≤ x → x ≤ (1 : ℝ) → (41 : ℝ) ≤ y → y ≤ (4105773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s2_N.lhi : ℝ) ≤ (513 / 200 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 672217 14)).P := by
    show ((47314964359118725498 : ℕ) : ℝ) ≤ (513 / 200 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 672217 14) oc2 (11 / 12 : ℝ) (672217 / 16384 : ℝ) hσ2 ht2 6 13 5 (by norm_num) (by norm_num)
    s2_1 s2_N inv2_1 inv2_N 882 10000 11 2000 check2 (441 / 5000 : ℝ) (513 / 200 : ℝ) (41 : ℝ) (43 : ℝ) ((41 : ℝ) + 5773 / 100000) (1193000000000000000000 : ℝ) 3 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (11 / 12 : ℝ) (672217 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-- The right half of the slab. -/
theorem right_half : ∀ x y : ℝ, 1 / 2 ≤ x → x < 1 → (41 : ℝ) ≤ y → y ≤ ((41 : ℝ) + 5773 / 100000) →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1
  by_cases h0 : x ≤ (2 / 3 : ℝ)
  · exact cell0 x y (by linarith) h0 (by linarith) (by linarith) (by linarith)
  by_cases h1 : x ≤ (5 / 6 : ℝ)
  · exact cell1 x y (by linarith) h1 (by linarith) (by linarith) (by linarith)
  exact cell2 x y (by linarith) (by linarith) (by linarith) (by linarith) (by linarith)

/-- **The edge-clearance slab `SlabClear 41 4105773/100000`, hypothesis-free.** -/
theorem slabClear : EdgeClearGlue.SlabClear (41 : ℝ) ((41 : ℝ) + 5773 / 100000) :=
  ArbEcon.Off.slabClear_of_right_half _ _ right_half

end H1000Slab.U41
