/-  H1000Slab_U840.lean -- a KERNEL-CHECKED zero-free edge slab `SlabClear a b`, a = 840, b = 84005773/100000
    (lane h1000-integrate; GENERATED by ../emit_h1000_offline.py; do not edit).

    3 cells cover [1/2, 1] x [a, b] (the reflection `ArbEcon.Off.slabClear_of_right_half` covers
    (0, 1/2)); each cell: ONE off-line evaluator run at its center (N = 253, 6 accumulators) and ONE
    `ArbEcon.Off.checkCell` (`decide +kernel`), assembled by `H1000Oct.cell_zeta_ne_zero_R` with the
    slab's error budget F = 33/5000 at radius R = 441/5000 (`norm_num`).
    conjecture1_proved = False.  A finite zero-free slab; nothing about RH.
-/
import H1000Octant

open Complex ZetaReflection ZetaReflection.EMHigh

namespace H1000Slab.U840

noncomputable section

def oc0 : ArbEcon.Off.OCfg := ⟨7, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s0_1 : ArbEcon.Off.StO := ⟨252, 101999963251048560352, 101999963251048564189, 732997916810240657, [⟨141151665194882083295, 117970097580596891851, 14656475, 142739011287032906611, 115356621667844895487, 14656473⟩, ⟨469658719121956330246, 455131774255519881940, 67640567, 524833594613608152499, 444373279265800082810, 67641457⟩, ⟨1998294044341611715162, 1967086318103620387906, 323428391, 2226636920821629152844, 1895900994512547609266, 323435749⟩, ⟨9025560694482349646625, 8987589541640338835756, 1581412627, 10070884328016552866782, 8588560055813397821425, 1581462817⟩, ⟨42284549218681613381922, 42466662230224170631649, 7854916744, 47241591251317465440778, 40385607975819885893824, 7855236054⟩, ⟨203041720190109063854651, 205337946207971343393185, 39480413053, 227053740359061781929843, 194779832787449732284157, 39482374205⟩]⟩
def s0_N : ArbEcon.Off.StO := ⟨253, 102073019758711108459, 102073019758711112306, 731306474635521511, [⟨141311676438692421685, 117970097580596891851, 14720769, 143452597695043949876, 115356621667844895487, 14720767⟩, ⟨470544123656534673199, 455131774255519881940, 67996366, 528782146142995286943, 444373279265800082810, 67997371⟩, ⟨2003193332486519200412, 1967086318103620387906, 325397352, 2248485794350038897361, 1895900994512547609266, 325405985⟩, ⟨9052670364005628078204, 8987589541640338835756, 1592308679, 10191782655139192317186, 8588560055813397821425, 1592369459⟩, ⟨42434557579064599063548, 42466662230224170631649, 7915214499, 47910568783822619859154, 40385607975819885893824, 7915611967⟩, ⟨203871774874673526618524, 205337946207971343393185, 39814095302, 230755453605620676481893, 194779832787449732284157, 39816597162⟩]⟩
def oc1 : ArbEcon.Off.OCfg := ⟨3, 0, 4, 115792089237316195423570985008687907853269984665640564039457584007913129639936, 64⟩
def s1_1 : ArbEcon.Off.StO := ⟨252, 101999963251048560352, 101999963251048564189, 291654926620417265, [⟨84833385053241409963, 63672670630875573775, 6872469, 79726543849211232697, 62114489115222842236, 6872474⟩, ⟨234932515514445277202, 224997193627102547821, 30730123, 263404863952780502934, 221876805262217853176, 30730592⟩, ⟨951945084963948298681, 928276115590762611541, 144018167, 1059630640387872077220, 901386494147327195844, 144021692⟩, ⟨4167326671597535603910, 4120551369464894552897, 694257575, 4645019218000405017868, 3955286486436473112878, 694280477⟩, ⟨19109996606981026781991, 19080961219733802874983, 3411630064, 21332261766456497689367, 18192328062689096754661, 3411771555⟩, ⟨90330101643433696031597, 90886556376799024483067, 17003215424, 100953711352157443040875, 86317714283798995216926, 17004067921⟩]⟩
def s1_N : ArbEcon.Off.StO := ⟨253, 102073019758711108459, 102073019758711112306, 290789909043097136, [⟨84897010436917482602, 63672670630875573775, 6898036, 80010287715670695139, 62114489115222842236, 6898041⟩, ⟨235284579543694713102, 224997193627102547821, 30871611, 264974929280938197633, 221876805262217853176, 30872126⟩, ⟨953893192362756185575, 928276115590762611541, 144801151, 1068318423371315389995, 901386494147327195844, 144805184⟩, ⟨4178106308601011476812, 4120551369464894552897, 698590539, 4693092105041336061984, 3955286486436473112878, 698617657⟩, ⟨19169644537068358402160, 19080961219733802874983, 3435608292, 21598267774301570959582, 18192328062689096754661, 3435780889⟩, ⟨90660156872803290825278, 90886556376799024483067, 17135908740, 102425626199905741798357, 86317714283798995216926, 17136976394⟩]⟩
def oc2 : ArbEcon.Off.OCfg := ⟨11, 0, 12, 1552518092300708935148979488462502555256886017116696611139052038026050952686376886330878408828646477950487730697131073206171580044114814391444287275041181139204454976020849905550265285631598444825262999193716468750892846853816057856, 64⟩
def s2_1 : ArbEcon.Off.StO := ⟨252, 101999963251048560352, 101999963251048564189, 116047527927670881, [⟨56213093731254914653, 36414234017326349100, 3310266, 47549341904279653736, 35105883340536307888, 3310267⟩, ⟨121902714301251612492, 115297906492002262025, 14208846, 137640254608507667449, 114924216380940326744, 14209104⟩, ⟨465121239520790888039, 448558720231845714287, 64944154, 517282888869593260467, 439763171613901826145, 64945932⟩, ⟨1959158213922555039991, 1921696997338124291108, 307737834, 2181107046019869322641, 1855712147302541332184, 307748822⟩, ⟨8753819853410409837254, 8685474729317048818133, 1493170559, 9762142367551269005748, 8311143411740416796659, 1493236146⟩, ⟨40613883944640282260845, 40640290493490177722140, 7368929904, 45352276879687374086470, 38678731116925754936631, 7369315715⟩]⟩
def s2_N : ArbEcon.Off.StO := ⟨253, 102073019758711108459, 102073019758711112306, 115626996524864980, [⟨56238393137418682599, 36414234017326349100, 3320434, 47662167177924887315, 35105883340536307888, 3320435⟩, ⟨122042705769389254284, 115297906492002262025, 14265117, 138264560791759009062, 114924216380940326744, 14265393⟩, ⟨465895866839095248713, 448558720231845714287, 65255555, 520737418141743831280, 439763171613901826145, 65257533⟩, ⟨1963444528583341576488, 1921696997338124291108, 309461101, 2200222301982888822774, 1855712147302541332184, 309473754⟩, ⟨8777537701899784725382, 8685474729317048818133, 1502706962, 9867914523971377162774, 8311143411740416796659, 1502784855⟩, ⟨40745124038166621164611, 40640290493490177722140, 7421703485, 45937555418222443673644, 38678731116925754936631, 7422174502⟩]⟩

end

theorem budget : ArbEcon.Off.Cp 5 * ((441 / 5000 : ℝ) * (2767 / 500 : ℝ)) ^ (5 + 1) * ((((253 : ℕ) : ℝ)) - 1 + ArbEcon.Off.emcB 6 253 (840 : ℝ) (841 : ℝ))
    + 3 * ArbEcon.Off.corrVar 6 253 (441 / 5000 : ℝ) (840 : ℝ) (841 : ℝ)
    + ArbEcon.Off.CK 6 * (103900000000000000000000000000000000000 : ℝ) / ((((253 : ℕ) : ℝ)) ^ (2 * 6) * ((15 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ ((33 : ℕ) : ℝ) / ((5000 : ℕ) : ℝ) := by
  have hC := H1000Oct.CK_six_le
  have hC0 := ArbEcon.Off.CK_nonneg 6
  have hm : ArbEcon.Off.CK 6 * (103900000000000000000000000000000000000 : ℝ) / ((((253 : ℕ) : ℝ)) ^ (2 * 6) * ((15 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2)
      ≤ (84107 / 1000000000000000 : ℝ) * (103900000000000000000000000000000000000 : ℝ) / ((((253 : ℕ) : ℝ)) ^ (2 * 6) * ((15 : ℕ) : ℝ)) / ((((2 * 6 : ℕ)) : ℝ) + 1 / 2) := by
    gcongr
  refine le_trans (add_le_add (le_refl _) hm) ?_
  rw [H1000Oct.emcB_betaN 6 253 (by norm_num), H1000Oct.corrVar_betaN 6 253 (by norm_num)]
  unfold ArbEcon.Off.Cp
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, ArbEcon.OrderK.betaN, ArbEcon.OrderK.Lbeta]
  norm_num [Nat.factorial]

theorem hQ : pochNormSq 1 ((840 : ℝ) + 5773 / 100000) (2 * 6 + 1) ≤ (103900000000000000000000000000000000000 : ℝ) ^ 2 := by
  simp only [pochNormSq]
  norm_num

/-! ### Cell 0: [1/2, 2/3] x [840, 84005773/100000] -/

theorem chunk0_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 13763033 14) oc0 251 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 13763033 14) 5)) s0_1 = true := by
  decide +kernel
theorem chunk0_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 13763033 14) oc0 1 s0_1) s0_N = true := by
  decide +kernel
theorem check0 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 13763033 14) oc0 6 253 5 s0_1.acc s0_N.acc 882 10000 33 5000 = true := by
  decide +kernel
theorem ht0 : (13763033 / 16384 : ℝ) = ((13763033 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid0 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 13763033 14) (13763033 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 13763033 14 _ ht0
theorem hσ0 : (7 / 12 : ℝ) = (((7 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid0 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 13763033 14) oc0 (7 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ0⟩
theorem inv0_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 13763033 14) (7 / 12 : ℝ) (13763033 / 16384 : ℝ) (253 - 1) s0_1 :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 251 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 13763033 14) 5) s0_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid0.one_eq) chunk0_1
theorem inv0_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 13763033 14) (7 / 12 : ℝ) (13763033 / 16384 : ℝ) 253 s0_N :=
  ArbEcon.Off.chunkO_sound _ oc0 _ _ 9 valid0 ovalid0 1 252 s0_1 s0_N inv0_1 chunk0_N
theorem cell0 : ∀ x y : ℝ, (1 / 2 : ℝ) ≤ x → x ≤ (2 / 3 : ℝ) → (840 : ℝ) ≤ y → y ≤ (84005773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s0_N.lhi : ℝ) ≤ (2767 / 500 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 13763033 14)).P := by
    show ((102073019758711112306 : ℕ) : ℝ) ≤ (2767 / 500 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 13763033 14) oc0 (7 / 12 : ℝ) (13763033 / 16384 : ℝ) hσ0 ht0 6 253 5 (by norm_num) (by norm_num)
    s0_1 s0_N inv0_1 inv0_N 882 10000 33 5000 check0 (441 / 5000 : ℝ) (2767 / 500 : ℝ) (840 : ℝ) (841 : ℝ) ((840 : ℝ) + 5773 / 100000) (103900000000000000000000000000000000000 : ℝ) 15 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (7 / 12 : ℝ) (13763033 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 1: [2/3, 5/6] x [840, 84005773/100000] -/

theorem chunk1_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 13763033 14) oc1 251 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 13763033 14) 5)) s1_1 = true := by
  decide +kernel
theorem chunk1_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 13763033 14) oc1 1 s1_1) s1_N = true := by
  decide +kernel
theorem check1 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 13763033 14) oc1 6 253 5 s1_1.acc s1_N.acc 882 10000 33 5000 = true := by
  decide +kernel
theorem ht1 : (13763033 / 16384 : ℝ) = ((13763033 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid1 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 13763033 14) (13763033 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 13763033 14 _ ht1
theorem hσ1 : (3 / 4 : ℝ) = (((3 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((4 : ℕ) : ℝ) := by norm_num
theorem ovalid1 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 13763033 14) oc1 (3 / 4 : ℝ) := ⟨by decide +kernel, by decide, hσ1⟩
theorem inv1_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 13763033 14) (3 / 4 : ℝ) (13763033 / 16384 : ℝ) (253 - 1) s1_1 :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 251 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 13763033 14) 5) s1_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid1.one_eq) chunk1_1
theorem inv1_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 13763033 14) (3 / 4 : ℝ) (13763033 / 16384 : ℝ) 253 s1_N :=
  ArbEcon.Off.chunkO_sound _ oc1 _ _ 9 valid1 ovalid1 1 252 s1_1 s1_N inv1_1 chunk1_N
theorem cell1 : ∀ x y : ℝ, (2 / 3 : ℝ) ≤ x → x ≤ (5 / 6 : ℝ) → (840 : ℝ) ≤ y → y ≤ (84005773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s1_N.lhi : ℝ) ≤ (2767 / 500 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 13763033 14)).P := by
    show ((102073019758711112306 : ℕ) : ℝ) ≤ (2767 / 500 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 13763033 14) oc1 (3 / 4 : ℝ) (13763033 / 16384 : ℝ) hσ1 ht1 6 253 5 (by norm_num) (by norm_num)
    s1_1 s1_N inv1_1 inv1_N 882 10000 33 5000 check1 (441 / 5000 : ℝ) (2767 / 500 : ℝ) (840 : ℝ) (841 : ℝ) ((840 : ℝ) + 5773 / 100000) (103900000000000000000000000000000000000 : ℝ) 15 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (3 / 4 : ℝ) (13763033 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-! ### Cell 2: [5/6, 1] x [840, 84005773/100000] -/

theorem chunk2_1 : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 13763033 14) oc2 251 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 13763033 14) 5)) s2_1 = true := by
  decide +kernel
theorem chunk2_N : ArbEcon.Off.StO.beq (ArbEcon.Off.runO (ArbEcon.OrderK.cfg64 13763033 14) oc2 1 s2_1) s2_N = true := by
  decide +kernel
theorem check2 : ArbEcon.Off.checkCell (ArbEcon.OrderK.cfg64 13763033 14) oc2 6 253 5 s2_1.acc s2_N.acc 882 10000 33 5000 = true := by
  decide +kernel
theorem ht2 : (13763033 / 16384 : ℝ) = ((13763033 : ℕ) : ℝ) / 2 ^ (14 : ℕ) := by norm_num
theorem valid2 : ArbEcon.Valid (ArbEcon.OrderK.cfg64 13763033 14) (13763033 / 16384 : ℝ) 9 := ArbEcon.OrderK.valid64 13763033 14 _ ht2
theorem hσ2 : (11 / 12 : ℝ) = (((11 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) / ((12 : ℕ) : ℝ) := by norm_num
theorem ovalid2 : ArbEcon.Off.OValid (ArbEcon.OrderK.cfg64 13763033 14) oc2 (11 / 12 : ℝ) := ⟨by decide +kernel, by decide, hσ2⟩
theorem inv2_1 : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 13763033 14) (11 / 12 : ℝ) (13763033 / 16384 : ℝ) (253 - 1) s2_1 :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 251 1 (ArbEcon.Off.StO.init (ArbEcon.OrderK.cfg64 13763033 14) 5) s2_1
    (ArbEcon.Off.initO_sound _ _ _ 5 valid2.one_eq) chunk2_1
theorem inv2_N : ArbEcon.Off.InvO (ArbEcon.OrderK.cfg64 13763033 14) (11 / 12 : ℝ) (13763033 / 16384 : ℝ) 253 s2_N :=
  ArbEcon.Off.chunkO_sound _ oc2 _ _ 9 valid2 ovalid2 1 252 s2_1 s2_N inv2_1 chunk2_N
theorem cell2 : ∀ x y : ℝ, (5 / 6 : ℝ) ≤ x → x ≤ (1 : ℝ) → (840 : ℝ) ≤ y → y ≤ (84005773 / 100000 : ℝ) → x ≤ 1 →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1 hx1'
  have hlhi : (s2_N.lhi : ℝ) ≤ (2767 / 500 : ℝ) * 2 ^ ((ArbEcon.OrderK.cfg64 13763033 14)).P := by
    show ((102073019758711112306 : ℕ) : ℝ) ≤ (2767 / 500 : ℝ) * 2 ^ (64 : ℕ)
    norm_num
  have hcell := H1000Oct.cell_zeta_ne_zero_R (ArbEcon.OrderK.cfg64 13763033 14) oc2 (11 / 12 : ℝ) (13763033 / 16384 : ℝ) hσ2 ht2 6 253 5 (by norm_num) (by norm_num)
    s2_1 s2_N inv2_1 inv2_N 882 10000 33 5000 check2 (441 / 5000 : ℝ) (2767 / 500 : ℝ) (840 : ℝ) (841 : ℝ) ((840 : ℝ) + 5773 / 100000) (103900000000000000000000000000000000000 : ℝ) 15 (by norm_num) hlhi
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hQ
    (by norm_num) (by norm_num) budget
  have hre : ((x : ℂ) + (y : ℂ) * I).re = x := by simp
  have him : ((x : ℂ) + (y : ℂ) * I).im = y := by simp
  apply hcell
  · apply ArbEcon.Off.dist_le_of_box x y (11 / 12 : ℝ) (13763033 / 16384 : ℝ) (1 / 12 : ℝ) (473 / 16384 : ℝ) (((882 : ℕ) : ℝ) / ((10000 : ℕ) : ℝ))
    · rw [abs_le]; constructor <;> linarith
    · rw [abs_le]; constructor <;> linarith
    · norm_num
    · norm_num
  · rw [him]; linarith
  · rw [him]; linarith
  · rw [hre]; linarith
  · rw [hre]; exact hx1'

/-- The right half of the slab. -/
theorem right_half : ∀ x y : ℝ, 1 / 2 ≤ x → x < 1 → (840 : ℝ) ≤ y → y ≤ ((840 : ℝ) + 5773 / 100000) →
    riemannZeta ((x : ℂ) + (y : ℂ) * I) ≠ 0 := by
  intro x y hx0 hx1 hy0 hy1
  by_cases h0 : x ≤ (2 / 3 : ℝ)
  · exact cell0 x y (by linarith) h0 (by linarith) (by linarith) (by linarith)
  by_cases h1 : x ≤ (5 / 6 : ℝ)
  · exact cell1 x y (by linarith) h1 (by linarith) (by linarith) (by linarith)
  exact cell2 x y (by linarith) (by linarith) (by linarith) (by linarith) (by linarith)

/-- **The edge-clearance slab `SlabClear 840 84005773/100000`, hypothesis-free.** -/
theorem slabClear : EdgeClearGlue.SlabClear (840 : ℝ) ((840 : ℝ) + 5773 / 100000) :=
  ArbEcon.Off.slabClear_of_right_half _ _ right_half

end H1000Slab.U840
