/-  H11K_h11000.lean -- lane H11K: the height-11000 statement, HYPOTHESIS-FREE.

        all_nontrivial_zeros_up_to_height_11000 :
          ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 11000 → ρ.re = 1 / 2

    (and the same up to 11004).  Composition:
      * [0, 8000]: `Arb4_h8000.all_nontrivial_zeros_up_to_height_8000` (lane Arb4, unchanged);
      * [8000, 11004]: ONE Turing band `[31851/4, 11004]` with 3541 zeros, certified by
        `H11K.boxCert_of_parts_sharp` (the Arb4 band glue with sharp pi pins, H11K_Turing):
          - hLine: `H11K.Line.hLine` (RS5 Riemann-Siegel sign changes, 3541 zeros);
          - bottom edge at 31851/4: `Arb4.H8000.E_T31851_4_hAH` and the slab
            `Arb4.H8000.S_L31851_4_clear` below it (both lane Arb4, reused unchanged);
          - top edge at 11004: `H11K.Edge.E_T11004_hAH` (Arb4 `edgeOK`, checked per piece) and the slab
            `H11K.Slab.S_U11004_clear` above it (Arb4 `slabOK`);
          - K6a range, K6b brackets (`Arb4.k6sideB`), ball cover and sharp pins (`H11K.validBS`):
            ONE `decide +kernel`;
          - hnzb, hnzt, hnzl, hins: K1 (`BandGlue.BandData.inputs_of_reduced`) from the two slabs and
            the cap geometry of the ball `1/2 + i 75867/8`, radius `sqrt (147987481/64)`;
      * glue: `AllZerosUpToHeight.all_nontrivial_zeros_in_segment_on_line` (the strip edges from the
        de la Vallee Poussin zero-free region), `HeightFloor.height_floor`, `height_chain`.
    Axioms [propext, Classical.choice, Quot.sound] (H11K_AxiomGuard); no `sorry`.
    (GENERATED by scratchpad h11k/emit_cap.py, UNTRUSTED; every value is re-checked here.)
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import H11K_Turing
import H11K_Line
import H11K_Edge_T11004
import H11K_Slab_U11004
import Arb4_h8000
import HeightFloor

open Complex Arb4 Arb4.Q

namespace H11K_h11000

/-- The K6b certificate at the top edge. -/
noncomputable def G_T11004 : GamD := ⟨(Q.ofNat 11004), 25, 12, 25, 12, 1, 2, 1, 2⟩

/-- The Blaschke ball of the band: center `1/2 + i 75867/8` (the band's midpoint). -/
noncomputable def cB : ℂ := ⟨1 / 2, 75867 / 8⟩

/-- Its radius `sqrt (147987481/64)` (squared radius = half-height squared + 4). -/
noncomputable def RB : ℝ := Real.sqrt (147987481 / 64)

theorem hs1B : (1 : ℂ) ∉ Metric.ball cB RB := by
  rw [Metric.mem_ball, Complex.dist_eq_re_im]
  unfold cB RB
  intro hlt
  simp only [Complex.one_re, Complex.one_im] at hlt
  have hle : Real.sqrt (147987481 / 64) ≤
      Real.sqrt (((1 : ℝ) - (1 / 2)) ^ 2 + ((0 : ℝ) - (75867 / 8)) ^ 2) :=
    Real.sqrt_le_sqrt (by norm_num)
  linarith [hlt, hle]

/-- **The band** `[31851/4, 11004]`, `n = 3541` (enclosures are supplied by `E` via `withEncl`). -/
noncomputable def band : BandGlue.BandData :=
  ⟨31851 / 4, 11004, 3541, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, cB, RB, hs1B⟩

/-- The five enclosures: K6a, the edges at 11004 and 31851/4, K6b. -/
noncomputable def E : EnclQ := ⟨Q.frac (-249) 250, Q.frac 249 250, H11K.Edge.E_T11004.Lo,
  H11K.Edge.E_T11004.Hi, Arb4.H8000.E_T31851_4.Lo, Arb4.H8000.E_T31851_4.Hi,
  (Q.frac 11123523695323 1000000000), (Q.frac 11123523803557 1000000000), (Q.frac 11123523669291 1000000000), (Q.frac 444940951101 40000000)⟩

/-- Ball cover, sharp pins, K6a range and K6b brackets: ONE kernel check. -/
theorem chk : (H11K.validBS (Q.frac 31851 4) (Q.ofNat 11004) (Q.frac 75867 8) (Q.frac 147987481 64)
    3541 E && k6sideB Arb4_h8000.G_T31851_4 G_T11004 E) = true := by decide +kernel

/-- **The band's box certificate**: every zero in `[1/4000000, 3999999/4000000] x [8000, 11004]` is on
    the line. -/
theorem box : BandGlue.BoxCert (1 / 4000000) (3999999 / 4000000) 8000 11004 := by
  have hc := chk
  rw [Bool.and_eq_true] at hc
  have hT0 : band.T0 = (Q.frac 31851 4).val := (Q.cv_frac 31851 4).symm
  have hT1 : band.T1 = (Q.ofNat 11004).val := (Q.cv_nat 11004).symm
  have hcc : band.c = (⟨1 / 2, (Q.frac 75867 8).val⟩ : ℂ) := by rw [(Q.cv_frac 75867 8)]; rfl
  have hR : band.R = Real.sqrt (Q.frac 147987481 64).val := by rw [(Q.cv_frac 147987481 64)]; rfl
  have hG : band.CapGeom (30989 / 500000) (3 / 1000) :=
    BandGlue.BandData.CapGeom.of_sqrt (31851 / 4) 11004 (75867 / 8) (147987481 / 64) rfl rfl rfl rfl
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  refine H11K.boxCert_of_parts_sharp band E (show (31851 / 4 : ℝ) ≤ 8000 by norm_num)
    (show (11004 : ℝ) ≤ 11004 from le_refl _) (H11K.validS_of_B _ _ _ _ _ E hT0 hT1 hcc hR hc.1) hG
    ?_ ?_ ?_ (k6side_of_B _ Arb4_h8000.G_T31851_4 G_T11004 E hT0 hT1 hc.2) ?_ ?_
  · exact H11K.Line.hLine
  · show EdgeClearGlue.SlabClear ((31851 / 4 : ℝ) - 30989 / 500000) (31851 / 4 : ℝ)
    exact Arb4.H8000.S_L31851_4_clear
  · show EdgeClearGlue.SlabClear (11004 : ℝ) ((11004 : ℝ) + 3 / 1000)
    exact H11K.Slab.S_U11004_clear
  · show DiffractionCore.argChangeHoriz riemannZeta (11004 : ℝ) 2 (-1) ∈
      Set.Icc (H11K.Edge.E_T11004.Lo).val (H11K.Edge.E_T11004.Hi).val
    exact H11K.Edge.E_T11004_hAH
  · show DiffractionCore.argChangeHoriz riemannZeta (31851 / 4 : ℝ) 2 (-1) ∈
      Set.Icc (Arb4.H8000.E_T31851_4.Lo).val (Arb4.H8000.E_T31851_4.Hi).val
    exact Arb4.H8000.E_T31851_4_hAH

/-- `1/4000000 ≤ dlvpRateC / log 11004` (`log 11004 ≤ 10`, `2.7^10 ≥ 11004`). -/
theorem haC_11004 : (1 / 4000000 : ℝ) ≤ ZeroFreeBridge.dlvpRateC / Real.log 11004 := by
  have hlog : Real.log 11004 ≤ 10 := by
    rw [Real.log_le_iff_le_exp (by norm_num)]
    have he1 : (2.7 : ℝ) ≤ Real.exp 1 := by linarith [Real.exp_one_gt_d9]
    have h10 : Real.exp 10 = (Real.exp 1) ^ 10 := by rw [← Real.exp_nat_mul]; norm_num
    have hpow : (2.7 : ℝ) ^ 10 ≤ (Real.exp 1) ^ 10 := pow_le_pow_left₀ (by norm_num) he1 10
    rw [h10]; nlinarith [hpow]
  have hpos : 0 < Real.log 11004 := Real.log_pos (by norm_num)
  rw [le_div_iff₀ hpos]
  calc (1 / 4000000 : ℝ) * Real.log 11004
      ≤ (1 / 4000000) * 10 := by nlinarith [hlog, hpos]
    _ ≤ 9 / 1369088 := by norm_num
    _ ≤ ZeroFreeBridge.dlvpRateC := ZeroFreeBridge.dlvpRateC_lower

/-- The one-band partition of `[8000, 11004]`. -/
noncomputable def bnd : ℕ → ℝ := fun i => if i = 0 then 8000 else 11004

theorem bnd_mono : Monotone bnd := by
  intro i j hij
  unfold bnd
  split_ifs <;> first | (exfalso; omega) | norm_num

/-- **The segment `[8000, 11004]`**: every zero of ζ with `8000 ≤ Im ρ ≤ 11004` is on the line. -/
theorem segment_8000_11004 :
    ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → (8000 : ℝ) ≤ ρ.im → ρ.im ≤ 11004 → ρ.re = 1 / 2 := by
  have hre_eq : (1 : ℝ) - 1 / 4000000 = 3999999 / 4000000 := by norm_num
  refine AllZerosUpToHeight.all_nontrivial_zeros_in_segment_on_line
    (1 / 4000000) 8000 11004 bnd 1 le_rfl bnd_mono (by simp [bnd]) (by simp [bnd]) haC_11004
    (by norm_num) (by norm_num) ?_ (HeightFloor.height_floor 11004)
  intro i hi ρ hre him hz
  have hi0 : i = 0 := by omega
  subst hi0
  have him' : (8000 : ℝ) ≤ ρ.im ∧ ρ.im ≤ 11004 := by simpa [bnd] using him
  exact box.box ρ ⟨hre.1, by linarith [hre.2, hre_eq]⟩ him' hz

/-- **Every nontrivial zero of ζ with `0 < Im ρ ≤ 11004` lies on the critical line** -- kernel-checked,
    NO hypotheses (a finite verification; conjecture1_proved = False). -/
theorem all_nontrivial_zeros_up_to_height_11004 :
    ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 11004 → ρ.re = 1 / 2 :=
  AllZerosUpToHeight.height_chain 8000 11004 Arb4_h8000.all_nontrivial_zeros_up_to_height_8000
    segment_8000_11004

/-- **Every nontrivial zero of ζ with `0 < Im ρ ≤ 11000` lies on the critical line** -- kernel-checked,
    NO hypotheses (a finite verification; conjecture1_proved = False). -/
theorem all_nontrivial_zeros_up_to_height_11000 :
    ∀ ρ : ℂ, riemannZeta ρ = 0 → 0 < ρ.im → ρ.im ≤ 11000 → ρ.re = 1 / 2 :=
  fun ρ hz h0 h1 => all_nontrivial_zeros_up_to_height_11004 ρ hz h0 (by linarith)

end H11K_h11000
