/-  H11K_Edge_T11004.lean -- lane H11K: the kernel certificate of the horizontal argument change at T = 11004.

    (GENERATED by scratchpad h11k/emit_edge.py, UNTRUSTED; every value is re-checked here.)  The edge data
    `Arb4.EdgeD` (25 octant pieces, EM cut N = 3302, planned by emit_h1000_offline.plan_edge, unchanged) and
    ONE `decide +kernel` per piece (`H11K.pieceJ`) plus one for the rest (`H11K.edgeRest`), assembled by
    `H11K.edge_sound_of_split` (the whole-edge `Arb4.edgeOK` decide is about 19 GB at this height).
    conjecture1_proved = False.  Finite verification up to a fixed height only.
-/
import H11K_EdgeSplit

open Arb4 Arb4.Q H11K

namespace H11K.Edge

/-- The edge `[2, -1] + i 11004` (25 pieces, N = 3302). -/
noncomputable def E_T11004 : EdgeD where
  tn := 11004
  tq := 0
  N := 3302
  L := (Q.frac 8103 1000)
  m := 25
  x := fun j => [(Q.frac 2 1), (Q.frac 31 16), (Q.frac 29 16), (Q.frac 27 16), (Q.frac 25 16), (Q.frac 23 16), (Q.frac 21 16), (Q.frac 19 16), (Q.frac 17 16), (Q.frac 15 16), (Q.frac 13 16), (Q.frac 11 16), (Q.frac 9 16), (Q.frac 7 16), (Q.frac 5 16), (Q.frac 3 16), (Q.frac 1 16), (Q.frac (-1) 16), (Q.frac (-3) 16), (Q.frac (-5) 16), (Q.frac (-7) 16), (Q.frac (-9) 16), (Q.frac (-11) 16), (Q.frac (-13) 16), (Q.frac (-15) 16), (Q.frac (-1) 1)].getD j (Q.frac (-1) 1)
  pc := fun j => [{ a := 2, b := 0, q := 1, rn := 1, rd := 16, kk := 0, FN := 113, FD := 1250, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 31, eb := 0, eqd := 16, Rn := 1, Rd := 1048576, xhi := (Q.frac 33 16), sigs := (Q.frac 33 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 119 1000000000) },
    { a := 15, b := 0, q := 8, rn := 1, rd := 16, kk := 0, FN := 113, FD := 1250, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 29, eb := 0, eqd := 16, Rn := 1, Rd := 1048576, xhi := (Q.frac 31 16), sigs := (Q.frac 31 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 1201 10000000000) },
    { a := 7, b := 0, q := 4, rn := 1, rd := 16, kk := 0, FN := 113, FD := 1250, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 27, eb := 0, eqd := 16, Rn := 2, Rd := 1048576, xhi := (Q.frac 29 16), sigs := (Q.frac 29 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 2423 10000000000) },
    { a := 13, b := 0, q := 8, rn := 1, rd := 16, kk := 0, FN := 113, FD := 1250, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 25, eb := 0, eqd := 16, Rn := 4, Rd := 1048576, xhi := (Q.frac 27 16), sigs := (Q.frac 27 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 489 1000000000) },
    { a := 3, b := 0, q := 2, rn := 1, rd := 16, kk := 0, FN := 113, FD := 1250, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 23, eb := 0, eqd := 16, Rn := 10, Rd := 1048576, xhi := (Q.frac 25 16), sigs := (Q.frac 25 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 617 500000000) },
    { a := 11, b := 0, q := 8, rn := 1, rd := 16, kk := 0, FN := 113, FD := 1250, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 21, eb := 0, eqd := 16, Rn := 26, Rd := 1048576, xhi := (Q.frac 23 16), sigs := (Q.frac 23 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 81 25000000) },
    { a := 5, b := 0, q := 4, rn := 1, rd := 16, kk := 0, FN := 113, FD := 1250, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 19, eb := 0, eqd := 16, Rn := 70, Rd := 1048576, xhi := (Q.frac 21 16), sigs := (Q.frac 21 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 11 1250000) },
    { a := 9, b := 0, q := 8, rn := 1, rd := 16, kk := 0, FN := 9041, FD := 100000, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 17, eb := 0, eqd := 16, Rn := 192, Rd := 1048576, xhi := (Q.frac 19 16), sigs := (Q.frac 19 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 2437 100000000) },
    { a := 1, b := 0, q := 1, rn := 1, rd := 16, kk := 0, FN := 181, FD := 2000, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 15, eb := 0, eqd := 16, Rn := 527, Rd := 1048576, xhi := (Q.frac 17 16), sigs := (Q.frac 17 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 3377 50000000) },
    { a := 7, b := 0, q := 8, rn := 1, rd := 16, kk := 1, FN := 453, FD := 5000, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 13, eb := 0, eqd := 16, Rn := 1451, Rd := 1048576, xhi := (Q.frac 15 16), sigs := (Q.frac 15 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 939 5000000) },
    { a := 3, b := 0, q := 4, rn := 1, rd := 16, kk := 1, FN := 9091, FD := 100000, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 11, eb := 0, eqd := 16, Rn := 3995, Rd := 1048576, xhi := (Q.frac 13 16), sigs := (Q.frac 13 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 5221 10000000) },
    { a := 5, b := 0, q := 8, rn := 1, rd := 16, kk := 1, FN := 919, FD := 10000, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 9, eb := 0, eqd := 16, Rn := 10998, Rd := 1048576, xhi := (Q.frac 11 16), sigs := (Q.frac 11 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 363 250000) },
    { a := 1, b := 0, q := 2, rn := 1, rd := 16, kk := 1, FN := 189, FD := 2000, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 7, eb := 0, eqd := 16, Rn := 30279, Rd := 1048576, xhi := (Q.frac 9 16), sigs := (Q.frac 9 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 101 25000) },
    { a := 3, b := 0, q := 8, rn := 1, rd := 16, kk := 1, FN := 1017, FD := 10000, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 5, eb := 0, eqd := 16, Rn := 83365, Rd := 1048576, xhi := (Q.frac 7 16), sigs := (Q.frac 7 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 1123 100000) },
    { a := 1, b := 0, q := 4, rn := 1, rd := 16, kk := 1, FN := 1217, FD := 10000, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 3, eb := 0, eqd := 16, Rn := 229525, Rd := 1048576, xhi := (Q.frac 5 16), sigs := (Q.frac 5 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 3123 100000) },
    { a := 1, b := 0, q := 8, rn := 1, rd := 16, kk := 1, FN := 887, FD := 5000, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 1, eb := 0, eqd := 16, Rn := 631941, Rd := 1048576, xhi := (Q.frac 3 16), sigs := (Q.frac 3 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 869 10000) },
    { a := 0, b := 0, q := 1, rn := 1, rd := 16, kk := 1, FN := 831, FD := 2500, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 0, gq := 1, Gn := 1, Gd := 1, ea := 0, eb := 1, eqd := 16, Rn := 1739897, Rd := 1048576, xhi := (Q.frac 1 16), sigs := (Q.frac 1 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 2417 10000) },
    { a := 0, b := 1, q := 8, rn := 1, rd := 16, kk := 1, FN := 461, FD := 500, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 2, gq := 16, Gn := 2887002, Gd := 1048576, ea := 0, eb := 3, eqd := 16, Rn := 4790388, Rd := 1048576, xhi := (Q.frac (-1) 16), sigs := (Q.frac 3 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 1681 2500) },
    { a := 0, b := 1, q := 4, rn := 1, rd := 16, kk := 1, FN := 64, FD := 25, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 4, gq := 16, Gn := 7948665, Gd := 1048576, ea := 0, eb := 5, eqd := 16, Rn := 13189179, Rd := 1048576, xhi := (Q.frac (-3) 16), sigs := (Q.frac 5 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 1871 1000) },
    { a := 0, b := 3, q := 8, rn := 1, rd := 16, kk := 1, FN := 3551, FD := 500, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 6, gq := 16, Gn := 21884737, Gd := 1048576, ea := 0, eb := 7, eqd := 16, Rn := 36313231, Rd := 1048576, xhi := (Q.frac (-5) 16), sigs := (Q.frac 7 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 521 100) },
    { a := 0, b := 1, q := 2, rn := 1, rd := 16, kk := 1, FN := 1971, FD := 100, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 8, gq := 16, Gn := 60254356, Gd := 1048576, ea := 0, eb := 9, eqd := 16, Rn := 99979743, Rd := 1048576, xhi := (Q.frac (-7) 16), sigs := (Q.frac 9 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 29 2) },
    { a := 0, b := 5, q := 8, rn := 1, rd := 16, kk := 1, FN := 547, FD := 10, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 10, gq := 16, Gn := 165895873, Gd := 1048576, ea := 0, eb := 11, eqd := 16, Rn := 275270169, Rd := 1048576, xhi := (Q.frac (-9) 16), sigs := (Q.frac 11 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 807 20) },
    { a := 0, b := 3, q := 4, rn := 1, rd := 16, kk := 1, FN := 1519, FD := 10, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 12, gq := 16, Gn := 456754375, Gd := 1048576, ea := 0, eb := 13, eqd := 16, Rn := 757890184, Rd := 1048576, xhi := (Q.frac (-11) 16), sigs := (Q.frac 13 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 562 5) },
    { a := 0, b := 7, q := 8, rn := 1, rd := 16, kk := 2, FN := 2108, FD := 5, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 14, gq := 16, Gn := 1257563283, Gd := 1048576, ea := 0, eb := 15, eqd := 16, Rn := 2086668286, Rd := 1048576, xhi := (Q.frac (-13) 16), sigs := (Q.frac 15 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 1564 5) },
    { a := 0, b := 1, q := 1, rn := 1, rd := 16, kk := 2, FN := 11703, FD := 10, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 16, gq := 16, Gn := 3462397952, Gd := 1048576, ea := 0, eb := 17, eqd := 16, Rn := 5745139111, Rd := 1048576, xhi := (Q.frac (-15) 16), sigs := (Q.frac 17 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 8709 10) }].getD j { a := 0, b := 1, q := 1, rn := 1, rd := 16, kk := 2, FN := 11703, FD := 10, aQ := (Q.frac 1375492 125), U := (Q.frac 11005 1), ga := 0, gb := 16, gq := 16, Gn := 3462397952, Gd := 1048576, ea := 0, eb := 17, eqd := 16, Rn := 5745139111, Rd := 1048576, xhi := (Q.frac (-15) 16), sigs := (Q.frac 17 16), Qr := 34690000000000000000000000000000000000000000000000000, E := (Q.frac 8709 10) }
  D0 := 1000000000
  reLo0 := 1433071352
  reHi0 := 1433071376
  imLo0 := 187948396
  imHi0 := 187948419
  Qp0 := 34686412196586685575365713605592726308135940406433491
  Rn0 := 394
  Rd0 := 4294967296
  qlo0 := (Q.frac 2623 20000)
  qhi0 := (Q.frac 131151 1000000)
  D1 := 1000000000
  reLo1 := 38052865875262
  reHi1 := 39095369809492
  imLo1 := 98137754714987
  imHi1 := 99180258649217
  Qp1 := 34686339580069404783803091119529337281193387968521229
  Rn1 := 14181982011392
  Rd1 := 4294967296
  qlo1 := (Q.frac (-398373) 1000000)
  qhi1 := (Q.frac (-383673) 1000000)
  Lo := (Q.frac 1041271 1000000)
  Hi := (Q.frac 1075553 1000000)

theorem E_T11004_rest : edgeRest E_T11004 = true := by decide +kernel

theorem E_T11004_p0 : pieceJ E_T11004 0 = true := by decide +kernel

theorem E_T11004_p1 : pieceJ E_T11004 1 = true := by decide +kernel

theorem E_T11004_p2 : pieceJ E_T11004 2 = true := by decide +kernel

theorem E_T11004_p3 : pieceJ E_T11004 3 = true := by decide +kernel

theorem E_T11004_p4 : pieceJ E_T11004 4 = true := by decide +kernel

theorem E_T11004_p5 : pieceJ E_T11004 5 = true := by decide +kernel

theorem E_T11004_p6 : pieceJ E_T11004 6 = true := by decide +kernel

theorem E_T11004_p7 : pieceJ E_T11004 7 = true := by decide +kernel

theorem E_T11004_p8 : pieceJ E_T11004 8 = true := by decide +kernel

theorem E_T11004_p9 : pieceJ E_T11004 9 = true := by decide +kernel

theorem E_T11004_p10 : pieceJ E_T11004 10 = true := by decide +kernel

theorem E_T11004_p11 : pieceJ E_T11004 11 = true := by decide +kernel

theorem E_T11004_p12 : pieceJ E_T11004 12 = true := by decide +kernel

theorem E_T11004_p13 : pieceJ E_T11004 13 = true := by decide +kernel

theorem E_T11004_p14 : pieceJ E_T11004 14 = true := by decide +kernel

theorem E_T11004_p15 : pieceJ E_T11004 15 = true := by decide +kernel

theorem E_T11004_p16 : pieceJ E_T11004 16 = true := by decide +kernel

theorem E_T11004_p17 : pieceJ E_T11004 17 = true := by decide +kernel

theorem E_T11004_p18 : pieceJ E_T11004 18 = true := by decide +kernel

theorem E_T11004_p19 : pieceJ E_T11004 19 = true := by decide +kernel

theorem E_T11004_p20 : pieceJ E_T11004 20 = true := by decide +kernel

theorem E_T11004_p21 : pieceJ E_T11004 21 = true := by decide +kernel

theorem E_T11004_p22 : pieceJ E_T11004 22 = true := by decide +kernel

theorem E_T11004_p23 : pieceJ E_T11004 23 = true := by decide +kernel

theorem E_T11004_p24 : pieceJ E_T11004 24 = true := by decide +kernel

theorem E_T11004_pieces : ∀ j, j < E_T11004.m → pieceJ E_T11004 j = true := by
  intro j hj
  have hm : E_T11004.m = 25 := rfl
  rw [hm] at hj
  interval_cases j
  · exact E_T11004_p0
  · exact E_T11004_p1
  · exact E_T11004_p2
  · exact E_T11004_p3
  · exact E_T11004_p4
  · exact E_T11004_p5
  · exact E_T11004_p6
  · exact E_T11004_p7
  · exact E_T11004_p8
  · exact E_T11004_p9
  · exact E_T11004_p10
  · exact E_T11004_p11
  · exact E_T11004_p12
  · exact E_T11004_p13
  · exact E_T11004_p14
  · exact E_T11004_p15
  · exact E_T11004_p16
  · exact E_T11004_p17
  · exact E_T11004_p18
  · exact E_T11004_p19
  · exact E_T11004_p20
  · exact E_T11004_p21
  · exact E_T11004_p22
  · exact E_T11004_p23
  · exact E_T11004_p24

/-- **The horizontal argument change at T = 11004, hypothesis-free.** -/
theorem E_T11004_hAH : DiffractionCore.argChangeHoriz riemannZeta (11004 : ℝ) 2 (-1) ∈
    Set.Icc E_T11004.Lo.val E_T11004.Hi.val := by
  have h := edge_sound_of_split E_T11004 E_T11004_rest E_T11004_pieces
  have hT : E_T11004.T = (11004 : ℝ) := by
    show ((11004 : ℕ) : ℝ) / 2 ^ (0 : ℕ) = (11004 : ℝ)
    norm_num
  rw [hT] at h
  exact h

end H11K.Edge
